### ISSUE TITLE
Link on install IPFS page which leads to https://docs.ipfs.io/introduction/install/ missing

### ISSUE THREAD

**Issue by 4tal** [graphprotocol/graph-node#1003]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
leads to a page with this line:
ipfs resolve -r /ipns/docs.ipfs.io/introduction/install/: no link named "install" under QmebR8zvqzuUFKKLGAjccXaJRmSkkiwYEjaUcoknpaHsX3

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal From the README page on github tried to enter IPFS install explaination and got that error.

**What is the expected behavior?**
See installations instructions.

**Comment by vishpari** [comment]
Install docker and run IPFS as container
$ docker run -d --name ipfs_host -e IPFS_PROFILE=server -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/go-ipfs:latest

**Comment by Jannis** [comment]
Fixed
