### ISSUE TITLE
No access token provided

### ISSUE THREAD

**Issue by vishpari** [graphprotocol/graph-node#1016]
I have done all steps for deploy graph and everything is working even i have created token(7c40f75018cd4a96bdfecee3d890a721).
but when i run:  graph auth https://api.thegraph.com/deploy/7c40f75018cd4a96bdfecee3d890a721
getting:  No access token provided
![Screen Shot 2019-06-25 at 3 44 50 PM](https://user-images.githubusercontent.com/13795288/60090474-401fef00-9760-11e9-9051-5cadd05e3a98.png)

**Comment by Jannis** [comment]
You need to run
```
graph auth https://api.thegraph.com/deploy/ 7c40f75018cd4a96bdfecee3d890a721
```
Note the space between the URL and the access token. You almost got it right! 😄 

(Note: Make sure to generate a new access token before doing this, since now the whole world knows the one above.)

**Comment by vishpari** [comment]
Still getting error
![Screen Shot 2019-06-26 at 3 57 02 PM](https://user-images.githubusercontent.com/13795288/60172970-69f21800-982b-11e9-85a3-4b79ec29766b.png)

**Comment by Jannis** [comment]
@vishpari The error suggests that you're running `graph auth` in an Ubuntu environment that doesn't run an X server / a D-Bus session server.

We have been using
https://github.com/graphprotocol/graph-cli/blob/e11487e1d1a2c725cbeaa3a19fb54375fdfb1243/.travis.yml#L12

and
https://github.com/graphprotocol/graph-cli/blob/e11487e1d1a2c725cbeaa3a19fb54375fdfb1243/.travis.yml#L21

together to make `graph auth` work in headless environments like yours. 

Note: other Graph CLI commands that require access to the access token will also have to be started with `dbus-launch`.

**Comment by vishpari** [comment]
how to use https://github.com/graphprotocol/graph-cli/blob/master/.travis.yml in ubuntu
Please assist me to setup
