### ISSUE TITLE
Graph processing should not fail when no matching handlers are found

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#1021]
The new support for trying multiple handlers is excellent, but graph processing still fails if at least one handler matches `topics[0]`, but none of them can successfully decode the event data.

This makes graphs that subscribe to events from multiple addresses still vulnerable to disruption. Instead, a warning should be logged and graph processing should continue.

**Comment by Jannis** [comment]
True. Ok, we'll relax this.
