### ISSUE TITLE
Automate Docker on Linux host IP address detection and injection

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1024]
1. Write a script that
   * starts Docker Compose env
   * runs `docker inspect <graph node>` to get the host IP
   * stops Docker Compose env
   * puts the IP into `docker-compose.yml`
2. Document the script in README and on https://thegraph.com/docs/

**Comment by j-mars** [comment]
Hello,

I tried running this in my Linux Virtual Machine (Ubuntu Mate) when doing a local quickstart.

`Note for Linux users: On Linux, host.docker.internal is not currently supported. Instead, you will have to replace it with the IP address of your Docker host (from the perspective of the Graph Node container). To do this, run:

$ CONTAINER_ID=$(docker container ls | grep graph-node | cut -d' ' -f1)
$ docker exec $CONTAINER_ID /bin/bash -c 'ip route | awk \'/^default via /{print $3}\''
This will print the host's IP address. Then, put it into docker-compose.yml:

$ sed -i -e 's/host.docker.internal/<IP ADDRESS>/g' docker-compose.yml`

And I couldn't get the IP Address - the graph-node gets stuck on INFO Connecting to Ethereum..., network: mainnet.

I tried following the solution depicted here: https://stackoverflow.com/questions/33102813/how-to-get-local-host-ip-address-in-docker-container

With no results as well

**Comment by Jannis** [comment]
@j-mars Sorry for the delay, I was on vacation the last two weeks. Did you try running

```bash 
docker-compose up
```

followed by

```bash
CONTAINER_ID=$(docker container ls | grep graph-node | cut -d' ' -f1)
docker inspect $CONTAINER_ID
```

The inspection output should include a gateway IP address somewhere. That's the host IP address.
