### ISSUE TITLE
Return initial data on subgraph subscription

### ISSUE THREAD

**Issue by nenadjaja** [graphprotocol/graph-node#1050]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
In Explorer playground that's hitting a graph-node endpoint, when we write subscriptions and click on the Play button - no data comes back initially. After some time, when a subgraph is being redeployed, or indexed, or anything else changes - we do receive the data..

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In your local environment, we use this endpoint `ws://localhost:8001` for subscriptions. You can access a subgraph on Details page, and type a subscriptions in the playground. Might need to set up a few more things for local testing, please contact @nenadjaja 

**What is the expected behavior?**
When I execute a subscription in the Explorer playground for a particular subgraph - it should return some initial data (or empty set of data) that would corresponding making a query.

**Comment by leodasvacas** [comment]
Done in https://github.com/graphprotocol/graph-node/pull/1062.
