### ISSUE TITLE
Improve restart time of subgraphs with many data sources

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#1081]
Uniswap in the hosted service is taking 15 minutes to restart. We need to identify if this is due to slow graphql queries to grab the data sources or something else and improve this. There are probably opportunities for concurrency.

**Comment by Jannis** [comment]
The first part of improving this was introducing the IPFS file cache. The second part of making this fast is is #1386. We should be able to close this issue after #1386 is merged and rolled out.

**Comment by lutter** [comment]
Here's the time it takes to run the query in `DataSourceLoader::dynamic_data_sources_query` for different `first` parameters, i.e., by varying the batch size with which they are loaded.

The data is pretty noisy, but it shows that we should raise the batch size for that particular query to 500 with prefetching.

 The `first` column is the number of dynamic data sources we fetch with each invocation of the query. The `slow` and `prefetch` columns show how long it takes to load such a batch, the `slow / 1k` and `prefetch / 1k` scale that time to a batch size of 1000 for easier comparison.

All times in ms; measurements were for the subgraph `leoyvens/nuonetworkdebug`
(`Qmf2aet9s2sdYA3qgTseffSyqDQijnZ9CSUZA6FQTCQHru`) which has ~ 5200 dynamic data source entities, and holds the record for that in the production dump I am working with.

| first |  slow | prefetch | slow / 1k | prefetch / 1k |
|-------|-------|----------|-----------|---------------|
|    50 |   750 |      170 |     15000 |          3400 |
|   100 |  1500 |      210 |     15000 |          2100 |
|   200 |  2800 |      320 |     14000 |          1600 |
|   500 |  6300 |      640 |     12600 |          1280 |
|  1000 | 14500 |     1400 |     14500 |          1400 |
|  2000 | 27000 |     2500 |     13500 |          1250 |

**Comment by Jannis** [comment]
Both the IPFS speedup as well as the query prefetching have been implemented, so this should be significantly faster now.
