### ISSUE TITLE
[Build Issue] Cannot depend on version 0.13.2

### ISSUE THREAD

**Issue by fleupold** [graphprotocol/graph-node#1090]
## Bug Report

I'm unable to depend on version 0.13.2, likely because of a version mismatch between the ethabi dependencies.

### Repro steps:

Create a new rust project:

```
mkdir build_failure
cd build_failure
cargo init
``` 

In `Cargo.toml`, add graph node as a dependency (pinned to version 0.13.2)

```
[dependencies]
graph = { git = "https://github.com/graphprotocol/graph-node", tag = "v0.13.2" }
```

**What is the expected behavior?**

`cargo build` to run successfully

**What is the actual behavior?**

See the following error:

```
...
   Compiling ethereum-types v0.4.2
   Compiling bigdecimal v0.0.14
   Compiling cookie_store v0.7.0
   Compiling jsonrpc-core v8.0.1
   Compiling ipfs-api v0.5.1 (https://github.com/ferristseng/rust-ipfs-api#55902e98)
   Compiling diesel v1.4.2
   Compiling reqwest v0.9.19
   Compiling ethereum-types v0.6.0
   Compiling ethabi v8.0.0 (https://github.com/graphprotocol/ethabi.git?branch=graph-patches#81aa6020)
   Compiling ethabi v6.1.0
   Compiling web3 v0.6.0 (https://github.com/graphprotocol/rust-web3?branch=trace-struct-pre-ethereum-types#1fc69c52)
   Compiling graph v0.13.2 (https://github.com/graphprotocol/graph-node?tag=v0.13.2#602fba1a)
error[E0277]: the trait bound `data::store::Value: std::convert::From<web3::types::H160>` is not satisfied
   --> /Users/felixleupold/.cargo/git/checkouts/graph-node-7b0a0749f2617083/602fba1/graph/src/data/subgraph/schema.rs:591:16
    |
591 |         entity.set("address", self.address);
    |                ^^^ the trait `std::convert::From<web3::types::H160>` is not implemented for `data::store::Value`
    |
    = help: the following implementations were found:
              <data::store::Value as std::convert::From<&'a std::string::String>>
              <data::store::Value as std::convert::From<&'a str>>
              <data::store::Value as std::convert::From<bigdecimal::BigDecimal>>
              <data::store::Value as std::convert::From<bool>>
            and 7 others
    = note: required because of the requirements on the impl of `std::convert::From<std::option::Option<web3::types::H160>>` for `data::store::Value`
    = note: required because of the requirements on the impl of `std::convert::Into<data::store::Value>` for `std::option::Option<web3::types::H160>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `graph`.

To learn more, run the command again with --verbose.
```

Note, that there are two versions of ethabi installed just before the error (v6.1.0 vs. v8.1.0). Until a few days ago these versions were still the same and the problem did not exist. Graph-node is pinned against 
```
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "graph-patches" }
```

This repo received a commit 2 days ago (https://github.com/graphprotocol/ethabi/commits/graph-patches). I believe this commit bumped the version number and thus caused the problem.

Would it be possible to pin the tagged versions of The Graph against specific commits rather than against branches which might update and become incompatible over time?

**Comment by leoyvens** [comment]
Hi, interesting that you are using the `graph` crate directly in a Rust project, out of curiosity, what are you building with it?

The problem there is that branch got rebased, until #1089 lands the latest commit will not be the one we are using. It might be good for us to pinpoint the commit in the `Cargo.toml`.

If you haven't already fixed it for your project, running:
```
cargo update -p https://github.com/graphprotocol/ethabi.git#ethabi --precise b2e44d8439d9712a5d911f9992112a4509f8a633
```
Should do it.

**Comment by fleupold** [comment]
> out of curiosity, what are you building with it?

We are using it to subscribe to Ethereum events with rust handlers (we already have a bunch of other 2nd layer infrastructure written in rust and would like to share logic between the event listener and the smart contract driver). This is the repo: https://github.com/gnosis/dex-services

**Comment by leoyvens** [comment]
Triage: Pinning the commit of our git dependencies is still a good idea.

**Comment by leoyvens** [comment]
Cargo gives a warning if you specify both a branch and a commit, so we can't really improve this.
