### ISSUE TITLE
Error when parsing the json-rpc id when using upstream rust-web3

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#1092]
When bumping our rust-web3 version for #1089, using vanilla upstream at this [commit](https://github.com/tomusdrw/rust-web3/tree/7c80ad3368d9a6d32ea92a91bca963268a16b9c2) all our json-rpc calls would fail with a deserialization error. On further investigation, it was specifically failing to parse the json-rpc id, which can be numerical or string but was numerical on this case.

I could not reproduce this inside an unit test in rust-web3, even with the exact same input to the exact same function that errors when called from graph-node. Even with all dependencies of `serde-json` locked to the same versions. [This workaround](https://github.com/graphprotocol/rust-web3/commit/1a5caf30d9c540a1f4f72775c0050273ba8fc831) was applied so that things work again. @Jannis and @olibearo observed the same in the past when debugging `jsonrpc-core-client` issues. We don't have any ideas at the moment for the root cause.

**Comment by Jannis** [comment]
@leoyvens Should we revisit this?

**Comment by leoyvens** [comment]
This is fixed in the upstream web3, as long as `features = ["arbitrary_precision"]` is set in the web3 dependency. We now have other patches in our fork so we can't just switch to upstream anyways.
