### ISSUE TITLE
Tokio runtime error when using callHandlers

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#1095]
The error is repeatable on my local machine and occurs for my test Betoken subgraph at block #8065416 on Ropsten. I have not pinpointed the culprit yet, but have stepped through to find that it appears to happen during or right after processing the traces for the block.  After the traces are converted to EthereumCalls one of the tokio runtime workers shows an error similar to the one below, then the entire runtime shuts down cancelling each thread and cleaning up.  I will post a more comprehensive set of logs and the mapping handler code in another comment.  

`thread 'tokio-runtime-worker-20' panicked at 'index 4 out of range for slice of length 0', src/libcore/slice/mod.rs:2569:5`

**Comment by leoyvens** [comment]
This is fixed, yes?

**Comment by olibearo** [comment]
Yes
