### ISSUE TITLE
Develop a cost model

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1098]
The [spec for the read interface](https://github.com/graphprotocol/research/tree/master/specs/graph-protocol-hybrid-network/read-interface) does not define the cost model for queries. That model needs to be developed based on measurements of representative queries, and taking the non-query overhead that an index node incurs into account.

**Comment by Jannis** [comment]
We're doing it but not tracking it via a graph-node issue, since it's outside graph-node anyway.
