### ISSUE TITLE
Stuck when a block in the log filter can no longer be found

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#1111]
As can be seen in [these logs](https://gist.github.com/iameli/18a4ab4d40ecefe2b43f5bccae319252), it can happen that we request `eth_getLogs` for a block hash which the Ethereum node no longer considers valid, and we then retry indefinitely. It's not clear if this issue persists across restarts. We should handle that error in a more robust way.

**Comment by iameli** [comment]
Confirmed that the issue persists across restarts - I actually produced that log by rebooting the node so we'd handle it expediently.

I've got a nicely automated deploy pipeline in place for that node, let me know if there's anything you'd like me to try!

**Comment by leoyvens** [comment]
@iameli could you try syncing the same subgraph again, but with some whitespace change so that it generates a different hash, and see if the error still happens?

**Comment by iameli** [comment]
Sure.
![image](https://user-images.githubusercontent.com/257909/62731631-7abfad00-b9d7-11e9-8f85-7b7578e9a0b0.png)
Syncing now, will check back in in ~2 hours

**Comment by iameli** [comment]
Precisely the same result, got to block https://etherscan.io/block/8272429 and stopped. Logs: https://gist.github.com/iameli/b0f34f5f377168a7f6304db909944720

**Comment by leoyvens** [comment]
@iameli Thanks, this is worse than I thought then. Could you link to the commit from which the subgraph was built, so that we can try to reproduce?

**Comment by iameli** [comment]
It's off of the tip of livepeerjs master: https://github.com/livepeer/livepeerjs/tree/master/packages/subgraph

Here's the exact IPFS file that's being used: https://graph.livepeer.org/ipfs/QmY7EY26HdgTPw6pMXZqkRDuksYm78PoTJ3fe3TZPC11RV

**Comment by iameli** [comment]
Update: it does get unstuck eventually after many hours of being on a particular block — we've made it as far as https://etherscan.io/block/8301996

**Comment by iameli** [comment]
Update again: we're all the way to https://etherscan.io/block/8324330!

Happy to arrange access to the Parity node this thing is syncing to if that would be helpful for y'all.

**Comment by leoyvens** [comment]
This hasn't been reproduced in a long time so I'm closing.
