### ISSUE TITLE
Entity serialization is slow

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1134]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`store.get` / `Entity.load` are currently slow because serializing even simple entities by allocating and writing to WASM memory is implemented in an inefficient way. We tracked this down to `AscHeap::asc_new` / `AscHeap::raw_new` causing a lot of small memory allocations, each of which take ~3-5ms. For a reasonably sized entity, this ends up at around 20-40 allocations and 150-200ms (locally, debug build).

What is likely taking so long under the hood is `memory.grow()` calls inside wasmi.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Clone and deploy any subgraph that uses `Entity.load` and follow the logs. You should see `Store get` messages that are fast, but `Done processing Ethereum event` messages that indicate the handler takes a long time (~500-1500ms):

```rust
Aug 24 20:20:25.758 DEBG Store get finished, time: 1ms, id: 0xd4fd252d7d2c9479a8d616f510eac6243b5dddf9, type: Account, block_hash: 0x3669b543ae19ed0a56c50f80f66e67d6dc3004e62bc3d848ecc2b95b42d253ee, block_number: 4161317, subgraph_id: Qmd1WDLn9QzX8tJYJyYh8AdCCjqqg3oqE8fDs4bQyjad7d, component: SubgraphInstanceManager
Aug 24 20:20:25.845 DEBG Store get finished, time: 3ms, id: 0xd4fd252d7d2c9479a8d616f510eac6243b5dddf9-0xe41d2489571d322189246dafa5ebde1f4699f498, type: AccountBalance, block_hash: 0x3669b543ae19ed0a56c50f80f66e67d6dc3004e62bc3d848ecc2b95b42d253ee, block_number: 4161317, subgraph_id: Qmd1WDLn9QzX8tJYJyYh8AdCCjqqg3oqE8fDs4bQyjad7d, component: SubgraphInstanceManager
Aug 24 20:20:26.101 INFO Done processing Ethereum event, waiting_ms: 0, total_ms: 1331, handler: handleTransfer, signature: Transfer(indexed address,indexed address,uint256), block_hash: 0x3669b543ae19ed0a56c50f80f66e67d6dc3004e62bc3d848ecc2b95b42d253ee, block_number: 4161317, subgraph_id: Qmd1WDLn9QzX8tJYJyYh8AdCCjqqg3oqE8fDs4bQyjad7d, component: SubgraphInstanceManager
```

**What is the expected behavior?**

The expected behavior is that each handler takes only a few milliseconds, even with `store.get` / `Entity.load` involved. The serialization of an entity to WASM should ideally only take <5ms overall.

**Comment by MaxGraey** [comment]
Also you could thy [this PR](https://github.com/AssemblyScript/assemblyscript/pull/790) which improve detection when `memory.grow` should call
