### ISSUE TITLE
Docker image stuck on "Connecting to Ethereum...." on linux

### ISSUE THREAD

**Issue by isaacmtz90** [graphprotocol/graph-node#1147]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Spinning up the docker image for a graph node get stuck on the `Connecting to Ethereum..., network: mainnet` message.. It doesn't finish up connecting, neither fails the connection after a considerable amount of time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 - install docker/ compose/ ganache 
 - Clone the repo
 - cd to `/docker` 
 - run  `sh setup.sh` to get the host's ip. 
 - confirm that the right host ip is on the `docker-compose` file. 
 - run `ganache-cli` make sure it starts on port `8545`
 - run `docker-compose up`

The image downloads properly and starts `postgres` and `ipfs` servers. When starting the graph node it gets stuck on the `Connecting to Ethereum` step. Left it running for around 40 minutes and nothing else happened.

![image](https://user-images.githubusercontent.com/5839644/64067727-7c514f00-cbea-11e9-85c2-9cc6cb22bc4d.png)

Ganache server was running and listening on `127.0.0.1:8545`, but the same behavior happened when there was no server up to connect to.

*Additional info*
- OS: Manjaro linux kernel 4.14.121-1-MANJARO  64-bit
- Ganache version: Ganache CLI v6.6.0 (ganache-core: 2.7.0)
- Docker version: version 18.09.6-ce, build 481bc77156
- Docker-compose version: 1.24.0,

**What is the expected behavior?**
Running the docker image with the proper host ip set should connect to the local running instance of ganache, or display a message that it failed to connect.

Let me know if  I can help with any extra info to reproduce/debug it

**Comment by isaacmtz90** [comment]
This seems to be an issue with the docker networking on arch Linux. I solved by running ganache inside docker as well.

**Comment by Jannis** [comment]
@isaacmtz90 How am I only seeing this now? Sorry. The problem is Ganache actually. It binds to `127.0.0.1:8545` but that is the loopback network device and can't be reached by Docker images.

Doing `ganache-cli -h 0.0.0.0` makes Ganache bind to `0.0.0.0` instead, which _can_ be reached from within Docker. But running Ganache inside Docker as well also works. 😄

**Comment by Jannis** [comment]
We added this information to our docs a while ago just to be sure: https://thegraph.com/docs/quick-start#local-development
