### ISSUE TITLE
"deadline has elapsed" error should not cause subgraph failure 

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#1148]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Failed to resolve subgraph files using IPFS, error: Subgraph resolve error: resolve error: deadline has elapsed - cause subgraph failure 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
"deadline has elapsed" error should not cause subgraph failure

**Comment by Jannis** [comment]
This will be resolved with #1336.

**Comment by Jannis** [comment]
This has been released with https://github.com/graphprotocol/graph-node/releases/tag/v0.16.1 and is going up to our staging environment right now.
