### ISSUE TITLE
Revamp Store.ancestor_block

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1186]
This method is used to retrieve an ethereum block a certain number of steps away from the subgraph head pointer. It is used only in [one place](https://github.com/graphprotocol/graph-node/blob/master/datasource/ethereum/src/block_stream.rs#L507) and there we only use the `parent_hash` of that block.

Since blocks can by quite large (up to 200kB, average of 60kB), this causes quite a bit of unnecessary data transfer. It would be much better to either only retrieve the `parent_hash` or do the check in which that is used in the database. Since `parent_hash` is a column on `ethereum_blocks`, we don't even need to touch the actual block data.

**Comment by leoyvens** [comment]
I believe this was done.
