### ISSUE TITLE
Do not use 'any' in queries that only look for one kind of entity

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1203]
The [ethownership](https://thegraph.com/explorer/subgraph/arachnid/ethownership) subgraph has 34M entities. The GraphQL query

```
erc20Ownerships(first: 5) {
    id
    contract
    account
    balance
}
```

gets turned into this SQL query:
```
SELECT data, entity
  FROM sgd1595.entities
 WHERE entity = ANY('{ERC20Ownership}')
 ORDER BY id ASC LIMIT 5
```

Because of the `ANY` clause, Postgres turns that query into a full table scan of `entities`, which is very slow. Rewriting the query to use `entity = 'ERC20Ownership'` results in a query that uses the primary key index on `entities` and returns almost instantly.

**Comment by leoyvens** [comment]
Done in #1231.
