### ISSUE TITLE
Make subgraph loading from IPFS more robust by retrying

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1239]

**Comment by orenyodfat** [comment]
currently the subgraph crash with : 
`Failed to resolve subgraph files using IPFS, error: Subgraph resolve error: resolve error: api returned unknwon error ' <html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8"> <title>502 Server Error</title> </head> <body text=#000000 bgcolor=#ffffff> <h1>Error: Server Error</h1> <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2> <h2></h2> </body></html> '`

**Comment by Jannis** [comment]
The 502 error means the IPFS node itself timed out. Usually, that only happens when the file is not pinned or can't be retrieved from the network. 

In this case, this is about the subgraph files themselves, not `ipfs.cat` being called from mappings. So we know that the files are pinned. We also know that because this is about the IPFS files that the timeout is 60 seconds (default).

A timeout in this case is unexpected. I have two theories:

1. The requests are rate-limited and too many IPFS files being fetched at once cause requests to time out. I'll have to double-check if we set things up this way, but if this is the case, the solution is to bypass any rate-limiting between the index nodes and the IPFS node.

2. IPFS itself can't handle the amount of requests and craps out. I'll double-check the logs and see what I can find out. The 502 does suggest that the timeout is inside the IPFS container, so this is my main theory at this point.

Either way, retrying (by restarting the index node responsible for the subgraph) has always helped so far, so retrying automatically will avoid this problem. We'll see if we can also identify and fix the root cause but if it's inside IPFS itself then I'm not too optimistic.
