### ISSUE TITLE
Custom ordering of event and block triggers

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#1263]
There are a few levels to this, as @leoyvens mentioned:
- You could just order events and the block as two groups - i.e. block first, events next, or events first and block last. Right now it is block triggers last. I actually need the block trigger first for my mappings
- You could order every single event, and block trigger however you want (and call triggers or any other triggers we add in the future)
- We could have no order, so that they could potentially be ran in parallel

AFAIK, just supporting my situation makes a lot of sense to do soon, and probably isn't hard. In general, I would imagine events should be ordered in the order that ethereum processes them, I can't think of a reason right now where you would do it custom (but there could very likely be a good reason).

Parallelizing them is a deeper discussion, but it doesn't seem like that is something we need to contribute resources to right now. 

I can work around this for now, but added this in within a few weeks would be nice!

**Comment by leoyvens** [comment]
I think the first step would be to allow a manifest config such as:
```
processOrder:
  - blocks
  - events
  - calls
```
This could be per data source.

**Comment by Jannis** [comment]
There are no plans to do this for now.
