### ISSUE TITLE
Revamp internal handling of GraphQL schemas

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1265]
We currently operate solely on the AST we get from `graphql_parser`, which is clumsy and requires lots of helpers. As a consequence, [this file](https://github.com/graphprotocol/graph-node/blob/master/graphql/src/schema/ast.rs) has become a dumping ground of various helpers, and code dealing with GraphQL schemas is harder to follow than it has to be.

We should turn the AST into a data structure that more directly reflects how we use GraphQL schemas in `graph-node`.

**Comment by Jannis** [comment]
I'd prefer if we stick to the GraphQL AST. With helpers like the ones we have, it becomes easy enough to work with. An abstraction on top of it would have to replicate all the features that are in GraphQL already, and due to the different schemas, there's a lot we can't type other than with opaque types like string -> value maps etc.

I do agree though that we could consolidate the helpers into `graphql_parser` extension traits.

**Comment by lutter** [comment]
There's (at least) two things that make any code that works with the GraphQL AST harder to read and follow than it has to:

(1) because the helpers get you some convenience of pulling things from the AST, but not everything you need, trivial AST traversal logic is interspersed with the actual logic of what the AST user is trying to do and it takes quite a bit of time to tell the two apart

(2) since the AST can represent data structures that are more general than what we allow in schemas, and since we do not transform at all after validation, there's a lot of places where the code looks like it could run into an error, but we know it can't because of the restrictions we put on schemas. For example, `get_root_query_type` is always followed by some form of `unwrap()`, even though we know there is one; similarly, code pretends that lists can be arbitrarily nested, even though we know that we only allow one level of list nesting.

Both these things not only make the code hard to read, but they also open the door for subtle bugs because there's a lot of knowledge that should be encoded in types that's just implicit in how we handle these data structures.
