### ISSUE TITLE
Exception while running introspection query

### ISSUE THREAD

**Issue by napolean0** [graphprotocol/graph-node#1280]
Hi Team,

I am trying to get schema of graphql using introspection query with apollo client. The same query works on explorer: https://thegraph.com/explorer/subgraph/ensdomains/ens
However it's giving me below error multiple times:

```
GraphQL error: Null value resolved for non-null field `__typename`
GraphQL error: Null value resolved for non-null field `__typename`
```

Can you please help?

npm packages version
```
"apollo-cache-inmemory": "1.6.2",1
"apollo-client": "2.6.0",
"apollo-link-http": "1.5.15",
"graphql": "14.3.1",
"graphql-tag": "2.10.1",
"node-fetch": "2.6.0",
"typescript": "3.6.2"
```
I am using below code to fetch the schema.

```
import { createHttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import ApolloClient from 'apollo-client';
import gql from 'graphql-tag';
import fetch from 'node-fetch';

let query = "query IntrospectionQuery{__schema {types {name description fields { name type { ofType {name}}}}}}";
let subgraphEndPoint = 'https://api.thegraph.com/subgraphs/name/ensdomains/ens';
let link = createHttpLink({ uri: subgraphEndPoint, fetch: fetch as any });
let cache = new InMemoryCache();
let variables = {}
let apolloClient = new ApolloClient({ link, cache });
let gqlQuery = gql(query);
apolloClient.query({query: gqlQuery,variables,fetchPolicy: 'no-cache'}).then(console.log);
```

**Comment by Jannis** [comment]
As said on Discord, I'm not 100% sure the introspection schema is supposed to also have `__typename` on returned objects. Here's how you can make this work though: Instead of
```js
let cache = new InMemoryCache();
```
use
```js
let cache = new InMemoryCache({ addTypename: false });
```
Note: Only do this for introspection queries. The cache works better if it uses type names, so for real application data, set the flag to true (or omit it). The GraphQL API in graph-node supports `__typename` on subgraph schemas.

**Comment by leoyvens** [comment]
No reason why introspection objects shouldn't have `__typename`, good that there is a workaround but this is a bug.

**Comment by quilldata** [comment]
Thank you @Jannis @leoyvens.
Solution works for me.
You guys rock 👊
