### ISSUE TITLE
Unexpected key in map: startBlock

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1325]
In the documentation
https://github.com/graphprotocol/graph-node/blob/master/docs/subgraph-manifest.md#151-ethereumcontractsource
it states that I can use `startBlock`

but I get the following error

```
Path: dataSources > 0 > source
  Unexpected key in map: startBlock
```

In order to test my subgraph it would be great if I could start at a later block as this take ages to reach where it errored out.

I see that there is https://github.com/graphprotocol/graph-node/issues/1131 and the PR https://github.com/graphprotocol/graph-node/pull/1262

But from what I read it is unclear whether the documentation is accurate. Or maybe the changes has not been deployed yet ?

**Comment by Jannis** [comment]
The feature is on master but hasn't been released yet. 0.16 is coming very soon.
