### ISSUE TITLE
Time-travel queries

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1329]
With relational schemas (#1159) we now have the backend plumbing for time-travel queries in place. What's missing to close out #813 is a way for users to access that functionality, and pass a specific block (number) at which a query should happen to the store.

There's a few ways in which this could be surfaced. My favorite options are either through a directive or a filter. We'd really want to restrict this to the top level of a query since it doesn't really make sense to mix different block heights in the same query. Either way, users should be able to either tell us a block number or a block hash at which a query should be run.

This would look like one of these variants:
```
users(...) @block(number: 5) { .. } 
users(...) @block(hash: "0xdeadbeef") { .. }
users(block_number: 5, ..) { .. }
users(block_hash: "0xdeadbeef", ..) { .. }
```

If they give us a hash, we first map it to the block number; strictly speaking, we should check that that hash is an ancestor of the current head block of the subgraph, but that can be an expensive query, since it needs to traverse the `hash -> parent_hash` pointers in blocks in the database. We could limit that search by treating blocks a certain distance behind head as final, as we do with the ingestor though.

**Comment by Jannis** [comment]
IMHO, having it as an argument on the fields feels more intuitive than a directive. 

A few additional considerations:

1. This will have to support multiple networks, across the Ethereum ecosystem but also on other blockchains. As such a single block directive or argument won't be sufficient.

2. It _could_ be useful to support a different block / point in time at each level of a query. Whether there are use cases for this is an open question but if we route/execute queries level-by-level anyway, this may be almost trivial to support.

**Comment by Jannis** [comment]
The initial thinking about this was done in https://github.com/graphprotocol/graph-node/issues/813.

**Comment by lutter** [comment]
If we make this an argument on fields, then specifying it for different networks is easy, since each collection/field belongs to exactly one network, i.e., it is possible to write

```
users(block: {number: 7000}) {
  accounts(block: {hash: "0xdeadbeef"}) {
    id
  }
}
```

That would work both if `users` and `accounts` come from the same network, but also if they are on different ones.

We would want the `block` argument to inherit downward so that users don't have to specify it everywhere, i.e., in  the query `users(block: {number: 7000}) { accounts { id } }` we would query both `users` and `accounts` at block 7000 if they are on the same network; if `accounts` is on a different network, it would be queried for the latest block there. So in summary, we would have the following:

* each field has an optional `block` argument, which is a hash that can either contain a `number` or a `hash`
* if the argument is not given, `block` defaults to the latest block
* descendant fields on the same network use the same block as the parent
* descendant fields on a different network use the latest block for that network, or one that is explicitly specified, but do not inherit the block from their parent
* we probably also want a way to say 'use the latest block for this child field' for completeness sake,  `users(block: {number: 7000}) { accounts(block: {latest: true}) { balance } }` would return the current balance of accounts for users that existed at block 7000

**Comment by Jannis** [comment]
- Both `latest` and `number` are moving targets and so for the sake of determinism, we may not want to allow them. Having said that, the pre-network graph-node will need to support querying the latest. Not sure what the best approach is to allowing it now but disallowing it later in the network. Perhaps allowing it could be a GraphQL API v1 thing.

- The read interface later can make the block hashes mandatory and leave it to the query engine to provide them. The query engine in turn would take queries with or without block information and, when appropriate, would tack the latest block hashes onto the read interface queries before sending them over to graph-node.

- I like the `block` argument at each level. It makes sense when you think about how queries will be split up and distributed in the network.

**Comment by leoyvens** [comment]
The solution of cascading the top level block number and defaulting to latest is cool, but I'd suggest supporting the block parameter only in top level fields for now. Mixing block parameters in children has no use case at the moment, and we don't know yet if that will constraint or complicate the implementation somehow.

**Comment by lutter** [comment]
The cascading stuff was in response to a comment earlier that this had to work with multiple networks; I agree that there is no need for that right now, but it shows how just a toplevel block argument could be generalized for that.

The `number` makes it much easier on humans to write queries at a certain block height. That still fits with keeping things deterministic as long as the response contains the actual block hash, so that the result can be checked by running that query again with that block hash.

For the initial implementation, I therefore suggest the following subset of functionality:

* queries support an optional `block` argument on the toplevel field which can contain either the `number` or `hash` of the block(i.e., `users(block: { number: 42 }) { .. }` or `users(block: {hash: "0xdeadbeef" }) { .. }`)
* if there is no `block` argument, it defaults to the latest block for that network
* the response will contain a `block { "$network_name": { hash: "0xdeadbeef", number: 43 } }` entry next to the `data` and `errors` keys that we currently include in the response

Once we support querying multiple networks we can expand this along the lines of my previous comments

**Comment by lutter** [comment]
Actually, we can simplify the `block` argument by typing it as `Int | Bytes` where an `Int` is interpreted as the block number, and `Bytes` as the block hash, so that you can write `users(block: "0xdeadbeef") { .. }` and `users(block: 7000) { .. }`

**Comment by lutter** [comment]
Based on the discussions we had, the proposal to expose time-travel queries in the current GraphQL API is:

* the toplevel field for a query takes an optional `block` argument. That argument is a hash that can either contain `hash`, `number`, or `latest`
* if the `block` argument is not present, we use the latest block

Examples:
```
users(block: { number: 7000 }) { ... }
users(block: { hash: "0xdeadbeef" }) { ... }
users(block: { latest: true }) { ... }
```

**Comment by yanivtal** [comment]
The block parameter should only accept block hashes. Block numbers aren't deterministic. We also can't support the undeterministic behavior of returning the latest block if no block is specified. This should be a breaking change (maybe in the GraphQL V2 API?) that requires block hashes to be set.

What should we do if a subgraph supports multiple networks? I know we've bounced around on that.

**Comment by Jannis** [comment]
@yanivtal David's proposal is specifically for the v1 API. Indeed, in v2, we'll need to get rid of the number and implicit latest, as discussed.

**Comment by leoyvens** [comment]
My understading was that it would be the same API in v2, because the query engine will resolve the block numbers client-side. It would be bad ergonomics to require the user to input the block hash on every query.

**Comment by Jannis** [comment]
Eh, yes, indeed. Sorry. We're still confusing the GraphQL API and the read interface in this discussion. 😄
