### ISSUE TITLE
Support "latest" Block Views

### ISSUE THREAD

**Issue by dOrgJelli** [graphprotocol/graph-node#1333]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Smart Contract view methods are called on the current block the subgraph is processing.

**What is the expected behavior?**
Support calling a view method on the "latest" block of the chain.

For example:
```typescript
const registrySC = Registry.bind(address);
const value = registrySC.mappingProp(key, "latest");
```
Note: `mappingProp` above refers to an EVM `mapping(key => vaue)`

**Comment by Jannis** [comment]
The main problem with this is that `latest` is a moving target and therefor, these calls would not be deterministic.

**Comment by dOrgJelli** [comment]
Ahhh shoot okay, thank you for the response. Going to close this issue.
