### ISSUE TITLE
Optimize the mapping timeout check by not always checking

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#1337]
We inject calls to the "gas" function, which actually checks a timeout, all over the WASM module, so this function is by far the hottest part of our code. It does a call do `Instant::elapsed()` on every call, this does a syscall to get the current time which becomes a noticeable slowdown. We can optimize this simply by checking the timeout only every 100 calls for example, making most calls a noop.

**Comment by Jannis** [comment]
How much time do we spend on this check?

**Comment by leoyvens** [comment]
In the order of 100ns per call, being called from 1k to 10k times per event, so the overhead could even reach 1ms per event. Reducing that by 100x should be enough to make it negligible.
