### ISSUE TITLE
Remove old object-by-object resolution from StoreResolver

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1340]
The `StoreResolver` still contains the old resolution code (without prefetching) so we can fall back to it and so we can compare query results. Once we are confident that the prefetching code does not contain any more bugs, we should

* remove the object-by-object resolution code from `StoreResolver` (in `resolve_object` and `resolve_objects`)
* remove the `GRAPH_GRAPHQL_NO_PREFETCH` environment variable

**Comment by Jannis** [comment]
Done
