### ISSUE TITLE
Fail subgraph if contract calls are not supported by the Ethereum node

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1351]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When graph-node runs against a non-archive Ethereum node, contract calls are not supported. However, when making contract calls from a subgraph on such a node, it simply retries forever. All it logs are debug messages that are easy to miss if you don't have debug logs enabled with e.g. `--debug` or `GRAPH_LOG=debug`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Connect graph-node to a non-archive Ethereum node.
2. Deploy a subgraph that makes contract calls.
3. Observe that it retries making the first contract call forever with no chance of recovering.

**What is the expected behavior?**

When a subgraph on such a node makes a contract call and it fails with an error like
```rust
Nov 14 14:18:17.159 DEBG Trying again after eth_call RPC call failed (attempt #1)
with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "This request
is not supported because your node is running with state pruning. Run with --pruning=archive.",
data: None }))), block_hash: 0xb4d3413066344d8f76368c0bd98c4a52184b9366e401215ffd0bf2e73e369b59,
block_number: 118842, subgraph_id: Qmaf6AFkpPWkULhyza2GT68NotJVL671JK2zjiLcR2Uczd,
component: SubgraphInstanceManager
```
we should immediately fail the subgraph, because there is no chance for it to ever get past this. Not all developers have the graph-node started with e.g. `--debug` and might think the call just hangs forever (which it kinda does).

**Comment by leoyvens** [comment]
We currently get that response routinely when connected to Alchemy, it goes away after retrying a few times. This looks like an issue on their end but for as long as that's happening we don't want to fail the subgraph on this case.

**Comment by Jannis** [comment]
This is expected to only happen with non-archive nodes (e.g. full nodes), which is why it was reported originally. But indeed, we're also seeing this against Alchemy where it is unexpected.

**Comment by leoyvens** [comment]
So, Alchemy has clarified that this is not particular to their service, because Parity will return that if you make an `eth_call` to a non-existing block. This can happen if the node that gets the `eth_call` is behind or if there was a reorg. This ties in with https://github.com/graphprotocol/graph-node/issues/400, because if we did `eth_call` by hash and a reorg happened, this would retry forever! Possibly if this retries too much, we should start over the block processing.

**Comment by leoyvens** [comment]
Now that we have the capabilities feature, this is solved.
