### ISSUE TITLE
Feature request: ENS integration

### ISSUE THREAD

**Issue by PaulRBerg** [graphprotocol/graph-node#1355]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**

I have a list of transactions with "from" and "to" address fields. When I render them in my app, I fetch the ENS domain after the UI loads, so there is a glitch for the time it takes to fetch the data. 

**What is the expected behavior?**

Ideally, I could add fields for the ENS domains (if any) for "from" and "to". I know about the [ENS subgraph](https://github.com/graphprotocol/ens-subgraph), but I'm not sure if I can query that data from my subgraph mappings.

**Comment by Jannis** [comment]
You can't query that data from the subgraph right now but we're working on a feature called subgraph composition right now that will allow your subgraph to reference entities in other subgraphs

This is the tracking issue: https://github.com/graphprotocol/graph-node/issues/1202

**Comment by neysofu** [comment]
This is now possible :rocket: https://github.com/graphprotocol/ens-rainbow.

**Comment by PaulRBerg** [comment]
Cc @razgraf and @gavriliumircea - this might be useful in V2 Interfaces.
