### ISSUE TITLE
graph failing with SubgraphSyncingFailure

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1364]
Getting the following error in my graph :

```
Subgraph instance failed to run: Error while processing block stream for a subgraph: store error: invalid byte sequence for encoding "UTF8": 0x00, code: SubgraphSyncingFailure, id: QmWHc5DG8PYTL8xJKZrekR5YtMp6swnBxSpL75LKRj5GAT
```

And as debug, we get this log before :

```
Subgraph stopped, WASM runtime thread terminated
```

**Comment by leoyvens** [comment]
Could you include reproduction instructions, with a link to a repo and commit of the subgraph on which you saw this?

**Comment by wighawag** [comment]
Hi @leoyvens sorry for the lack of details

The graph is the following https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph?selected=logs

the repo is : https://github.com/wighawag/eip721-subgraph

Unfortunately I am not sure which commit is representative as I was playing with various thing

**Comment by ianlapham** [comment]
Was this resolved? Dealing with essentially the same error on a separate subgraph.
