### ISSUE TITLE
New subgraph assignments are not always picked up

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1373]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When new deployments are created, the registrar in graph-node reconciles the subgraph assignments and writes assignment changes to the store. At the same time, the registrar subscribes to the store for entity changes, specifically those involving deployment assignments.

It looks like not all of these changes are coming through. Just today we had a case where the assignment changes for a new deployment were written (https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/registrar.rs#L800-L811 + https://github.com/graphprotocol/graph-node/blob/master/graph/src/components/store.rs#L880-L891) and we saw the
```rust
Nov 22 02:33:42.808 DEBG Adding subgraph node assignments for 1 subgraph deployment ID(s) 
(QmSyTT5AXp2dCxJ6NsqrGiRcuyPZMF995cHN2HfFxb16wt), subgraph_id: 
QmSyTT5AXp2dCxJ6NsqrGiRcuyPZMF995cHN2HfFxb16wt, component: SubgraphRegistrar
``` 
log message that confirms this. We also saw one `Set` and several `Remove` changes being processed in https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/registrar.rs#L162-L163:
```rust
TRCE Received assignment change, entity_change: EntityChange { subgraph_id: 
SubgraphDeploymentId("subgraphs"), entity_type: "SubgraphDeploymentAssignment", entity_id: 
"QmSyTT5AXp2dCxJ6NsqrGiRcuyPZMF995cHN2HfFxb16wt", operation: Set }, component: 
SubgraphRegistrar
```
But after that, the specific node that was assigned this deployment (the same that the logs are from, so it _did_ receive the `Set` change) never started the deployment.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not sure.

**What is the expected behavior?**

The expected behavior is that after the 
```rust
Received assignment change ... operation: Set
```
log, the deployment starts indexing on the target node.

**Comment by Jannis** [comment]
One suspicion I have (may be a red herring) is that there is a race condition between the assignment change being received and the subgraph version/deployment being written to the store.

The reason I'm thinking this is because the following log is coming through _after_ the assignment changes have been handled:
```rust
Nov 22 02:33:44.597 DEBG Wrote new subgraph version to store, subgraph_hash: QmSyTT5AXp2dCxJ6NsqrGiRcuyPZMF995cHN2HfFxb16wt, subgraph_name: protofire/aragon, subgraph_id: QmSyTT5AXp2dCxJ6NsqrGiRcuyPZMF995cHN2HfFxb16wt, component: SubgraphRegistrar
```

So could it be that when this happens, we can't start the deployment yet because it hasn't been written to the database yet?

**Comment by lutter** [comment]
> So could it be that when this happens, we can't start the deployment yet because it hasn't been written to the database yet?

That's not possible since `Store.create_subgraph`[https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/store.rs#L1010-L1021] applies the changes and sends the event in one transaction; the send only happens when the transaction commits, and therefore anybody who receives the notification will also see the metadata changes.

It would be good to put some logging [here](https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/registrar.rs#L204) to make sure we didn't miss anything. Is there any way that the assignment was deleted in between sending the `Set` event and processing it?

For the timestamp on the `Wrote new subgraph` log message, I am not sure what causes the delay, but it is written in a separate future, so there is a scheduling delay in between calling `create_subgraph_version` and logging about it.

**Comment by leoyvens** [comment]
Closing, I don't think this is happening anymore.

**Comment by lakshman-jdp** [comment]
90% of the it happens. If you make changes to subgraph then you have to create new subgraph domain and deploy there otherwise it will not effect. If you have made 100 changes in 100 different times then 100 deploys & 100 different domains for one single contract

**Comment by lutter** [comment]
> 90% of the it happens. If you make changes to subgraph then you have to create new subgraph domain and deploy there otherwise it will not effect. If you have made 100 changes in 100 different times then 100 deploys & 100 different domains for one single contract

@lakshman-jdp Can you describe what exactly happens? When you have a subgraph that is already synced, deploying a new subgraph will create a pending version (top right of the subgraph details page in the explorer) that will only replace the current version when it finished syncing which can take quite some time. IOW, deploying a new version will only replace the current version with possibly significant delay.
