### ISSUE TITLE
Optimize store.get and store.set

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1381]
In https://github.com/graphprotocol/graph-node/issues/1347#issuecomment-555539043 we have identified `store.get`/`store.set` to take up the majority of indexing time (~30-50%). Optimizing these should significantly boost indexing performance.

Next steps:

1. Plan specific optimizations (like for non-existent entities).
2. Implement them.

**Comment by leoyvens** [comment]
Discussing with @lutter, we decided to start with some straightforward improvements to the entity cache, which are not going to the DB for validation if we can help it, and loading entities in a single DB query in `as_modifications`. After these we can evaluate doing a bloom filter for non-existing entities or better caching for existing entities.

At least for now we don't see a need for a user-facing `store.overwrite` or `store.insert`, we'd like to optimize as much as possible without complicating things for the user.

**Comment by leoyvens** [comment]
Update: The optimizations for `store.set` are done, the next target is `store.get`, I'll evaluate the impact of the bloom filter and plan it in detail if it has the large impact.

**Comment by leoyvens** [comment]
Optimizations have now been implemented for store.set and store.get, so that they are no longer among the most time consuming sections. There is more that can be done, such as the bloom filter, but I feel we've done enough in the context of this issue.
