### ISSUE TITLE
Migrate subgraph metadata to relational storage

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1394]
The metadata for subgraphs (in the `subgraphs` database schema) still uses JSONB storage; it needs to be moved to relational storage so we can eventually delete the JSONB storage code.

There's two big things that need to be done here:

* write a database migration that creates a relational `subgraphs` schema and copies the data from the `entities` and `entity_history` tables into that schema
* make it possible to not record history for certain entities/tables as only subgraph metadata related to dynamic data sources should be versioned, and at least for the case of `SubgraphDeployment` versioning the data is completely nonsensical and would lead to enormously bloated tables

**Comment by leoyvens** [comment]
We can only delete JSONB code after dropping support for subgraphs that were deployed under it, right? Or if we put those on a legacy system that stops getting updates.

Regarding the issue with only the dynamic data sources needing history, I wonder if we want to keep those in a shared table or move them into the per-subgraph schema.

**Comment by lutter** [comment]
Yes, we absolutely need to have all subgraphs use relational storage before we can delete the JSONB code. We will also need to come up with and communicate a deprecation plan to users (on their end, it will consist of "Redeploy your subgraph by this date/release")

In prod, we currently have 460 JSONB subgraphs and 322 relational ones, so it looks like the natural cycle of updating subgraphs is taking care of a lot of this; but there will be a point where we need to identify inactive JSONB subgraphs and come up with a plan for how to move them forward or delete them with the owner's consent.

Either way, as long as subgraph metadata uses JSONB storage, it won't be possible to move away from JSONB.

As for dynamic data sources: I was going to leave them in shared tables, simply because it will reduce risk when making this change. Longer term, I think it's a worthwhile goal.
