### ISSUE TITLE
FEATURE: Parameterized dynamic data source

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#1404]
It would be nice to be able to provide parameters to dynamic data sources that are available in the mappings of the data source.

The use case we have for Melon is this:

When a fund is created, we also pass some addresses from the current `Version` contract of the network. One of these is the `PriceFeed` contract The `PriceFeed` is controlled by an off-chain component that sends an `update` transaction every 24h. This transaction triggers a `PriceUpdate` event that we are currently globally listening to.

The event handler for this event is then used to globally update some values (new prices for the supported assets in the network, etc.). But we also use it to then loops through all funds of the current version and computes a few new performance values for each fund. 

This is problematic because it doesn't scale well and also doesn't work anymore once the `PriceFeed` contract is replaced when a new `Version` is deployed. The loop also only conceptually works because our `Version` contract has a list of all `Funds` that it has deployed. This is a trait of our contract but shouldn't be required for such a setup to work.

I want to be able to generate multiple dynamic data sources for the same eventful target contract (e.g. our `PriceFeed`) and pass additional parameters to it so that during the execution phase of the mapping I can load the `Fund` and re-compute values for it without storing a list of addresses to loop on in our contract.

**Comment by Jannis** [comment]
I'll try to repeat the request in my own words to confirm I understand the use case.

There is one `PriceFeed` contract with a `PriceUpdate` event. Currently, you're handling this in a single, global data source and loop over all `Fund`s to update them after a price update. This only works because there the list of `Fund` contracts is stored in another contract and that allows the `PriceUpdate` handler to loop over them.

What you would like to see is the ability to create data sources from templates with some contextual information. Specifically, in this situation, you would like to create multiple dynamic `PriceFeed` data sources, each with a `Fund` address on its context. Each of these would monitor the same `PriceFeed` contract with the same `PriceUpdate` event handler. In this handler, each of them would then be able to get the `Fund` address from its context and update only this fund.

Instead of looping over all, say, N funds in one handler, there would be N dynamic `PriceFeed` data sources with a different fund address, each responsible only for updating that particular fund.

**Comment by leoyvens** [comment]
An alternative to `dataSource.context()`, which would presumably load all context variables at once, would be an API such as `dataSource.getContext("fund")` to pull only the necessary variables as needed.

**Comment by ajcronk** [comment]
Has this issue been worked on elsewhere? Would you be open to receiving a PR for it?  Or a better route to prioritize?

**Comment by leoyvens** [comment]
@ajcronk I'm working on this, expect it to land on master this week. What's your use case for it?

**Comment by ajcronk** [comment]
> @ajcronk I'm working on this, expect it to land on master this week. What's your use case for it?

Great news! We were chatting with @adamsoffer about using this feature on the Livepeer subgraph. Will be very helpful.

**Comment by adamsoffer** [comment]
@leoyvens Yeah, I chatted about this with Jannis briefly a while back. Livepeer has a similar use case where every time a delegate calls `reward()` and a `Reward` event is emitted, we would need to loop through all delegators bonded to the delegate that called `reward()` and update their reward shares which didn't scale. 

So I believe the same user story holds: 

> What you would like to see is the ability to create data sources from templates with some contextual information. Specifically, in this situation, you would like to create multiple dynamic 
**`BondingManager`** data sources, each with a **`Delegator`** address on its context. Each of these would monitor the same **`BondingManager`** contract with the same **`Reward`** event handler. In this handler, each of them would then be able to get the **`Delegator`** address from its context and update only this **`Delegator`**.

> Instead of looping over all, say, N **`Delegators`** in one handler, there would be N dynamic **`BondingManager`** data sources with a different **`Delegator`** address, each responsible only for updating that particular **`Delegator`**.

One improvement to this strawman design that just occurred to me would be the ability to conditionally trigger dynamic data sources monitoring a specific event based on context. In the case of Livepeer, according to this design, it seems *every* dynamic data source monitoring the `Reward` event (every bonded delegator) would get triggered. But ideally, we only trigger those that contain the delegate that called reward as part of its context. Or in the case of Melon, not every fund is going to contain let's say, DAI. If the price of DAI gets updated, you don't necessarily want to update every fund, but rather only those that contain DAI in its context. Of course, you can do this check inside the handler itself, but I imagine it wouldn't be as performant.

**Comment by leoyvens** [comment]
Hey @adamsoffer, thanks for joining the discussion. The overhead of having this ignore logic in the handler itself is small, in the order of a couple ms per call, and there's room for optimizing that further. Even so I can see how that would be a meaningful performance impact if we're talking about `n_data_sources*n_events` being in the scale of millions.

Once this feature ships and you have the updated subgraphs deployed and synced, let me know so I can check the performance statistics and estimate how much of a gain there is with that optimization.

**Comment by adamsoffer** [comment]
Sounds good! Thanks, @leoyvens. Excited for this feature.

**Comment by adamsoffer** [comment]
FYI in the case of Livepeer, as of now, it would be around 42 data sources x 2538 events. (42 delegates x 2538 delegators)
