### ISSUE TITLE
Change default order in GraphQL queries

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1407]
Right now, we order collections in GraphQL queries by `id`when the user does not specify an order. In one example I was looking at, such a query took ~ 300ms, most of that time went into sorting results. Changing that query to order by `vid` instead sped up the query to ~60ms.

Since the only reason we order by `id` is so that entities are always in a consistent order for paging etc. it would be better to sort by `vid` which would return them in the order they were inserted/last updated. We might even want to default to `vid desc`, so that entries appear in reverse chronological order.

The query in question is part of a larger GraphQL query from Livepeer (and the change would be in the `order by` in the `rank() over ...`:
```sql
select 'Pool' as entity, to_jsonb(c.*) as data
from (
	select c.*,
	       rank() over (partition by c.g$parent_id order by	id nulls last) as g$pos
	from (
		select c.*,	c."delegate" as g$parent_id
		from "sgd9402"."pool" c
		where
			c."delegate" = any(array['0x21d1130dc36958db75fbb0e5a9e3e5f5680238ff',
			'0x31990bebc4fd07ac4898e7c67210f38651f1d2e8',
			'0x43793ab4a56e5d4c263e6320d59072e01819b6c9',
			'0x4712e01e944802613de3a0a6d23274e7e0243015',
			'0x481efb669b423cfaffa49890205427dea9b3d693',
			'0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc',
			'0x4ff088ac5422f994486663ff903b040692797168',
			'0x525419ff5707190389bfb5c87c375d710f5fcb0e',
			'0x88e103b26e1a4ce226739d37d356b22afbfeed85',
			'0x8d3803ecfe86afbb25899a806b46714914b0a4b5',
			'0x9c10672cee058fd658103d90872fe431bb6c0afa',
			'0x9d2b4e5c4b1fd81d06b883b0aca661b771c39ea3',
			'0x9e14de5cc84e437518c2c303c88570fe13f0ad15',
			'0xa20416801ac2eacf2372e825b4a90ef52490c2bb',
			'0xa5e37e0ba14655e92deff29f32adbc7d09b8a2cf',
			'0xa6a9eb29e786b5233bd99c0ba28be882fe954a0e',
			'0xbd91c9df3c30f0e43b19b1dd05888cf9b647b781',
			'0xbe9a8b21353ea73794553c154c6c9a06823fcd11',
			'0xcdfc898128dbc380a60895c6e8c0975dc07d07e0',
			'0xcfa2a70fdf74ebda788eeb1498425ceb0630e1cb',
			'0xd0aa1b9d0cd06cafa6af5c1af272be88c38aa831',
			'0xd18a02647d99dc9f79afbe0f58f8353178e6141f',
			'0xd84781e1a9b74d71ea76cda8bb9f30893bfd00d1',
			'0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9',
			'0xdac817294c0c87ca4fa1895ef4b972eade99f2fd',
			'0xdbe6270bcceed7d29ac404fd770eab237253ac9e',
			'0xe0a4a877cd0a07da7c08dffebc2546a4713147f2',
			'0xe9e284277648fcdb09b8efc1832c73c09b5ecf59',
			'0xf1ee89810f4441b025d2d42ff58a0cdc4d797310',
			'0xfb9849b0b53f66b747bfa47396964a3fa22400a0'])
			and c.block_range @> 2147483647) c) c
where
	c.g$pos <= 30
order by
	c.g$parent_id,
	c.g$pos;
```

**Comment by lutter** [comment]
This might be due to the fact that the `id` in this is example is pretty big, 84 chars; we should look at that for other subgraphs, though sorting by `vid` would make this always independent of the size of the `id`

**Comment by lutter** [comment]
For completeness' sake, here is the execution plan for ordering by `id`; note how the `Sort` node in both plans has identical cost, but hugely different execution time:
```
 Sort  (cost=3123.39..3132.14 rows=3500 width=115) (actual time=472.893..473.015 rows=869 loops=1)
   Sort Key: c."g$parent_id", c."g$pos"
   Sort Method: quicksort  Memory: 864kB
   Buffers: shared hit=708
   ->  Subquery Scan on c  (cost=2567.32..2917.36 rows=3500 width=115) (actual time=454.947..472.020 rows=869 loops=1)
         Filter: (c."g$pos" <= 30)
         Rows Removed by Filter: 9509
         Buffers: shared hit=708
         ->  WindowAgg  (cost=2567.32..2777.34 rows=10501 width=271) (actual time=454.896..464.825 rows=10378 loops=1)
               Buffers: shared hit=708
               ->  Sort  (cost=2567.32..2593.58 rows=10501 width=220) (actual time=454.884..458.326 rows=10378 loops=1)
                     Sort Key: c_1.delegate, c_1.id DESC NULLS LAST
                     Sort Method: quicksort  Memory: 3089kB
                     Buffers: shared hit=708
                     ->  Seq Scan on pool c_1  (cost=0.00..1865.95 rows=10501 width=220) (actual time=0.014..27.247 rows=10378 loops=1)
                           Filter: ((block_range @> 2147483647) AND (delegate = ANY ('{0x21d11...}'::text[])))
                           Rows Removed by Filter: 12781
                           Buffers: shared hit=708
 Planning time: 0.301 ms
 Execution time: 473.528 ms
(20 rows)
```

And here it is for ordering by `vid`:
```
 Sort  (cost=3123.39..3132.14 rows=3500 width=115) (actual time=47.472..47.619 rows=869 loops=1)
   Sort Key: c."g$parent_id", c."g$pos"
   Sort Method: quicksort  Memory: 864kB
   Buffers: shared hit=708
   ->  Subquery Scan on c  (cost=2567.32..2917.36 rows=3500 width=115) (actual time=30.163..46.665 rows=869 loops=1)
         Filter: (c."g$pos" <= 30)
         Rows Removed by Filter: 9509
         Buffers: shared hit=708
         ->  WindowAgg  (cost=2567.32..2777.34 rows=10501 width=271) (actual time=30.109..39.771 rows=10378 loops=1)
               Buffers: shared hit=708
               ->  Sort  (cost=2567.32..2593.58 rows=10501 width=220) (actual time=30.097..33.625 rows=10378 loops=1)
                     Sort Key: c_1.delegate, c_1.vid DESC NULLS LAST
                     Sort Method: quicksort  Memory: 3089kB
                     Buffers: shared hit=708
                     ->  Seq Scan on pool c_1  (cost=0.00..1865.95 rows=10501 width=220) (actual time=0.011..12.593 rows=10378 loops=1)
                           Filter: ((block_range @> 2147483647) AND (delegate = ANY ('{0x21d11...}'::text[])))
                           Rows Removed by Filter: 12781
                           Buffers: shared hit=708
 Planning time: 0.318 ms
 Execution time: 47.962 ms
(20 rows)
```

**Comment by leoyvens** [comment]
That performance data certainly shows there's an issue, but sorting by `vid` is problematic since `vid`s are not a part of the protocol. Queries need to be deterministic wrt to the client input, not wrt to implementation details of the database.

A couple possible solutions are to either specify in an implementation agnostic way what a `vid` is, or to make sorting by id less slow by doing features such as allowing integers to be ids and autogenerated determinstic ids. I favor the latter, it's not a short-term solution but it's a backwards compatible one.

**Comment by lutter** [comment]
> That performance data certainly shows there's an issue, but sorting by `vid` is problematic since `vid`s are not a part of the protocol. Queries need to be deterministic wrt to the client input, not wrt to implementation details of the database.

Do we make any guarantees on the order in which entities are returned when the user doesn't specify one? Because sorting by `vid` doesn't change determinism of query results; it's just an order the user couldn't produce by themselves.

> A couple possible solutions are to either specify in an implementation agnostic way what a `vid` is, or to make sorting by id less slow by doing features such as allowing integers to be ids and autogenerated determinstic ids. I favor the latter, it's not a short-term solution but it's a backwards compatible one.

Yes, we absolutely should move to `ID` being an integer type, together with autogenerated id's; but that requires that mappings can look up entities by their attributes. What users do when they know that they need to look up entities by attribute `x` and `y` is to make the id `{x}-{y}`, which as the example shows, is terrible for performance. To move to synthetic primary keys, we need to give them another way to look up by `x` and `y` in their mappings.

**Comment by leoyvens** [comment]
> Do we make any guarantees on the order in which entities are returned when the user doesn't specify one?

That's a product question so we'd need to check on the requirements here, but I'm under the assumption that a valid query should have exactly one correct response, and that requires an ordering that can be specified and not left up to the implementation.

> that requires that mappings can look up entities by their attributes

That's a good point, maybe that would require it to be possible for attributes other than `ID` to be marked as unique. For now users can work around this by having a separate integer field to sort by in their queries.

**Comment by leoyvens** [comment]
@lutter What do you think, is there still a case for changing the default order or is ordering by id the best we can do?

**Comment by lutter** [comment]
I think this is moot at this point. What would help is if we could make `id` shorter, i.e., steer subgraphs away from using long strings as `id` and use ints instead, but that requires changes to the store API that mappings have available.
