### ISSUE TITLE
FEATURE: Expose fiat <> crypto conversion rates as part of default block/event/txs data 

### ISSUE THREAD

**Issue by jamesmorgan** [graphprotocol/graph-node#1409]
**Feature request**

**What is the current behavior?**

Currently we have built a similar solution to The Graph for listening and indexing events/txs, however not using GQL/assemblyscript etc.

In general the approach you guys are taking is far superior and the tooling you provide is excellent 👍  

Currently our indexer also records the current USD/GBP/EUR to ETH rates based on the timestamp of the block for both the event and any watched txs. 

This allows us to then further downstream, similar to subgraph handlers, to work out the FIAT values for any ETH that was consumed. We use this for tallying up totals for users, allows for better UX for real time conversions rates at the point of time of any sales and can nicely graph FIAT and ETH over time.

It would be amazing if this was also available within the context of the event/block/tx when handling events and txs on The Graph.

We have used coingecko and coinmarketcap in the past but there may be other/better sourcess - we also cache the rates using the block timestamp as a key so we dont hammer the 3rd party service if we ever replay the blockchain.

Anyway, would love to see this and hear your feedback on the feature. 

Cheers

James

**Comment by leoyvens** [comment]
Closing to keep the issue tracker focused on bugs.
