### ISSUE TITLE
Contract calls dont revert on inccorect return type

### ISSUE THREAD

**Issue by ianlapham** [graphprotocol/graph-node#1427]
- Experiencing an issue with the Uniswap subgraph https://github.com/graphprotocol/uniswap-subgraph

- A call is being made using an ERC20 abi, specifcally for fetching token symbol, which is defined as type string in ABI. The call is not reverting, however causes a fatal error when assigning call value to a variable of type string. The code below is from the Factory mapping. It works on almost all events but recently an event triggered this loop and caused the failure. 

```
 let symbolValue = 'unknown'  // sets default 
 const symbolResult = contract.try_symbol()
 if (symbolResult.reverted) {
       ...
 } else {
   // gets to this point
   symbolValue = symbolResult.value // breaks on current deploy
 }
 exchange.tokenSymbol = symbolValue
```

- Code is failing in Factory mapping with this error 

```Subgraph instance failed to run: Error while processing block stream for a subgraph: store error: invalid byte sequence for encoding "UTF8": 0x00, code: SubgraphSyncingFailure, id: QmR35kmrpSMaZqWtrmb4MWdPiofeeYiTiUpMr53RxE8kjj```

- Here's the failed subgraph https://thegraph.com/explorer/subgraph/graphprotocol/uniswap?selected=logs

- In general it seems like that call should revert if the returned type doesn't match ABI, but in this case it does not

**Comment by leoyvens** [comment]
@ianlapham Could you give details on why this was closed?

**Comment by leoyvens** [comment]
There's a question of whether this should set `reverted` or it should be a separate flag, named for example `abiError`. IMO the better user experience is to use `reverted` so that there's only one flag to check, I don't think mappings would care about the difference, and we already use `reverted` for errors decoding the output, we just need to make the check stricter.

**Comment by Jannis** [comment]
I think it's fine if we use `reverted` for this as well. I'd love for it to be called `failed` but I guess it's a little late for that now — unless we were willing to do an `apiVersion` bump for it.

**Comment by leoyvens** [comment]
@Jannis That rename doesn't require an `apiVersion` bump, and we can prevent it from breaking by keeping `reverted` getter, and eventually removing it.

**Comment by Jannis** [comment]
Oh, yeah, that would work. Are you also in favor of calling it `failed`?

**Comment by leoyvens** [comment]
@Jannis sure, that is probably more readable and allows us to be flexible with the semantics. I'll include that as part of this task.

**Comment by leoyvens** [comment]
Looking again at this error, it seems to be the same as #1597.
