### ISSUE TITLE
Getting "Error resuming asynchronous request"

### ISSUE THREAD

**Issue by Amxx** [graphprotocol/graph-node#1435]
I'm trying to restart a graphnode (through docker) after having removed one of the networks in the docker-compose configuration.

Error is really long: [error2.txt](https://github.com/graphprotocol/graph-node/files/4025680/error2.txt)

Any clue what is going on?

**Comment by Jannis** [comment]
I think the web3 / JSON-RPC error is a red herring. The actual error is this one:
```rust
graph-node_1  | thread 'tokio-runtime-worker-106' panicked at 'expected store that matches subgraph network: viviani', src/libcore/option.rs:1185:5
```
The node is trying to start a subgraph deployed previously using a network that is no longer supported. 

This could be handled more gracefully, but it's not a common scenario. You're basically ripping out the foundation of subgraphs the node is supposed to be indexing.

I see two ways to resolve this:

1. Put the network back in, start up the node and run `graph remove --node <node-admin-endpoint> <subgraph-name>` for all subgraphs that were deployed against this network. Then remove the network again and restart the node. 

2. Log into Postgres, load the following script and run it for all subgraphs that were deployed against this network.

```sql
-- Remove a subgraph and all its versions, but not the deployments or any
-- of their assignments.
--
-- The 'subgraph' parameter must be in the form 'account/name'
create or replace function remove_subgraph(subgraph text)
returns void as
$$
declare
  sid text;
  deployment text;
begin
  select s.id
    into sid
    from subgraphs.entities s
    where s.entity = 'Subgraph'
      and s.data->'name'->>'data' = subgraph;

  if sid is null then
    return;
  end if;

  raise notice 'Deleting subgraph versions for these deployments:';
  for deployment in
    delete from subgraphs.entities
     where entity = 'SubgraphVersion'
       and data->'subgraph'->>'data' = sid
    returning  data->'deployment'->>'data'
  loop
    raise notice '  %', deployment;
  end loop;

  delete from subgraphs.entities
   where entity = 'Subgraph'
     and id = sid;
end;
$$ language plpgsql;
```

**Comment by Jannis** [comment]
@lutter May be able to help further but my guess is the above already resolves your problem. Let us know how it goes. 😄

**Comment by Amxx** [comment]
I have removed the "viviani" blockchain because the only public node is unavailable (expired SSL certificate) which is preventing the graphnode to boot properly. This prevents the first (clean) option to be used as the graphnode does not respond.

I run the second option, which confirmed removing one subgraph. However, when restarting the graphnode I get the same error. Is there a way to list all subgraph targetting a specific blockchain?

**Comment by Jannis** [comment]
I've come up with this:
```sql
-- Collect all deployments made against the network
select distinct substring(id, 0, 47)
into deployment_ids
from subgraphs.entities
where entity = 'EthereumContractDataSource'
and data->'network'->>'data' = 'rinkeby';

-- Collect all versions that use these deployments
select id
into version_ids
from subgraphs.entities
where entity = 'SubgraphVersion'
and data->'deployment'->>'data' in (select * from deployment_ids);

-- Collect all subgraph names that include these versions
select data->'name'->>'data' as name
from subgraphs.entities
where entity = 'Subgraph'
and (
  (data->'currentVersion'->>'data' in (select * from version_ids)) or
  (data->'pendingVersion'->>'data' in (select * from version_ids))
);
```

That should give you all the names of subgraphs that have a version (and deployment) that refers to `rinkeby` (in this case). Note: These subgraphs may have a current version that does _not_ operate against `rinkeby`. You may not want to remove these, but instead only remove and unset the version that _does_ use `rinkeby`. This is a bit more tricky.

@lutter Can you double check my amateur SQL up there? 😁

**Comment by Amxx** [comment]
Looking for an `entity = 'EthereumContractDataSource'` with the right data->network->>data I can see a entry (First select). But I have no SubgraphVersion with that use this deployment

**Comment by lutter** [comment]
The easiest way to get out of this is probably to just delete the `SubgraphDeploymentAssignment` for the deployments that use the non-existent network (fill in your network name for `$network`):

```sql
delete from subgraphs.entities a
 where a.entity='SubgraphDeploymentAssignment'
   and a.id in (     
       select distinct substring(ds.id, 0, 47)
         from subgraphs.entities ds
        where ds.entity = 'EthereumContractDataSource'
          and ds.data->'network'->>'data' = '$network');
```

Once these assignments are gone, your `graph-node` should start again.

**Comment by Amxx** [comment]
This worked, thank you so much.

While you are being extemelly helpfull, I this issue emerges from the fact that trying to connect to an invalid endpoint (offline or with invalid certificat) causes the entier node to stop. I think this should be addressed when you have some time.

**Comment by leoyvens** [comment]
Closing since this might not be a panic anymore. If it still is, please open a new issue.
