### ISSUE TITLE
Pass deadline for GraphQL execution into database

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1451]
When we execute GraphQL queries, we set a deadline for how long the overall query is allowed to take. Currently, the deadline is only checked in between issuing SQL queries, and a long running query can cause us to massively exceed the deadline.

We should set a `session_timeout` just before executing a query based on the remaining time until the deadline expires so that Postgres will abort the query if we exceed the deadline.

Since `session_timeout` is set per connection, and sticks around after the query finishes, we need to make sure to reset the `session_timeout` right after running the query so that other queries that later uses this connection is not affected by it.

**Comment by leoyvens** [comment]
@lutter I believe we have timeouts for the statements now, can this be closed?

**Comment by lutter** [comment]
Yep, that's pretty much what's implemented now.
