### ISSUE TITLE
It is not possible to pass the GraphQL block argument as a variable

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1460]
Brendan on Discord reported this: 

This works:
```graphql
query poolContractsDrawQuery($poolAddress: ID!, $drawId: String!, $winnerAddress: String!, $first: Int!, $skip: Int!) {
  poolContract(id: $poolAddress, block: { number: 15561871 }) {
  }
}
```

This doesn't:
```graphql
query poolContractsDrawQuery($poolAddress: ID!, $blockNumber: Int!, $drawId: String!, $winnerAddress: String!, $first: Int!, $skip: Int!) {
  poolContract(id: $poolAddress, block: { number: $blockNumber }) {
  }
}
```

```
Message: Invalid value provided for argument `block.number`: Variable("blockNumber"), Location: [object Object], Path: undefined
```

**Comment by nionis** [comment]
I am experiencing this issue too, any ideas on how to workaround this @lutter ?

**Comment by lutter** [comment]
You can work around this issue by putting the hash or number directly into a query, rather than using a variable.

**Comment by moodysalem** [comment]
Would there be an ETA for this fix? @lutter 
GraphQL queries are usually expected to be immutable, and work best with other tooling when they are

**Comment by JasoonS** [comment]
I'm in the same boat as @moodysalem 

I eagerly await this change!
