### ISSUE TITLE
Invalid WebSocket requests cause 502 responses

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1499]
In our production infrastructure, websocket requests that should result in an error (like a 404) end up returning a `502 Bad Gateway` An example of such a request is an attempt to subscribe to a nonexistent subgraph id.

The 502 is ultimately caused by `graph-node` rather rudely closing the connection without producing any output. That in turn is caused by the old version of tungstenite (0.6.1) we are using. We need to update tungstenite to a version that has [this fix](https://github.com/snapview/tungstenite-rs/pull/59#discussion_r281173568) in it.

**Comment by leoyvens** [comment]
Tungstenite was upgraded, this is fixed.
