### ISSUE TITLE
Error setting up Postgres database

### ISSUE THREAD

**Issue by j-mars** [graphprotocol/graph-node#1545]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I am trying to run a local graph node.

When running
cargo run -p graph-node --release -- \
  --postgres-url postgresql://user:pw@localhost:5432/graph-node \
  --ethereum-rpc 'mainnet:http://127.0.0.1:8545' \
  --ipfs 127.0.0.1:5001

I get the following error:
Store thread 'tokio-runtime-worker-4Mar 18 19:07:28.585' panicked at 'Error setting up Postgres database: You may need to drop and recreate your database to work with the latest version of graph-node. Error information: MigrationError(IoError(Custom { kind: Other, error: "formatter error" })) ', store/postgres/src/store.rsINFO:88 :19

![image](https://user-images.githubusercontent.com/45543880/76998044-4e481800-694c-11ea-9171-c777ef4a7894.png)

I have tried droping the graph-node db in my postgres cluster and re-creating it but the error persists. I have tried switching postgres versions and it did not help as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use either the release version or clone the master repo 

- Run a ganache instance
- Run ipfs daemon
- Create a node-graph db at current cluster (main)

and then:

cargo run -p graph-node --release -- \
  --postgres-url postgresql://user:pw@localhost:5432/graph-node \
  --ethereum-rpc 'mainnet:http://127.0.0.1:8545' \
  --ipfs 127.0.0.1:5001

**What is the expected behavior?**
Normal start of the graph node

Thank you

**Comment by fordN** [comment]
Hey @j-mars, that indicates an error during the migration, but unfortunately this particular error originating from Diesel is pretty opaque doesn't provide details as to which migration failed or how.  

Could you share some more details about your setup to help reproduce the error? 
- Which commit of `graph-node` are you on? 
- Which Postgres version do you have installed?  

If you are on a version of Postgres prior to 9.6 it'll have trouble with the format of our migration file names, so that is a likely culprit.

**Comment by j-mars** [comment]
> Hey @j-mars, that indicates an error during the migration, but unfortunately this particular error originating from Diesel is pretty opaque doesn't provide details as to which migration failed or how.
> 
> Could you share some more details about your setup to help reproduce the error?
> 
> * Which commit of `graph-node` are you on?
> * Which Postgres version do you have installed?
> 
> If you are on a version of Postgres prior to 9.6 it'll have trouble with the format of our migration file names, so that is a likely culprit.

- Can't remember the commit of graph-node I was on as I have updated to the latest (and now I can't even run cargo build because it gives many 'can't find crate' errors.) Should I just grab your latest release version and base myself from that?
- I am using Postgres 12

Currently using docker version as that is working fine

**Comment by ginardev** [comment]
Hello @fordN ,

Do you have any solution to fix this issue?
I am getting this error with graph-node at commit b1b1aac1e and postgresSQL 12.2

**Comment by lutter** [comment]
As @fordN said, unfortunately, Diesel swallows the actual errror, so it's hard to tell what is going wrong. Can you look into the logs for your PostgresQL and see what error it reports? (The logs will be in `$PGDATA/log`)

**Comment by lutter** [comment]
One thing to try is if your Postgres user can create extensions; you can check that with `psql -U user` and then issuing
```sql
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
create extension if not exists btree_gist;
```

If that leads to an error, you should recreate the database and make the same Postgres user that you will log in with from your `POSTGRES_URL` the owner of the database (`createdb -O user ..`)

**Comment by ginardev** [comment]
it's fixed after install `postgresql12-contrib` and `CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
create extension if not exists btree_gist;`

thank you so much for your support
