### ISSUE TITLE
cannot start the example from following the docs

### ISSUE THREAD

**Issue by wuichen** [graphprotocol/graph-node#1548]
trying to follow the get started from docs to get gravatar smart contract working on local. however, its bringing up errors when i reach the step to run `yarn create-local`. here are some screenshots of the error including the graph-node logs. im running it on docker and my systems mac.

<img width="675" alt="Screen Shot 2020-03-22 at 3 59 47 PM" src="https://user-images.githubusercontent.com/6353587/77245040-74283200-6c56-11ea-85b7-ad31dd4ea940.png">
<img width="679" alt="Screen Shot 2020-03-22 at 3 59 41 PM" src="https://user-images.githubusercontent.com/6353587/77245041-77232280-6c56-11ea-88b4-81eb99068ad5.png">

**Comment by fordN** [comment]
@wuichen Ganache generates a new net_version each time, so if you've already run the node with a Ganache instance and you run it again with a network of the same name the newly created Ganache network will have a different net_version than the `graph-node` expects. 

To reset the db and start fresh: remove the data  directory created by Docker  by running `rm -rf data/postgres` from the `docker/` directory.

**Comment by wuichen** [comment]
thanks!! that solved the problem!
