### ISSUE TITLE
Best practice to make contract data available via Subgraph?

### ISSUE THREAD

**Issue by osnwt** [graphprotocol/graph-node#1556]
I am new in both contracts and graph, so maybe the question is incorrect.

**In short**: how to expose the `totalSupply` value calculated by contract via Subgraph:

```
contract SimpleTokenCoin is Ownable {
    string public constant name = "Simple Coin Token";
    string public constant symbol = "SCT";
    uint32 public constant decimals = 18;
    uint public totalSupply = 0;
    ...
```

Assuming I have a token contract, it may have few functions like totalSupply(), mintCount(), transferCount(), etc. I want that data be available via GraphQL. I see the following options:
1) Not using Graph: make direct calls to ETH RPC for `totalSupply()`.
2) Using Graph, pass `totalSupply` as a dedicated event parameter, update DB in handlers.
3) Using Graph, calculate `totalSupply` in event handlers from other event params like `mintedAmount`, update DB.

Option 1 is impractical. Option 2 requires to pass extra data with each event for not obvious (for contract) reason. Option 3 creates another one source of truth (the same amounts are available from contract directly, and they also calculated using Mint event params and stored in the database). Also calculations may differ (rounding, etc) or contract code may be updated, so it's really bad solution.

Is there any option to provide such contract data from its getters via Subgraph directly? Say, call contract function from an event handler and update stored in the DB value to expose via GraphQL later? I am ok to call such updater after each event, but would like to not duplicate calculations made by the contract itself.

**Comment by osnwt** [comment]
Answer found, my bad.

**Comment by fafrd** [comment]
What? what was the answer? how can you just ask some complicated question and not tell us what the answer is?

**Comment by ccostel** [comment]
Would be nice if you could share the solution you found :)
