### ISSUE TITLE
json.fromBytes should not crash subgraph in any case.

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#1577]
Possible solutions:

-  providing try /catch pattern on it 
-  return error code or null value if error ...
at https://github.com/graphprotocol/graph-node/blob/4b46753dc5c539da5dd0b0d6c179f5ea683b0fa3/runtime/wasm/src/host_exports.rs#L348

**Comment by Jannis** [comment]
Closed via #1578 and graphprotocol/graph-ts#110.
