### ISSUE TITLE
Any suggestion how to use 3rd-party libs like wasm-flate?

### ISSUE THREAD

**Issue by osnwt** [graphprotocol/graph-node#1589]
I wish I can save binary compressed data in contracts and be able to parse them in a mapping. How can I implement gzip/deflate decompression? I tried to use [wasm-flate](https://wapm.io/package/drbh/flate) library as is, but it is not recognized.

Any other options/suggesions how to:
- use existing wasm libraries?
- maybe native implementation of comression/decompression?
- same question about some symmetric encryption?

**Comment by leoyvens** [comment]
You would need to write or find an implementation in AssemblyScript. Here are some libraries written in AssemblyScript https://github.com/AssemblyScript/docs/blob/master/community/built-with-assemblyscript.md#libraries.

**Comment by osnwt** [comment]
This is an obvious answer, but I assumed you may have some examples of working code.

I have never used wasm. After few attempts I have managed to import an [LZMA decoder](https://github.com/01alchemist/AS-LZMA) into `mapping.ts`. Then I encoded a short "Hello World" string under node.js using this [LZMA encoder](https://github.com/LZMA-JS/LZMA-JS). Finally, I successfully decoded and logged it when processing chain events. But every `decode` call takes near 2 seconds (looking at logs). So it works somehow, but if someone has a better experience embedding some compression into mapping.ts, it would be good to know.

**Comment by leoyvens** [comment]
We have switched to wasmtime which greatly improves the execution performance of wasm. This issue is not the best place to discuss how to pull in dependencies for assemblyscript and wasm, so closing for now.
