### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by j-mars** [graphprotocol/graph-node#1594]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In W10 - WSL, runing cargo build fails by not finding extern crates:

![image](https://user-images.githubusercontent.com/45543880/78887263-744a6f00-7a57-11ea-84eb-2bf29bfdf691.png)

`error[E0463]: can't find crate for `scopeguard`
  --> /home/briing/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.3/src/lib.rs:92:1
   |
92 | extern crate scopeguard;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

0. graph node commit ee6b274
1. Rust installed with rustup for wsl, latest stable: stable-x86_64-unknown-linux-gnu - Up to date : 1.42.0 (b8cedc004 2020-03-09)
2. Run cargo build in root folder

**What is the expected behavior?**
Normal build procedure

**Comment by leoyvens** [comment]
Hi, I hope you have resolved this by now, but I'm closing because this is a general Rust error and happens when building a dependency, so it's best to ask for help in the Rust support channels than here.
