### ISSUE TITLE
Error while processing block stream for a subgraph: store error: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1597]
BUG

**What is the current behavior?**
graph-node have various decoding error, that should be able to be handled via the mapping function.
This one seems that a tokenURI function is returning an invalid string.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

see : https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph?selected=logs
```
Done processing Ethereum trigger, waiting_ms: 0, handler: handleTransfer, total_ms: 445, trigger_type: Log, address: 0x586b…e35d, signature: Transfer(indexed address,indexed address,indexed uint256), block_hash: 0x9eadbed9c4e7c7c0c625a23241ba9bd19425a0fcecca72a55759baf798654b2c, block_number: 6367157
```

from https://github.com/wighawag/eip721-subgraph

**What is the expected behavior?**
I expect the decoding to be catchable via the mapping function

I am not sure it is coming from tokenURI but as the error is about UTF-8 it must be about the graph-node expecting a string value

in my code I have

```
let metadataURI = contract.try_tokenURI(tokenId);
if(!metadataURI.reverted) {
   eip721Token.tokenURI = metadataURI.value; 
}
```

Maybe we should have another option like :
```
if(!metadataURI.reverted) {
   if (metadataURI.decodedSuccesfuly) {
      eip721Token.tokenURI = metadataURI.value;
   } else {
     // do something with metadataURI.rawData;
      eip721Token.rawTokenData = metadataURI.rawData;
   }
}
```

**Comment by wighawag** [comment]
I can confirm this is the issue.
I reproduced it locally with the following contract and return value : https://github.com/wighawag/eip721-subgraph/blob/master/contracts/EIP721ExampleWithWrongBytesMetadata.sol#L16

My local graph fails with the same error when trying to get the tokenURI as a string : 
```
Subgraph instance failed to run: Error while processing block stream for a subgraph: store error: invalid byte sequence for encoding "UTF8": 0x00, code: SubgraphSyncingFailure, id: QmZnUHFx5rpNWQrgarPGnv3iYRpXmkwQVS7hLbiWcH15F2, subgraph_id: QmZnUHFx5rpNWQrgarPGnv3iYRpXmkwQVS7hLbiWcH15F2, component: SubgraphInstanceManager
```

**Comment by leoyvens** [comment]
The issue here is that while null bytes in a string are accepted by the AssemblyScript and internally in the Graph Node, once it hits the DB we have an error.

Solutions would be to remove null bytes from strings before saving them, or to remove them from the decoded solidity input before giving it as input to mappings.

In that case where the string is a single null byte, you can workaround that in your mapping by checking if `your_string == \u0000"`.
