### ISSUE TITLE
store.remove('TypeName', id) does not (always) remove an entity

### ISSUE THREAD

**Issue by osnwt** [graphprotocol/graph-node#1598]
Handing an event, I want to clear most optional props of an entity and keep just few like `isRemoved` with other data nulled (to show that the instance was created but later removed).

To make life easier I try to remove the instance from the store, then recreate it as a new and set just few props:

```
  store.remove('DocumentObject', id)

  let obj = new DocumentObject(id)
  obj.isRemoved = true
  obj.save()
```

But instead of making a new fresh object, this code revives the existing instance with all fields kept from the past. 

What is the proper way to do this?

**Comment by leoyvens** [comment]
@osnwt this was a bug which is now fixed on master, thank you very much for reporting!

**Comment by osnwt** [comment]
Thanks, great work!
