### ISSUE TITLE
Query filtering on related entities - is it possible?

### ISSUE THREAD

**Issue by osnwt** [graphprotocol/graph-node#1599]
I set up a one-to-one relationship between two entities like explained in the [documentation](https://thegraph.com/docs/define-a-subgraph#defining-entities).

I am able to do queries like below and filter by props of `documents` object:

```
query {
  documents (where: { id: "12345" }) {
    id
    dateCreated
    documentObject {
      isRevoked
      isRemoved
    }
  }
}
```  
But I am unable to select, say, all `documents` whose `isRevoked` property of one-to-one related `documentObject` is true.

Is it possible with Graph at all? Other GraphQL implementations have `filter` or like that to do such kind of queries. I did not find anything similar here.

PS. I can of course swap entities and query for `documentObjects { document {} }` and filter by `documentObjects` props. But in that case I am unable to filter by `document` props or both at once. I also can duplicate data when processing events, but this is suboptimal if I really want to separate entities.

Any ideas?

**Comment by osnwt** [comment]
Somehow related issue: https://github.com/graphprotocol/graph-node/issues/1573

**Comment by leoyvens** [comment]
We do not currently support this. It is and long term goal to support this form of filter. The workarounds you mention would be required to achieve this at the moment.

Thank you for the report, but since this is a known limitation I'll go ahead and close it.
