### ISSUE TITLE
Allow for case insensitive queries

### ISSUE THREAD

**Issue by tibetsprague** [graphprotocol/graph-node#1624]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Right now doing a query with a `xxx_contains` property in the `where` is case sensitive. 

**What is the desired behavior?**
Is there a way we could indicate that we want to match while ignoring case? I could imagine wanting this for all properties in the `where`

**Comment by azf20** [comment]
Fixed in https://github.com/graphprotocol/graph-node/issues/3293
