### ISSUE TITLE
Refactor GraphQL execution

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1657]
When we execute a GraphQL query, we currently call `collect_fields` for each field in the response, even though it only depends on the query, but not on any values in the response. We can reduce the amount of computation during query execution by precomputing the result of `collect_fields` and effectively memoizing it in an appropriate data structure.

**Comment by azf20** [comment]
@lutter does this issue still apply?

**Comment by azf20** [comment]
Closing this as I think it was addressed during the GraphQL refactor, please re-open if still valid
