### ISSUE TITLE
Address performance issues caused by subgraph grafting

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1669]
When grafting a new subgraph onto an existing one, we need to copy data from the source to the new subgraph, which can take hours. This causes performance issues in production because it keeps Postgres from doing some important housekeeping tasks (vacuuming) As a result some tables, most importantly `subgraph_deployment` grows to an unmanageable size because of build up of dead tuples. Since pretty much every index and query operation accesses the table, database load grows and the whole system slows down.

We need to change grafting in the following ways:
1. Only copy data at the graft block, not the whole subgraph; that precludes time-travel queries against blocks before the graft point from running (could be fixed if needed) but should speed things up quite a bit in the common case
1. Split the long transaction that does all the copying into multiple transactions. Data should be copied in batches, where the size of each batch is some number of rows, say 10,000 though the right number needs to be determined experimentally. This requires that we keep state about the table and `vid` of the last item copied
1. Cancel the copying if the subgraph becomes unassigned

**Comment by azf20** [comment]
Closing this as Grafting is live
