### ISSUE TITLE
graph auth not working

### ISSUE THREAD

**Issue by ajsantander** [graphprotocol/graph-node#1714]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
After a successful `graph auth`, `graph deploy` does not work. Workaround is using `graph deploy --access-token xxx`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Follow the getting started guide, or deploy any subgraph.

**What is the expected behavior?**
After a successful `graph auth`, `graph deploy` should work.

**Comment by leoyvens** [comment]
Please try with the latest graph-cli version.

**Comment by schmidsi** [comment]
There is already an issue for this: https://github.com/graphprotocol/graph-cli/issues/569
