### ISSUE TITLE
Feature request: Include graph-node compatibility information in subgraph manifest

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#1717]
There are several subgraph features that require a specific setup in graph-node to be supported, this information should be easily accessible so indexers can make decisions on which subgraphs can be deployed effectively to their nodes.  

These include:
  - call handlers - currently require the Parity tracing API
  - network the subgraph syncs from (mainnet, rinkeby, ropsten, etc...) - this is already available from the indexing statuses API
  - contract call - requires an archive node

**Comment by leoyvens** [comment]
We're doing this, see #2715.
