### ISSUE TITLE
Proper reset of Graph Node Docker Image to allow different genesis Blocks (ganache-restart)

### ISSUE THREAD

**Issue by 0xTimepunk** [graphprotocol/graph-node#1729]
**Do you want to request a *feature* or report a *bug*?**
Question
**What is the current behavior?**
How do you correctly restart the Graph Node Docker Image to allow fast development with Ganache (lot's of ganache restarts). It constantly throws an error that the genesis block is different and I can't manage to clean the data to reset this behaviour.

Please note I am on Windows 10 WSL2 with Docker enabled on WSL2

Edit: I had some success by doing 'sudo rm -rf data/postgres/' is this the intended way ?

Thank you

**Comment by leoyvens** [comment]
Closing since this is an old issue, and we're working on a better dev network story using hardhat.
