### ISSUE TITLE
Feature request: Add support for persisted queries & caching

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#1745]
This is a feature request.

I'd like to propose to add support for persisted queries. This could be an additional proxy service layer that handles both storage and resolving of query ids to their respective query statements. Once persisted queries are supported, caching could be implemented for these persisted queries (now GET requests). A very basic solution could simply allow saving persisted queries (just like the example queries) in the graphql explorer and assigning a TTL for those (with optional stale-while-revalidate).

**Comment by fubhy** [comment]
It could even be implemented as an APQ service layer where the query itself defines its desired TTL in the `extensions` section of the query. The query would then be collected by the proxy (alongside its respective query hash) and stored. For more information on how APQ would work: https://www.apollographql.com/docs/apollo-server/performance/apq/

**Comment by lutter** [comment]
I am not quite sure what this is asking for; if it is about ensuring that the same query returns the same result, block constraints in the query fulfill that requirement. If it is about speeding up queries, `graph-node` can be configured to do extensive caching internally.
