### ISSUE TITLE
Should be able to retrieve transaction/block data with GraphQL

### ISSUE THREAD

**Issue by vporton** [graphprotocol/graph-node#1780]
**Do you want to request a *feature* or report a *bug*?**
*feature*

Should be able to retrieve transaction/block data (for example, corresponding to an event) with GraphQL (whatever the schema is).

**Comment by fredlacs** [comment]
https://github.com/graphprotocol/graph-node/issues/297

**Comment by lutter** [comment]
This has been addressed by adding a `_meta` field the the GraphQL schema.
