### ISSUE TITLE
Stuck connecting graph-node docker container to geth on a VPS

### ISSUE THREAD

**Issue by 0xTimepunk** [graphprotocol/graph-node#1788]
**What is the current behavior?**
Cannot connect graph-node to geth on a Google Cloud VPS, it stays stuck while "Connecting to Ethereum"
Running the following command (experimental, "ACCOUNT" stands for the initially generated account, "ethdata" for the blockchain data)

geth --datadir ethdata --nodiscover --rpc --rpcport "8545" --rpcaddr localhost --rpccorsdomain "*" --rpcvhosts="*" --rpcapi "admin,debug,eth,miner,net,personal,txpool,web3" --etherbase ACCOUNT--mine --minerthreads 1 --allow-insecure-unlock --unlock ACCOUNT --password default-password

And in graph-node docker-compose.ym

 ethereum: "mainnet:http://obtained_ip:8545" where obtained_ip is written after running setup.sh

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/45543880/87811307-5d859680-c856-11ea-82a1-fe920b82d06b.png)

**What is the expected behavior?**
Successful connection from graph-node to geth in a VPS

**Comment by HenriJSantos** [comment]
I'm also having this problem, specifically with the ethereum network connection hanging. Any solutions so far?

**Comment by j-mars** [comment]
The connection eventually times out. I am using host's ip as detected by setup.sh

![image](https://user-images.githubusercontent.com/45543880/88050888-99b74080-cb4f-11ea-9e74-f9acf8be938e.png)

Anyone with experience connecting graph-node to geth?

**Comment by leoyvens** [comment]
I do not see how this connection issue is actionable by us, so closing for now.
