### ISSUE TITLE
receive() payable {} fallback function fails graph deploy

### ISSUE THREAD

**Issue by jeffywu** [graphprotocol/graph-node#1790]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Graph deploy fails with this error if the ABI has a `receive() payable` fallback function:
✖ Failed to deploy to Graph node http://127.0.0.1:8020/: subgraph resolve error: resolve error: Serialization error: Invalid operation type. at line 1188 column 1

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a contract with a `receive() payable` fallback function, attempt to load it as an ABI in a data source.

Removing this from the ABI gets the deployment to succeed:
```
    {
      "stateMutability": "payable",
      "type": "receive"
    }
```

**What is the expected behavior?**
It should build and deploy.

**Comment by leoyvens** [comment]
I believe this has been fixed.
