### ISSUE TITLE
Recommendations for running a graph-node in a PoA

### ISSUE THREAD

**Issue by gperezalba** [graphprotocol/graph-node#1798]
Hi,

I'm going to run a graph-node for a network using PoA (with 10 validators) and I'd like to hear some advice from you.

Some questions:
1. Do you recommend connecting graph-node with only one validator? or would be better to use a domain which balances between 10 validators? I'm thinking about some small reorg happening... how does it handle reorgs?.

2. Any security recommendation for graph-node? The server only expose port to query the subraph... do I need to change some stuff regarding with postgres or ipfs? (I'm thinking in postgres user/password)

3. Is there an aprox max queries per second tested?

That's all...I'd like to congrat for your great work it's really amazing

**Comment by leoyvens** [comment]
Hi @gperezalba, answering your questions:

1. I'd recommend having nodes dedicated to serving the Graph Node, which do not also act as validators in the network. This is to make sure serving the Graph Node doesn't interfere with the performance of the validators.

2. From the Graph Node perspective hiding the admin ports is the important thing. If you need to expose IPFS to the outside world you might want to restrict which methods can be called. In the current master, the DB url can now be passed as the `POSTGRES_URL` env var.

3. We currently serve thousands of queries per second from a single DB, but it's a large DB.

**Comment by gperezalba** [comment]
Okey @leoyvens  thanks for your help ;)
