### ISSUE TITLE
Failed to connect to IPFS: api returned unknwon error '405 - Method Not Allowed ''

### ISSUE THREAD

**Issue by kevholder** [graphprotocol/graph-node#1799]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
Failed to connect to IPFS: api returned unknwon error '405 - Method Not Allowed'
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Rung `ipfs daemon` with `go-ipfs version: 0.6.0` and then:

```bash
cargo run -p graph-node --release -- \
  --postgres-url postgresql://user@localhost:5432/graph-node \
  --ethereum-rpc mainnet:https://localhost:8333 \
  --ipfs 127.0.0.1:5001
```

**What is the expected behavior?**

`graph-node` should work with ipfs v6

**Comment by kevholder** [comment]
Probably becasue graph-node uses GET requests instead of POST? https://discuss.ipfs.io/t/getting-a-405-method-not-allowed-error-in-the-latest-go-ipfs-docker-image/7665

**Comment by kevholder** [comment]
A temporary workaround is to use this old version of ipfs: https://github.com/ipfs/go-ipfs/releases/download/v0.4.23/go-ipfs_v0.4.23_darwin-amd64.tar.gz

**Comment by j-mars** [comment]
I have the same error

**Comment by krogla** [comment]
Same issue. What progress?

**Comment by holisticode** [comment]
I am having this issue as well and the last message here is from Jul 22 last year.

What is the workaround to fix this today?
Thanks

**Comment by leoyvens** [comment]
@holisticode Are you running your own IPFS node? Unfortunately Graph Node supports only IPFS v0.4 right now.

**Comment by holisticode** [comment]
Hey @leoyvens 

Yes, was using a local node.
Thanks for the note, I will use the docker image then.

**Comment by KillerByte** [comment]
should probably add a note to the documentation regarding the usage of an older version of IPFS. not sure how new users are supposed to not run into this issue at this point.
