### ISSUE TITLE
queries should or shouldn't produce duplicate records

### ISSUE THREAD

**Issue by dkent600** [graphprotocol/graph-node#1816]
In reference to subgraph:  https://thegraph.com/explorer/subgraph/daostack/v39_4

Which is query is producing the correct behavior, this one that produces duplicate vote records:

```
query ProposalsSearchAllData {
  proposals {
    id
    ...ProposalFields
    votes {
      id
    }
  }
}

fragment ProposalFields on Proposal {
  votes {
    id
  }
}
```

or this one that does not:

```
query ProposalsSearchAllData {
  proposals {
    id
    
  votes {
    id
  }

    votes {
      id
    }
  }
}
```

**Comment by leoyvens** [comment]
@dkent600 The first one is wrong, thank you for reporting this.

**Comment by leoyvens** [comment]
A different symptom of what must be the same bug, a query of the form:
```graphql
 {
  foos {
    ...Frag
    child {
      id
    }
  }
}

fragment Frag on Foo {
  child {
    id
  }
}
```
Which is different from the original case only in that `child` is not an array, will panic with:
```
panic processing query: only derived fields can lead to multiple children here
```
Ping @lutter, I'd guess something is wrong with field collection in prefetch.

**Comment by roienatan** [comment]
What is the status of this?
