### ISSUE TITLE
Improve error message 'oneshot canceled'

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1817]
Several mistakes in mappings can lead to the error message `Mapping terminated before handling trigger: oneshot canceled` which doesn't indicate what actually went wrong.

We need a catch unwind around [here](https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/mapping.rs#L44), get the panic string and send it back as the result.

**Comment by leoyvens** [comment]
https://github.com/graphprotocol/graph-node/pull/2112 should have fixed this by eliminating panics in the runtime.
