### ISSUE TITLE
Fulltext search allows `where` conditions but ignores them

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1823]
The following query against [everest](https://thegraph.com/explorer/subgraph/graphprotocol/everest) should only return one result, but returns four:
```graphql
{
  projectSearch(text: "Project:*", where: {name:"Everest"}, orderBy: totalVotes) {
    name
  }
}
```

The problem is that the SQL query we end up running completely ignores `where` and `orderBy`:
```sql
select 'Project' as entity,
           to_jsonb(c.*) as data
  from (select * 
          from sgd28.project c
         where c.block_range @> $1
           and project_search @@ to_tsquery($2)
         order by ts_rank("project_search", to_tsquery($3)) asc nulls last, "id" limit 100) c
```

**Comment by Jannis** [comment]
We currently only validate the parts of the GraphQL API that we _expect_, not the ones that we don't expect. Fulltext search fields like `projectSearch` don't support `where` and `orderBy`, they only support `text`. So the behavior here is correct.

It would be nice to have richer validation but we've been doing ok without it and it would be a lot of effort now (and probably break a lot of queries out there). Closing this as won't fix for now.
