### ISSUE TITLE
GraphQL: Add a case-insensitive filter for string containment

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1837]
We have a filter `field_contains: "something"` which matches any entity whose `field` contains the string `"something"`. The comparison for that is case sensitive. It would be good to also have a filter for string containment that is not case sensitive.

- [x] #3116
- [x] #3117
- [x] https://github.com/graphprotocol/graph-node/issues/3293
- [x] #3118

**Comment by orenyodfat** [comment]
any update re that @lutter 
?

**Comment by lutter** [comment]
Hi @orenyodfat - I am sorry, but I haven't had time to work on this at all yet.

**Comment by remon-nashid** [comment]
A pretty important feature to have.

It's worth noting that case-insensitivity also matters for `_starts_with`, `_ends_with` and all string matching suffixes.

**Comment by morrigan** [comment]
Bumping this as well, hoping it will be added soon since the search feature is still not fully supported and this is the only similar replacement.

**Comment by azf20** [comment]
As a user I think this is how you would expect this functionality to work. @lutter what do you think about making this the default for `contains` and `starts_with`, and introduce new `_contains_strict` and `_starts_with_strict` for exact matching? That would of course introduce some query variability between versions

**Comment by lutter** [comment]
Yes, I totally agree that that is much more what users would expect. Making `contains` and `starts_with` case insensitive is a trivial change in the backend (replacing `like` with `ilike` in queries) One small wrinkle is that case-sensitivity is locale-dependent, and the response will depend on the locale in which the database is running, but that's not a new thing, we have that with ordering too. More a reminder that we need to define the locale for all these operations for the network.

**Comment by azf20** [comment]
> One small wrinkle is that case-sensitivity is locale-dependent, and the response will depend on the locale in which the database is running, but that's not a new thing, we have that with ordering too. More a reminder that we need to define the locale for all these operations for the network.
This is interesting and I hadn't considered it. Is the deterministic solution here to make the locale configurable somehow (so all indexers can set the same value)?

**Comment by lutter** [comment]
> This is interesting and I hadn't considered it. Is the deterministic solution here to make the locale configurable somehow (so all indexers can set the same value)?

I don't think it's something that `graph-node` should do. Locale can be configured easily through the environment resp. on creation of the database. We should mandate that everything runs in some fixed locale (maybe `en_US.UTF8`, though we'd need to look into if there are other locales that are more palatable to the non-English world) `graph-node` could then check on startup that its locale and the locale of the database are the expected one.

**Comment by dotansimha** [comment]
List of actual tasks: 
- https://github.com/graphprotocol/graph-node/issues/3117
- https://github.com/graphprotocol/graph-node/issues/3118
- https://github.com/graphprotocol/graph-node/issues/3116
