### ISSUE TITLE
Failed call output decoding

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#1841]
I've now seen a few reports of subgraphs failing on this line with the message: `Generating function outputs for an Ethereum call failed: Invalid data`. The latest example being `QmabWhS38ENWDVYL3MHpF7os57yFrfEFvqE397j5Pauqoo` at https://thegraph.com/explorer/subgraph/tech-nerd/productioneip20token.

Some subgraphs were reported to have "fixed themselves" after a restart. I tried one restart for that one and it did not work.

**Comment by leoyvens** [comment]
[This transaction](https://etherscan.io/tx/0xc58a79a458b677e7ed5f3a9e76b03fdfbac88cdf40805779fb2a6b1764198baa) triggers the issue on [this subgraph](https://github.com/stevepro-lab/Subgraph).

**Comment by kinrezC** [comment]
Hi there,

I'm running into a related issue where the subgraph fails with `Generating function inputs for an Ethereum call failed`. The latest example is at `QmXeyfE9zNJNV6Pugm5zmGfrjbAJ9S2wYayD8SQfV8WTSa` and the line in the mapping where it fails can be found here: https://github.com/asyncart/async-subgraph/blob/v2-contract/src/mapping.ts#L241.

**Comment by stevepro-lab** [comment]
@leoyvens 
I made output params optional in the schema and only handling input params of the call handler. Now I am getting below error.  Seems below error is also related to the same issue 

```
Subgraph instance failed to run: Failed to process trigger in block #10457921 (34e887a7d9ed070a24cdeea3d27d707cde7c6d953e7089f3b61dba4b00110d7d), transaction cb0ba75fcb46c36f6d693e06ba4302784d39aea3626f98c9a2d32e308d283e94: Generating function inputs for an Ethereum call failed: Invalid data, code: SubgraphSyncingFailure, id: QmckE99oyeHMcg8pTFNEvKQEZVJ25muja3hC4DLWMgqCtN
```

**Comment by epiqueras** [comment]
I am getting these all the time for various functions.

**Comment by epiqueras** [comment]
Now I'm also getting the error for generating inputs.

**Comment by fordN** [comment]
@epiqueras I'm diving into this encoding issue and could use any additional detail you have (the `invalid data` error from ethabi isn't very specific unfortunately.)  We've added detailed logs which include the raw data and abi structure of the param, could you share that log here?

**Comment by epiqueras** [comment]
```
Subgraph instance failed to run: Failed to process trigger in block #20289686 (82c900b940fd43cfe59c20c2a4606d189bc3c6c2ad6bf161f0b895cc04875525), transaction c921f7e0d5971245d17fc606088709c86896dfed7bffa06ede3b1234d5506e07: Generating function inputs for the call Function { name: "addSubmission", inputs: [Param { name: "_evidence", kind: String }, Param { name: "_name", kind: String }, Param { name: "_bio", kind: String }], outputs: [], constant: false, state_mutability: Payable } failed, raw input: e0f0ea6f0000000000000000000000006695dc16e6c3e1f0d62f30355d7848a3cb37517a00000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000462f697066732f516d5661746466693475394a436a4e355a55334558364d53506874315a465262716f6547667153725154715951312f726567697374726174696f6e2e6a736f6e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b416c69636520536d6974680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000037536f66747761726520456e67696e6565722c20536f6c6964697479204578706572742c20426c6f636b636861696e2c2043727970746f2e000000000000000000: Invalid data, code: SubgraphSyncingFailure, id: QmZ6fsnnmVy26aKJfYGxcA4V5knDA1nsyKgnLHqhMKu9dH
```

**Comment by epiqueras** [comment]
@fordN thanks! It's working now.
