### ISSUE TITLE
Cannot create new graph with Web interface

### ISSUE THREAD

**Issue by vporton** [graphprotocol/graph-node#1855]
**Do you want to request a *feature* or report a *bug*?**
*bug*

* I entered _Zon Directory Templates Rinkeby10_ graph name at https://thegraph.com/explorer/subgraph/create?account=All%20Subgraphs

* It shows `thegraph.com/explorer/vporton/zon-directory-templates-rinkeby10`

* I entered the description _Zon Directory blog templates (Rinkeby)_

* I click "Create subgraph" and get:

```
bundle.esm.js:60 Uncaught (in promise) Error: GraphQL error: Invalid params: invalid value: string "vporton/zon-directory-templates-rinkeby10", expected valid subgraph name.
    at new t (bundle.esm.js:60)
    at e.<anonymous> (bundle.esm.js:980)
    at tslib.es6.js:97
    at Object.next (tslib.es6.js:78)
    at tslib.es6.js:71
    at new Promise (<anonymous>)
    at t.b (tslib.es6.js:67)
    at Object.next (bundle.esm.js:972)
    at b (Observable.js:130)
    at g (Observable.js:165)
```

**Comment by leoyvens** [comment]
Probably this name was too long. Closing but let us know if this is a blocking issue for you.
