### ISSUE TITLE
/graphql endpoints should return a Content-Type header

### ISSUE THREAD

**Issue by joe-bowman** [graphprotocol/graph-node#1859]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

`/graphql` endpoints do not return a Content-Type header; this leads to some proxies (i.e. Traefik) to 'auto-detect' the MIME type as text/plain causing the browser to not render the page.

The `/graphql` endpoint emitting a correct Content-Type header would mean that all content is rendered as expected, and not left to the behest of proxies.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
Header is emitted `Content-Type: text/html`

**Comment by kucharskim** [comment]
This is not only problem for /graphql but for any endpoint. Anything which doesn't return Content-Type header gets text/plain inserted by Traefik.

In other words, Content-Type header should be generated by http://127.0.0.1:8030 (index-node) and http://127.0.0.1:8000 (graph-node-http). I didn't see problem with http://127.0.0.1:8001 (graph-node-ws) but I imagine it may be also affected.

**Comment by kucharskim** [comment]
This affects anything, html, css, javascript.
