### ISSUE TITLE
Audit uses of `Mutex` or `RwLock` for performance

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#186]
Any form of synchronous locking may degrade the performance of the tokio thread pool as it will block the whole thread, we should try replace with something that does not lock at all. Some of our mutexes are may be unnecessary, one way to replace them is by using a oneshot channel internally and returning a future corresponding to the receiver.

**Comment by lutter** [comment]
Is this still needed?

**Comment by leodasvacas** [comment]
@lutter Yes, the motivation is the same as #905, but this one has much less impact.

**Comment by leoyvens** [comment]
This is old and we haven't had issues related to this. And the recommendation is to prefer the synchronous locks in short critical sections that do not block https://github.com/tokio-rs/tokio/issues/2479#issuecomment-623158758. So closing.
