### ISSUE TITLE
trace_filter Error

### ISSUE THREAD

**Issue by masterdubs** [graphprotocol/graph-node#1863]
Method trace_filter not found

I'm trying to index using geth (PIRL network). I got an error whith trace_filter, is there a way to replace it ?

```(attempt #10) with result Err(Rpc(Error { code: MethodNotFound, message: "the method trace_filter does not exist/is not available", data: None })), block_hash: 0x58c88a91b87ebdfb92ef828d1689269b2e986db1b0b7ff51a152d053e477b082, block_number: 6952057, subgraph_id: QmU2xx5j9AoXL9nsMK6qGuuvvEtUGcoQJpFG2EJQ1C3kxp, component: SubgraphInstanceManager ```

**Comment by guifel** [comment]
I get the same issue when using the latest docker image (https://hub.docker.com/layers/graphprotocol/graph-node/latest/images/sha256-d820a109d87be2c9fd004676559c7bd475208995037070e89a57982c57966795?context=explore). 

My subgraph do not rely on anything else event handlers. I tried with Infura and parity full nodes. It keeps calling the `trace_filter` endpoint for some reasons.

When using the master branch it works without any issue. This is an issue with the Docker image.

**Comment by matthewlilley** [comment]
I am also suffering this issue but will take your recommendation and try master @guifel. We're using an infura archive node which I expected to be supported.

**Comment by matthewlilley** [comment]
@guifel It appears I was already on master. Did you avoid using docker and docker-compose entirely and run the nodes individually?

**Comment by leoyvens** [comment]
Infura currently does not support `trace_filter`.
