### ISSUE TITLE
Syncing Stops when Using Directed Eth Queries

### ISSUE THREAD

**Issue by joesixpack** [graphprotocol/graph-node#1895]
Took me almost a week to get this sorted.  When splitting traces among one and archive among three for the Ethereum nodes, the subgraphs will not start or sync at all.  Only solution is to default to archive+traces for all, which is less than ideal.

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/92714660-55574e00-f311-11ea-84b4-9f651286ff4f.png)

Crashes.

**Comment by leoyvens** [comment]
@joesixpack could you clarify what combination of Ethereum node capabilities you were using? Ideally provide the CLI arguments you used, with the endpoints redacted of course.

**Comment by joesixpack** [comment]
It was any combination of capabilities like this:

mainnet:full:
mainnet:full,traces:
mainnet:traces:
mainnet:archive:

It would also crash if no archive was specified.  Not specifying at all implies archive,traces.

**Comment by leoyvens** [comment]
@joesixpack It sounds like you wanted to balance calls within a single subgraph to multiple nodes. Right now each subgraph is assigned to one node, and if you need traces and archive calls that needs to be an `archive,traces` node. Does that clarify things?

**Comment by joesixpack** [comment]
That makes sense, but seems a little clunky when there is actually no traces available.  Can some routing meta-logic be added to deal with splitting subgraph queries to the nodes that do support whatever is requested?

**Comment by joesixpack** [comment]
https://github.com/graphprotocol/graph-node/pull/1810 did not address this.

**Comment by leoyvens** [comment]
Things have since changed and improved in this area. Probably still not perfect but this is issue is now a bit out of context. If necessary free to open an issue with suggestions updated to the current state of the capabilities feature.
