### ISSUE TITLE
Syncing Stops when an Ethereum Node is Down

### ISSUE THREAD

**Issue by joesixpack** [graphprotocol/graph-node#1896]
If one (the first) of the Ethereum nodes is unreachable, the syncing will stop.  Wasn't there supposed to be round robin?  If so, the delay before moving onto the next sucks.

**Comment by huglester** [comment]
What syntax are you using for round robin eth nodes?

**Comment by Jannis** [comment]
There is a graph-node PR to enable trying all nodes per request (https://github.com/graphprotocol/graph-node/pull/1856). Right now, we're picking one node per subgraph and when that node is having issues, so is the subgraph. My expectation is that we'll be able to include this PR this or next week.

**Comment by azf20** [comment]
Closing this given general move towards Firehose as source of data see #2959
