### ISSUE TITLE
Build fail on openssl conflict

### ISSUE THREAD

**Issue by koen84** [graphprotocol/graph-node#1906]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
`cargo build` fails

Error :
```
note: /usr/bin/ld: warning: libssl.so.1.1, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpq.so, may conflict with libssl.so.1.0.0
          /usr/bin/ld: /home/graph/graph-node/target/debug/deps/libopenssl-0ec60fad5ae7acae.rlib(openssl-0ec60fad5ae7acae.openssl.2j1ky13a-cgu.0.rcgu.o): undefined reference to symbol 'OPENSSL_cipher_name@@OPENSSL_1_1_1'
          //usr/lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `graph-node`.
```
**What is the expected behavior?**
Compiles without error.

**Comment by koen84** [comment]
In `/usr/lib/x86_64-linux-gnu/` there both `libssl.so.1.0.0` and `libssl.so.1.1`

**Comment by leoyvens** [comment]
This error must come from building a dependency, so it's not a graph-node specific issue. You could check if you have two versions of openssl installed, and keep only one version.

**Comment by koen84** [comment]
Strange thing is `git pull; cargo build` consistently gave the above error, while moving the dir and going `git clone; cargo build` worked straight away.

**Comment by leoyvens** [comment]
maybe you just needed a `cargo clean`. Glad it worked.
