### ISSUE TITLE
I need a cryptographic hash of the entire database

### ISSUE THREAD

**Issue by vporton** [graphprotocol/graph-node#1908]
_Feature._

I need a cryptographic hash of the entire database of TheGraph.

The hash should be retrievable by some kind of block number. (Does TheGraph have block numbers like Ethereum has?)

**Comment by leoyvens** [comment]
At the `/index-node/graphql` route, you can query the indexing status API. You can use the proof of indexing query https://github.com/graphprotocol/graph-node/blob/master/server/index-node/src/schema.graphql#L14 to get a hash of a subgraph's data at a given block. Note that this is a hash of a specific subgraph, not the whole database.
