### ISSUE TITLE
Repeated ipfs.cat() failures when indexing new blocks

### ISSUE THREAD

**Issue by jamesmorgan** [graphprotocol/graph-node#1931]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

We index blocks and load IPFS data to be stored in our subgraph, however over the last 2 weeks we have seen repeated failures when trying to load the IPFS hash on our hosted subgraph. 

We use the following ipfs method:

```typescript
let data = ipfs.cat(ipfsHash)
```

We have been using this method for many months and within the last few weeks its almost a daily occurrence that the we see failures when trying to index and load the IPFS data, usually failing with the following exception, which we catch and try to handle gracefully. 

```
Failed ipfs.cat, returning `null`, error: Uncategorized("<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.19.2</center>\r\n</body>\r\n</html>\r\n"), link: Qmf1GKcPWDrSNJbwDfjPcHgc5PGeTXmixhD28hNHNGSMFV, runtime_host: 1/1, block_hash: 0x4cd0c9ac2558f8558891d7b49838dd8c8ba9583c88b1404c7de3c36428b8e2d8, block_number: 10999510

06/10/2020, 03:37:24

ERROR

Failed to find IPFS, data null for token URI [Qmf1GKcPWDrSNJbwDfjPcHgc5PGeTXmixhD28hNHNGSMFV], data_source: KnownOrigin, runtime_host: 1/1, block_hash: 0x4cd0c9ac2558f8558891d7b49838dd8c8ba9583c88b1404c7de3c36428b8e2d8, block_number: 10999510
```

Internally we pin the hash to two different public IPFS providers - `Pinata` and `Infura` to try give the hash more availability when being resolved in order to avoid this. We also have implemented a basic retry mechanism which will retry and failed IPFS load 10 times before bombing out. 

However these two mechanisms seem to have little effect on the bug and it keeps happening. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I am unsure of how to exactly reproduce it as all the error IPFS we log can be immediately resolved when we try.

**What is the expected behavior?**

Previously this was not an issue but we are kind of stumped...

Atm we resync daily which fixes all the errors which happen but it would be great to know how to avoid this in the future and what is causing it.

It is something we are doing?

Has TheGraphs IPFS node recently changed?

Any thoughts in general?

Cheers

James

**Comment by jamesmorgan** [comment]
Thanks for looking at this. I guess what you say is the problem and seems to align with the dates of the release. Is there any ideas on how to resolve this from our side, is there anything I can do? @leoyvens 

Atm it is causing us some headache and as the entire IPFS network upgrades to the latest version this problem is going to be compounded further I expect.	

Let me know any ideas or things I can help with to expedite this further.

**Comment by leoyvens** [comment]
The first thing to be said about IPFS support is that the `ipfs.cat` API will not be allowed in the network. We will still support it in the hosted service while we work on a deterministic API for IPFS. So having a version of your subgraph that doesn't use IPFS is something to consider.

@jamesmorgan Ideally we'd upgrade our nodes and have graph-node support newer IPFS versions, but I can't give you a time frame as we have a lot going on right now. If you manage to get these files pinned on an IPFS 0.4 node, see these docs https://thegraph.com/docs/define-a-subgraph#ipfs-pinning for how to pin them to the hosted service nodes.

**Comment by jamesmorgan** [comment]
Ye that's not ideal, I have been doing some investigation myself and this is going to be wider problem I believe as more of the IPFS network upgrades, running on 0.4 basically means its wont connect to any other peers and will stop working completely. So the hosted version will stop working fullstop as eventually no other IPFS peers will be contactable on that version. 

Feels like a real big problem tbh...

I have a possible solution and we will need to rework our dapp but kind of upset that there is no better support for what is advertised as a core feature of the subgraph which will soon stop working without any upfront warning. Really that link (https://thegraph.com/docs/define-a-subgraph#ipfs-pinning) should real state that this is no longer supported if this is the stance.

**Comment by azf20** [comment]
Closing this, as graph-node has been updated to be compatible with the latest IPFS, and the hosted service's IPFS node is also up to date. Please re-open if you are still having issues. Thanks!
