### ISSUE TITLE
Subgraphs fail due to ETH node request throttling

### ISSUE THREAD

**Issue by cag** [graphprotocol/graph-node#1934]
**Do you want to request a *feature* or report a *bug*?**

:bug: 

**What is the current behavior?**

I'm kind of guessing as I don't have access to the backend for the publicly hosted service, but one of my subgraphs failed due to a 429 error code while the Graph node was trying to do an `eth_getLogs`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not sure how reproducible it is, though I guess you can watch for it after your account RPC limit gets hit. It's [logged on this subgraph](https://thegraph.com/explorer/subgraph/cag/hg-rinkeby?selected=logs) though.

**What is the expected behavior?**

I'd say probably that retries for 429 errors do not count towards failure, and that the public service knows about the service's recommendations when trying again due to the rate limit. For example, if that service is Infura, that the [`backoff_seconds`](https://infura.io/docs/ethereum/json-rpc/ratelimits) gets considered.

**Comment by leoyvens** [comment]
This really shouldn't happen, the workaround is to reset the indexing node.

Screenshot of the logs:
![image](https://user-images.githubusercontent.com/9885558/95348940-eaa81c80-0894-11eb-85d8-eac132b74ac3.png)

**Comment by leoyvens** [comment]
This would now be retried automatically.
