### ISSUE TITLE
CORS error on example UI

### ISSUE THREAD

**Issue by nikita-fuchs** [graphprotocol/graph-node#1935]
Bug:

The react UI of the example gets CORS errors, because the server's responses probably don't take care of that?
```
Access to fetch at 'http://localhost:8000/subgraphs/name/nikita-fuchs/test' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Expectedly, the UI doesn't seem to get an answer, although the docker is running.
![image](https://user-images.githubusercontent.com/11761828/95340844-f0fac080-08b5-11eb-9415-438c9f8b33d1.png)

**Comment by leoyvens** [comment]
After https://github.com/graphprotocol/graph-node/pull/2196 the error should be at least different. Please re-open if still an issue.
