### ISSUE TITLE
warning unused import

### ISSUE THREAD

**Issue by koen84** [graphprotocol/graph-node#1949]
**Do you want to request a *feature* or report a *bug*?**  BUG

**What is the current behavior?**  compiling emits the following warnings : 
```
warning: unused import: `PgConnection`
 --> store/test-store/src/lib.rs:5:26
  |
5 | use diesel::{Connection, PgConnection};
  |                          ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Connection`
 --> store/test-store/src/lib.rs:5:14
  |
5 | use diesel::{Connection, PgConnection};
  |              ^^^^^^^^^^

warning: 2 warnings emitted
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`git pull; cargo build --release`
**What is the expected behavior?**
No warnings

**Comment by koen84** [comment]
Same on a fresh `git clone`

**Comment by fattox** [comment]
Happens for me too, unless i omit the `--release` flag. Maybe that helps shine a light on the issue for the devs.

**Comment by leoyvens** [comment]
Thank you for reporting this is fixed on master.
