### ISSUE TITLE
Add cargo.lock to .gitignore

### ISSUE THREAD

**Issue by koen84** [graphprotocol/graph-node#1951]
**Do you want to request a *feature* or report a *bug*?** usability

**What is the current behavior?** when having built and then checking out another commit / tag / branch, git complains about Cargo.lock having changed and being needed to commit / stashed.  The file itself says :
```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
```
so is a built byproduct.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`cargo build; git checkout v0.19.0`

**What is the expected behavior?**
Not needing to commit / stash upon checkout if no manual editing was done.

**Comment by Jannis** [comment]
It's not a build artifact. It's a lock file that guarantees specific dependency versions and that they don't change between builds unless that is actively changed. It's similar to `package-lock.json` and `yarn.lock` and is _supposed_ to be committed.
