### ISSUE TITLE
Trace enabled subgraphs lag behind the head

### ISSUE THREAD

**Issue by czarly** [graphprotocol/graph-node#1984]
I'm not sure if this is a bug.

I did some intensive testing with different OpenEthereum versions and Parity nodes to compare results and find the best combination to index subgraphs that require the traces feature. Currently every subgraph that needs traces usually lags some blocks behind, catches up to be 0 blocks behind and falls back behind again. 

Interestingly every subgraph that is connected to the same Ethereum node lags behind the exact same number of blocks. When I distribute them across different Ethereum nodes each one of them lags behind, the same amount as all other subgraphs on the same Ethereum node, but a different number of blocks from subgraphs on other Ethereum nodes.

Additionally subgraphs that do not require traces are always current, that means they are showing no lag. I tried with 3 different Ethereum nodes, one of them being Quiknode which runs Parity 2.5.13 with EIP-1898 support patched in. The other two are running OpenEthereum 3.1-RC1. 

To verify you can add subgraphs that require traces and subgraphs that do not require traces to one indexer which is connected to a traces enabled Ethereum node. Once they are fully synced you will see the described behavior. 

Subgraphs should not fall back up to 12 blocks before they are syncing back up to the head. They should stay current.

**Comment by czarly** [comment]
This might be coincidence but there exists a command line flag for OpenEtheruem to set the number of blocks that the Ethereum node will allow to fall back behind the current head before it switches to syncing mode to catch up again. The default is set to --max-round-blocks-to-import=12 which is the highest lack that I so far observed before the subgraphs sync back up to head in a split second.

**Comment by azf20** [comment]
Hi @czarly! Sorry about the delay on this. Subgraphs using traces appear to be indexing properly, so closing this issue, please do re-open if you are still seeing this problem!
