### ISSUE TITLE
Unable to input skip value greater than 50000 in thegraph queries

### ISSUE THREAD

**Issue by rshah-deqode** [graphprotocol/graph-node#2000]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Subgraph instance failed to run query for **skip** value greater than 50000 throwing following error
Error:

```
{
  "errors": [
    {
      "message": "Value of \"skip\" must be greater than 0"
    }
  ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I used [UniswapV2](https://thegraph.com/explorer/subgraph/uniswap/uniswap-v2) here but also tried with other subgraphs and facing the same error

```
{
  uniswapFactories(first: 1000,skip:51000) {
    id
    pairCount
    totalVolumeUSD
  }
}
```

**What is the expected behavior?**
It should either return array of uniswap data results or null array, that it was doing earlier

**Comment by leoyvens** [comment]
Skip is currently limited to 5000 now anyways, please use the more efficient pagination described here https://thegraph.com/docs/graphql-api#pagination.
