### ISSUE TITLE
Error indexing subgraph QmYPh4BHfJRszYBP7tnPFPHpKf2DdyHAtgRbE8PAnU1fZN

### ISSUE THREAD

**Issue by Chainode** [graphprotocol/graph-node#2005]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Syncing of the subgraph QmYPh4BHfJRszYBP7tnPFPHpKf2DdyHAtgRbE8PAnU1fZN delivers the following error:

Ethereum node returned an error when calling function \"getPair\" of contract \"Factory\": RPC error: Error { code: InvalidParams, message: \"Unknown block number\", data: None }\nwasm backtrace:\n  0: 0x1e38 - <unknown>!<wasm function 126>\n  1: 0x290a - <unknown>!<wasm function 163>\n  2: 0x295d - <unknown>!<wasm function 166>\n  3: 0x2c92 - <unknown>!<wasm function 172>\n

State:
        "chains": [
          {
            "chainHeadBlock": {
              "number": "11248326"
            },
            "lastHealthyBlock": null,
            "latestBlock": {
              "number": "11246943"
            },
            "network": "mainnet"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simply indexing the subgraph

**What is the expected behavior?**
Index the subgraph to chain head.

**Comment by leoyvens** [comment]
@Chainode is this on your own Graph Node? Do you have GRAPH_ETH_CALL_BY_NUMBER set in your configuration?

**Comment by leoyvens** [comment]
@Chainode It should _not_ be set, I just wanted to rule it out as a cause for the issue. Does this go away after restarting the Graph Node? Which Ethereum client or service provider are you using?

**Comment by Chainode** [comment]
After changing allocations and restart of the node I noticed it moved past that. I think we can close this issue but still weird these type of errors.
