### ISSUE TITLE
An error occurred while updating the graph node (cargo.lock)

### ISSUE THREAD

**Issue by heretikkk** [graphprotocol/graph-node#2006]
When I update a node to a new version, I enter the commands:
cd ~/graph-node
sudo systemctl stop graph
git pull && cargo build --release
sudo systemctl restart graph
journalctl -fu graph

...... git pull && cargo build --release
**Updating 491022a4..8877fa95
error: Your local changes to the following files would be overwritten by merge:
	Cargo.lock
Please commit your changes or stash them before you merge.
Aborting**
such an error pops up and the node is not updated

**Comment by leoyvens** [comment]
Run `git reset --hard` before `git pull`.

**Comment by heretikkk** [comment]
manually corrected Cargo.lock and updated everything


thanks!
