### ISSUE TITLE
Compile subgraphERROR AS100: Operation not supported.

### ISSUE THREAD

**Issue by Activity00** [graphprotocol/graph-node#2010]
export function handleAtomicMatch(call: AtomicMatch_Call): void {
  let entity = AtomicMatch.load(call.transaction.hash.toHexString())
  if (entity == null) {
    return
  }
  entity.token = call.inputs.addrs[7].toHexString()
  entity.save()
}

error:
Compile subgraphERROR AS100: Operation not supported.

   entity.token = call.inputs.addrs[7].toHexString()
                  ~~~~~~~~~~~~~~~~~
 in src/mapping.ts(21,17)

**Comment by leoyvens** [comment]
@Activity00 Assign the array to an auxiliary variable `let addrs = call.inputs.addrs;`. Ask on Discord if you have further questions.
