### ISSUE TITLE
graphprotocol/graph-node:latest image error

### ISSUE THREAD

**Issue by vanphandinh** [graphprotocol/graph-node#2012]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The container run with the image graphprotocol/graph-node:latest exited with logs:
![Screen Shot 2020-11-18 at 5 38 09 PM](https://user-images.githubusercontent.com/13887599/99519788-e2c7b600-29c4-11eb-8257-3c1f35935249.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is my docker-compose.yml:
`
version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - 5001:5001
    volumes:
      - ${DATA}/ipfs:/data/ipfs

  postgres:
    image: postgres:latest
    command:
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ${DATA}/postgres:/var/lib/postgresql/data

  graphnode:
    image: graphprotocol/graph-node:latest
    depends_on:
      - ipfs
      - postgres
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
      - 8030:8030
      - 8040:8040
    environment:
      postgres_host: postgres:5432
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASSWORD}"
      postgres_db: "${DB_NAME}"
      ipfs: "ipfs:5001"
      ethereum: "bsc-testnet:https://data-seed-prebsc-1-s1.binance.org:8545/"
      GRAPH_NODE_ID: "1"
`

**What is the expected behavior?**
I see tag 43314f8 of the graph-node works, but my subgraph seems not working.. I don't know why.

**Comment by leoyvens** [comment]
To fix this, switch replace `postgres_host: postgres:5432` with `postgres_host: postgres`. The port is now controlled by a separate `postgres_port` environment variable.
