### ISSUE TITLE
deploy problem

### ISSUE THREAD

**Issue by Ivan123-ops** [graphprotocol/graph-node#2030]
Using ubuntu  18.04

When I  use graph deploy --access-token <myaccesstoken> \
    --debug \
    --node https://api.thegraph.com/deploy/ \
    --ipfs https://api.thegraph.com/ipfs/ \
    Ivan123-ops/Tbtcgraph

It says something, what can be seen on the screenshot. 

<img width="1007" alt="Снимок экрана 2020-11-30 в 01 44 14" src="https://user-images.githubusercontent.com/58822673/100555598-8f4f4500-32ad-11eb-9d95-63e1d4831b9a.png">

**Comment by leoyvens** [comment]
If this is still an issue please ask for help on the Discord.
