### ISSUE TITLE
Пример использования Сабграфа

### ISSUE THREAD

**Issue by sergey552** [graphprotocol/graph-node#2041]
В руководстве дан пример как установить Сабграф из примера, и устанавливается Gravatar. Я хочу установить из примера, но не Gravatar,  а другой сабграф взять для дублирования, но не получается и все равно устанавливается Gravatar. На первом шаге в дашборде при добавлении сабграфа указывал свой репозитарий на githab, есть ли возможность установить другой сабграф?

**Comment by leoyvens** [comment]
Please ask question in English, use a translator if you need to. Support questions are better suited to our Discord.
