### ISSUE TITLE
Graph-node stopped syncing with error "Option::unwrap() on a None value ... "

### ISSUE THREAD

**Issue by nk-the-crazy** [graphprotocol/graph-node#2053]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

- Graph-node 0.19.2 (2020-11-24) -DockerImage:graph-node:latest 
- Uniswap-Subgrapv-V2 : master branch
------------------------------------------
Not sure if this error is related to Graph-node or UniswapSubgraph. 
Using local graph-node docker container with deployed Uniswap-Subgraph-V2. 
Today it stucked with error :
```
INFO Done processing Ethereum trigger, waiting_ms: thread 'mapping-QmQkfiA1MRv4WQRfxgVgi7PCZ6gziNhXwJkjD1NYfRHwHt-24a75a94-b7ab-44c7-b700-e1d06221edf7' 
panicked at 'called `Option::unwrap()` on a `None` value', graph/src/components/ethereum/types.rs:323:41
stack backtrace:
0, handler: handleSwap, total_ms: 100, trigger_type: Log, address: 0x583c…01f1, 
signature: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address), 
runtime_host: 1/1, 
block_hash: 0xaf7f22c74a9a83291286644015369af80f5fb97afbe5692a82f2d3bff3614726, 
block_number: 10637439, subgraph_id: QmQkfiA1MRv4WQRfxgVgi7PCZ6gziNhXwJkjD1NYfRHwHt, 
component: SubgraphInstanceManager
   0:     0x55a4e288aef0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
   1:     0x55a4e28aef1c - core::fmt::write::h7a1184eaee6a8644
   2:     0x55a4e2882f32 - std::io::Write::write_fmt::haeeb374d93a67eac
   3:     0x55a4e288d33d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
   4:     0x55a4e288cfe8 - std::panicking::default_hook::h9b1a691049a0ec8f
   5:     0x55a4e288da21 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
   6:     0x55a4e288d5c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
   7:     0x55a4e288b35c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
   8:     0x55a4e288d589 - rust_begin_unwind
   9:     0x55a4e28ac391 - core::panicking::panic_fmt::h48c31e1e3d550146
  10:     0x55a4e28ac2dd - core::panicking::panic::h184ede6dd822ffb4
  11:     0x55a4e20be197 - <graph::components::ethereum::types::EthereumTransactionData as core::convert::From<&web3::types::transaction::Transaction>>::from::hf2a1e5089dee2ab5
  12:     0x55a4e1b00927 - graph_runtime_wasm::module::WasmInstance::handle_ethereum_log::h24c562be7979de0d
  13:     0x55a4e1ab1aaf - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::ha68e3d047783eb9a
  14:     0x55a4e1aa943c - futures::task_impl::std::set::h76fc19cee70f9909
  15:     0x55a4e1b2bc36 - futures::task_impl::Spawn<T>::poll_future_notify::hc5d3e4e72c577123
  16:     0x55a4e1ab109e - futures::future::Future::wait::h369d8faf2f596bdf
  17:     0x55a4e1ae617e - tokio::runtime::context::enter::h1d4ac43047ca276b
  18:     0x55a4e1ad7b07 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb6cb81cfdd6e0805
  19:     0x55a4e1ad8d16 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h37e5ce076cefb8c2
  20:     0x55a4e28914fa - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
  21:     0x7f68cc9defa3 - start_thread
  22:     0x7f68ccc764cf - clone
  23:                0x0 - <unknown>

ERRO Subgraph instance failed to run: Failed to process trigger in block #10637439 (af7f22c74a9a83291286644015369af80f5fb97afbe5692a82f2d3bff3614726), 
transaction 156fea9ee3d5d2806dd05b4d6cec0e6002c3f7367837843165fc152fa11a6de9: 
Mapping terminated before handling trigger: oneshot canceled, code: 
SubgraphSyncingFailure, id: QmQkfiA1MRv4WQRfxgVgi7PCZ6gziNhXwJkjD1NYfRHwHt, 
subgraph_id: QmQkfiA1MRv4WQRfxgVgi7PCZ6gziNhXwJkjD1NYfRHwHt, 
component: SubgraphInstanceManager
```
How can this issue be resolved ?
What version of Graph-node (docker-image) is deployed in https://thegraph.com ??

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Comment by leoyvens** [comment]
What is the Ethereum client this Graph Node is connected to?

**Comment by nk-the-crazy** [comment]
> What is the Ethereum client this Graph Node is connected to?

Tested with :

1. infura.io
2. quicknode.io (geth)
3. archivenode.io (geth)

same error for above clients.

**Comment by McAronDev** [comment]
I've had same error on customized unisvap-v2 subgraph local node but on block 11595723. Ii've removed all entities except Pairs from original uniswap subgraph and hardcoded initial Pairs state at recent block to avoid long syncing. Error happened when i was on graph-node v19.2. I've upgraded graph-node to v20.0 and error still persists. But after i cleaned postgres volume and re-synced my subgraph error gone!

**Comment by leoyvens** [comment]
I've gotten other reports of this happening with archivenode.io. It must be a turbo-geth bug. To workaround this, there is no need of resetting the entire DB, simply:
1. Shutdown the Graph Node.
2. Run on the DB the following SQL: `DELETE FROM ethereum_blocks WHERE ethereum_blocks.number = <AFFECTED_BLOCK_NUMBER>` if you know the affected block number or simply `DELETE FROM ethereum_blocks;` to clear the entire block cache.
3. Start Graph Node again.

**Comment by nk-the-crazy** [comment]
> I've gotten other reports of this happening with archivenode.io. It must be a turbo-geth bug. To workaround this, there is no need of resetting the entire DB, simply:
> 
> 1. Shutdown the Graph Node.
> 2. Run on the DB the following SQL:
> 
> ```
> DELETE FROM ethereum_blocks WHERE ethereum_blocks.number = <AFFECTED_BLOCK_NUMBER>`
> ```
> 
> if you know the affected block number or simply `DELETE FROM ethereum_blocks;` to clear the entire block cache.
> 3. Start Graph Node again.

Thanx @leoyvens  , issue resolved
