### ISSUE TITLE
docker graphprotocol/graph-node:v0.20.0 reporting wrong version in log message during startup

### ISSUE THREAD

**Issue by sharppanda** [graphprotocol/graph-node#2083]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Log message: `Graph Node version: 0.19.2 (2020-12-17)`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
startup docker container with image `graphprotocol/graph-node:v0.20.0`

**What is the expected behavior?**
Log message: `Graph Node version: 0.20.0`

**Comment by leoyvens** [comment]
I think this will stay as it is for this release, we need to remember to bump the crate version on future releases.
