### ISSUE TITLE
Add contributing.md to graph-node

### ISSUE THREAD

**Issue by Zerim** [graphprotocol/graph-node#209]
Leo - please coordinate with Nena on the common set of contributing guidelines that are not rust-specific (she's writing them for the Typescript repo).

**Comment by html5cat** [comment]
Here's the first pass I added yesterday: https://github.com/graphprotocol/graph-node/blob/master/CONTRIBUTING.md
@fordN @nenadjaja what else do you think we should add there?

**Comment by leodasvacas** [comment]
Looks good, it would be nice to add a "hi, welcome!" first paragraph, to sound friendly and encourage people to send issues and PRs. Also link the CoC and communcation channels (discord).
