### ISSUE TITLE
support IPFS pinning of new data

### ISSUE THREAD

**Issue by xiphiness** [graphprotocol/graph-node#2090]
Requesting an IPFS pinning feature (with options, using ipfs_api::IpfsClient.add_with_options)

I could do this myself and make a PR. My use case is I am deterministically generating an ipfs hash on chain for tokenUri() in ERC721's and would like to automatically recreate such a hash and pin the corresponding json when an event comes through that indicates a change in the tokenUri() hash.

The with options is important, as cidv1 with raw content type & sha2-256 is much easier to implement in solidity than cidv0(which is dag-pb/protobuff merkelized dag content type).

I would guess it would be added to
https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/module/mod.rs#L472

and

https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/host_exports.rs

**Comment by azf20** [comment]
Hi, thanks this is interesting! I don't think graph-node is necessarily the best place to pin to ipfs - is all the data (including the corresponding json) available on-chain? We are planning to revisit our ipfs implementation and I'm not sure how this will fit into that new architecture, so will close this for now, but happy to chat more through your specific use case if of interest!
