### ISSUE TITLE
POI returns null when a block isn't present in the `ethereum_block` table

### ISSUE THREAD

**Issue by madumas** [graphprotocol/graph-node#2092]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a block isn't cached in the `ethereum_block` table, POI queries return `null` because `get_proof_of_indexing` is unable to determine the block number from the block hash.

This fails without error or warnings.

It is unclear to me why a specific block would be missing from this table. Might be related to #2089 .

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Remove one block from the `ethereum_block` and query a POI
`query { proofOfIndexing(  subgraph: "" blockHash:""  indexer: "" ) }`

**What is the expected behavior?**
graph-node should obtain the information of the missing block and add it to the cache.

**Comment by azf20** [comment]
@otaviopace do you know if this is still the case?

**Comment by otaviopace** [comment]
@madumas can you confirm if this still happens please? I just tried reproducing the error following your instructions and the PoI returned normally.
