### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by koko7786** [graphprotocol/graph-node#2099]
![5AC0A0C6-9325-4CF0-92DF-7A6361A86D6E](https://user-images.githubusercontent.com/76911722/103573621-294d7300-4e94-11eb-8a4b-8807c85e3908.png)

I accidentally sent 18,464.15540204 GRT coins to the wrong address I need help to reverse this back to my coin base account: 0x7Ce949625B1851B2F0eDF2d801EF1de78128B94A

**Comment by leoyvens** [comment]
We cannot undo on-chain transactions. This is not the right place to discuss this, you can try our Telegram.
