### ISSUE TITLE
Checking subgraph health

### ISSUE THREAD

**Issue by mezz2020** [graphprotocol/graph-node#2107]
When I deploy a local graph node, how to check subgraph health？

**Comment by leoyvens** [comment]
You mean like this https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health? It's on port 8030.

**Comment by mezz2020** [comment]
@leoyvens I use the command docker-compose up to start the graph node, but I request http://47.242.241.235:3030/index-node/graphql, and a 404 error is returned

**Comment by leoyvens** [comment]
@mezz2020 the route you should use is `:8030/graphql`, no `index-node`

**Comment by mezz2020** [comment]
@leoyvens Thank you, the graph node service is running successfully
