### ISSUE TITLE
Naming around non-fatal errors

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#2110]
The non-fatal errors features introduced the `subgraphError` argument to top-level fields, which can currently be either `subgraphError: allow` or `subgraphError: deny`, defaulting to `deny`. Also a `hasIndexingErrors` boolean was added to the `_meta` field, as in the example:
```graphql
foos(first: 100, subgraphError: allow) {
  id
}
_meta {
  hasIndexingErrors
}
```
Do we want to rename any of these? Other suggestions that were previously considered for `subgraphError` were `indexingError` and `deploymentError`.

**Comment by Jannis** [comment]
So `hasIndexingErrors` or `hasErrors` is fine IMHO.

Ideas for replacing `subgraphError: allow`:

- `failOnIndexingErrors: true/false` (default: `false`)
- `allowIndexingErrors: true/false` (default: `false`? `true`?)

**Comment by leoyvens** [comment]
The thinking for using an enum instead of a boolean is that we can add more options backwards compatibly.

**Comment by leoyvens** [comment]
@Jannis note that the current default is `subgraphError: allow`, though we can also debate the default.

**Comment by Jannis** [comment]
An alternative could be
* `allow(Subgraph)Errors: indexing | none`
and we can later add other variants.

**Comment by yanivtal** [comment]
What are examples of other values we would want to use in the enum? I think the first decision point is whether it should be boolean or enum.

**Comment by leoyvens** [comment]
@yanivtal The enum was first suggested by @That3Percent, with the reasoning that we might eventually have the variant `indexingError: verbose`. That would return error messages. For now we won't return detailed error messages because those are not stable yet.

**Comment by Zerim** [comment]
If we're thinking of letting them specify the severity of errors to fail on, I agree that switching to a parameter like the following would be preferable:
- `allowSubgraphErrors: all | info | warn | error | none` (default: `none`)

There should be a separate field for actually retrieving errors as part of a query, and that should also have it's own verbosity parameter.

**Comment by yanivtal** [comment]
I like this option

**Comment by leoyvens** [comment]
It's the first time the idea of specifying the severity of the error comes up. Generally it is difficult to tell how severe an error is for a subgraph. Having the error details be included in the `_meta` field makes sense to me.

**Comment by Jannis** [comment]
I'm not sure about info, warn etc. Those are not errors. 😉

**Comment by Zerim** [comment]
Was asked to own making a final call here. I propose going with the enum approach that I showed above.

It strikes a balance between somewhat future proof, without going over the top, i.e., passing a config object as an argument to allow for error levels, types of errors, etc.

**Comment by leoyvens** [comment]
@Zerim We currently use an enum which is `subgraphError: [allow|deny]`. Based on your comment above, should that be renamed to `allowSubgraphErrors: [all|none]`?

**Comment by Zerim** [comment]
If developers are already depending on the experimental API, I'm fine leaving as-is. Not worth a breaking change, even on an experimental feature, for this minor of a change.

We can do another pass on this when we add more full-featured errors to the subgraph mapping runtime.

**Comment by leoyvens** [comment]
@Zerim Agreed that it's not worth renaming. Closing this, thanks to all who provided opinions. I'll move on to document the API with the current names.
