### ISSUE TITLE
Any suggestions on subgraph performance improvement?

### ISSUE THREAD

**Issue by k06a** [graphprotocol/graph-node#2131]
We deployed one new subgrah. Do you have any suggestions on performance optimizations? https://github.com/1inch-exchange/dexcandles/blob/master/src/mappings/swaps.ts

1. Should we use `keccak256` for creating `ID` or unique string with 88 hex characters is good enough?

2. I would like to avoid having these fields, since they are all included into ID, but I need to use them in queries:
    ```
    time: Int!
    period: Int!
    token0: Bytes!
    token1: Bytes!
    ```

3. Does it make sense to have 6 different tables for 6 types of candles? Or even have 6 different subgraphs?

**Comment by leoyvens** [comment]
1. Shorter IDs are better, but 88 hex characters seems short enough.
2. If you need them in the queries then you need them as separate fields.
3. If they come from the event it doesn't make sense to have separate subgraphs. Separate tables might help if queries are slow.

GitHub is not the best place for this type of conversation, please lets continue the conversation on our Discord.

**Comment by k06a** [comment]
@leoyvens GitHub is at least searchable by other devs.

**Comment by leoyvens** [comment]
We also have https://github.com/graphprotocol/support/issues if you prefer GitHub, but Discord is likely to get a faster response.
