### ISSUE TITLE
Local graph-node subgraphs sync blocks very slowly.

### ISSUE THREAD

**Issue by mezz2020** [graphprotocol/graph-node#2137]
My local graph-node subgraphs sync blocks very slowly. Is there a way to solve this problem? I started using docker-compose up

`
{
  "errors": [
    {
      "message": "Failed to decode `block.number` value: `subgraph QmSJ6dtcbosRZoqpnYA2FV1UHqngmaAvgz9a993JKAejZ6 has only indexed up to block number 1568546 and data for block number 1569687 is therefore not yet available`"
    }
  ]
}
`

**Comment by dsky1990** [comment]
same problem， anyone can help

**Comment by leoyvens** [comment]
Is it the case that the subgraph at some point fully syncs, but then starts falling behind?

**Comment by dsky1990** [comment]
yes @leoyvens

**Comment by leoyvens** [comment]
@dsky1990 It may be that the DB is overwhelmed with the amount of blocks, try setting `GRAPH_ETHEREUM_CLEANUP_BLOCKS=true`.

**Comment by dsky1990** [comment]
@leoyvens thanks， I'll test it

**Comment by mezz2020** [comment]
@leoyvens I use graph node to synchronize the heco chain network. This network has a block every 3 seconds; is the processing lagging due to this reason?

**Comment by dsky1990** [comment]
@leoyvens still have a question， should i just add the config and restart the sever, or use new serve and the config to sync blocks from start block

**Comment by leoyvens** [comment]
@dsky1990 you may simply add the config to your existing setup.
@mezz2020 A faster chain will be more demanding, and we can't promise it will work since we haven't tested that chain, but that config might help.

**Comment by mezz2020** [comment]
@leoyvens  setting the env var GRAPH_ETHEREUM_CLEANUP_BLOCKS: true get error:

`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.graph-node.environment.GRAPH_ETHEREUM_CLEANUP_BLOCKS contains true, which is an invalid type, it should be a string, number, or a null`

**Comment by leoyvens** [comment]
@mezz2020 you need quotes `GRAPH_ETHEREUM_CLEANUP_BLOCKS="true"`

**Comment by mezz2020** [comment]
@leoyvens It seems to have no effect, it may be that the heco chain network is too fast; is there any other way to improve the processing speed and efficiency?

**Comment by leoyvens** [comment]
Are you running this on an SSD? At this point my recommendation is to try it on a cloud setup that has good latency to the Ethereum node and also a fast database.

**Comment by mezz2020** [comment]
@leoyvens  Thank you, the data synchronization problem has been solved!

**Comment by lutter** [comment]
Seems this is solved. Feel free to reopen if this is still an issue.
