### ISSUE TITLE
New CORS error

### ISSUE THREAD

**Issue by qbig** [graphprotocol/graph-node#2141]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
```
VM87:1 Access to fetch at 'https://api.thegraph.com/index-node/graphql' from origin 'https://info.uniswap.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just open info.uniswap.org -> CHARTS -> check console

**What is the expected behavior?**
We didn't see this CORS error before.. How should we work around this ?

**Comment by Jannis** [comment]
This was a temporary issue on the hosted service, not a graph-node bug. See https://status.thegraph.com/incidents/3zplc2y0gjhv.

**Comment by Deams51** [comment]
@Jannis The issue seems to be happening again today.
I can confirm that everything was fine yesterday.

**Comment by Jannis** [comment]
@Deams51 Yes, check https://status.thegraph.com/. It's an outage on the hosted service, not a graph-node issue.

**Comment by Deams51** [comment]
@Jannis Thanks, that was a really quick reply. :D 
There doesn't seem to be any indication of an outage nor any incidents today when checking the status page from my side.
Am I missing something?
