### ISSUE TITLE
Retries should not fail a subgraph

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#2144]
We have seen subgraphs fail with `Subgraph instance failed to run: Transport("Unexpected response status code: 429 Too Many Requests")`, but this should never be a fatal error and always be retried. The block stream will retry indefinitely, so my guess is that this happens for calls in the instance manager.

**Comment by leoyvens** [comment]
One example of retries on contract calls failing a subgraph:
![image](https://user-images.githubusercontent.com/9885558/110517266-67138580-80e9-11eb-89ea-7f8af15e8054.png)

**Comment by azf20** [comment]
@leoyvens @otaviopace will this be solved by the in-progress retry mechanism?

**Comment by leoyvens** [comment]
@azf20 yes, we can consider this closed!

**Comment by otaviopace** [comment]
I'll close once it's deployed 😉

**Comment by azf20** [comment]
This was deployed 🙏
