### ISSUE TITLE
docker-compose up throws transport error (code: 111, kind: ConnectionRefused)

### ISSUE THREAD

**Issue by ndrslmpk** [graphprotocol/graph-node#2153]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After running `docker-compose up` i get the following error message.

`
graph-node_1  | Feb 02 14:02:22.990 WARN Trying again after net_version RPC call failed (attempt #17) with result Err(Transport error: Error(Connect, Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. `git clone https://github.com/graphprotocol/graph-node/`
2. `cd graph-node/docker`
3. `docker-compose up`

**What is the expected behavior?**
Running the graph-node without problems.

**Comment by GraphicalDot** [comment]
If you are running it locally..then you also must have a local blockchain up and running ..
Simplest is to use 
`ganache-cli -h 0.0.0.0`

**Comment by lutter** [comment]
Please reopen this issue if the above tip doesn't fix it for you
