### ISSUE TITLE
graph node crash after deploy subgraph

### ISSUE THREAD

**Issue by kai1412** [graphprotocol/graph-node#2158]
When i start the graph-node, everything is working, but after i create and deploy subgraph, it's crash after a while.

this is debug log: `thread 'tokio-runtime-worker' panicked at 'called Result::unwrap()on anErrvalue: Column hash was not present in query', /graph-node/chain/ethereum/src/block_stream.rs:463:86`

Full Log: 

`graph-node_1  | Feb 03 03:03:06.772 INFO Scanning blocks [15399711, 15401710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.809 INFO Scanning blocks [15401711, 15403710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.840 INFO Scanning blocks [15403711, 15405710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.874 INFO Scanning blocks [15405711, 15407710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.899 INFO Scanning blocks [15407711, 15409710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.925 INFO Scanning blocks [15409711, 15411710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.954 INFO Scanning blocks [15411711, 15413710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:06.994 INFO Scanning blocks [15413711, 15415710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.028 INFO Scanning blocks [15415711, 15417710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.061 INFO Scanning blocks [15417711, 15419710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.087 INFO Scanning blocks [15419711, 15421710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.109 INFO Scanning blocks [15421711, 15423710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.138 INFO Scanning blocks [15423711, 15425710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.168 INFO Scanning blocks [15425711, 15427710], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | Feb 03 03:03:07.219 INFO Scanning blocks [15427711, 15429656], range_size: 2000, subgraph_id: QmcB4tbumfcKjaQaLsQQiotVMJnYh5JGiBzj3f8bP62B1E, component: SubgraphInstanceManager > BlockStream
graph-node_1  | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Column `hash` was not present in query', /graph-node/chain/ethereum/src/block_stream.rs:463:86
graph-node_1  | stack backtrace:
graph-node_1  |    0:     0x55e8465be860 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
graph-node_1  |    1:     0x55e8465e3c1c - core::fmt::write::h77b4746b0dea1dd3
graph-node_1  |    2:     0x55e8465b68b2 - std::io::Write::write_fmt::heb7e50902e98831c
graph-node_1  |    3:     0x55e8465c0ea5 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
graph-node_1  |    4:     0x55e8465c0b48 - std::panicking::default_hook::hb52d73f0da9a4bb8
graph-node_1  |    5:     0x55e8465c1641 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
graph-node_1  |    6:     0x55e8465c1187 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
graph-node_1  |    7:     0x55e8465bed1c - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
graph-node_1  |    8:     0x55e8465c10e9 - rust_begin_unwind
graph-node_1  |    9:     0x55e8465e0941 - core::panicking::panic_fmt::ha0bb065d9a260792
graph-node_1  |   10:     0x55e8465e0763 - core::result::unwrap_failed::h53240067144083fb
graph-node_1  |   11:     0x55e84515e2b6 - graph_chain_ethereum::block_stream::BlockStreamContext<S,C>::get_next_step::h7ff3dc3ff0f70fee
graph-node_1  |   12:     0x55e844e7631b - futures::future::loop_fn::loop_fn::h242c562773b3ba66
graph-node_1  |   13:     0x55e84514de80 - <graph_chain_ethereum::block_stream::BlockStream<S,C> as futures::stream::Stream>::poll::hc1c5b1c042912c83
graph-node_1  |   14:     0x55e844f214dd - <graph::ext::futures::Cancelable<S,C> as futures::stream::Stream>::poll::h3524c4edd9604e79
graph-node_1  |   15:     0x55e845143474 - futures::task_impl::std::set::h73eec30a0cd1459a
graph-node_1  |   16:     0x55e8452cbda0 - graph_core::subgraph::instance_manager::run_subgraph::{{closure}}::h30b72dd06ce33ed0
graph-node_1  |   17:     0x55e84532605d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1b0aca16fde9e98e
graph-node_1  |   18:     0x55e84526500c - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h5878f5c7473cffc2
graph-node_1  |   19:     0x55e84513879f - tokio::runtime::enter::Enter::block_on::h6ecc53ae95645ccb
graph-node_1  |   20:     0x55e8452a9a7a - tokio::runtime::context::enter::h411cc9868d4e378b
graph-node_1  |   21:     0x55e8452a8138 - graph::task_spawn::block_on::h852ca107fc122d7b
graph-node_1  |   22:     0x55e8452be332 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h00de1c34eea0f611
graph-node_1  |   23:     0x55e84506bfcb - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hab345509223b6a4d
graph-node_1  |   24:     0x55e844e5ecdf - tokio::runtime::task::harness::Harness<T,S>::poll::h8c271767180b42b1
graph-node_1  |   25:     0x55e846567ea1 - tokio::runtime::blocking::pool::Inner::run::hcb7d774dd8bc69af
graph-node_1  |   26:     0x55e84656ea00 - tokio::runtime::context::enter::h7e368fd7b15fcd22
graph-node_1  |   27:     0x55e846575fd2 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3e78feb8a502b8a3
graph-node_1  |   28:     0x55e84656a7da - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3430eea7edb15987
graph-node_1  |   29:     0x55e8465c535a - std::sys::unix::thread::Thread::new::thread_start::h587efff279c68ba7
graph-node_1  |   30:     0x7fa02b91dfa3 - start_thread
graph-node_1  |   31:     0x7fa02b6c44cf - clone
graph-node_1  |   32:                0x0 - <unknown>
graph-node_1  | Panic in tokio task, aborting!
graph-node_1  | /usr/local/bin/start: line 74:    29 Aborted                 (core dumped) graph-node --postgres-url "$postgres_url" --ethereum-rpc $ethereum --ipfs "$ipfs"
docker_graph-node_1 exited with code 134
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker_postgres_1   ... done
Stopping docker_ipfs_1       ... done`

**Comment by leoyvens** [comment]
@kai1412 this should be fixed on master.

**Comment by lutter** [comment]
This was indeed fixed in PR #2169
