### ISSUE TITLE
Coudnt start graphnode 

### ISSUE THREAD

**Issue by GraphicalDot** [graphprotocol/graph-node#2166]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

***
ubuntu@ip-172-31-11-171:~/graph-node$ cargo run -p graph-node --release --   --postgres-url postgresql://ubuntu[:ToppleGovernment87790#]@localhost:5432/graph-node  --ethereum-rpc goerli:https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c   --ipfs ipfs.infura.io:5001
warning: /home/ubuntu/graph-node/Cargo.toml: unused manifest key: patch.crates-io.graphql-parser.commit
    Finished release [optimized] target(s) in 0.42s
     Running `target/release/graph-node --postgres-url 'postgresql://ubuntu[:ToppleGovernment87790#]@localhost:5432/graph-node' --ethereum-rpc 'goerli:https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c' --ipfs 'ipfs.infura.io:5001'`
Feb 06 13:33:27.718 INFO Graph Node version: 0.21.1 :: hosted-current (671d885ea 2021-02-04)
Feb 06 13:33:27.719 INFO Generating configuration from command line arguments
Feb 06 13:33:27.731 INFO Starting up
Feb 06 13:33:27.734 INFO Trying IPFS node at: http://ipfs.infura.io:5001/
Feb 06 13:33:27.741 INFO Creating transport, capabilities: archive, trace, url: https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c, network: goerli
thread '<unnamed>' panicked at 'failed to connect notification listener to Postgres: Error(ConnectParams("Illegal character in authority"))', store/postgres/src/notification_listener.rs:123:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ubuntu@ip-172-31-11-171:~/graph-node$
 u  20.04 0:-- 1:-* 2:-
***

**Comment by GraphicalDot** [comment]
Do you want to request a feature or report a bug? Bug

What is the current behavior?
Facing some error with starting the graphnode on ec2 instance. Followed all the steps but still facing some error with the boot. 
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.



`
ubuntu@ip-172-31-11-171:~/graph-node$ cargo run -p graph-node --release --   --postgres-url postgresql://ubuntu[:ToppleGovernment87790#]@localhost:5432/graph-node  --ethereum-rpc goerli:https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c   --ipfs ipfs.infura.io:5001
warning: /home/ubuntu/graph-node/Cargo.toml: unused manifest key: patch.crates-io.graphql-parser.commit
    Finished release [optimized] target(s) in 0.42s
     Running `target/release/graph-node --postgres-url 'postgresql://ubuntu[:ToppleGovernment87790#]@localhost:5432/graph-node' --ethereum-rpc 'goerli:https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c' --ipfs 'ipfs.infura.io:5001'`
Feb 06 13:33:27.718 INFO Graph Node version: 0.21.1 :: hosted-current (671d885ea 2021-02-04)
Feb 06 13:33:27.719 INFO Generating configuration from command line arguments
Feb 06 13:33:27.731 INFO Starting up
Feb 06 13:33:27.734 INFO Trying IPFS node at: http://ipfs.infura.io:5001/
Feb 06 13:33:27.741 INFO Creating transport, capabilities: archive, trace, url: https://goerli.infura.io/v3/3a28bbb91f1942aa9cbd635d27cbfc4c, network: goerli
thread '<unnamed>' panicked at 'failed to connect notification listener to Postgres: Error(ConnectParams("Illegal character in authority"))', store/postgres/src/notification_listener.rs:123:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ubuntu@ip-172-31-11-171:~/graph-node$
 u  20.04 0:-- 1:-* 2:-`

**Comment by leoyvens** [comment]
@GraphicalDot  In your docker-compose please set just `postgres_host: postgres`, removing the port.

**Comment by leoyvens** [comment]
Closing, if still an issue please reopen.
