### ISSUE TITLE
Stuck at  Deploying to Graph node http://127.0.0.1:8020/

### ISSUE THREAD

**Issue by GraphicalDot** [graphprotocol/graph-node#2167]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
It gets stuck at 
```
Build completed: QmRRaVLu1ZjKYB9VZaf2fHo1YhT8Nkisnf3Bu5Ju7x49Xa

⠧ Deploying to Graph node http://127.0.0.1:8020/
```
after yarn deploy-local

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

`ubuntu@ip-172-31-12-200:~/ens-subgraph$ yarn create-local
yarn run v1.22.5
$ graph create graphprotocol/ens --node http://127.0.0.1:8020
Could not get access token from libsecret (usually gnome-keyring or ksecretservice):

Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards.

The original error was: Cannot find module 'keytar'

Continuing without an access token

Created subgraph: graphprotocol/ens
Done in 1.72s.`

Then i did yarn deploy-local. BUt it gets stuck at 
`$ graph deploy graphprotocol/ens --debug --ipfs http://localhost:5001 --node http://127.0.0.1:8020/
Could not get access token from libsecret (usually gnome-keyring or ksecretservice):

Cannot store the access token because dependencies are missing. If you
are on Linux, try installing 'libsecret-1-dev' (Debian, Ubuntu etc.) or
'libsecret-devel' (RedHat, Fedora etc.) and reinstalling Graph CLI
afterwards.

The original error was: Cannot find module 'keytar'

Continuing without an access token

  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: ENSRegistry => build/ENSRegistry/ENSRegistry.wasm
⠋ Compile subgraphWARNING AS206: Compiling constant with non-constant initializer as mutable.

 const BIG_INT_ZERO = BigInt.fromI32(0)
                      ~~~~~~~~~~~~~~~~~
 in src/ensRegistry.ts(23,21)

  Compile data source: ENSRegistryOld => build/ENSRegistry/ENSRegistry.wasm (already compiled)
  Compile data source: Resolver => build/Resolver/
✔ Compile subgraph
  Copy subgraph file build/schema.graphql
  Write subgraph file build/ENSRegistry/abis/Registry.json
  Write subgraph file build/ENSRegistryOld/abis/Registry.json
  Write subgraph file build/Resolver/abis/PublicResolver.json
  Write subgraph file build/BaseRegistrar/abis/BaseRegistrar.json
  Write subgraph file build/EthRegistrarController/abis/EthRegistrarController.json
  Write subgraph manifest build/subgraph.yaml
✔ Write compiled subgraph to build/
  Add file to IPFS build/schema.graphql
                .. QmYTpNtiL3aowFvApEi8Lmy71dGVft51n19o8GEumZ2UPu
  Add file to IPFS build/ENSRegistry/abis/Registry.json
                .. QmRTphmVWBbKAVNwuc8tjJjdxzJsxB7ovpGHyUUCE6Rnsb
  Add file to IPFS build/ENSRegistryOld/abis/Registry.json
                .. QmRTphmVWBbKAVNwuc8tjJjdxzJsxB7ovpGHyUUCE6Rnsb (already uploaded)
  Add file to IPFS build/Resolver/abis/PublicResolver.json
                .. QmYyNtiPDxt8Y4Zmn1uHw5xaz2j8KFrndzftMgHhtzAcny
  Add file to IPFS build/BaseRegistrar/abis/BaseRegistrar.json
                .. QmWqXtDCvMtpnV28Z5f6P6rPCaCA2d8gKnacGaohDWgALN
  Add file to IPFS build/EthRegistrarController/abis/EthRegistrarController.json
                .. Qmb6zHLHHGd1wpe2CuyVijkPrxG1M9VZKwK7aGhY1o3xKf
  Add file to IPFS build/ENSRegistry/ENSRegistry.wasm
                .. QmRAMqFdZPfXgGRV2adM96aCbakqLMHup6NaWEWJAzDUd3
  Add file to IPFS build/ENSRegistry/ENSRegistry.wasm
                .. QmRAMqFdZPfXgGRV2adM96aCbakqLMHup6NaWEWJAzDUd3 (already uploaded)
  Add file to IPFS build/Resolver/Resolver.wasm
                .. Qmasd4V46dRnkMnwqsLNEFq9KMvN89d6xcLu4ECmPrdzMY
  Add file to IPFS build/BaseRegistrar/BaseRegistrar.wasm
                .. QmYR3eVgkHZEkLaNArPdhFEm3o6LFxLwddEQNyuZEtRPub
  Add file to IPFS build/BaseRegistrar/BaseRegistrar.wasm
                .. QmYR3eVgkHZEkLaNArPdhFEm3o6LFxLwddEQNyuZEtRPub (already uploaded)
✔ Upload subgraph to IPFS

Build completed: QmRRaVLu1ZjKYB9VZaf2fHo1YhT8Nkisnf3Bu5Ju7x49Xa

⠇ Deploying to Graph node http://127.0.0.1:8020/
`

**Comment by adamzerella** [comment]
This might be a simple one, can you confirm if you have `libsecret` installed? On Ubuntu, this package is called `libsecret-1-dev`

**Comment by leoyvens** [comment]
Please try with the latest graph-cli 0.20. If still an issue try passing the access token with the `--access-token` option. If still an issue, please report on Discord first.
