### ISSUE TITLE
Template strings are not interpolated in mapping.ts

### ISSUE THREAD

**Issue by liamzebedee** [graphprotocol/graph-node#2171]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Template strings are not interpolated in `mapping.ts`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I encountered this while reconstructing an IPFS CID from a 32 byte sha256 digest value.

```ts 
// This doesn't evaluate hashDigest.toHexString().slice(2).
// Instead it just returns the raw string.
const hexStringConcatenated = `1220${hashDigest.toHexString().slice(2)}`

// Workaround.
const hexStringConcatenated = `1220` + hashDigest.toHexString().slice(2)

log.info("New market with CID {}", [cid])
```

**What is the expected behavior?**
ES6 Template Strings are interpolated correctly.

**Comment by tilacog** [comment]
Mappings are not written in ES6 but in AssemblyScript, which still doesn't seems to support template strings.  

This is the relevant issue on their repository:
AssemblyScript/assemblyscript#466
