### ISSUE TITLE
How to define the manifest to capture the event without specifying the contract address?

### ISSUE THREAD

**Issue by ezpod** [graphprotocol/graph-node#2184]
I'd like to track ERC20's Transfer event of all tokens with a subgraph, how should I define the manifest?  Thank you.

**Comment by Jannis** [comment]
The `address` field field of data sources is optional. That allows to scan for events across all contracts. However, the Transfer event is so common that it's currently unrealistic, for performance and storage reasons, to index all of them. It'll take a _long_ time to index.

**Comment by Jannis** [comment]
Questions like this are better suited for https://thegraph.com/discord by the way. 😉
