### ISSUE TITLE
INFO Possible reorg detected

### ISSUE THREAD

**Issue by ClownYar** [graphprotocol/graph-node#2199]
Feb 18 09:50:03.481 INFO Possible reorg detected, retrying, id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, error: "Failed to process trigger in block #4843590 (afe5ea0636169bfb6f46c3fc2jzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager
Feb 18 09:50:03.587 INFO Scanning blocks [4843590, 4843590], range_size: 1, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager > BlockStream
Feb 18 09:50:03.809 INFO 1 trigger found in this block for this subgraph, block_hash: 0xafe5ea0636169bfb6f46c3fc2b8ac4d8f477e4f437f231474d1b81269953f8c0, block_number: 4843590, subgraph_id: 
Feb 18 09:50:04.567 WARN Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "missing trie node 14c74d67d39dbe84685e19da8b38bd539c055f37438ce2e, block_number: 4928373, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:04.567 INFO Done processing Ethereum trigger, waiting_ms: 0, handler: handleTransfer, total_ms: 1901, trigger_type: Log, address: 0x23e8…d89e, signature: Transfer(indexed addres928373, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:04.567 INFO Possible reorg detected, retrying, id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, error: "Failed to process trigger in block #4928373 (6b412a3f1bb51cab0a3a70c4bQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:04.569 INFO Scanning blocks [4928373, 4928373], range_size: 1, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager > BlockStream
Feb 18 09:50:04.659 INFO 5 triggers found in this block for this subgraph, block_hash: 0x6b412a3f1bb51cab0a3a70c4b0f258484685e19da8b38bd539c055f37438ce2e, block_number: 4928373, subgraph_id:
Feb 18 09:50:05.236 WARN Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "missing trie node fd6b7fe89857a38f477e4f437f231474d1b81269953f8c0, block_number: 4843590, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager
Feb 18 09:50:05.237 INFO Done processing Ethereum trigger, waiting_ms: 1, handler: handleTransfer, total_ms: 1428, trigger_type: Log, address: 0x23e8…d89e, signature: Transfer(indexed addres843590, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager
Feb 18 09:50:05.237 INFO Possible reorg detected, retrying, id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, error: "Failed to process trigger in block #4843590 (afe5ea0636169bfb6f46c3fc2jzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager
Feb 18 09:50:05.240 INFO Scanning blocks [4843590, 4843590], range_size: 1, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager > BlockStream
Feb 18 09:50:05.402 INFO 1 trigger found in this block for this subgraph, block_hash: 0xafe5ea0636169bfb6f46c3fc2b8ac4d8f477e4f437f231474d1b81269953f8c0, block_number: 4843590, subgraph_id: 
Feb 18 09:50:05.942 WARN Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "missing trie node 14c74d67d39dbe84685e19da8b38bd539c055f37438ce2e, block_number: 4928373, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:05.943 INFO Done processing Ethereum trigger, waiting_ms: 0, handler: handleTransfer, total_ms: 1283, trigger_type: Log, address: 0x23e8…d89e, signature: Transfer(indexed addres928373, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:05.944 INFO Possible reorg detected, retrying, id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, error: "Failed to process trigger in block #4928373 (6b412a3f1bb51cab0a3a70c4bQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:50:05.946 INFO Scanning blocks [4928373, 4928373], range_size: 1, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager > BlockStream
Feb 18 09:50:06.102 INFO 5 triggers found in this block for this subgraph, block_hash: 0x6b412a3f1bb51cab0a3a70c4b0f258484685e19da8b38bd539c055f37438ce2e, block_number: 4928373, subgraph_id:
[root@ip-172-31-28-32 graph-node]# tail -n 20 nohup.out
Feb 18 09:51:20.493 INFO Scanning blocks [4843590, 4843590], range_size: 1, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager > BlockStream
Feb 18 09:51:20.498 INFO 5 triggers found in this block for this subgraph, block_hash: 0x6b412a3f1bb51cab0a3a70c4b0f258484685e19da8b38bd539c055f37438ce2e, block_number: 4928373, subgraph_id: QmUMi1kMQq2QMUijSEKpPZTUjkGhgB17i1Prxr7rvywkCL, component: SubgraphInstanceManager
Feb 18 09:51:20.579 INFO 1 trigger found in this block for this subgraph, block_hash: 0xafe5ea0636169bfb6f46c3fc2b8ac4d8f477e4f437f231474d1b81269953f8c0, block_number: 4843590, subgraph_id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, component: SubgraphInstanceManager
Feb 18 09:51:20.971 INFO Syncing 1 blocks from Ethereum., code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 4975617, current_block_head: 4975616, network_name: bsc-main-net, component: BlockIngestor

**Comment by ClownYar** [comment]
Hello, as shown in the picture, it has been stuck in the repeated index in the 4843590 block number, what do I need to make it continue to run?

**Comment by ClownYar** [comment]
There is another item, I adjust the view type method of the contract in the sub-picture, but it will return a warning [[ WARN Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error {code: ServerError(-32000) ]], here it looks like the call failed. Will the node repeat the call until it succeeds?

**Comment by shaokun11** [comment]
the same error message with me!!! 
I found it happen when I with instance a ERC20 contact with below code
`let contract = ERC20.bind(tokenAddress)`

**Comment by TheoThug** [comment]
This is also happening on one of our subgraphs (for BSC mainnet)

**Comment by ClownYar** [comment]
I want to join discord, is there an invitation link? The link on the official website is invalid

**Comment by Jannis** [comment]
@ClownYar https://thegraph.com/discord

**Comment by leoyvens** [comment]
An archive node is required for subgraphs that use contract calls.

**Comment by ClownYar** [comment]
> @ClownYar https://thegraph.com/discord


thanks |  
-- | --

**Comment by ClownYar** [comment]
> An archive node is required for subgraphs that use contract calls.

You are right

**Comment by deantheiceman** [comment]
Were you able to solve this? @leoyvens @ClownYar ?

**Comment by leoyvens** [comment]
@deantheiceman If you are having this issue in the context of running your own graph node, please see the comment above. An archive node is required.

**Comment by deantheiceman** [comment]
Hi @leoyvens What is an archive node? I'm using the provided docker-compose to sync bsc

**Comment by leoyvens** [comment]
An archive node is a node running in a special mode that has more data than a full node. Check with BSC for how to run a BSC archive node. Closing this, if you want to continue the conversation please do so on the Discord.

**Comment by langsen111** [comment]
> 嗨@leoyvens什么是存档节点？我正在使用提供的 docker-compose 来同步 bsc

你有解决这个问题么？
