### ISSUE TITLE
Uniswap v2 subgraph syncing too slow - is there any already partially synced version available?

### ISSUE THREAD

**Issue by tokyo786** [graphprotocol/graph-node#2200]
**Do you want to request a *feature* or report a *bug*?**
Uniswap v2 subgraph syncing too slow - is there any already partially synced version available? We're syncing using infura, it's processing about 10 tps, but using local node seems even slower - is there any image available or some sort of partially sycned version which we can download and gap sync?

**What is the current behavior?**
Uniswap v2 subgraph syncing slower on local node AWS i3.2xlarge than on infura.

**What is the expected behavior?**
Should be faster, or need a partially synced version if available.

**Comment by lutter** [comment]
Unfortunately, there is currently no way to export/import partially synced subgraphs. We are planning on making some improvements to speed up syncing of huge subgraphs like Uniswap, but that is going to take a little while.
