### ISSUE TITLE
ServerError(-32000), message: missing trie node

### ISSUE THREAD

**Issue by tokyo786** [graphprotocol/graph-node#2202]
**Do you want to request a *feature* or report a *bug*?**
Getting: ServerError(-32000), message: missing trie node while trying to sync with a local geth node in fast sync as described by your documentation.

**What is the current behavior?**
Getting error with local geth node: ServerError(-32000), message: missing trie node

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Should work fine

**What is the expected behavior?**
Should work similarly like it works with infura node.

**Comment by leoyvens** [comment]
If your subgraph does contract calls within mappings this is expected because then an archive node is required.

**Comment by omurgokyar** [comment]
I lived this problem on Huobi ECO Chain. How can i solve this?

`Feb 23 03:57:05.777 DEBG Found 1 relevant block(s), subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager > BlockStream

Feb 23 03:57:05.778 DEBG Requesting 0 block(s), subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager > BlockStream

Feb 23 03:57:05.779 DEBG Processing 1 triggers, subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager > BlockStream

Feb 23 03:57:05.779 INFO 1 trigger found in this block for this subgraph, block_hash: 0x33856eb6a0a44fc371890f782163617a57e6834313e334c86e4860f4e6828208, block_number: 867157, subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager

Feb 23 03:57:05.779 DEBG Start processing Ethereum trigger, data_source: Factory, handler: handleNewPair, trigger_type: Log, address: 0xc32c…b719, signature: PairCreated(indexed address,indexed address,address,uint256), runtime_host: 1/1, block_hash: 0x33856eb6a0a44fc371890f782163617a57e6834313e334c86e4860f4e6828208, block_number: 867157, subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager

Feb 23 03:57:06.190 DEBG Trying again after eth_call RPC call failed (attempt #1) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "missing trie node 93640656c6c663ff60b38617452487c3096d863e2ec92756d2fdb4058443c3b7 (path )", data: None }))), runtime_host: 1/1, block_hash: 0x33856eb6a0a44fc371890f782163617a57e6834313e334c86e4860f4e6828208, block_number: 867157, subgraph_id: QmTXfVewLoDqTjj2kT2Fofb1kh8tYr7yHmPjzLJCs2VFzy, component: SubgraphInstanceManager
`

**Comment by leoyvens** [comment]
@omurgokyar See the comment above, the Geth or OpenEthereum node must be an archive node because Graph Node does eth_call against historical blocks.

**Comment by leoyvens** [comment]
Closing this, please go to our Discord if you require further support.
