### ISSUE TITLE
cant deploy organization subgraph using personal github

### ISSUE THREAD

**Issue by niicoder** [graphprotocol/graph-node#2204]
**Do you want to request a *feature* or report a *bug*?**
Bug(not sure)

**What is the current behavior?**
I have the correct Access token but it says that is invalid.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It does build correctly and saving IPFS under organization fails.

**What is the expected behavior?**
Deploy successfully.

**Comment by lutter** [comment]
If this is still a problem, can you contact us in #hosted-service in our Discord?
