### ISSUE TITLE
BSC Pancakeswap not syncing

### ISSUE THREAD

**Issue by marcelomorgado** [graphprotocol/graph-node#2208]
Hi there,

I'm running a `graph-node` point to the BSC with a couple of subgraphs. The node itself seems to work as expected, the problem is that the PancakeSwap subgraph isn't syncing fast enough (I'm about a week around 97%).
It looks like a well know issue (https://twitter.com/PancakeSwap/status/1362428932545372163).
Could you please share more information about it? 
I've tried to change some env parameters [1] to improve the performance but didn't change too much so far, there is some recommended setup?
From the infra perspective, I didn't found an obvious bottleneck too. My current env is a large instance (running all services from docker-compose) connected to a BSC full-node from the local network.
There is something that I can do to speed the sync up?

[1] Custom parameters that I'm using right now:
```
      RUST_LOG: info
      ETHEREUM_POLLING_INTERVAL: 50
      ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: 128
      ETHEREUM_BLOCK_BATCH_SIZE: 200
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: 2000
      STORE_CONNECTION_POOL_SIZE: 20
```

Thank you very much!

**Comment by leoyvens** [comment]
One thing to try out is to set `GRAPH_ETHEREUM_CLEANUP_BLOCKS=true` in the env, though this shouldn't be an issue in large infras. We will be looking into PancakeSwap performance.

**Comment by marcelomorgado** [comment]
For the records, the `GRAPH_ETHEREUM_CLEANUP_BLOCKS` parameter made the performance even worst, I've back to the default value.

**Comment by deantheiceman** [comment]
Get a lot of this result:

```
Feb 18 09:50:03.481 INFO Possible reorg detected, retrying, id: QmdhgJsqjzB9igR4m2FExP6ybM48oSqeSMbdswfEYGbDQR, error: "Failed to process trigger in block #4843590
```
Is this also because of pancake swap?

**Comment by marcelomorgado** [comment]
Hi there, any progress with this issue?

Thanks!

**Comment by leoyvens** [comment]
We have this syncing on the hosted service now https://thegraph.com/explorer/subgraph/pancakeswap/exchange. And we have some performance improvements coming up #2222 and #2223. It will take weeks to sync at the current pace, lets see how it goes.

**Comment by leoyvens** [comment]
PancakeSwap is revamping their subgraphs for better performance.
