### ISSUE TITLE
Indexing issue in UniSwap Subgraph -bsg/Dai pair

### ISSUE THREAD

**Issue by cryptogambler01** [graphprotocol/graph-node#2211]
Verified by Ian (the uniswap graph developer as a sync issue in the graph).  The actual pair computes and works fine it is the Subgraph powering the .info site that is broken.  You can also see this price replicated in a number or locations due to this issue. 

The BSG/DAI pair has not updated in 40 days.  
https://info.uniswap.org/pair/0x4a9596e5d2f9bef50e4de092ad7181ae3c40353e

The pair has daily transactions
https://etherscan.io/address/0x4a9596e5d2f9bef50e4de092ad7181ae3c40353e

If you go into the uniswap Subgraph you can see that the pair data and the token (bsg) data is not updating since 40 days ago.

Bsg token tracker - https://etherscan.io/token/0xb34ab2f65c6e4f764ffe740ab83f982021faed6d

Basis.gold site with accurate price
https://basis.gold/

Bad Price in graph/shown is 200k+
Actual Price is ~1400-2000

Given the duration of this issue I hope that it can get quick attention.  The price propagation and lack of updates on the info page is slowly killing our project.

Thanks!

**Comment by leoyvens** [comment]
This can likely be attributed to the bug fixed in https://github.com/graphprotocol/graph-node/pull/2062. The Uniswap subgraph must be resynced or switched to a version that was more recently synced.
