### ISSUE TITLE
Defer validation during `store.set`

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#2222]
Currently, `store.set` will load an entity from the store if the changes passed in do not constitute a valid entity. This causes performance issues when a subgraph calls set on a large number of entities as we end up fetching entities one by one. It would be better to defer validation until after the `EntityCache` has bulk loaded entities at the end of block processing.

This change needs to make sure that validation errors still contain useful information about which handler caused the validation error.

**Comment by leoyvens** [comment]
We decided that we want to defer the full validation as described in the OP, but have a validation for the fields given in `store_set`.

**Comment by tilacog** [comment]
After closer inspection, we discovered that `store.set` wasn't responsible for the performance issues.
