### ISSUE TITLE
Record when a subgraph was created

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#2224]
The `deployment_schemas` table should have a column `created_at` that records when a deployment was created. The information could be gleaned from `subgraph_version`, but that's a bit too cumbersome, and longer term, `subgraph_version` should go away.

The `created_at` timestamp should also be copied to `unused_deployments` when a deployment is recorded as unused.

**Comment by azf20** [comment]
@lutter could we pick this up alongside tracking graph-node version for deployments? cc @tilacog

**Comment by lutter** [comment]
Yeah, I think so; it should be a fairly straightforward database migration, and might not require any code changes since we can just set the default for the new column to `now()`

**Comment by azf20** [comment]
@aodhgan this is referencing storage on the graph-node in the database, but your request is interesting and something that we are investigating (better support for deployment & management of multiple subgraphs from the cli) - I do not think what you describe is currently surfaced.

**Comment by schmidsi** [comment]
@aodhgan Until we have better tooling ready, you can query the management table in your postgresql by yourself:

```SELECT * FROM subgraphs.subgraph```

If you then want to remove a subgraph, simply run:

```graph remove --node http://localhost:8020/ [username/subgraphname]```
