### ISSUE TITLE
Graph writes only fresh blocks in Postgres

### ISSUE THREAD

**Issue by hypnagonia** [graphprotocol/graph-node#2240]
I'm not sure if it is a bug or expected behavior, could you bring some light on it

When I run Graph it listens to new blocks and writes them to Postgres, but historical data is ignored
`select min(number) from chain1.blocks;` - never returns 0 or any early block, and I don't see Graph syncing them

**Comment by Jannis** [comment]
Graph Node only caches blocks locally that

- have relevant for subgraphs (i.e. blocks with data for contracts/events/calls that any of the subgraphs on the node are interested in)
- are detected as new blocks on the chain _while_ Graph Node is running.

Old blocks are not ingested by default.

**Comment by leoyvens** [comment]
Closing as expected behavior. Feel free to jump on the Discord if you have further questions.
