### ISSUE TITLE
Bytes field of over a certain size won't be indexable

### ISSUE THREAD

**Issue by juanmardefago** [graphprotocol/graph-node#2287]
Related to #1133, but instead of having the issue with a field of type `String` we get the same behavior if it's declared as `Bytes`.

As a current workaround I managed to index it correctly by saving the field as a `String` using `.toHexString()`. It works perfectly.

Example of barely short enough byte data that managed to be indexed:
![image](https://user-images.githubusercontent.com/17829741/111410662-eb50a480-86b7-11eb-9d61-1028e22f5c7c.png)

The next entity had a bytes field longer than that and it threw this error:
![image](https://user-images.githubusercontent.com/17829741/111410605-d247f380-86b7-11eb-9683-46a9cea90e5c.png)

I'm guessing the same approach used to fix #1133 could be used. PR that solved it for reference: #1138

**Comment by azf20** [comment]
@lutter I think you might have fixed this one?

**Comment by lutter** [comment]
> @lutter I think you might have fixed this one?

No, this is still open. It requires two things:

1. Changing the DDL we create for a subgraph to only index a prefix of byte fields similar to what we do for strings in `store::postgres::relational::Table.as_ddl` ([here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/relational.rs#L1277-L1293))
2. Adapting the machinery in `store::postgres::relational_queries::PrefixComparison` ([here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/relational_queries.rs#L633-L753)) to work for bytes in addition to strings and use it for byte fields, too, when we generate queries

**Comment by leoyvens** [comment]
We've seen the same issue on GIN indexes for string arrays.

**Comment by azf20** [comment]
Closed by #3340
