### ISSUE TITLE
Improve error when an event signature isn't matched

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#229]
Event signatures must be supplied without spaces in the subgraph manifest.  The error does reference an incorrect event signature which is great, but it is not obvious that one must remove spaces as well as supplying the right set of types.

**Comment by fordN** [comment]
I'm now thinking the preferable solution here is to remove white spaces when parsing the event signature, reducing the number of instructions/steps one must be aware of.  I haven't yet come up with a scenario where white spaces being removed would be undesirable.
