### ISSUE TITLE
Subgraph not working after successful deployment

### ISSUE THREAD

**Issue by oikos1** [graphprotocol/graph-node#2294]
Hello,
A subgraph I have deployed is not working and I cannot determine what the problem is.
The target network is bsc and the subgraph is [here](https://thegraph.com/explorer/subgraph/oikos1/oikos?selected=logs). There are no error messages displayed whatsoever.

**Comment by leoyvens** [comment]
We are having instability with logs on the hosted service, to check the health of your subgraph please use the indexing status api:
```
curl --location --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{ indexingStatusForCurrentVersion(subgraphName: \"<SUBGRAPH-NAME>\") { subgraph fatalError { message } nonFatalErrors {message } } }"}'
```
Replace `<SUBGRAPH-NAME>` with the name of your subgraph. If it's a pending version replace `indexingStatusForCurrentVersion` with `indexingStatusForPendingVersion`

**Comment by oikos1** [comment]
Thank you so much. I was able to pinpoint the issue and solve it. Closing this.

**Comment by oikos1** [comment]
Hello,
I am trying the following command to no avail:

`curl --location --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{ indexingStatusForPendingVersion(subgraphName: \"test") { subgraph fatalError { message } nonFatalErrors {message } } }"}'
 ` 
Is the API still working? thank you in advance

Cheers

**Comment by leoyvens** [comment]
@oikos1 yes it is working. You were missing a backlash in `subgraphName: \"test"`, should be `subgraphName: \"test\"`.

**Comment by oikos1** [comment]
Thank you so much!
