### ISSUE TITLE
Add validation to GraphQL schema for references

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#230]
Currently requires running graphql queries to test type references (relationships). Can we automate validation that these references are setup correctly in the schema file? or provide a warning/message during data load that a specific reference did not return any linked results.

**Comment by Jannis** [comment]
We also want to catch missing `id: ID!` fields on entity types.

**Comment by leoyvens** [comment]
Old issue that's out of context since we now have a lot more validation around everything.
