### ISSUE TITLE
@derivedFrom isn't working in all instances

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#232]
We need to investigate when this doesn't work.

**Comment by fordN** [comment]
After revisiting the adchain example I was able to get the @derivedFrom directive to work; effectively pulling `Challenges` into the `Application` type.  The solution to the difficulties I had getting the two-way relationship working appears to be clear, detailed documentation and a diverse set of example subgraphs to reference.

**Comment by Jannis** [comment]
@fordN Is this not a bug then?

**Comment by Jannis** [comment]
Closing, since we got this to work in the adchain subgraph and it wasn't a bug in the software.
