### ISSUE TITLE
Starting up graph-node fails with eth_getBlockByNumber(0, false) call

### ISSUE THREAD

**Issue by firke** [graphprotocol/graph-node#2320]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Starting up Docker compose graph-node fails.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Clone repo.
2. Change value for 'ethereum' environment variable to 'fantom:https://rpcapi.fantom.network' in docker/docker-compose.yml file.
3. Run 'docker-compose up -d'
4. Logs output the following:

`Mar 29 09:54:58.911 INFO Graph Node version: 0.22.0 (2021-03-25)
Mar 29 09:54:58.912 INFO Generating configuration from command line arguments
Mar 29 09:54:58.957 INFO Starting up
Mar 29 09:54:58.959 INFO Trying IPFS node at: http://ipfs:5001/
Mar 29 09:54:58.977 INFO Creating transport, capabilities: archive, trace, url: https://rpcapi.fantom.network, network: fantom
Mar 29 09:54:58.983 INFO Successfully connected to IPFS node at: http://ipfs:5001/
Mar 29 09:54:59.175 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node, pool: main, shard: primary
Mar 29 09:54:59.199 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
Mar 29 09:54:59.205 INFO Waiting for other graph-node instances to finish migrating, pool: main, shard: primary, component: ConnectionPool
Mar 29 09:55:00.291 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
Mar 29 09:55:00.298 INFO Connecting to Ethereum..., capabilities: archive, trace, network: fantom
Mar 29 09:55:01.314 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Decoder error: Error("invalid type: number, expected a 0x-prefixed hex string with length between (0; 64]", line: 0, column: 0))
Mar 29 09:55:01.473 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #11) with result Err(Decoder error: Error("invalid type: number, expected a 0x-prefixed hex string with length between (0; 64]", line: 0, column: 0))
Mar 29 09:55:02.629 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #12) with result Err(Decoder error: Error("invalid type: number, expected a 0x-prefixed hex string with length between (0; 64]", line: 0, column: 0))`

**What is the expected behavior?**
Graph-node starts up properly, syncing up with the public API endpoint as referenced in Fantom docs - https://ftmscan.com/apis#rpc

Believe is that eth_getBlockByNumber tries to call with values '0, false', whereas it would need to be '0x0, false', value being HEX<number>. This applies to Fantom network, as well as Ethereum, calling Infura with '0, false', referenced here: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbynumber

**Comment by otaviopace** [comment]
I was able to reproduce following your instructions 👍 
I'm gonna check here with the team why this happens 🤔

**Comment by leoyvens** [comment]
Reproducing the call:
```
curl --location --request GET 'https://rpcapi.fantom.network' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 0,
    "method": "eth_getBlockByNumber",
    "params": [
        "0x0",
        false
    ]
}'
```
One of the returned fields is `"extraData": "0x"`, which is most likely the trouble maker, if it were `0x0` I believe we would be able to decode it.

**Comment by leoyvens** [comment]
Actually `"extraData"` might not be the problem. Could you try rpcapi-staging.fantom.network? It has some fixes which are not on the standard node yet.

**Comment by firke** [comment]
Thank you for helping out with this! So that did the trick, both v0.22.0 and latest were able to start syncing rpcapi-staging - this excluded that something got fixed in graph-node docker image along the way.
` Apr 06 08:53:50.627 INFO Syncing 1 blocks from Ethereum., code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 3438062, current_block_head: 3438061, provider: fantom-rpc-0, component: BlockIngestor`

Apologies as I am not an expert in blockchain/rust, but would think it would be beneficial to have '0x' to be included in the output to avoid confusion, e.g. for debugging purposes? Since the actual call is "0x0,  false", and not "0, false"?

As to why this issue appeared - the only different in the call returned is size field, for rpcapi it is "size": 543, and for rpcapi-staging it is "size": "0x21f", which is consistent with the initial error, as int was returned. Might think it might be good to have offending field being included in the output as well?
![diff](https://user-images.githubusercontent.com/16689615/113688972-b7b6d800-96c1-11eb-9a46-d10b3e2bf1ab.png)

Happy for this to be closed, since issue itself is with Fantom RPC Api and not graph-node itself. Thank you for your help on this! 😄

**Comment by leoyvens** [comment]
@firke thanks for reporting back on what the difference is. I'm fine with logging the number in decimal rather than hex, it's more readable.
