### ISSUE TITLE
Where's log.debug output in local graph?

### ISSUE THREAD

**Issue by adamazad** [graphprotocol/graph-node#2323]
**Do you want to request a *feature* or report a *bug*?**

Not sure. But it seems like a bug, at least when you run the graph locally.

**What is the current behavior?**

Running the graph locally via Docker. See [docker-compose.yml](https://github.com/cryptonative-ch/mesa-subgraph/blob/v2/docker-compose.yml). I am trying to debug why a few handlers fail inside the build.

When I debug using `log` from `graph-ts` 

```typescript
import { log } from '@graphprotocol/graph-ts'

export function handleEvent(event: Event): void {
   log.debug(`using contract {} address`, [event.address])
}
```

I don't see the output in the graph's log in the container's logs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

You can fiddle with the current repo https://github.com/cryptonative-ch/mesa-subgraph/tree/v2

**What is the expected behavior?**

See the output of `log.debug` in the logs.

**Comment by jacobrosenthal** [comment]
Drive by comment from another user here. I think the default is like error. you can set it in the docker under RUST_LOG like
```      
GRAPH_LOG: debug
```

**Comment by leoyvens** [comment]
Closing please reopen if still an issue.
