### ISSUE TITLE
 Unknown(the genesis block hash for chain mainnet has changed from 578cbc4d9c32fb20b5d232cf5356c801848f3c56f5fc75807bbc355beceec9cb to 626364ecc527797a4ff6921f575ac303a3d255c7776c03c46fe69853db170fe4 since the last time we ran

### ISSUE THREAD

**Issue by landoyjx** [graphprotocol/graph-node#2332]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Apr 02 08:54:08.304 INFO Graph Node version: 0.22.0 (2021-03-31)
Apr 02 08:54:08.304 INFO Generating configuration from command line arguments
Apr 02 08:54:08.352 INFO Starting up
Apr 02 08:54:08.352 INFO Trying IPFS node at: http://ipfs:5001/
Apr 02 08:54:08.369 INFO Creating transport, capabilities: archive, trace, url: http://rpc:port, provider: mainnet-rpc-0
Apr 02 08:54:08.376 INFO Successfully connected to IPFS node at: http://ipfs:5001/
Apr 02 08:54:08.837 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node, pool: main, shard: primary
Apr 02 08:54:09.038 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
Apr 02 08:54:09.257 INFO Waiting for other graph-node instances to finish migrating, pool: main, shard: primary, component: ConnectionPool
Apr 02 08:54:09.382 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
Apr 02 08:54:09.673 INFO Connecting to Ethereum..., capabilities: archive, trace, network: mainnet
Apr 02 08:54:09.862 INFO Connected to Ethereum, capabilities: archive, trace, network_version: 65, network: mainnet
thread 'tokio-runtime-worker' panicked at 'Creating the BlockStore works: Unknown(the genesis block hash for chain mainnet has changed from 578cbc4d9c32fb20b5d232cf5356c801848f3c56f5fc75807bbc355beceec9cb to 626364ecc527797a4ff6921f575ac303a3d255c7776c03c46fe69853db170fe4 since the last time we ran)', node/src/store_builder.rs:230:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in tokio task, aborting!
/usr/local/bin/start: line 52:    46 Aborted                 graph-node --node-id "${node_id//-/_}" --postgres-url "$postgres_url" --ethereum-rpc $ethereum --ipfs "$ipfs"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I start with docker for ipfs and postgres, and start graph-node with cargo run
when first runing is ok.
Then i stop graph-node ,and restart graph-node, it will report above bug

**What is the expected behavior?**

It should restart normally

**Comment by leoyvens** [comment]
Is this on ganache? Please delete your database when you modify the ganache chain.

**Comment by wojijiwo** [comment]
no, this is not ganache. this is okexchain, i do not change chain or graph. node, just restart graph node

**Comment by landoyjx** [comment]
no, this is not on ganache. it is okexchain. i do not change chain, just restart restart granch-node.

**Comment by uncleGena** [comment]
same error
<details>
  <summary>Click to expand</summary>
 
![image](https://user-images.githubusercontent.com/11743243/113582100-03716f00-9639-11eb-9415-c42d2b7fc0e5.png)

</details>

**Comment by leoyvens** [comment]
@landoyjx Did that chain change its genesis block?

**Comment by landoyjx** [comment]
no, i just restart graph-node, does not change chain code, include genesis block

**Comment by leoyvens** [comment]
@landoyjx does it happen even when you start from a clean database?

**Comment by landoyjx** [comment]
no, it does not happen when start from a clean database

**Comment by leoyvens** [comment]
Then I'll close this since you found the solution of cleaning the DB, and currently there is no other solution for the genesis block changing.
