### ISSUE TITLE
Design robust Ethereum block ingestion/stream algorithm

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#235]
Right now we're simply using RPC and IPC event subscriptions. This is a tenuous solution at best.

Once we implement block explorer data we should switch to an implementation that resembles https://github.com/ethereumjs/ethereumjs-blockstream.

This will ensure that we're not dependent on long-lived connections to reliably produce a stream of events.

Providing an EthereumBlockStream component with an `impl EventProducer<Block> for EthereumBlockStream` would be nice. It could take a block range and fetch existing blocks the usual way and future blocks as described. We could then turn that stream into block explorer data stored in Postgres.

**Comment by timmclean** [comment]
cc @Jannis

Here's a first pass at a high-level description. Next, I'll get more specific with how this fits with existing components, Streams, etc and nail down some naming, but feedback is welcome!

Configurable parameters:
-	what chain to use (TODO spec this)
-	history_depth (positive integer): how far back to store blocks
	-	the number of blocks in the inclusive range [latest_block, oldest_block] will be at least history_depth

DB tables:
-	chains
	-	id
	-	head_block_hash
	-	head_block_height
-	blocks
	-	hash
	-	parent_hash
	-	height
	-	JSON blob with remaining info?

On set up:
-	ask for latest block
-	recursively request parent blocks until # of blocks is history_depth
-	insert a chain with appropriate ID and head_block_hash == latest block hash

After set up, the following invariants are maintained in DB:
-	chain.head_block_height == height of block with hash chain.head_block_hash
-	chain.head_block_hash points to a block present in DB and whose history_depth-1 ancestors are also present in DB

On startup:
-	subscribe to receive new blocks from Eth node
	-	web3.eth_subscribe().subscribe_new_heads()
	-	each notification received triggers a BlockIngestEvent
-	ask for latest block
	-	web3.eth().block(BlockId::Number(BlockNumber::Latest))
	-	trigger a BlockIngestEvent
		-	note: block may not be new to us, trigger event anyway

if none received in last 5 minutes, log error, restart subscription, check again for latest block

On BlockIngestEvent (parameter: a list of blocks to ingest):
-	upsert each new block into blocks table with appropriate chain ID
	-	note: if none of the blocks were new, this will be a no-op
-	start a DB transaction:
	-	check for gaps:
		-	select all blocks in this chain where:
			1.	parent_hash does not correspond to a block in table, AND
			2.	the block's height > (largest block height of any block in the table)-history_depth+1
				-	note: ensures block is recent enough that we care about its parent
		-	if # == 0 then continue (there are no gaps in the region we care about)
		-	if # > 0 then there are missing blocks:
			-	get parent_hash from each block in this list
			-	dedupe list of parent_hashes
			-	end transaction
			-	outside of DB transaction:
				-	load these blocks
				-	trigger a new BlockIngestEvent with list of blocks
				-	end
	-	note: if we are here, then (in this chain) every block with height > max(block.height)-history_depth+1 has its parent block in DB
	-	get (block_hash, block_height) of some block with max(block.height) in this chain
		-	note: if multiple blocks have the same largest height, it doesn't matter which we pick
	-	if chain.head_block_height < block_height:
		-	note: use of strict inequality here should mean less thrashing
		-	set chain.head_block_hash = block_hash
		-	set chain.head_block_height = block_height
	-	if chain was modified, trigger ChainUpdateEvent, probably via postgres pubsub?
-	clean up:
	-	note: this is optional, could be done in a background process periodically, etc
	-	for each chain:
		-	delete all blocks with block height <= max(block height)-history_depth

On ChainUpdateEvent (received from DB, indirectly)
-	advise each runtime of new head hash
-	each runtime:
	-	let common_ancestor = first common ancestor of [new_head, current_head]
	-	get list of blocks on range [current_head, common_ancestor)
		-	empty list if current_head == common_ancestor
	-	trigger RewindBlockEvent for each
	-	get list of blocks on range (common_ancestor, new_head]
	-	trigger ProcessBlockEvent for each
	-	note: ideally, runtime tracks current_head in DB, updating current_head (compare and set?) in the same transaction as any other database updates to prevent double processing/rewinding of blocks
		-	alternative: could do same, but with Process/RewindLogEvent, tracking current_log in DB

**Comment by Jannis** [comment]
@timmclean Perfect! 

A couple notes:

* The `On ChainUpdateEvent` section is still a bit rough but we can make that more specific as we go.
* I wonder if it's worth subscribing to new blocks at all or if polling is going to more stable/reliable. It's easy enough to poll in a worker thread using a timeout. Dealing with subscription errors (connections being dropped etc.) could be a pain.
* If we store block data using JSONB, that keeps our table schema simple and may allow us to to deserialize/serialize the blocks that we get from `rust-web3` (https://docs.rs/web3/0.3.1/web3/types/struct.Block.html) without much extra work (may require a newtype wrapper that implements serde traits but that's easy). So I like that approach.

**Comment by timmclean** [comment]
I like that suggestion on using polling over subscriptions. That sounds a lot easier!

What do you think about this blocks table schema:

- hash (primary key)
- parent_hash
- height
- as_json (JSONB)

Do you think it's better if I move `parent_hash` and `height` inside the JSONB? Or keep them split out into separate columns for easier querying?
IIRC primary keys have to have their own column though, so there will have to be at least a bit of redundancy there with `hash` being in both the JSONB column and its own column.

**Comment by Jannis** [comment]
I think that's fine. Those fields are so essential in the ingestion algorithm that we can (maybe even should) have dedicated columns for them. The schema looks good to me.
