### ISSUE TITLE
`ipfs.cat` not properly handling timeouts

### ISSUE THREAD

**Issue by acolytec3** [graphprotocol/graph-node#2351]
Our subgraph has recently begun to experience issues where calls to `ipfs.cat` are resulting in an endless loop where the subgraph gets stuck trying to resolve the same IPFS hash, dumping endless warnings to the subgraph logs like below:
```
Trying again after object.stat failed (attempt graphprotocol/graph-ts#20) with result Err(Uncategorized("<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.19.8</center>\r\n</body>\r\n</html>\r\n")), runtime_host: 1/1, block_hash: 0x88f43bd517170d43d12a4a2fdf59c135422935f1dd7f82d9e6a75f3e7b6f31fd, block_number: 24052377
```
This is happening for at least 3 separate IPFS hashes in our subgraph that I know are all returning 504s from the IPFS gateway (presumably because of the content not being pinned and then garbage collected by the IPFS nodes).

From looking at the GraphQL API docs, I would expect `ipfs.cat` to return `null` in cases where the hash doesn't resolve on IPFS  within some timeout period but from the error above, it looks like it's trying to resolve the HTML string to `bytes`.

The only workaround I've identified for this is to manually catch those IPFS hashes in our subgraph handler method and then skip them so the subgraph doesn't get stuck.

**Comment by acolytec3** [comment]
[Here's]( https://thegraph.com/explorer/subgraph/charged-particles/dev-universe) the kovan deployment where it's breaking.  Check the pending version logs.  

[This](https://kovan.etherscan.io/tx/0x58295cfaf4783f0101152068a17a6b04c81b2cf796cff275a2731dc2d444aa50) is the specific transaction which is minting an NFT.  

This is the IPFS hash it's getting stuck on - QmcfMBWdXMubqGGS6nYKNJXAeB9PTJpCH8NTuzN5uGLkvp though there are two other instances in later blocks where the same issue happens.

**Comment by acolytec3** [comment]
[Here](https://github.com/Charged-Particles/charged-particles-subgraph/blob/2f3f246a369b70f0eae3f5cffd5be5157b88a752/src/helpers/common.ts#L24) is our code where `ipfs.cat` is called.  If I add additional logic to specifically not call `cat` with the above noted IPFS hash, it is able to continue syncing.

**Comment by acolytec3** [comment]
This looks like it might be related to the initial issue that was reported under #2306 though not sure if the underlying issue is the same or not.

**Comment by leoyvens** [comment]
@acolytec3 that's different. I will look into this one to see how feasible it is to return null on 504.

**Comment by leoyvens** [comment]
This should be fixed.

**Comment by acolytec3** [comment]
@leoyvens Just confirming that this appears to have resolved the issue our subgraph was facing.  I removed the edits I had made for the bad ipfs hashes and redeployed and it appears to be syncing.

Thank you!
