### ISSUE TITLE
Subgraph instance failed to run: Failed to process trigger in block XXXX

### ISSUE THREAD

**Issue by AlexBHarley** [graphprotocol/graph-node#2353]
**Do you want to request a *feature* or report a *bug*?** Report a bug

**What is the current behavior?** The sub graph stalls at around 1% with the error `Subgraph instance failed to run: Failed to process trigger in block #190080 (ac57ac5a96108b0f133ac6bac59e1bd0df0263d248a4fcc36393464b7c73835d), transaction ac57ac5a96108b0f133ac6bac59e1bd0df0263d248a4fcc36393464b7c73835d: Found no transaction for event, code: SubgraphSyncingFailure, id: QmfBAFQ6JX1QyVG8rfzUYSkax6Lot4j7qaTWdGVZcYWEsL`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here's the [link](https://discord.com/channels/438038660412342282/438070183794573313/829290504436580434) to my Discord message, but concretely here is my bash history.

```
10020  graph init --from-contract 0x471EcE3750Da237f93B8E339c536989b8978a438 --network celo --abi ../celo-monorepo/packages/protocol/build/contracts/GoldToken.json alexbharley/celo-token ./celo-token
10021  cd celo-token
10023  yarn
10024  yarn codegen
10022  yarn deploy
10025  graph auth https://api.thegraph.com/deploy/ XXX
10026  yarn deploy
```

Here is:

- the explorer link https://thegraph.com/explorer/subgraph/alexbharley/celo-token 
- my code https://github.com/AlexBHarley/celo-token

**What is the expected behavior?** The subgraph builds without error and I can query it.

**Comment by azf20** [comment]
There appear to be no transactions in the error block on Celo: https://explorer.celo.org/blocks/190080/transactions

**Comment by azf20** [comment]
This appears to relate to [Epoch rewards on Celo](https://docs.celo.org/celo-codebase/protocol/proof-of-stake/epoch-rewards). These appear in `eth_getLogs` but do not have a corresponding transaction. Investigating with the Celo team.

**Comment by azf20** [comment]
This has also affected [this subgraph](https://thegraph.com/explorer/subgraph/manangouhari/celoelection)

**Comment by azf20** [comment]
This likely requires an update to the Celo client so that a transaction is returned for `eth_getTransactionByHash` for these epoch logs

**Comment by leoyvens** [comment]
@AlexBHarley This is issue happens when the subgraph tries to process an epoch reward event from Celo. Does your subgraph need those events, or would you be happy if the subgraph just skipped over those?
