### ISSUE TITLE
Implement @entity directive for entity types in GraphQL schema

### ISSUE THREAD

**Issue by Zerim** [graphprotocol/graph-node#236]
We currently don't parse the subgraph GraphQL schema's according to what's in the spec here: https://github.com/graphprotocol/specs/tree/master/graphql-api.

There should be an `@entity` directive required for entity types. I'm labeling this for the DX milestone, since this will be a breaking API change and we should make it soon.

**Comment by Jannis** [comment]
This is also required to identify which entity change events we want to subscribe to when handling subscriptions. Without `@entity` we don't know which GraphQL types correspond to entities. I'll assign this one to me and mark it as part of GraphQL subscriptions.
