### ISSUE TITLE
Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure

### ISSUE THREAD

**Issue by dmotz** [graphprotocol/graph-node#2360]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Successfully calling a contract method produces `Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure` in my local graph node.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I've deployed a simple subgraph to my local graph node. Calling a contract method succeeds with an emitted event but causes this error on the node and gives no further details.

**What is the expected behavior?**
The node should succeed in handling the contract event.

My contract is simple and emits an event from the method I'm calling. The mapping function is simply setting event parameters as fields in a new entity object and saving it, nothing more. I'm guessing maybe there's some issue with the mapping function -- is there any other log the node provides?

Only other thing to note is the event has some indexed parameters. I'm not sure if that makes a difference.

**Comment by leoyvens** [comment]
Please run with `GRAPH_LOG=trace` in the environment and post a link to the complete logs. Having the subgraph source available might also help.

**Comment by dmotz** [comment]
Through trial and error I found the offending line was this:

```typescript
entity.created = (Date.now() / 1000) as i32
```

I changed the schema's `created` field to a `BigInt` and changed the mapping to this and it now works:

```typescript
entity.created = event.block.timestamp
```

Is this considered the proper way of getting a rough time for an entity's creation?
