### ISSUE TITLE
try adding it to the 'abis' section of the subgraph manifest

### ISSUE THREAD

**Issue by novaknole** [graphprotocol/graph-node#2361]
**Do you want to request a *feature* or report a *bug*?**
**BUG**
**What is the current behavior?**
I am using dynamic templates in `yaml`.  Now, I want to use `.bind` in the mapping, so that I can call some `view` functions on the contract.

```js
import { GovernQueue as GovernQueueContract } from '../generated/templates/GovernQueue/GovernQueue'

queue.nonce = GovernQueueContract.bind(queueAddress).nonce()
```

`queueAddress` is correct. The above results in the following: 

> Subgraph instance failed to run: Failed to process trigger in block #8244999 (03c22a005a0bb985f1bbdc180c39af9e46d7f499e47fbbf50468b49a47cc4675), 
>   transaction 20b3d7db4b649fbcc675873a86d72d7a27c477dd096c78a3af5652fb5f0c636c: Could not find ABI for contract "GovernQueue", 
>   try adding it to the 'abis' section of the subgraph manifest wasm backtrace: 
>   0: 0x1f21 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 
>   0x1fc1 - <unknown>!src/GovernQueue/loadOrCreateQueue 2: 0x2214 - <unknown>!src/GovernRegistry/handleRegistered , 
>   code: SubgraphSyncingFailure, id: QmT8FXVVbQVvxzuPYucZysnbUjXCdFfm5kN7AwM8ema8SZ
> 

The `yaml` - https://gist.github.com/novaknole/bc69c3883eae8879bf0dbc7622ba0fdc
The contract - https://gist.github.com/novaknole/1a6c5f0c7e63b9ba8afd87fc3135ed5d

**Comment by leoyvens** [comment]
The error message seems correct, you need the `GovernQueue` abi in all data sources from which you will call it.

**Comment by novaknole** [comment]
@leoyvens  if you look at the `yaml` file, you will notice that `abis` section contains the url of the abi.  and this contract that I do `bind` on, seems like contains function declarations too https://gist.github.com/novaknole/1a6c5f0c7e63b9ba8afd87fc3135ed5d

So doesn't make sense what I should do to fix it.

**Comment by leoyvens** [comment]
@novaknole But not all the `abis` sections, only from one data source. I'd need the full source to be able to confirm that this is the issue.

**Comment by novaknole** [comment]
@leoyvens 

Fixed it. Thanks a lot.

**Comment by itopmoon** [comment]
@novaknole would you mind letting me know how you fixed it? I get the same error and no idea why it happens

**Comment by azf20** [comment]
@itopmoon you need to add all the `abis` you use for a given mapping to that mapping specifically, in the yaml - I think in @novaknole 's case it was here https://gist.github.com/novaknole/bc69c3883eae8879bf0dbc7622ba0fdc#file-subgraph-yaml-L88

**Comment by itopmoon** [comment]
@azf20 yes, i've just noticed that I had to add the abi under the datasource context when I use  a template contract in there.
Thanks! It works now

**Comment by akugone** [comment]
Hello guyz, i have the same problem, could you help me, it thrown the same error even if i import all the needed abis

**Comment by azf20** [comment]
@akugone  are they imported to the individual templates, as well as the parent datasources?

**Comment by akugone** [comment]
hello i solve the problem, i forget one datasource, all good :)

**Comment by PatSsso** [comment]
I also encountered this problem, but all the data in the yaml file is written correctly, what else could be the problem.
