### ISSUE TITLE
502 while deploying subgraph

### ISSUE THREAD

**Issue by novaknole** [graphprotocol/graph-node#2363]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I use this 

```
 graph deploy $FULLNAME \
        --ipfs https://api.thegraph.com/ipfs/ \
        --node https://api.thegraph.com/deploy/ \
        --access-token $token > deploy-output.txt
```

It seems like that every 2nd time, running it from `bash` script returns 502 error. Then I try to run it again and it works fine.

What could be the actual issue ? at least something to get me started.

**Comment by leoyvens** [comment]
One of the index nodes was being reset when you posted this, is it still happening?

**Comment by novaknole** [comment]
This is basically happening the whole day today. Every nth deploy returns 502, every (n+1)th succeeds. 

Very interesting.

**Comment by QYuQianchen** [comment]
I also got the same experience today.

**Comment by azf20** [comment]
Thanks @novaknole & @QYuQianchen!  @leoyvens made some changes which should have resolved this issue (except for networks where we have unhealthy eth_nodes, notably BSC, see https://status.thegraph.com/).
Please let us know if you see this again!
