### ISSUE TITLE
504 while deploying subgraph

### ISSUE THREAD

**Issue by pynixwang** [graphprotocol/graph-node#2368]
deploy failed with 504,

log show received deploy request but response with 504

**Comment by azf20** [comment]
Apologies for the slow response. Was this on the Hosted Service? Will close this for now, please do re-open if you are still seeing this issue.

**Comment by pynixwang** [comment]
@azf20 no, self host node

**Comment by azf20** [comment]
OK interesting - are you still having the problem? Could you share the logs if so?

**Comment by RongxinZhang** [comment]
@azf20 I'm having this issue when I deploy the docker container on a server.
All the other ports: 8001 and others all work. It's seems to only be allowing connections from 127.0.0.1:8020?
```
aph-nodeJan 19 02:53:39.514 INFO Starting JSON-RPC admin server at: http://localhost:8020, component: JsonRpcServer
```
Where can I set this server to be from `0.0.0.0:8020` instead?
