### ISSUE TITLE
Error in cargo build |  unable to get packages from source

### ISSUE THREAD

**Issue by guru260** [graphprotocol/graph-node#2371]
I am trying to set up graph-node. I followed the following steps.
```
git clone https://github.com/graphprotocol/graph-node.git
cd graph-node
cargo build
```
I am getting the following error,```

➜  graph-node git:(master) cargo build
warning: /Users/user/hack/subgraph/graph-node/Cargo.toml: unused manifest key: patch.crates-io.graphql-parser.commit
error: failed to download `cranelift-codegen-shared v0.73.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/selvam/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-shared-0.73.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

cargo version:
```
cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)
```

**Comment by leoyvens** [comment]
Please update to Rust 1.51
