### ISSUE TITLE
Question: Syncing a graph node using WSS instead of HTTP

### ISSUE THREAD

**Issue by Corfucinas** [graphprotocol/graph-node#2375]
Is there's a way to use the current `docker-compose.yml` file under docker/ with a `wss` in the `ethereum:` env for the graph-node?

I wish to sync a graph node using was, but I keep getting 301 responses

**Comment by lutter** [comment]
We generally recommend using rpc endpoints, and that's what's most thoroughly tested. If you need to use `wss`, could you try with the URL that the service is redirecting you to in the `301` response?
