### ISSUE TITLE
Update to tokio 1.0

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#2380]
This upgrade was attempted, but it had to be reverted in #2379 because it caused at least two bugs that remain mysterious:
1. Seemly randomly, a very loaded node would not send chain head updates to syncing subgraphs. This could be worked around by a fallback such as #2378, but ideally chain head updates should always work.
2. Serious performance regressions in block processing time, at least in very loaded nodes. Uniswap in a community node had a 2x slowdown in block processing time.

We also had an update for web3 in #2362 which had to be reverted along with tokio. Attempting to upgrade again will require deep investigation into these two bugs.

**Comment by azf20** [comment]
Is there urgency around this tokio upgrade or is this just good hygiene?

**Comment by leoyvens** [comment]
Not urgent, but it prevents us from updating other networking dependencies such as hyper (the http server) and web3. This makes it unpleasant to contribute to the networking parts of the code and outdated dependencies may generate security issues. I'd classify this is high-interest technical debt. But resolving it would require commitment because the above issues are difficult to reproduce and root cause, it could take weeks.

**Comment by leoyvens** [comment]
This is done!
