### ISSUE TITLE
Lot's of 504 Gateway Timeouts - Trying again after eth_getLogs RPC call failed

### ISSUE THREAD

**Issue by pkmelee337** [graphprotocol/graph-node#2394]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
I'm not sure if this is the correct place to report this bug (if not I'm sorry), but I'm seeing a lot of warning messages with subgraphs on the bsc chain:

> Trying again after eth_getLogs RPC call failed (attempt #9) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream
> 
> 20-4-2021 15:08:34
> 
> DEBUG
> 
> Trying again after eth_getLogs RPC call failed (attempt #9) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream
> 
> 20-4-2021 15:07:32
> 
> DEBUG
> 
> Trying again after eth_getLogs RPC call failed (attempt #7) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream
> 
> 20-4-2021 15:07:01
> 
> DEBUG
> 
> Trying again after eth_getLogs RPC call failed (attempt #6) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream
> 
> 20-4-2021 15:04:58
> 
> DEBUG
> 
> Trying again after eth_getLogs RPC call failed (attempt #2) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream
> 
> 20-4-2021 15:04:27
> 
> DEBUG
> 
> Trying again after eth_getLogs RPC call failed (attempt #1) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream

Sometimes it's also ending with the following error:

> 20-4-2021 15:08:12
> 
> WARNING
> 
> Unexpected RPC error, error: Transport("Unexpected response status code: 504 Gateway Timeout"), component: BlockStream
> 
> 20-4-2021 15:08:12
> 
> WARNING
> 
> Trying again after eth_getLogs RPC call failed (attempt #10) with result Err(Transport("Unexpected response status code: 504 Gateway Timeout")), component: BlockStream

Is this cause by a wrong written subgraph or does it have to do with the BSC network? Above error messages are on the pancakeswap subgraph and some other DEX subgraphs as well, while the uniswap subgraph (form which most of these subgraphs are basically cloned) does not have this problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I checked the logs on the following places:
https://thegraph.com/explorer/subgraph/pancakeswap/dex-candles?selected=logs
https://thegraph.com/explorer/subgraph/pancakeswap/exchange?selected=logs
https://thegraph.com/explorer/subgraph/psi-passive-income/exchange?selected=logs

**What is the expected behavior?**
These debug logs/warnings are causing the subgraphs getting out of sync. My expected behavior would be for this to work correctly.

**Comment by azf20** [comment]
This is a Hosted Service issue, rather than a graph-node bug. There are ongoing problems with our eth_node providers from BSC, you can track at https://status.thegraph.com/ and on our [discord](https://discord.gg/vtvv7FP)
