### ISSUE TITLE
Deprecated subgraph in README.md and getting-started.md

### ISSUE THREAD

**Issue by simsekgokhan** [graphprotocol/graph-node#2395]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
Due to this deprecated subgraph: https://github.com/graphprotocol/ens-subgraph, used in https://github.com/graphprotocol/graph-node#running-a-local-graph-node deploy step fails. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Working/deploy-able https://github.com/ensdomains/ens-subgraph should be used in README.md and getting-started.md

**Comment by otaviopace** [comment]
Hey @simsekgokhan I've done a PR to fix this 😊 
We recommend using this docs for a quick start: https://thegraph.com/docs/quick-start#local-development

**Comment by simsekgokhan** [comment]
Thanks @otaviopace :)
