### ISSUE TITLE
local deployment failed with error "  Failed to deploy to Graph node http://localhost:8020/: subgraph deployment error: Fulltext search not yet deterministic "

### ISSUE THREAD

**Issue by Chimbili-Pavan** [graphprotocol/graph-node#2400]
I am trying to deploy subgraph on graph node running locally.
It is throwing the error saying  " fulltext search not yet deterministic ", but when I remove fulltext search in schema.graphql file then it is getting deployed successfully.
How do i include this fulltext search feature in subgraph which is getting deployed in local graph node.

**Comment by leoyvens** [comment]
You need to set the `GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH` environment variable.

**Comment by waybeforenow** [comment]
@leoyvens Please document this.
