### ISSUE TITLE
RPC call failed ServerError(-32000)

### ISSUE THREAD

**Issue by tdergouzi** [graphprotocol/graph-node#2401]
**network: bsc**
```sh
RPC error: Error { code: ServerError(-32000), message: "header for hash not found", data: None } wasm backtrace: 0: 0x14aa - <unknown>!<wasm function 49> 1: 0x1694 - <unknown>!<wasm function 56> 2: 0x1753 - <unknown>!<wasm function 57>
```

**Comment by lutter** [comment]
Can you share more details, like which subgraph this is, and a longer excerpt of the subgraph logs before this error? Was this on the hosted service or on a graph-node that you are running locally? Basically, we need more information to be able to reproduce the error.

**Comment by azf20** [comment]
There were some issues on the Hosted Service BSC nodes, which may have contributed. These have now been resolved. Given that will close this issue, let us know if you see any further problems!
