### ISSUE TITLE
Out of gas tx triggers subgraph call handler

### ISSUE THREAD

**Issue by fnanni-0** [graphprotocol/graph-node#2409]
[This transaction](https://etherscan.io/tx/0x2cd6ef64770b12e29006fd3e4a9cd008e98f62d51f9f7b91e58d7d670219b8da) ran out of gas. The purpose of this transaction was to execute 3 different transactions through a transaction batcher contract. You can see that the first of those transactions is calling executeRequest() of [this contract](https://etherscan.io/address/0xC5E9dDebb09Cd64DfaCab4011A0D5cEDaf7c9BDb).

My understanding is that this reverted transaction should not have triggered any call in the [subgraph](https://thegraph.com/explorer/subgraph/kleros/proof-of-humanity-mainnet). However, it did trigger executeRequest() call handler. Is this a bug or am I missing something?

**Comment by leoyvens** [comment]
No ETA yet, but I'll share some thoughts on what it takes to fix this:

- A transaction is considered reverted if either the gas spent equals the provided gas, or if the status field has a value of `0`, see [EIP-658](https://eips.ethereum.org/EIPS/eip-658).

- Gas spent and the status are fields of the transaction receipt, but for historical blocks Graph Node does not fetch receipts. So fixing this will incur a performance hit to the sync time of all subgraphs employing call handlers.

- A decision needs to be made if this fix will be versioned in Graph Node and therefore apply to existing subgraphs, or if this fix will be versioned in the manifest.

**Comment by fnanni-0** [comment]
Got it, thanks for the explanation!
