### ISSUE TITLE
Running local graph node with ganache-cli results in `(node:10343) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.`

### ISSUE THREAD

**Issue by n1punp** [graphprotocol/graph-node#2410]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When running local graph node with `ganache-cli`, ganache produces:

```(node:10343) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Steps to reproduce:
1. Run ganache (tried with both having `--chainId 1` and not having it):
```
ganache-cli --accounts 10 --defaultBalanceEther 10000000000000 --hardfork istanbul --fork ALCHEMY_API --gasLimit 12000000 --mnemonic brownie --port 8545 --chainId 1
```

2. Run `docker-compose up` from graph-node repo.

Result: When ganache is called `eth_getBlockByHash`, the error is produced.

```(node:10343) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.```

**What is the expected behavior?**

**Expected Behavior**: no error.

**Tested environment**:
- Ganache CLI v6.12.2 (ganache-core: 2.13.2) --- have also tried downgrading to 6.8.2, 6.9.0, 6.10.0, 6.11.0, and still doesn't work.
- System: OS X Catalina 10.15.4

**Comment by n1punp** [comment]
> I think ganache may inherit the chainId from ALCHEMY - do you get the same error if you pass a `localhost` chainId (e.g. 1337)

Same error when passing `--chainId 1337` too.

**Comment by dan13ram** [comment]
Any updates guys ? I'm facing the same issue.

**Comment by azf20** [comment]
This seems somewhat similar to https://github.com/EthWorks/Waffle/issues/180, which was a ganache issue, though it looks like the underlying was fixed some time ago. You get that error when graph-node calls `eth_getBlockByHash`, rather than when a transaction is actually being made?

**Comment by dan13ram** [comment]
@azf20 Its only when graph-node calls `eth_getBlockByHash`. I'm able to deploy contracts and interact with it without any issues, so I'd say sending transactions work fine.

Just like @n1punp has shared, I've tried multiple different versions of ganache-cli with and without setting chainId. And I get similar errors everytime.

**Comment by kylezs** [comment]
I believe this is a ganache issue since I'm not using graph protocol. Not sure on the solution, but found this issue when looking around for a solution. I'd raise it with ganache. I have exactly the same scenario, getting the error on `eth_getLogs`, after submitting some transactions successfully.

**Comment by bogatyy** [comment]
Can confirm that it is a ganache issue and I'm having the same problem as of `ganache-cli version 6.12.2, ganache-core version 2.13.2`

Found a Ganache pull request that claimed to fix the issue, but doesn't seem like it's fully fixed
https://github.com/trufflesuite/ganache-core/pull/532

**Comment by azf20** [comment]
Thanks @bogatyy! Will close this for now, but please do re-open if this looks like a graph-node issue

**Comment by Shubhamkunwar10** [comment]
start npx-ganahce with port number. Like this:
npx ganache-cli --chainId 5777

**Comment by luisanton-io** [comment]
I absolutely found no way to make this work with a mainnet fork.
While it works fine without forking, unfortunately this error is still precisely what I have been getting for hours.
I even tried swapping Ganache for Hardhat, but others error pop up (but that's perhaps for another thread)

Did anyone actually follow [this guide](https://thegraph.academy/developers/local-development/) and get it working running ganache like this:
``` 
ganache-cli -h 0.0.0.0 --fork https://your.rpc.url 
```
without this error?

**Comment by luisanton-io** [comment]
Update: for any future Googlers coming from that walkthrough, please be aware that `ganache-cli` is deprecated. Install and use `ganache`.
