### ISSUE TITLE
Unexpected RPC error, error: Transport("Unexpected response status code: 502 Bad Gateway"), component: BlockStream

### ISSUE THREAD

**Issue by mohamed-nasir** [graphprotocol/graph-node#2415]
I have deployed pancakeswap subgraph. but syncing is failed.

![image](https://user-images.githubusercontent.com/73598690/116365959-5c978180-a838-11eb-8b6d-c1d0a12bb29e.png)

Please help me and solve this problem.

Thanks.

**Comment by lutter** [comment]
This is an issue with our BSC provider; we are working with them to get it resolved, but it might take a little longer before that is available.

**Comment by trgiangvp3** [comment]
> This is an issue with our BSC provider; we are working with them to get it resolved, but it might take a little longer before that is available.

What is the status of this issue?
I'm getting the same issue and just want to know when it gets fixed, or are there any workaround?

**Comment by zenithcodeservices** [comment]
> This is an issue with our BSC provider; we are working with them to get it resolved, but it might take a little longer before that is available.

I'm the same here, I'm facing this error right now.
