### ISSUE TITLE
Clones of double references

### ISSUE THREAD

**Issue by vrmiguel** [graphprotocol/graph-node#2434]
There are currently at least fourteen instances of clones of double references*:

* [graph/src/components/metrics/mod.rs:24](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L24)
* [graph/src/components/metrics/mod.rs:34](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L34)
* [graph/src/components/metrics/mod.rs:72](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L72)
* [graph/src/components/metrics/mod.rs:84](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L84)
* [graph/src/components/metrics/mod.rs:96](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L96)
* [graph/src/components/metrics/mod.rs:116](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L116)
* [graph/src/components/metrics/mod.rs:130](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L130)
* [graph/src/components/metrics/mod.rs:168](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L168)
* [graph/src/components/metrics/mod.rs:188](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L188)
* [graph/src/components/metrics/mod.rs:208](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L208)
* [graph/src/components/metrics/mod.rs:223](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L223)
* [graph/src/components/metrics/mod.rs:247](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/components/metrics/mod.rs#L247)
* [graph/src/data/schema.rs:213](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/data/schema.rs#L213)
* [graph/src/data/schema.rs:1192](https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graph/src/data/schema.rs#L1192)

I'm not sure if the intended behavior is to actually clone the references or the underlying data being referenced.

I could change these lines to make them clone the underlying data or to make the reference cloning explicit.
@lutter @tilacog @leoyvens 

*: Example: 

```rust
fn main() {
    let x = vec![5];
    let y = &&x;
    let z = y.clone();
    println!("{:p} {:p}", *y, z); // Will print out the same pointer
}
```

**Comment by lutter** [comment]
I am pretty sure these are just leftovers where maybe at some point, it was necessary to clone, and a refactor changed it to pass references but the clone wasn't cleaned up. Since cloning a reference is really a noop, I think we should just remove the clone.

**Comment by vrmiguel** [comment]
> I am pretty sure these are just leftovers where maybe at some point, it was necessary to clone, and a refactor changed it to pass references but the clone wasn't cleaned up. Since cloning a reference is really a noop, I think we should just remove the clone.

True :thinking: it probably is a side-effect from the recent change from &String to &str.

I'll make a small PR to remove those
