### ISSUE TITLE
Introspection queries stop working after a subgraph has encountered an indexing error

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#2443]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Introspection queries fail after a subgraph has encountered an indexing error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This potentially also happens if the subgraph flat fails (not sure) but we encountered it whilst using the nonFatalErrors feature. Hence:

1. Deploy a failing subgraph using the nonFatalErrors feature
2. Wait for it to fail and then try to run a schema introspection or type query
3. The query returns `message: indexing_error`

**What is the expected behavior?**
Even if a subgraph has failed, introspection queries should always work (both when using the nonFatalErrors feature or not). The schema is immutable and not affected by any indexing errors.

The `__schema` and `__type` fields are part of the spec and used by various tooling. Hence, adding a `subgraphErrors: allow` input field to those fields wouldn't work well. Instead, both `__type` and `__schema` should simply always work.

**Comment by mshakeg** [comment]
Hi @leoyvens , would it be possible to get this addressed? This issue has been open for quite a while now.
