### ISSUE TITLE
when i build on centos7 display fail. why this error?

### ISSUE THREAD

**Issue by 0xCaviar** [graphprotocol/graph-node#2447]
warning: /opt/www/graph-node/Cargo.toml: unused manifest key: patch.crates-io.graphql-parser.commit
   Compiling graph-node v0.22.0 (/opt/www/graph-node/node)
thread 'rustc' panicked at 'found unstable fingerprints for evaluate_obligation(c2297113fabf0317-aa6020c34b4b0694): Ok(EvaluatedToOkModuloRegions)', /rustc/88f19c6dab716c6281af7602e30f413e809c5974/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0 (88f19c6da 2021-05-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `graph_graphql::graphql_parser::query::Value<std::string::String>: std::marker::Sized`
#1 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All }, value: ProjectionTy { substs: [combine::parser::combinator::Map<(((combine::parser::choice::Optional<graph_graphql::graphql_parser::helpers::NameMatch<std::string::String>>, combine::parser::combinator::Map<combine::parser::choice::Optional<combine::parser::sequence::Skip<combine::parser::sequence::With<graph_graphql::graphql_parser::helpers::Value, combine::parser::repeat::Many1<std::vec::Vec<graph_graphql::graphql_parser::query::VariableDefinition<std::string::String>>, combine::parser::combinator::Map<(combine::parser::item::Position<graph_graphql::graphql_parser::tokenizer::TokenStream>, combine::parser::sequence::Skip<combine::parser::sequence::With<graph_graphql::graphql_parser::helpers::Value, graph_graphql::graphql_parser::helpers::NameMatch<std::string::String>>, graph_graphql::graphql_parser::helpers::Value>, combine::parser::function::FnParser<graph_graphql::graphql_parser::tokenizer::TokenStream, for<'r> fn(&'r mut graph_graphql::graphql_parser::tokenizer::TokenStream) -> std::result::Result<(graph_graphql::graphql_parser::query::Type<std::string::String>, combine::error::Consumed<()>), combine::error::Consumed<combine::error::Tracked<<graph_graphql::graphql_parser::tokenizer::TokenStream as combine::stream::StreamOnce>::Error>>> {graph_graphql::graphql_parser::common::parse_type::<std::string::String>}>, combine::parser::choice::Optional<combine::parser::sequence::With<graph_graphql::graphql_parser::helpers::Value, combine::parser::function::FnParser<graph_graphql::graphql_parser::tokenizer::TokenStream, for<'r> fn(&'r mut graph_graphql::graphql_parser::tokenizer::TokenStream) -> std::result::Result<(graph_graphql::graphql_parser::query::Value<std::string::String>, combine::error::Consumed<()>), combine::error::Consumed<combine::error::Tracked<<graph_graphql::graphql_parser::tokenizer::TokenStream as combine::stream::StreamOnce>::Error>>> {graph_graphql::graphql_parser::common::default_value::<std::string::String>}>>>), [closure@graph_graphql::graphql_parser::query::grammar::operation_common<std::string::String>::{closure#0}]>>>, graph_graphql::graphql_parser::helpers::Value>>, [closure@graph_graphql::graphql_parser::query::grammar::operation_common<std::string::String>::{closure#1}]>), combine::parser::function::FnParser<graph_graphql::graphql_parser::tokenizer::TokenStream, for<'r> fn(&'r mut graph_graphql::graphql_parser::tokenizer::TokenStream) -> std::result::Result<(std::vec::Vec<graph_graphql::graphql_parser::query::Directive<std::string::String>>, combine::error::Consumed<()>), combine::error::Consumed<combine::error::Tracked<<graph_graphql::graphql_parser::tokenizer::TokenStream as combine::stream::StreamOnce>::Error>>> {graph_graphql::graphql_parser::common::directives::<std::string::String>}>), combine::parser::function::FnParser<graph_graphql::graphql_parser::tokenizer::TokenStream, for<'r> fn(&'r mut graph_graphql::graphql_parser::tokenizer::TokenStream) -> std::result::Result<(graph_graphql::graphql_parser::query::SelectionSet<std::string::String>, combine::error::Consumed<()>), combine::error::Consumed<combine::error::Tracked<<graph_graphql::graphql_parser::tokenizer::TokenStream as combine::stream::StreamOnce>::Error>>> {graph_graphql::graphql_parser::query::grammar::selection_set::<std::string::String>}>), [closure@graph_graphql::graphql_parser::query::grammar::operation_common<std::string::String>::{closure#2}]>], item_def_id: DefId(219:2739 ~ combine[7984]::parser::Parser::Output) } } }`
end of query stack
error: could not compile `graph-node`
--------------------------------------
can you help me this why? is rust's bug?

**Comment by lutter** [comment]
This is an issue introduced by Rust 1.52.0. Please see their [blog post](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html) on the background and how to handle it.
