### ISSUE TITLE
How to run the graph-node in the rinkeby test rpc

### ISSUE THREAD

**Issue by suganth745** [graphprotocol/graph-node#2451]
I am trying to write a subgraph for the contract which is deployed in the rinkeby test network.

for that I need to run the graph-node in the same rinkeby test network.

With the reference of the below repo

https://github.com/graphprotocol/graph-node

I am running it in my local machine using the below cargo command

`cargo run -p graph-node --release --  --postgres-url postgresql://postgres:postgres@localhost:5432/graph-node  --ethereum-rpc 'rinkeby':'https://rinkeby.infura.io/v3/2a46ac7cdb4c44acac4de87dadfd6e39'  --ipfs 127.0.0.1:5001`

I used infura.io for getting the rinkeby rpc url.

but its throws an error 401 Unauthorized. I don't know where i am making the mistake.

` WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Transport error: Unexpected response status code: 401 Unauthorized), provider: 'rinkeby-rpc-0`

I m unable to connect the rinkeby network.

Kindly please help me to resolve the issue.

Thanks in advance.

**Comment by lutter** [comment]
This is an issue with the URL you are passing for `--ethereum-rpc`. It might be an issue on your local network. Save this as `/tmp/net-version`

**Comment by lutter** [comment]
Oh, also try passing `--ethereum-rpc 'rinkeby:https://rinkeby.infura.io/v3/2a46ac7cdb4c44acac4de87dadfd6e39'` to `graph-node`.

Closing this for now since it's most likely a network issue. Feel free to open if that's not the case.

**Comment by suganth745** [comment]
sorry its my typo issue, I have updated my command in the issue.. it throw the same issue 401 Unauthorized
