### ISSUE TITLE
How to run the graph-node in the rinkeby test rpc

### ISSUE THREAD

**Issue by suganth745** [graphprotocol/graph-node#2452]
I am trying to write a subgraph for the contract which is deployed in the rinkeby test network.

for that I need to run the graph-node in the same rinkeby test network.

With the reference of the below repo

https://github.com/graphprotocol/graph-node

I am running it in my local machine using the below cargo command

`cargo run -p graph-node --release -- --postgres-url postgresql://postgres:postgres@localhost:5432/graph-node --ethereum-rpc 'rinkeby:https://rinkeby.infura.io/v3/2a46ac7cdb4c44acac4de87dadfd6e39' --ipfs 127.0.0.1:5001`

I used infura.io for getting the rinkeby rpc url.

but its throws an error 401 Unauthorized. I don't know where i am making the mistake.

`WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Transport error: Unexpected response status code: 401 Unauthorized), provider: 'rinkeby-rpc-0
`
I m unable to connect the rinkeby network.

Kindly please help me to resolve the issue.

Thanks in advance.

**Comment by azf20** [comment]
I am not sure that you will be able to run against an infura endpoint, as you need an archive node (though your error looks Auth related). Have you verified and tested the contract & subgraph on a local network? If yes then you could deploy to the hosted service which can index Rinkeby

**Comment by suganth745** [comment]
I did a blunder mistake in the command.

removing the single quote in the rpc url resolves the issue

`cargo run -p graph-node --release -- --postgres-url postgresql://postgres:postgres@localhost:5432/graph-node --ethereum-rpc rinkeby:https://rinkeby.infura.io/v3/2a46ac7cdb4c44acac4de87dadfd6e39 --ipfs 127.0.0.1:5001`
