### ISSUE TITLE
Deploy to the bsc network returns 502

### ISSUE THREAD

**Issue by mike-p-blaize** [graphprotocol/graph-node#2461]
Trying to deploy subgraph to the Hosted Service. The same subgraph can easily be deploy to rinkeby network. So what's wrong with bsc?

✔ Upload subgraph to IPFS

Build completed: QmXC8moe4wB51H7H5CmU2u5Y5N8nywNUwtrqaHNUftPb9u

✖ HTTP error deploying the subgraph 502
error Command failed with exit code 1.

**Comment by teekenl** [comment]
Any more log in detail, eg: messages from logs?

**Comment by mike-p-blaize** [comment]
> Anymore in detail, eg: logs messages?
```✖ HTTP error deploying the subgraph 502
error Command failed with exit code 1.```
That's the only error I got. All other logs are fine.

**Comment by leoyvens** [comment]
BSC in the hosted service is having issues, see https://status.thegraph.com/. Closing because it's not an issue in graph node itself, please follow the status page for updates.
