### ISSUE TITLE
Create a dedicated method to check if a field is derived.

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/graph-node#2464]
We must create a `schema_field.is_derived()` method to `DirectiveFinder` to cut down on the number of places where we hardcode the string "derivedFrom" across the codebase to detect if a field is derived or not.

_Originally posted by @lutter in https://github.com/graphprotocol/graph-node/pull/2352#discussion_r631329917_

**Comment by ScaredIbis** [comment]
keen to have a crack at this
