### ISSUE TITLE
How to add  Support for XinFin Netowrk

### ISSUE THREAD

**Issue by OutOfBoundCats** [graphprotocol/graph-node#2484]
*feature*
Hi Everyone 
i want to to know what needs to be done to support XinFin network on graph-node.
https://www.xinfin.org/

**Comment by schmidsi** [comment]
The biggest question here is: Is XinFin network EVM compatible?

If yes, it's pretty straight-forward: Are there any JSON-RPC endpoints? You can run a local-graph node and pointing to that endpoint and try it out.

If no: This is way more complicated.

**Comment by OutOfBoundCats** [comment]
Thanks for reply 
I can see xinfin does have JSON-RPC endpoints 
https://apidocs.xinfin.network/
https://apidocs.xinfin.network/docs/#xinfin-apis
Can you suggest what and where changes needs to be made.

**Comment by azf20** [comment]
If you are running a local graph-node you just need to set the rpc URL e.g. on this line in the docker-compose:
https://github.com/graphprotocol/graph-node/blob/bcb5b44a099095ceb0917bbc4fd97641084eaba2/docker/docker-compose.yml#L20
If this chain is EVM compatible this shouldn't require any changes in graph-node, so closing this issue. Thanks!
