### ISSUE TITLE
How to know why "sync failed"

### ISSUE THREAD

**Issue by Changdao** [graphprotocol/graph-node#2487]
Nothing, just to ask a question:
![图片](https://user-images.githubusercontent.com/2177183/119283046-61502980-bc6e-11eb-868a-8028b527b4fa.png)
how to know what's the reason. 
There is no any docs about this, and no any log about this.
Thanks and sorry for annoying.

**Comment by benesjan** [comment]
You can fetch the logs from console using the following commands:
pending version:
`curl --location --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{ indexingStatusForPendingVersion(subgraphName: \"uniswap/uniswap-v3-subgraph\") { subgraph fatalError { message } nonFatalErrors {message } } }"}'`

current version:
`curl --location --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{ indexingStatusForCurrentVersion(subgraphName: \"uniswap/uniswap-v3-subgraph\") { subgraph fatalError { message } nonFatalErrors {message } } }"}'`

Just replace the subgraph name with yours.

**Comment by Changdao** [comment]
Thanks for a lot!!!

**Comment by Changdao** [comment]
Should close.
