### ISSUE TITLE
Check input schemas for reserved types on deploy

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#2498]
Certain operations fail when a subgraph's GraphQL input schema contains types that we reserve for the API schema, such as `Subscription` or `Query`. Using such types leads to obscure and hard to track down error messages. Instead, we should check for these types when a subgraph is deployed and reject the deploy with a clear error message.

To find the types affected by that, search the code for `APISchemaError::TypeExists`

**Comment by schmidsi** [comment]
We could use https://github.com/dotansimha/graphql-eslint and also lint in `graph-cli` even before deploying to the graph-node.

**Comment by santteegt** [comment]
You can also run into the same issue if you set `signature` as an entity field name
