### ISSUE TITLE
Invalid GraphQL Schema at https://gateway.testnet.thegraph.com/network

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#2507]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
The schema hosted at https://gateway.testnet.thegraph.com/network is invalid

The invalid part of the schema seems to be an empty enum type.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Regenerating a schema from an introspection query on https://gateway.testnet.thegraph.com/network currently yields this error:

```Error: _Schema__orderBy values must be an object with value names as keys```

This can easily be reproduced by using a graphql query client like graphiql or graphql playground (yoga) or postmark, insomnia, etc. or by attempting to use code generation tooling (e.g. graphql-codegen).

**What is the expected behavior?**

Enums aren't generated if the enum would end up not having any key-value pairs.

**Comment by fubhy** [comment]
https://github.com/graphprotocol/graph-node/blob/ed7510674993b4d3436e1967a923b16cf385e04a/graphql/src/schema/api.rs#L283

**Comment by fubhy** [comment]
Related: https://github.com/graphprotocol/graph-node/issues/1804

**Comment by fubhy** [comment]
There also seem to be other schema issues as I'm also now getting this error: `Null value resolved for non-null field __typename`

Maybe it would be good to run the introspection query alongside the queries sent by the existing test cases that run queries against subgraphs and the other (e.g. status) graphql endpoints.

**Comment by Jannis** [comment]
@fubhy Is still a problem? I can't reproduce it using graphiql-online.com.

**Comment by fubhy** [comment]
@Jannis Looks good now (also just verified that on https://studio.apollographql.com/).

I think #2508 might've fixed this.
