### ISSUE TITLE
Trying again after eth_call RPC call failed "out of gas" [Ethereum Mainnet]

### ISSUE THREAD

**Issue by raugfer** [graphprotocol/graph-node#2516]
**Do you want to request a *feature* or report a *bug*?**

Possibly a bug, AFAICT.

**What is the current behavior?**

Subgraph synchronization stuck with an 'Trying again after eth_call RPC call failed' warning message.

The issue produces ServerError(-32000) "out of gas" on the Ethereum mainnet.

Here is the full warning message:

```
Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: ServerError(-32000), message: "out of gas", data: None }))), block_hash: 0xf39eb489773304ba7906e9ad896b6fd13f8e1d369c3ab6b0c74622769e1c9975, block_number: 5258109
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just check the logs (with WARN filter) for the following subgraph:

https://thegraph.com/explorer/subgraph/nftfy/nftfy-v1-mainnet

I am just trying to sync that particular subgraph.

**What is the expected behavior?**

Unless I am missing something, the subgraph synchronization should progress on.

**Comment by leoyvens** [comment]
The gas limit for contract calls is 25 million. Was you intention to handle that error with `try_` calls? That's something we could enable.

**Comment by raugfer** [comment]
Yes, that would work. How should we go about that?

I also think this would be good in general, to have a way to handle this sort of error as part of the API.

BTW, I am not sure how to identify which contract call is causing the problem. How can I do that?

**Comment by raugfer** [comment]
@leoyvens would you mind sharing any updates on this?

**Comment by leoyvens** [comment]
Hey @raugfer, you can read about `try_` calls here https://thegraph.com/docs/define-a-subgraph#code-generation. I intend on enabling catching this case, that should be ready by next week.

**Comment by raugfer** [comment]
Hey @leoyvens, has this been fixed last week? Would you mind sharing another update? Thanks!

**Comment by fabriciomirandabr** [comment]
Hey @leoyvens , Do you have some news about this problem?

I'm facing the same thing here ;(

Thank you so much!

**Comment by leoyvens** [comment]
@raugfer @fabriciomirandabr apologies for the delay, I've opened a PR for this.

**Comment by raugfer** [comment]
Thanks @leoyvens ! I have two more questions:
1- How long before the change is applied to the indexing service?
2- Do we need to restart the subgraph synchronization or would it pick up from where it is (either aborting or continuing, in case ir is a `try_` primitive)?

**Comment by leoyvens** [comment]
@raugfer Might be rolled out still this week. If you're already using `try_` there is no need to redeploy, the subgraph will simply start making progress.

**Comment by leoyvens** [comment]
Just to confirm, this was rolled out last week.

**Comment by raugfer** [comment]
Yes, I've noticed, thanks again!
