### ISSUE TITLE
Does thegraph.com support the PR ethereum.encode/ethereum.decode #2348 function?

### ISSUE THREAD

**Issue by sc0Vu** [graphprotocol/graph-node#2531]
**Do you want to request a *feature* or report a *bug*?**
No.

**What is the current behavior?**
The deployment worked great but the playground page didn't work, and there was error in console: `Uncaught 
Exception { name: "NS_ERROR_FILE_NO_DEVICE_SPACE", message: "", result: 2152857616, filename: "https://thegraph.com/explorer/static/js/main.0d101c52.js", lineNumber: 296,`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I try to decode Transaction.input with ethereum.decode when I see this PR: https://github.com/graphprotocol/graph-node/pull/2348 was merged. But it didn't work with thegraph environment.

**What is the expected behavior?**
Should decode the input.

**Comment by azf20** [comment]
Hello - the error in the playground looks like a frontend error, rather than a subgraph error - can you share the affected subgraph?
Though also cc @otaviopace to clarify - should `ethereum.decode` be supported now?

**Comment by otaviopace** [comment]
Yes `ethereum.{encode, decode}` are supported now, but it would be great if we can see the mapping code like @azf20 suggested, so we can understand the error better.

**Comment by sc0Vu** [comment]
Hi,

Here is our subgraph: https://github.com/consenlabs/tokenlon-v5-subgraph/commit/9b5e9214697f85cc61ca6b12634831bbaa6505d7

And this is subgraph playground: https://thegraph.com/explorer/subgraph/sc0vu/tokenlon-v5-goerli-exchange

I tried to decode transaction input and add another test copied from this repository.

Both of them will show the same error.

**Comment by sc0Vu** [comment]
It works now! Thanks!

**Comment by otaviopace** [comment]
Great!
