### ISSUE TITLE
Why Transaction.input is null in some transaction

### ISSUE THREAD

**Issue by sc0Vu** [graphprotocol/graph-node#2535]
**Do you want to request a *feature* or report a *bug*?**
Might be

**What is the current behavior?**
I got null input from event.transaction.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In our smart contract, we proxy the bytes payload of order to another smart contract, you can see I decoded and  sanitized transaction.input to decode uint256. And it worked in some transactions.

Somehow, I noticed that some transaction.input was null and I could find transaction.input on explorer.

Subgraph: https://github.com/consenlabs/tokenlon-v5-subgraph/tree/goerli-next

URL: https://thegraph.com/explorer/subgraph/sc0vu/tokenlon-v5-goerli-exchange?version=current

Query:
```
// null transaction input
{
  swappeds(first: 5, where: { inputs: null }) {
    id
    inputs
    transactionHash
  }

// non null transaction input
  swappeds(first: 5, where: { inputs_not: null }) {
    id
    inputs
    transactionHash
  }
)
```

**What is the expected behavior?**

Should return transaction data when use transaction.input.

Thanks!

**Comment by leoyvens** [comment]
I don't see `inputs` being set in the mapping.

**Comment by sc0Vu** [comment]
Sorry, I had typo, it's transaction.input

**Comment by sc0Vu** [comment]
Here I set the inputs to the decoded bytes :https://github.com/consenlabs/tokenlon-v5-subgraph/blob/goerli-next/subgraphs/exchange/src/mapping_ammwrapperwithpath.ts#L47

**Comment by leoyvens** [comment]
On which block does this happen? Have you been able to narrow down which transaction had this behavior?

**Comment by sc0Vu** [comment]
There are 37 transactions without swapped.inputs, here are 5 of them: 
```
0x0c5a144db3e9fe8d5955416aa8abf3b2134a7f7815e216958a2085516d41c741,
0x166694477c03048049935cf69706cdc8f1aabd6d79cfaed3f4ab6e64a197a1fc,
0x0c1e858bcd41c25abadc4ad9e1d8d552b38a992790102211e0cb0d5c4df61797,
0x25a2eae281ac4091c0048a128faf3a63f130a3baeb2bea56e1cfcf3c96ffcd0c,
0x09bcdfab6b1dcca0aa4d2c322e197aec99cf3101fb680f2e4a057ca2be02b44c,
0xcd159cad248d420ac17beab2e0d99ab193cf3aa0cfb6e404baa15600b2e13767
...
```

This is a normal transaction with swapped.input: 0x833ea1bb801dd52a197d31136a53524efbdd9c8b084b6cb388b6622b576b5f60

Data looks familiar, and I can't tell the difference between them.

**Comment by leoyvens** [comment]
I checked the hosted service DB, and those transactions do contain an input there. So it doesn't seem to be the case that graph-node received incorrect input from the Ethereum client. This needs further investigation by attempting a local reproduction.

**Comment by sc0Vu** [comment]
Hi @leoyvens,

Because we have multiple mapping files for AMM, I finally find out we didn't add decode code in these files.

It works now. Thanks for your help!

**Comment by leoyvens** [comment]
@sc0Vu thanks for getting back to me, glad it worked!
