### ISSUE TITLE
cargo build graph-node

### ISSUE THREAD

**Issue by Wakuangdachengzi** [graphprotocol/graph-node#2536]
![image](https://user-images.githubusercontent.com/80933753/120798435-ee995500-c56f-11eb-8dbf-71a9a9463c4a.png)

**Comment by schmidsi** [comment]
Which OS do you use? Is postgresql already installed?

**Comment by tilacog** [comment]
Hello! :wave: 
It seems that there is more text on that error message. 
Could you share the full text so we can better inspect it?

**Comment by Wakuangdachengzi** [comment]
I have solved this problem, because gcc id occupies too much memory and was killed directly. I added virtual memory to my server and it was ok.

**Comment by jjhesk** [comment]
you may want to take a look of this research.
https://www.reddit.com/r/rust/comments/ez34iu/trying_to_compile_the_migrations_macro_dependency/
