### ISSUE TITLE
cargo run cargo run -p graph-node --release --

### ISSUE THREAD

**Issue by Wakuangdachengzi** [graphprotocol/graph-node#2548]
When I execute the following command, I encountered an unexpected error。

![image](https://user-images.githubusercontent.com/80933753/120979090-cdbb4480-c7a7-11eb-9eb0-15229dd42bfe.png)
![image](https://user-images.githubusercontent.com/80933753/120979113-d3188f00-c7a7-11eb-85b9-c3b7d77357fc.png)

**Comment by tilacog** [comment]
It seems that the backlash in your command is escaping the space character before the `--postgres-url` parameter, causing it to be interpreted as: 
```
 --postgres-url
```
(mind the space character before the dash)

From the `bash` manual:

`A non-quoted backslash (\) is the escape character. It preserves the literal value of the next character that follows, with the exception of <newline>. If a \<newline> pair appears, and the backslash is not itself quoted, the \<newline> is treated as a line continuation (that is, it is removed from the input stream and effectively ignored).`

That being said, I suppose you can try to remove those backslashes if you are writing a single-line command.

**Comment by azf20** [comment]
Thanks @tilacog! Closing this for now @Wakuangdachengzi , please re-open if you are still having problems
