### ISSUE TITLE
Skipping data if ETH node returns empty data

### ISSUE THREAD

**Issue by akme** [graphprotocol/graph-node#2550]
If an ETH node has an issue with returning data and instead of returning data or error if it returns an empty result, graph-node after 10 retries goes further without getting any data which leads to incorrect subgraph data.

Probably there is no connection with the number of retries, but only with an empty response that we can't check if it should contain any data.

Example of query:
```
curl -X POST -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0xbf967d","toAddress":["0x511bc4556d823ae99630ae8de28b9b80df90ea2e"],"toBlock":"0xbf9686"}],"id":59911}' 
```
Erigon response was (before fix):
```
{"jsonrpc":"2.0","id":59911,"result":[]}
```
and OE response was: 
```
{"jsonrpc":"2.0","result":[{"action":{"callType":"call","from":"0x1746228c3146cbd32f2f41f31a9b009dfd77993f","gas":"0x1c078","input":"0x25d5971f0000000000000000000000000000000000000000000000000000000000000000","to":"0x511bc4556d823ae99630ae8de28b9b80df90ea2e","value":"0x0"},"blockHash":"0xe81003879ce15d988852a1c242a8c14f7ecbb4883dbe6a13ffa36308dead5c0c","blockNumber":12555906,"result":{"gasUsed":"0x1634e","output":"0x"},"subtraces":2,"traceAddress":[],"transactionHash":"0xf5dd73bd781767d61b333705a8a9ea320d6873d6ecc72dd81f9dd6a8ecc8c5a6","transactionPosition":168,"type":"call"}],"id":59911}
```

**Comment by azf20** [comment]
I think @leoyvens was looking into this, was this an issue with Erigon?

**Comment by leoyvens** [comment]
Yes this is an issue with Erigon. I don't think there is an easy way in we could check if an empty response is correct or not, so my tendency is to take no action on our side.

**Comment by azf20** [comment]
We are working with the clients on reliability here (I think Erigon have made some fixes), and will also look to improve our testing and monitoring in this area, but as Leo says we probably don't have a way to check empty responses without requiring eth node client redundancy. Many thanks for reporting, will close and do re-open if you see regression or have other questions on this issue.
