### ISSUE TITLE
Broken link to sharding docs

### ISSUE THREAD

**Issue by ebaizel** [graphprotocol/graph-node#2582]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
The link to the sharding docs on this page are broken. It is the last sentence in this section:
https://github.com/graphprotocol/graph-node#advanced-configuration

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Visit: https://github.com/graphprotocol/graph-node#advanced-configuration
Click on the hyperlink on `multiple databases`.

**What is the expected behavior?**
I see the docs. Instead, it is giving a 404.

**Comment by leoyvens** [comment]
Thank you for the report, fix incoming.
