### ISSUE TITLE
Support for GraphQL interfaces and unions?

### ISSUE THREAD

**Issue by heri16** [graphprotocol/graph-node#2593]
Is there support for GraphQL interfaces and unions?

**Comment by adamazad** [comment]
Interfaces are supported, I've implemented them [here](https://github.com/cryptonative-ch/mesa-subgraph). Unions aren't last I tried implementing them.

**Comment by azf20** [comment]
Yes unions are not currently supported. Thanks!

**Comment by jasonpearson** [comment]
@azf20 I've been able to find several examples of interfaces, but can you point to any examples of subgraphs using unions? 

I'm trying to do unions with something like the code below, but codegen fails with `- Field 'foobar': Unknown type 'Foobar'.`

```
type Foo @entity { 
  id: ID!
  foofoo: Bytes!
}

type Bar @entity {
  id: ID!
  barbar: BigInt!
}

union Foobar = Foo | bar

type Baz @entity {
  id: ID!
  foobar: Foobar!
}
```

Any tips would be appreciated, thanks!

**Comment by azf20** [comment]
Hi I think [per my comment](https://github.com/graphprotocol/graph-node/issues/2593#issuecomment-872140338) unions are **not** currently supported in subgraphs

**Comment by jasonpearson** [comment]
Must have misread that! Thanks for pointing out 👍
