### ISSUE TITLE
[Question] Is Polkadot supported?

### ISSUE THREAD

**Issue by paulvi** [graphprotocol/graph-node#2594]
The was announce in Feb 2021 about Polkadot support
https://thegraph.com/blog/multiblockchain-support

However documentation never mentions Polkadot support
https://thegraph.com/docs/define-a-subgraph#from-an-existing-contract

nothing in Subgraph Manifest 
https://github.com/graphprotocol/graph-node/blob/master/docs/subgraph-manifest.md

Is Polkadot really supported, and where to start from?

Also on https://stackoverflow.com/questions/68130435/thegraph-subgraph-for-polkadot-network-project

**Comment by azf20** [comment]
Hello! Polkadot is not yet supported by graph-node. We are currently working on adding support for the chains mentioned. Will close this issue, please do re-open if you have any other questions!

**Comment by gilescope** [comment]
Any news?
