### ISSUE TITLE
Variables not expanding in the providers section of the config toml

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/graph-node#2597]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Ethereum providers are not expanded in the config.toml files for the graph-node and the graph-node errors out with the following error:
```Jun 28 13:41:40.293 INFO Reading configuration file `/root/graph-node-configs/index_node_0_config.toml`
configuration error: the url `${ETHEREUM_RPC_0}` for provider mainnet is not a legal URL: relative URL without a base```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It's not necessarily a bug, but the steps to reproduce is to pass an env var to the graph-node and then try to read it within the toml file's provider section.
```provider = [ { label = "mainnet", url = "${ETHEREUM_RPC_0}", features = ["archive", "traces"] } ]```

**What is the expected behavior?**
The variable should be expanded like in the db connection strings (ie. `connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}"` <--- this works)

This will make our [advanced branch](https://github.com/StakeSquid/graphprotocol-mainnet-docker/tree/advanced) of the StakeSquid mainnet repo be more easily managed without having to edit too many filed to get started initially 🙏🏻

**Comment by lutter** [comment]
Just a note for whoever picks that up: look for `shellexpand::env` in `node/src/config.rs` and do something similar for the provider URL's in the config module.
