### ISSUE TITLE
Problem with subgraphs

### ISSUE THREAD

**Issue by oikos1** [graphprotocol/graph-node#2604]
Hello,

Getting the following error consistently across several of our subgraphs, e.g. [this one](https://thegraph.com/explorer/subgraph/oikos1/exchanges1?version=pending) :

`Trying again after eth_getLogs RPC call failed (attempt #10) with result Err(Transport("Unexpected response status code: 403 Forbidden")), component: BlockStream`

Is it related to the current BSC outage? is there any ETA for resolution?

Cheers

**Comment by schmidsi** [comment]
Yes, this is exactly the effect that the current outage describes. I do not have an estimation at the moment since it is outside of our hands. But we are on it.

**Comment by schmidsi** [comment]
Your subgraph is syncing again 🎉. Closing this since [we were probably able to resolve this issue](https://status.thegraph.com/incidents/1wkgfbjgxyj5).

**Comment by oikos1** [comment]
yes, sorry for not closing the issue and thanks a lot for assisting me. All of our subgraphs are working correctly. 

Keep up the good work.
