### ISSUE TITLE
Checking subgraph health does not work on hosted service or locally

### ISSUE THREAD

**Issue by paulvi** [graphprotocol/graph-node#2605]
https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health gives information abour how to check subgraph status via index-node GraphQL endpoint, however it does not work for both https://api.thegraph.com and local network server.

**Do you want to request a *feature* or report a *bug*?**
This is bug or documentation need update.

**What is the current behavior?**
Documentation "Checking subgraph health" https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health says
> Graph Node exposes a graphql endpoint which you can query to check the status of your subgraph. 
> On the hosted service, it is available at https://api.thegraph.com/index-node/graphql. 
> On a local node it is available on port 8030 by default.

However  http POST to https://api.thegraph.com/index-node/graphql with QueryQL gives 404 or 400 errors;
opening in browser (http GET) gives 
> response 404 (backend NotFound), service rules for the path non-existent 

While local network graph server instance gives 404
```
% node health.js
(node:13759) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
```
or just OK for http GET

> OK

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I use this minimal Node.js script (run locally or on https://npm.runkit.com/axios )
```js
const axios = require("axios")
axios({
  //url: 'http://localnetworkserverip:8030',
  url: 'https://api.thegraph.com/index-node/graphql',
  method: 'post',
  data: {
    query: `
    indexingStatusForCurrentVersion(subgraphName: "org/subgraph") {
      synced
      health
      fatalError {
        message
        block {
          number
          hash
        }
        handler
      }
      chains {
        chainHeadBlock {
          number
        }
        latestBlock {
          number
        }
      }
    }
      `
  }
}).then((result) => {
  console.log(result.data)
});
```

**What is the expected behavior?**

It should be GraphQL response, so http status code must be 200.

**Comment by azf20** [comment]
Hi! I think your Node.js script is missing some curly brackets, this works:
```
const axios = require("axios")
axios({
  //url: 'http://localnetworkserverip:8030',
  url: 'https://api.thegraph.com/index-node/graphql',
  method: 'post',
  data: {
    query: `{
    indexingStatusForCurrentVersion(subgraphName: "org/subgraph") {
      synced
      health
      fatalError {
        message
        block {
          number
          hash
        }
        handler
      }
      chains {
        chainHeadBlock {
          number
        }
        latestBlock {
          number
        }
      }
    }
    }`
  }
}).then((result) => {
  console.log(result.data)
});
```

CURL equivalent:
```
curl --request POST 'https://api.thegraph.com/index-node/graphql'  --data-raw '{"query":"{ indexingStatusForCurrentVersion(subgraphName: \"org/subgraph-name\") { subgraph fatalError { message } nonFatalErrors {message } } }"}'
```

**Comment by paulvi** [comment]
Yes, QueryQL query must be within { } pair.
Also local graph URL must have `/graphql` path, like :8030/graphql
(that is different from subgraph URL, where `/graphql` appears in browser, but must be removed for URL used in scripts )

so 
- [ ] example should be updated at https://thegraph.com/docs/deploy-a-subgraph#checking-subgraph-health 
- [ ] local node URL should be shown to have `/graphql` path, like :8030/graphql

**Comment by azf20** [comment]
For sure! That will go into the next docs update, thanks @paulvi
