### ISSUE TITLE
cargo build takes forever

### ISSUE THREAD

**Issue by DeveloperInProgress** [graphprotocol/graph-node#2608]
Hi!

The build process has been stuck like this for more than 10  minutes:

![image](https://user-images.githubusercontent.com/40036742/124190291-9fe3ca00-dadf-11eb-9635-071adf7b02d4.png)

is this normal? or should I do something about this?

**Comment by leoyvens** [comment]
How beefy is the instance?

**Comment by DeveloperInProgress** [comment]
@leoyvens  it's the t2.micro ec2 instance that aws provides

**Comment by leoyvens** [comment]
That's probably just to weak to efficiently compile graph-node.

**Comment by DeveloperInProgress** [comment]
@leoyvens It finally came out. Here is the  error message i recieved:
 `error: could not compile cranelift-codegen`

`Caused by:
  process didn't exit successfully: rustc --crate-name cranelift_codegen --edition=2018 /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.74.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enable-serde"' --cfg 'feature="gimli"' --cfg 'feature="serde"' --cfg 'feature="std"' --cfg 'feature="unwind"' -C metadata=cc19b208c816d5b9 -C extra-filename=-cc19b208c816d5b9 --out-dir /home/ec2-user/graph-node/target/debug/deps -L dependency=/home/ec2-user/graph-node/target/debug/deps --extern cranelift_bforest=/home/ec2-user/graph-node/target/debug/deps/libcranelift_bforest-0cbabaf7e93a7f43.rmeta --extern cranelift_codegen_shared=/home/ec2-user/graph-node/target/debug/deps/libcranelift_codegen_shared-47ebe25fb6df25f5.rmeta --extern cranelift_entity=/home/ec2-user/graph-node/target/debug/deps/libcranelift_entity-99026e87b95c2bc3.rmeta --extern gimli=/home/ec2-user/graph-node/target/debug/deps/libgimli-2cc91a9d17cb0635.rmeta --extern log=/home/ec2-user/graph-node/target/debug/deps/liblog-87f52410a15272ba.rmeta --extern regalloc=/home/ec2-user/graph-node/target/debug/deps/libregalloc-2828bf7dc7abfa9c.rmeta --extern serde=/home/ec2-user/graph-node/target/debug/deps/libserde-69f30454961ef94b.rmeta --extern smallvec=/home/ec2-user/graph-node/target/debug/deps/libsmallvec-07597d84eb6d38d4.rmeta --extern target_lexicon=/home/ec2-user/graph-node/target/debug/deps/libtarget_lexicon-36839ff2dbef26d5.rmeta --cap-lints allow --cfg 'feature="x86"' (signal: 9, SIGKILL: kill)`

**Comment by leoyvens** [comment]
It might have just run out of memory.

**Comment by DeveloperInProgress** [comment]
thanks for the help , i'll try it on a bigger server

**Comment by leoyvens** [comment]
Cool, closing this for now.
