### ISSUE TITLE
transaction.gasUsed is not gasUsed.

### ISSUE THREAD

**Issue by Amxx** [graphprotocol/graph-node#2619]
When handling an event, I wanted to log gas-related information.
However, I noticed that `event.trasaction.gasUsed` does not contain the gas used but gas limit.

It would be nice to gas these 2 entries (gasUsed and gasLimit) in the transaction object

**Comment by azf20** [comment]
Hey @crazyrabbitLTC very sorry about that. In the immediate term @leoyvens has made a change to rename gasUsed to gasLimit https://github.com/graphprotocol/graph-ts/pull/192 (will be in a new graph-ts version). We have also been making changes to fetch tx receipts, which could extend to surface the actual gasUsed, will keep this issue open to track.
Definitely heard on the developer communication point, and apologies for any time lost

**Comment by NelsonGaldeman** [comment]
Hi @leoyvens & @azf20 ! Is there any ETA for gasUsed support? We've been relying on gasUsed at SimpleFi. We started upgrading our subgraphs to 24.1 and found it's always been gasLimit. Thank you.

**Comment by Rburdett4** [comment]
Bumping this issue. Would be fantastic to track gasUsed for transactions, even if the team could provide a workaround calculation method (though I am not aware of one).

**Comment by mariorz** [comment]
Bumped and agree with the sentiment here, gasUsed is confusingly named and getting actual gasSpent should be considered an absolute requirement. Thanks!

**Comment by leoyvens** [comment]
Including the receipt is being worked on and tracked here https://github.com/graphprotocol/graph-node/issues/3218

**Comment by azf20** [comment]
Hi this is available on the Hosted Service with the alpha versions of graph-ts and graph-cli, and will be in the next Graph Node release, documentation here https://github.com/graphprotocol/docs/pull/102. Note that an eventHandler has to specifically require receipts
