### ISSUE TITLE
How to decode event.transaction.input param

### ISSUE THREAD

**Issue by divyaN73** [graphprotocol/graph-node#2628]
**Do you want to request a *feature* or report a *bug*?**
How to use a feature

**What is the current behavior?**
No examples anywhere on how to decode input parameters from event.transaction.input

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I expect a code example which shows how to decode the input param to the function

**Comment by divyaN73** [comment]
I tried this but did not work

let decoded = ethereum.decode("sendFundsToUser(address, uint256, address, bytes, uint256)", event.transaction.input);
  log.info("decoded:", [decoded.toString()]);

**Comment by azf20** [comment]
Hello are you still seeing this issue on [your subgraph](https://thegraph.com/legacy-explorer/subgraph/divyan73/lpmanagergoerli?selected=logs)?

**Comment by azf20** [comment]
it looks likes the subgraph is synced, so closing this issue, but please re-open if it is still causing problems!
