### ISSUE TITLE
Generating Entities with IDs as `uint256` instead of `ID!`

### ISSUE THREAD

**Issue by gxxcastillo** [graphprotocol/graph-node#2631]
**Do you want to request a *feature* or report a *bug*?**
I have a question...

I'm new to blockchain development so please bear with me.  I've built a dApp and have been using a local mongo db instance to capture events and populate data that my web client then queries.  However, I thought I'd explore doing away with my local db instance and leverage the Graph instead.  I'm using the Docker setup and have hit up on the following issues:

1. `npm run codegen` is giving me an error, saying I need to have an "id" field.  Which my contract entities do not have (we call it tokenId).  That said, it's not too much trouble to rename it, but I wonder should that be necessary?

2. If I rename the "tokenId" field to "id" I get a different error saying `Entity IDs must be of type ID!`.  My ids, however are `uint256`.  Why is it necessary that it be a an ID!? Is there a workaround for this?

3. Is this the right place to ask this type of question?  I tried going to the discord link I found on the contributing guidelines page but that link was invalid.

**Comment by azf20** [comment]
Hello!
1. Entities need a primary key (mentioned in the docs [here](https://thegraph.com/docs/developer/create-subgraph-hosted#optional-and-required-fields))
2. We require that that ID is a String - you can cast the uint256 with `.toString()` (see notes on casting [here](https://thegraph.com/docs/developer/assemblyscript-api#bigint))
3. Discord is probably best! You can join the Discord [here](https://discord.com/invite/vtvv7FP).
Hopefully that makes sense, will close this issue, thanks!

**Comment by gxxcastillo** [comment]
Thanks @azf20.

Where would I do the casting?  Would that be in `mapping.ts`?

**Comment by azf20** [comment]
Yes, that would be the place.
