### ISSUE TITLE
Updating startBlock every time that event is called

### ISSUE THREAD

**Issue by bkioshn** [graphprotocol/graph-node#2654]

**Comment by leoyvens** [comment]
Not currently possible, you mean you want to instantiate a template with a custom start block? Or update the startBlock of an existing data source, to effectively skip blocks?

**Comment by bkioshn** [comment]
Sorry for the confusion. The scenario is when a new event is received, I want to use the latest block from that event to update the startBlock, so I can save the computation time.

**Comment by leoyvens** [comment]
Understood, basically you the data source to "sleep" until the given block. Interesting.

**Comment by bkioshn** [comment]
> Not currently possible, you mean you want to instantiate a template with a custom start block? Or update the startBlock of an existing data source, to effectively skip blocks?

Oh sorry, it should update the startBlock of an existing data source

**Comment by azf20** [comment]
hi @bkioshn - what do you mean `save the computation time`?

**Comment by bkioshn** [comment]
> hi @bkioshn - what do you mean `save the computation time`?

Hi, Instead of spending time. querying all the block, let's say from start block 2,000,000, I want to query from the latest block that has the event instead. So basically just update the startblock, but my problem is startblock is in the .yaml file and it won't be a great idea to change something in config file.

**Comment by azf20** [comment]
OK - in this case I think the preferred path is to update the config file, as the config file dictates which blocks are inspected for events

**Comment by bkioshn** [comment]
> OK - in this case I think the preferred path is to update the config file, as the config file dictates which blocks are inspected for events

Ooh okay, I thought it will be a better approach. Thank you all for replying 😋
