### ISSUE TITLE
Feature: add base fee to the Block object (EIP-1559)

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2663]
The London hardfork introduces a change to fee markets on Ethereum ([EIP-1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md)). This introduces a new "base fee per gas" per block, which is not currently available. Can we add this to the Block object so it is available to developers in mappings?

[Discord request](https://discord.com/channels/438038660412342282/438070183794573313/869519459562450964)

**Comment by dmihal** [comment]
I created a really simple PR to add baseFee to the Block class here graphprotocol/graph-ts#197

I'm now looking into how this can be populated by the node

**Comment by leoyvens** [comment]
We would also need to deal with the outdated data in the block cache for existing DBs. Maybe by having a migration that clears the block cache.

**Comment by dmihal** [comment]
Created a PR (tomusdrw/rust-web3#530) to add the base fee to rust-web3, which I imagine is an upstream prerequisite for this feature

**Comment by azf20** [comment]
This is available in graph-node:v0.25.0 ([PR](https://github.com/graphprotocol/graph-node/pull/3002)), graph-ts:v0.24.1 and graph-cli:v0.25.0. Thanks for opening @dmihal!
