### ISSUE TITLE
ERROR Failed to establish WS connection, no data found for subgraph

### ISSUE THREAD

**Issue by qq745960380** [graphprotocol/graph-node#2684]
how to fixed???

**Comment by schmidsi** [comment]
Thanks for the report @qq745960380 . Can you please provide more details to that error? What did you try to do? What are the steps that you did before? What would be the expected outcome? What OS do you use? Etc.

We need to be able to reproduce your problem in order to fix it. That said, if this is about GraphQL subscriptions: This is not fully supported at the moment.

**Comment by qq745960380** [comment]
> Thanks for the report @qq745960380 . Can you please provide more details to that error? What did you try to do? What are the steps that you did before? What would be the expected outcome? What OS do you use? Etc.
> 
> We need to be able to reproduce your problem in order to fix it. That said, if this is about GraphQL subscriptions: This is not fully supported at the moment.

more detail,can see that https://gitmemory.com/issue/graphprotocol/graph-node/2420/830255479

**Comment by qq745960380** [comment]
> > Thanks for the report @qq745960380 . Can you please provide more details to that error? What did you try to do? What are the steps that you did before? What would be the expected outcome? What OS do you use? Etc.
> > We need to be able to reproduce your problem in order to fix it. That said, if this is about GraphQL subscriptions: This is not fully supported at the moment.
> 
> more detail,can see that https://gitmemory.com/issue/graphprotocol/graph-node/2420/830255479
when i  deploy local-node,i can't get any data,i think is that problem.

**Comment by dueldanov** [comment]
I have the same issue with example Gravatar subgraph (and any other) on my Mac, doing everything as instructed in https://thegraph.com/docs/developer/quick-start

**Comment by qq745960380** [comment]
> I have the same issue with example Gravatar subgraph (and any other) on my Mac, doing everything as instructed in https://thegraph.com/docs/developer/quick-start

i solve it ,in docker-compose.yml this file, i use localhost

**Comment by langsen111** [comment]
> > 我的 Mac 上的示例 Gravatar 子图（和任何其他）也有同样的问题，按照[https://thegraph.com/docs/developer/quick-start 中的](https://thegraph.com/docs/developer/quick-start)说明执行所有操作[](https://thegraph.com/docs/developer/quick-start)
> 
> 我解决了它，在 docker-compose.yml 这个文件中，我使用 localhost

我没有修改docker-compose.yml，我看启动docker-compose up 后显示的 Starting GraphQL WebSocket server at: ws://localhost:8001, component: SubscriptionServer，为什么还要改localhost呢

**Comment by qq745960380** [comment]
> > > 我的 Mac 上的示例 Gravatar 子图（和任何其他）也有同样的问题，按照[https://thegraph.com/docs/developer/quick-start 中的](https://thegraph.com/docs/developer/quick-start)说明执行所有操作
> > 
> > 
> > 我解决了它，在 docker-compose.yml 这个文件中，我使用 localhost
> 
> 我没有修改docker-compose.yml，我看启动docker-compose up 后显示的 Starting GraphQL WebSocket server at: ws://localhost:8001, component: SubscriptionServer，为什么还要改localhost呢

因为我用的window系统，我得手动的去配置这个ip。我用window跑私有节点的，https://learnblockchain.cn/article/2871
