### ISSUE TITLE
Set the 'from' address for contract calls

### ISSUE THREAD

**Issue by dmihal** [graphprotocol/graph-node#2687]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When executing an arbitrary contract call, the "from" address passed to the EVM is undefined, I assume the msg.sender address visible to contracts is 0x0.

While this is generally not a problem, there are some instances where setting the from address is desired. For example, I'm hoping to use the MakerDAO V3 medianizer oracle to get the ETH/USD price. This oracle has a whitelist, so only calls from approved addresses will succeed.

**What is the expected behavior?**

It would be great if it was possible to optimally set the from address for calls.

**Comment by azf20** [comment]
Hi @dmihal thanks for this, this has previously been requested here https://github.com/graphprotocol/graph-node/issues/1785 so closing this in favour if that works!
