### ISSUE TITLE
`address[]` event param types are generated as `Bytes` instead of `Array<Bytes>`

### ISSUE THREAD

**Issue by jjranalli** [graphprotocol/graph-node#2707]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`address[]` event param types are generated as `Bytes`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Handle an event which emits an array of addresses as one of its params.

**What is the expected behavior?**
`address[]` event params types should be generated as `Array<Bytes>`

**Additional notes**
As previously suggested on Discord, I tried making an explicit cast in the mappings `let myArray = event.params.addresses as Array<Bytes>` which allows the build to finish, but then I get a Failed Syncing in the subgraph with a 'Heap out of bounds' error (triggered when I try to access one of the values with `myArray[0]`)

Is this behaviour expected? What is the correct way to handle an array of addresses in the mappings?

**Comment by azf20** [comment]
Hi - `address[]` event params are not stored directly, but a hash is stored instead, so in this case the data is not usable and this is the expected behaviour (it is a Solidity constraint, rather than a graph-node issue) - see details here https://docs.soliditylang.org/en/v0.8.6/abi-spec.html?highlight=indexed#encoding-of-indexed-event-parameters

**Comment by jjranalli** [comment]
Thanks for the clarification!

I'm thinking of using `abi.encodePacked()` in solidity to turn the `address[]` into `bytes`, and emit that through the event. Would I be able to catch the emitted bytes param in the event handler? Or is there any other workaround you could suggest me? Many thanks in advance!

**Comment by jjranalli** [comment]
Thanks for the clarification! By the way this seems to only happen to indexed event params, so removing it make it work as expected. I'm now able to access the individual addresses in the array.
