### ISSUE TITLE
[Bug] Fragments are discarded on the root Query type

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#2720]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Fragments are discarded on the root Query type

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run this query on any subgraph:

```graphql
fragment Metadata on Query {
  _meta {
    deployment
    block {
      number
    }
  }
}

query MyQuery {
  ...Metadata
}
```

**What is the expected behavior?**
The query should return the contents of the Metadata fragment but instead it is empty.

**Comment by azf20** [comment]
Thanks @fubhy - discussed with @leoyvens who had a view on where this issue is?

**Comment by leoyvens** [comment]
Haven't dug in, but we should be able to just fix this.
