### ISSUE TITLE
Graph Node support Loki log server or could save log to file

### ISSUE THREAD

**Issue by regardfs** [graphprotocol/graph-node#2773]
**feature**
Graph Node support Loki Log Server or could save log to file.
For now, Graph node only support es or local stdou/stderr, I use loki to store or analyze log, Is there a way to store log to local file or directly to loki?
`Loki URL: https://github.com/grafana/loki/`

**Comment by aapelismith** [comment]
@regardfs  Hi, buddy, maybe you can do this:
Use this `Dockerfile` to build your own image
Try to set the environment variable GRAPH_LOG_FILE, to specify the log file path


```
FROM graphprotocol/graph-node

ENV GRAPH_LOG_FILE=""

CMD ["/bin/sh", "-c", "start 2>&1 | tee -a ${GRAPH_LOG_FILE}"]
```

**Comment by regardfs** [comment]
> @regardfs Hi, buddy, maybe you can do this:
> Use this `Dockerfile` to build your own image
> Try to set the environment variable GRAPH_LOG_FILE, to specify the log file path
> 
> ```
> FROM graphprotocol/graph-node
> 
> ENV GRAPH_LOG_FILE=""
> 
> CMD ["/bin/sh", "-c", "start 2>&1 | tee -a ${GRAPH_LOG_FILE}"]
> ```

Well, It Is not a native way when compared to es or stdout/stderr

**Comment by mmchougule** [comment]
I was able to do the following:
1. ```cargo run -p graph-node --release -- \
  --postgres-url postgresql://username:@localhost:5432/graph-node \
  --ethereum-rpc mainnet:ethurl/ \
  --ipfs 127.0.0.1:5001 &> logs/info.log```
2. `./promtail-darwin-amd64 -config.file=loki.yaml` where loki.yaml config has loki url, credentials, etc.

Should we try to streamline it a bit better and create something for it?

**Comment by azf20** [comment]
Thanks @promaty ! Closing this given that update, @regardfs please re-open if you believe further changes might be required to graph-node
