### ISSUE TITLE
graph-node postgres db takes a lot of space

### ISSUE THREAD

**Issue by amirtotem** [graphprotocol/graph-node#2775]
**Do you want to request a *feature* or report a *bug*?**
Yes seems like a logical problem to me
**What is the current behavior?**
I expect data base to only index data i need regarding the contracts i've mapped and it grows to 100gb in matter of days
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
setup a graph-node with BSC mainnet RPC : https://bsc-dataseed.binance.org/
**What is the expected behavior?**
Only index needed data related to my contracts

**Comment by leoyvens** [comment]
Try setting `GRAPH_ETHEREUM_CLEANUP_BLOCKS=true`, see the docs here https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md.

**Comment by amirtotem** [comment]
Thanks @leoyvens ,  i missed that doc there is not integrity in documents that points to different sections of it . Thank you anyway saved me a lot of time.
