### ISSUE TITLE
INFO receipt block mismatch

### ISSUE THREAD

**Issue by BenTokenFinance** [graphprotocol/graph-node#2779]
Hi I was tring to run a graph node for smartbch chain. However it always runs into this after a while:

Sep 07 23:30:55.184 INFO receipt block mismatch, tx_hash: 0x1530…6946, block_hash: 0xfd2f…424c, receipt_block_hash: 0x0a59…8dc3, provider: smartbch-rpc-0, component: BlockIngestor

and the subgraphs stopped syncing.   The only way for me is to start over but it will happen again after a while.

Could you help?? Thank you!!!!!!

**Comment by BenTokenFinance** [comment]
Sep 07 23:25:08.285 INFO Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0x4ac0dcdcbe7a96569c7d376195f1f2118faf5c1c83a519e68f74aaf03f832d4e), provider: smartbch-rpc-0, component: BlockIngestor

**Comment by BenTokenFinance** [comment]
Sep 07 23:01:56.365 ERRO the genesis block hash for chain smartbch has changed from 46959de13b851836bdfa8f4c0387ed9a6060d1214368f2e3af6bcf35500c1c0a to e8e8784d1b64cb5c6484f10772dd2a69ef93ee4ad81131bedca9a20466b60d3c since the last time we ran, component: BlockStore

**Comment by BenTokenFinance** [comment]
Can I pay someone to build a local graph-node for a certain EVM sidechain???????  Please DM me!!!!!!!!

**Comment by BenTokenFinance** [comment]
![image](https://user-images.githubusercontent.com/84253083/132537639-62330fe2-698e-4d0f-8ffb-974ae53c05ca.png)

**Comment by azf20** [comment]
hi! this seems to be relating to an issue with smartbch, rather than with graph-node? i.e. inconsistent data being returned?

**Comment by azf20** [comment]
Closing this, as it appears to be an rpc issue rather than affecting graph-node

**Comment by BenTokenFinance** [comment]
Thanks for the response. This issue was solved already.
