### ISSUE TITLE
Database pruning

### ISSUE THREAD

**Issue by vietthang207** [graphprotocol/graph-node#2789]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The db is using too much disk (100+) and increasing
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Is there a way to set up database pruning, or somehow reduce the storage usage?

**Comment by leoyvens** [comment]
Try `GRAPH_ETHEREUM_CLEANUP_BLOCKS`, see https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md

**Comment by azf20** [comment]
Thanks @leoyvens! closing based on that recommendation, @vietthang207 please do re-open if that did not solve your issue

**Comment by hiendaovinh** [comment]
Hi, can we pruning blocks with a time range applied? More like a TTL thing for blocks cache.
 Is it safe for me to truncate the blocks table? It's getting really huge here with 283GB of `blocks` after a month of running.

**Comment by leoyvens** [comment]
@hiendaovinh is `GRAPH_ETHEREUM_CLEANUP_BLOCKS` not working for you?

**Comment by hiendaovinh** [comment]
@leoyvens I don't have problem with it but I don't want to skip the cache. I just want to make the cache more like LRU by cleaning old blocks.

**Comment by leoyvens** [comment]
If you want to delete rows manually from the DB it is safe to do so, the safest is if you do it with graph node shut down.

**Comment by hiendaovinh** [comment]
Thank you!
