### ISSUE TITLE
ability to access event.transaction.nonce

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#2796]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
current behaviour does not allow the mapping to access the transaction nonce

**What is the expected behavior?**
I expect to be able to fetch the transaction nonce from the event object

**Comment by azf20** [comment]
hey thanks - @leoyvens I think this would be possible to add as part of a new apiVersion? nonce is already part of the data type so I think this should be quite straightforward, or is there a reason this wasn't yet included?

**Comment by leoyvens** [comment]
It was probably just an oversight to not include it, it can be included as part of a new apiVersion.

**Comment by azf20** [comment]
This is available in graph-node:v0.25.0 ([PR](https://github.com/graphprotocol/graph-node/pull/3002)), graph-ts:v0.24.1 and graph-cli:v0.25.0
