### ISSUE TITLE
Improve error message for runtime panics (`oneshot canceled`)

### ISSUE THREAD

**Issue by evaporei** [graphprotocol/graph-node#2797]
Nowadays when the `runtime` code panics before the mappings code, we save something like this to the `SubgraphErrors` table:

```
Subgraph instance failed to run: failed to process trigger: block #15730765 (0x3fc4…457f), transaction f7fd51db1b13c53b571d767503af8d6ad946708fe8ff67de8bceab3dd30f69d6: Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure
```

The message `Mapping terminated before handling trigger: oneshot canceled` is actually an `anyhow` context ([that happens here](https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/host.rs#L195)) of `Mapping terminated before handling trigger` with `oneshot canceled`, which is the panic from the channel.

Maybe look [here](https://github.com/graphprotocol/graph-node/blob/master/runtime/wasm/src/mapping.rs#L54).

- [ ] Investigation on where exactly we're losing the error message
- [ ] Implement the solution

**Comment by otaviopace** [comment]
@vrmiguel maybe if you want to take a look 😉

**Comment by leoyvens** [comment]
I believe this happens when the runtime panics, we should try to capture the panic message and print it.
