### ISSUE TITLE
Migrating to v0.24.1 "unexpected upcast"

### ISSUE THREAD

**Issue by jacobrosenthal** [graphprotocol/graph-node#2799]
"@graphprotocol/graph-cli": "0.22.0",
"@graphprotocol/graph-ts": "0.22.0",
graph-node:latest

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Updating a graph to the new assembly script version (yes!!)

This previously working code compiles but runtime errors
```
  const getters = DarkForestGetters.bind(Address.fromString(GETTERS_CONTRACT_ADDRESS));
  const planetDatas = getters.bulkGetPlanetsDataByIds(meta._currentlyRefreshingPlanets);
  const planetDecIds = meta._currentlyRefreshingPlanets.map<BigInt>((x) => x);
  for (let i = 0; i < meta._currentlyRefreshingPlanets.length; i++) {
    const rawData = planetDatas[i];
   // unexpected upcast here
    const p: DarkForestGetters__bulkGetPlanetsDataByIdsResultRetPlanetStruct = rawData.planet;
  }
```
```
Sep 17 02:23:51.350 ERRO Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 116, column 21, with message: unexpected upcast	wasm backtrace:	    0: 0x6287 - <unknown>!src/mapping/handleBlock	 in handler `handleBlock` at block #45 (c38b660bc121a54085e954946c8ccfcbab4d78f04a183b2a9877a9d8dce6811e), code: SubgraphSyncingFailure, sgd: 1, subgraph_id: QmQGPJNoCdMUC96Kq1T56qeyyR9bNnyytJMWxYB6SQcKP8, component: SubgraphInstanceManager
```

**Comment by azf20** [comment]
Hi! We are pushing a migration guide to the docs imminently (gist here: https://gist.github.com/otaviopace/8406cb39644d2e7678570d1e7f50dac4). cc @otaviopace who might have a fix on the specific issue?

**Comment by otaviopace** [comment]
Hey Jacob! The new AssemblyScript version only allows casting from a superclass into a subclass using the `changetype` function, because they're not safe, since you could be casting to a to a value that has not the methods you need. Take a look [here](https://gist.github.com/otaviopace/8406cb39644d2e7678570d1e7f50dac4#casting) at the guide.

You should change your code to:

```typescript
const p = changetype<DarkForestGetters__bulkGetPlanetsDataByIdsResultRetPlanetStruct>(rawData.planet);

```

**Comment by jacobrosenthal** [comment]
Its still odd to me because its already typed. I'm not trying to change its type. Thats the existing return type from the contract function, Im just passing it to a function. (for the repro case above I just showed typing it in a variable for a smaller repro)

**Comment by otaviopace** [comment]
@jacobrosenthal could you try again using `graph-ts` version `0.22.1` please? 🙂

**Comment by jacobrosenthal** [comment]
Yep that appears to solve it. Thanks!
