### ISSUE TITLE
Subgraph failed to sync

### ISSUE THREAD

**Issue by gabrieldemian** [graphprotocol/graph-node#2800]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
My subgraph is not syncing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Import the upgradeable contracts from Open Zeppelin

```
contract NFTMarket is
  Initializable,
  IERC721Upgradeable,
  ERC721URIStorageUpgradeable,
  UUPSUpgradeable,
  OwnableUpgradeable
```

**Notes**
Basically, my node was fully synced before I upgraded my contracts to use the upgradeable version of some contracts from Open Zeppelin. After that, It always fails to sync. Do I need to do a proxy configuration on the subgraph config? Or do I need to use a non-upgradeable contract?

**Comment by azf20** [comment]
hi @gabrieldemian - which contract address are you using in your `subgraph.yaml` file?
