### ISSUE TITLE
Document on how to use pending version.

### ISSUE THREAD

**Issue by vietthang207** [graphprotocol/graph-node#2802]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

When you using a self-hosted node, is there a way to enable pending version feature (i.e. redeployed subgraph will be marked as pending while it is syncing in the background)

**Comment by leoyvens** [comment]
You need to set `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE=synced` in the environment. This is lacking documentation.

**Comment by azf20** [comment]
Thanks Leo! Closing this for now, created a small PR adding this to the docs
