### ISSUE TITLE
[How to] Monitoring and metrics

### ISSUE THREAD

**Issue by wenmoonsir** [graphprotocol/graph-node#2803]
Hi,

I would like to know how we monitor statuses of subgraphs. For example,
- Is it being indexed
- How far away from current blockhash
- etc.

I'm trying to find info/docs about monitoring, metrics etc. how to integrate with other solutions (grafana, prometheus, etc.) but i can't find any.

Any best practice. Any recommendation. etc.

Would you mind giving me some guidance on this. Sorry if I duplicate the issue.

Thanks a lot!

**Comment by azf20** [comment]
hi @wenmoonsir - are you running your own graph node?

There are some details on checking individual subgraph health [here](https://thegraph.com/docs/legacyexplorer/deploy-subgraph-hosted#checking-subgraph-health)

**Comment by wenmoonsir** [comment]
Hi @azf20  thanks for the tips. Yeah i'm running my own graph node. Oh guess i can make similar query then?

**Comment by azf20** [comment]
Yes you should be able to query port 8030/graphql in the same way. Will close this, please do re-open if that doesn't do what you need!

**Comment by azf20** [comment]
Hi @wenmoonsir I think the URL changed: https://thegraph.com/docs/hostedservice/deploy-subgraph-hosted#checking-subgraph-health

**Comment by wenmoonsir** [comment]
Thank you very much for quick reply! @azf20
