### ISSUE TITLE
there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by numonedad** [graphprotocol/graph-node#2828]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I'm unable to create new or existing subgraphs. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```
$ graph create --verbose --node http://localhost:18020/ ethblock
✖ Error creating the subgraph: subgraph registrar error with store: store error: there is no unique or exclusion constraint matching the ON CONFLICT specification
error Command failed with exit code 1.
```
It appears to be an issue here: https://github.com/graphprotocol/graph-node/blob/f9bbf49db09b5c3478bad3ed15f10e8e7dc8cf30/store/postgres/src/primary.rs#L541
I assume the name is blank which is resulting in an invalid sql statement. It would be helpful if the server had debug logging for sql commands that it is running.

**What is the expected behavior?**
Subgraph is created.

**Comment by numonedad** [comment]
pgAudit on shows this as the insert statement
```
2021-09-30 15:41:47.169 UTC [287]: [47-1] db=graph_node,user=postgres STATEMENT:  INSERT INTO "subgraphs"."subgraph" ("id", "name", "created_at", "block_range") VALUES ($1, $2, 1633016507, $3) ON CONFLICT ("name") DO NOTHING
```

**Comment by drewwells** [comment]
Resolved this by deleting all the duplicate entries in subgraphs.subgraph table, then inserting one unique constraint.

I then altered the table to add name unique constraint found here https://github.com/graphprotocol/graph-node/blob/master/store/postgres/migrations/2020-11-03-170839_subgraph_name_unique/up.sql#L10-L11

**Comment by lutter** [comment]
Awesome! Glad this got resolved. Make sure that your schema has the latest version (`select max(version) from __diesel_schema_migrations` should return `20210614201635` for 0.24.x), otherwise schema issues might crop up in other places.

**Comment by numonedad** [comment]
> Awesome! Glad this got resolved. Make sure that your schema has the latest version (`select max(version) from __diesel_schema_migrations` should return `20210614201635` for 0.24.x), otherwise schema issues might crop up in other places.

Version looks good, I wonder how I was missing just one migration.

```
select max(version) from __diesel_schema_migrations;
      max
----------------
 20210614201635
(1 row)
```
