### ISSUE TITLE
HTTP_PORT and WS_PORT can not be configured via environment variables

### ISSUE THREAD

**Issue by numonedad** [graphprotocol/graph-node#2829]
**Do you want to request a *feature* or report a *bug*?**
feature, or bug if you read the description of the PR introducing these options, which states there's env variables to configure them. #592

**What is the current behavior?**
These are only configurable via cli args which are hard to do with docker container due to the complicated start script required to start graph-node inside the container

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Set HTTP_PORT and/or WS_PORT env variables, notice thegraph still only listens on default ports

**What is the expected behavior?**
setting HTTP_PORT and/or WS_PORT should change the listening port for these servers. In the case of WS_PORT, graphiql also needs to make calls on WS_PORT

**Comment by leoyvens** [comment]
Resolved in #2832.
