### ISSUE TITLE
Local node on docker refuses to connect to ganache-cli running on port 127.0.0.1:8545

### ISSUE THREAD

**Issue by carterax** [graphprotocol/graph-node#2850]
**Do you want to request a *feature* or report a *bug*?**
No i do not.

**What is the current behavior?**
Graph-Node on docker refuses to connect to ganche-cli running on port 127.0.0.1:8545, error object returned in logs
`WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #10) with result Err(Transport error: Error(Connect, Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))`

I also deployed my upgradeable contracts to rinkeby, created and deployed a subgraph to the legacy explorer but it fails to capture events, at first i thought i did something  wrong until yesterday when i saw in the logs it was trying to index past events and then it stopped, i would like to know if this is expected with testnets on the legacy explorer, if so we don't mind running our own nodes locally just for testing until we deploy to mainnet

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Comment by azf20** [comment]
Hey @carterax seems like you solved your problem so closing the issue, please re-open if you are still having issues!

**Comment by ethabhijit** [comment]
I have tried @carterax method but still having the issue.

Here is the full error log https://drive.google.com/file/d/1WS1ZBevkkoTreqoZUfQAr1jmALGdUBU3/view?usp=sharing
