### ISSUE TITLE
Enable tracking of RPC performance by named endpoint

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2853]
Enable tracking for specific RPC providers (to feed histograms of historical performance)

- Label providers in the config → set these labels on all relevant metrics
- 2 metrics for all Ethereum JSON-RPC calls (labels: `call_name`, `provider`)
    - Histogram for request duration
    - Counter for requests made (with an extra boolean `success` label)

- this will make it easier to diagnose and debug RPC issues on graph node

**Comment by azf20** [comment]
This has been instrumented by provider for `eth_getLogs` and `traceFilter`, `eth_call` is harder to do

**Comment by lutter** [comment]
The `deployment_eth_rpc_request_duration` metric is labelled with the deployment id, provider and method, though the method will only give you `eth_getLogs` and `trace_filter` for now

**Comment by azf20** [comment]
@schmidsi @promaty this is now in Prometheus, but we need verify / check with a dedicated Grafana visualisation

**Comment by azf20** [comment]
Closing this in initial issue and tracking eth_call in #2973
