### ISSUE TITLE
Investigate "unknown" in "time spent while indexing"

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2854]
Identify the process that corresponds to "unknown", which has been more frequently observed as contributing to indexing time in Grafana

**Comment by azf20** [comment]
@lutter based on some recent investigations, this does seem to be associated with connection wait time?

**Comment by lutter** [comment]
With pipelined store writes, most of the `unknown` time is actually known: it's the background writer waiting for write requests to come in. I've opened #3509 to make that clearer in the metrics.

**Comment by azf20** [comment]
Closing this given #3509
