### ISSUE TITLE
Subgraph deployment fails when the ABI contains "error" types

### ISSUE THREAD

**Issue by hbriese** [graphprotocol/graph-node#2877]
## Issue
`graph  deploy` fails when an ABI contains an [error type](https://docs.soliditylang.org/en/latest/abi-spec.html#json) the schema generation fails.
Deployment succeeds after removing the troublesome error objects from the ABI 

**Example ABI error type**
```
{
    "inputs": [],
    "name": "MyError",
    "type": "error"
  }
```

I'm not sure whether `error` is a standard type, but it's included within the ABI hardhat generates so many others will likely run into this issue

**Deployment error**
```
Failed to deploy to Graph node http://127.0.0.1:8020/: subgraph resolve error: resolve error: Serialization error: Invalid operation type error. at line 36 column 3
``` 

## Versions
graph-node image: **graphprotocol/graph-node:v0.24.2**
graph-cli: **v0.22.3**
graph-ts:  **v0.22.1**
apiVersion: **0.0.5**

**Comment by azf20** [comment]
Hi @hbriese thanks for this! I think this is the same as https://github.com/graphprotocol/graph-node/issues/2577 - we hope to fix it, but our dependency [hasn't implemented yet](https://github.com/rust-ethereum/ethabi/issues/225). In the interim we may implement a short term fix, as errors are not pertinent to Graph Node. Given that closing this issue, but please re-open if you think this is separate!
