### ISSUE TITLE
process didn't exit successfully

### ISSUE THREAD

**Issue by wanglonghong** [graphprotocol/graph-node#2900]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

When I try to build graph-node, I get following issues.

   Compiling hyper-timeout v0.4.1
error: failed to run custom build command for `graph v0.24.2 (/root/graph/graph-node/graph)`

Caused by:
  process didn't exit successfully: `/root/graph/graph-node/target/release/build/graph-68c7bcaa764bfabb/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=proto

  --- stderr
  error running rustfmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  
  Is there anyone who can help me with this?

**Comment by azf20** [comment]
Thanks @maoueh! Where would be best to update this in the docs? cc @leoyvens
