### ISSUE TITLE
Check whether code is present at a given address

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2917]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Graph Node is not able to distinguish whether an Ethereum address is a contract, or a EOA

**What is the desired behavior?**
Add a means to check whether code is present at a given address (via `eth_getCode`, docs [here](https://github.com/ethereum/execution-apis/blob/bea0266c42919a2fb3ee524fb91e624a23bc17c5/src/eth/state.json#L92))

If code is present, it is a smart contract

Considerations: this will need to check for code at a particular block, as contracts can be destroyed. `eth_getCode` seems to support block number, not block hash which introduces determinism problems.

Discussed [here](https://forum.thegraph.com/t/a-framework-to-build-any-data-applications-entirely-on-the-decentralized-web3-infrastructures/1979/14)

**Comment by silasdavis** [comment]
> not block hash which introduces determinism problems

I don't follow. Why would picking a block number not give you a deterministic value for the code at a particular height?

**Comment by azf20** [comment]
If there is a re-org, during indexing, the state for the same block height might change depending on which branch the subgraph is indexing

**Comment by Jerrywang959** [comment]
Any update about this issue
