### ISSUE TITLE
Mapping execution order should be deterministic

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#292]
I was thinking through the implications of having multiple contracts as data sources, and I think I found some situations where, due to concurrency, the order in which mappings get executed is not deterministic, implying that the entities in the store are not produced deterministically.

In the current implementation, each RuntimeHost gets its own stream of events from the EthereumAdapter, consuming events as fast or as slow as it wants. I think we need to force each RuntimeHost within a subgraph to process events in a particular order and at particular times so that the mappings are executed in a consistent order.

Fixing this would require reworking a number of components. I'm thinking we should aim for something like this:
- Information about blocks (and the events they contain) flows to the different subgraphs (SubgraphProviders?).
- Every time a block (or block rollback) is received, each subgraph provider is responsible for ensuring its store is updated in a single atomic transaction
- To do this, the subgraph provider iterates through the events in the block once, passing events off to the appropriate RuntimeHost as appropriate
- Importantly, if multiple RuntimeHosts are interested in the same event, we need a deterministic answer to the question of who sees the event first.

@yanivtal 
@Jannis

**Comment by Jannis** [comment]
The _Subgraph Provider_ serves a different purpose—it's the component that manages registered subgraphs and notifies the system of when they change.

For each subgraph, we currently spin up multiple _Runtime Hosts_, one for each mapping. The spinning up and lifecycle management of these is done via a single _Runtime Manager_.

We should improve this a little and incorporate the above requirement for deterministic execution.

## Proposed architecture

_Note: I'd love to simplify the vocabulary it bit, align it more closely with the terminology used in manifest specs (e.g. Runtime Host => Mapping Host or Mapping Runtime Host) and get rid of "manager", "provider" wherever we can think of something more specific._

I'd turn the Runtime Manager into a _Subgraph Manager_ and make it manage several _Subgraph Instance_s, one for each subgraph. Each of these manages multiple _Mapping Runtime Host_s, one for each mapping.

## Event streaming / processing

We have each _Mapping Runtime Host_ request an event stream for the event/transaction signatures it wants to monitor from the _Subgraph Instance_.

The _Subgraph Instance_ in turn requests a single stateful blockchain event stream based on these from e.g. the _Ethereum Adapter_.

Upon receiving a block's events via this stream, the _Subgraph Instance_ opens a "transaction", processes all events in deterministic order, collects the created entities and, upon success, submits the transaction to the store.
