### ISSUE TITLE
[meta] Update NEAR Proto definitions for the latest Firehose types

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2936]
The type definitions have been updated for the NEAR firehose. In order to migrate to the latest version, we need to make the Graph Node and graph-ts types compatible too

- [x] Add types to Graph Node
- [x] Update hosted service configuration (near-mainnet, add near-testnet) & handle switch-over

**Comment by azf20** [comment]
This sounds good @maoueh - let us know when the `v1` symlink is in place and we can make the config update

**Comment by azf20** [comment]
We will also add testnet support at the same time as this switch-over, assuming the endpoint is ready cc @sduchesneau

**Comment by maoueh** [comment]
To fix an issue when dealing with undo on Near, we will need to add a field `previous_block_height` in the protobuf definition so we are able to fully reconstruct the parent ptr when a block is undo.

This means we will need to reprocess again so we will need to post-pone a bit the upgrade.
