### ISSUE TITLE
Slowdown in SQL Inserts for Graph Nodes with many subgraphs

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2940]
When a Graph Node is indexing many subgraphs (observed at 1000+, but may be the case at a lower number), there was a significant increase in the time taken by SQL INSERT statements (longer than time taken to clamp the old version). This  is surprising, and lead to indexing slowness for those subgraphs.

**Comment by azf20** [comment]
@lutter is this still worth tracking? (I know we have made lots of changes with #3177

**Comment by lutter** [comment]
Let's close this - this is probably still an issue in some fashion, but very hard to quantify without more detail, and should just generally be improved by ongoing performance work.
