### ISSUE TITLE
Add retry loop to Graph Node for failed subgraphs

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2945]
Improvement over: https://github.com/graphprotocol/graph-node/issues/2932

This applies for non-deterministic failures.

**Comment by otaviopace** [comment]
This will help a lot: https://github.com/graphprotocol/graph-node/blob/master/graph/src/util/backoff.rs

@lutter made this a month ago.

**Comment by azf20** [comment]
Solved in https://github.com/graphprotocol/graph-node/pull/2988
