### ISSUE TITLE
Docker-compose not indexing properly

### ISSUE THREAD

**Issue by teddav** [graphprotocol/graph-node#2949]
I have been trying to run a graph node locally with the docker-compose provided in this repo, with hardhat running locally with a mainnet fork but I'm having some issues.
I setup a test repo with the entire code and the steps I took: [https://github.com/teddav/thegraph-debug](https://github.com/teddav/thegraph-debug)
Basically I'm running `hardhat node` which is running a mainnet fork and then running the graph node, and deploying my subgraph onto it. I run some transactions in order to emit a few events and check my graph status.
But nothing gets updated, and even more weird: it seems like the indexing starts going backward. When I look at the logs from hardhat, I see that the graph node is requesting the data for the transactions for each block, and block numbers go backward, starting from the block I indicated in `startBlock` in subgraph.yaml.
Either it's something really stupid on my part and it can be easily fixed, or there is a bigger issue with the Docker.

Btw, I tried multiple versions of the image published on hub.docker.com. First the latest official (`v0.24.2`), and then `v0.24.1` and the latest that was pushed a few days ago `b5c7c9f`

I posted my issue on Discord and was advised to open an issue here.

**Comment by azf20** [comment]
Hey @teddav ! Thanks for reporting, and for the example. Wondering if this is related to the mainnet fork you are running - have you tried with a regular hardhat node without the fork, and if so do you have the same issue? It looks like the underlying is an Alchemy node?
Also could you share the logs you are seeing in Graph Node, and the reverse logs you see on your hardhat node?

**Comment by teddav** [comment]
Hey @azf20 thanks a lot for answering.
I just tested the exact same setup, but with a local hardhat node and everything runs well. So it must be due to the mainnet fork, maybe due to Alchemy?
What do you think could be the issue there?

**Comment by leoyvens** [comment]
@teddav About the call revert issue, you should be able to fix that by setting `GRAPH_GETH_ETH_CALL_ERRORS='Error: Transaction reverted'` in the environment.

**Comment by teddav** [comment]
hey @leoyvens thanks for answering.
After a few months, I'm trying again to set that up and I'm still running into the same issues.
When running the setup on local nodes it's working well, but when running on a mainnet fork, it doesnt index properly the transactions.
What i'm doing: running a mainnet fork node locally `hardhat node` and in my hardhat.config.ts it's setup to run as a mainnet fork (using Alchemy).  
Then I launch the graph-node in Docker with docker-compose.  
When looking at the console where the `hardhat node` is running, I see that the graph-node keeps requesting new blocks to index them, but it's going backwards, starting from the block where i started running `hardhat node`.
I'm using the latest versions of all packages, and v0.25.1 of graph-node

cc @azf20

**Comment by azf20** [comment]
See this comment for details (requirement is to reduce the reorg depth, which is not required for local test chains)
https://github.com/graphprotocol/graph-node/issues/3159#issuecomment-1062827725

**Comment by teddav** [comment]
Nice! Thanks @azf20 and @leoyvens
