### ISSUE TITLE
Subgraph composability 

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#296]
Composability needs to exist at a few levels:

- Entity types should be able to reference entity types from other subgraphs
  - What invariants should we enforce on this?
- GraphQL queries should be able to reference entity types from multiple subgraphs
- Mappings will need to be able to reference data from other subgraphs
  - We should enable this through 2 API's:
     1) store.get() where we take an additional subgraph ID parameter
     2) store.query() which takes a GraphQL query
  - When we implement sharding we'll need to translate these calls to graph queries over the network
  - What invariants should we enforce on validators and SLA's to ensure that a given subgraph doesn't halt if query nodes are unavailable for dependent subgraphs?
- A hook should exist to run a handler on one subgraph when data matching a predefined filter is emitted in another subgraph

**Comment by Jannis** [comment]
Duplicate of #1202 (+ subgraph pipelining, which we have on the roadmap).
