### ISSUE TITLE
Transaction triggers

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#298]
Right now we can only call handlers in response to events. We need to add support for a few more trigger types:
- External transactions
  - Matching a filter such as: sender address, to address, data payload, function call, etc
 - Internal transactions
   - Matching a function call
   - This requires an Ethereum archive node

**Comment by Jannis** [comment]
Summary for a future development update:
> Until now, the only trigger for indexing smart contract data was events. In order to support smart contracts and interfaces that do not log events-such as ERC20-we will have added support for transaction triggers.

**Comment by tarrencev** [comment]
I'm not sure if this is already on the roadmap, or feasible, but block triggers would be great too. They would be useful for any function that returns data dependent on the latests blocks properties, i.e. time.

**Comment by yanivtal** [comment]
This issue has been superseded by https://github.com/graphprotocol/graph-node/issues/788
