### ISSUE TITLE
Filter an Ethereum Firehose for addresses of interest

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2980]
In order to better support syncing sparse subgraphs (where there are not many events), Graph Node should be able to ask the firehose only for blocks that include calls to a contract of interest. This would radically reduce the number of blocks that the graph node needs to process in order to sync the subgraph.

- This should be a simple filter to optimise for performance
- When syncing the chain head, graph node will need to update the subgraph's block pointer

This will likely require a similar implementation to #2942 

- [x] Investigation (Firehose, BlockStream, filters, ...)
- [ ] Implementation
- [ ] Run/test against real Firehose

**Comment by otaviopace** [comment]
In a brief chat with @sduchesneau he mentioned that they still need to implement a filter in the Firehose side (they have a similar old thing there, but it'll probably not apply to what we need today).

The format passed would be something like this:
```
to in ["0xaaaaaaaaaaaaaa","0xbbbbbbbbbbbb...",...]
```

Where `to` is the address of the contract called in any call/subcall. And any transaction that matches this contract (`to`), will be excluded from the Firehose block (or maybe even the full block, but this might be an optimization for later).

@sduchesneau feel free to correct me if I said something wrong 🙂

**Comment by otaviopace** [comment]
## Notes

After further code investigation I've noted a couple of things:

- In our `chain/ethereum` crate we have a [`TriggerFilter` structure](https://github.com/graphprotocol/graph-node/blob/8155ed5299e96a79a1554642486bcf88254b4a59/chain/ethereum/src/adapter.rs#L118) that contains the addresses, events, etc related to a subgraph (originated from it's data sources). The data that will be sent to Firehose will come from here.
- The [`firehose::BlocksRequestV2` structure](https://github.com/graphprotocol/graph-node/blob/8155ed5299e96a79a1554642486bcf88254b4a59/graph/src/firehose/dfuse.bstream.v1.rs#L39) will need to accept these addresses/contracts.
- And the [`firehose::BlockStream`](https://github.com/graphprotocol/graph-node/blob/8155ed5299e96a79a1554642486bcf88254b4a59/graph/src/blockchain/firehose_block_stream.rs#L126) will need to extract the addresses from the `TriggerFilter`, to send them in the `BlocksRequestV2` structure.

## Technical questions

- @leoyvens or @maoueh should I just extract all of the addresses contained in the three fields (`log`, `call` and `block`) from the `TriggerAdapter` structure to send them on the Firehose request? (so it can filter by them)
- @leoyvens by looking at our dynamic data source creation in the [`instance_manager`](https://github.com/graphprotocol/graph-node/blob/8155ed5299e96a79a1554642486bcf88254b4a59/core/src/subgraph/instance_manager.rs#L817), I don't see how the new addresses will be added to the `TriggerFilter` contained in the `BlockStream`. How should I add them? May I create a similar method to the `notify_block_consumed` for this?

## Behavioral questions

- @azf20 how should a subgraph specify it's a sparse one? Should it be a flag on the `.yaml` file? If that's not decided yet I can leave the filter behind a feature flag once the implementation is complete.

**Comment by azf20** [comment]
This shouldn't be a subgraph-level configuration, I think it should apply to all subgraphs? Unless we anticipate significant performance implications if applied to dense subgraphs?
I know there are some known complications with dynamic data sources (as it may require a new firehose connection if the filters / required position is changed?), but I think @maoueh and Stephane had some ideas (or maybe there wouldn't be filtering in that case to start with)

**Comment by leoyvens** [comment]
If a subgraph has templates, then we should not be including contract adresses in the filter. But we can include log and call signatures, making sure to include those in the templates.

**Comment by otaviopace** [comment]
@azf20 okay, I guess then this depends on the Firehose implementation itself, if it's performance suffers or not from filtering in non-sparsed subgraphs. Maybe @sduchesneau can answer this one 🙂

**Comment by otaviopace** [comment]
I'll start doing the filtering for addresses on the `graph-node` side.

On the Firehose there are a couple of things that need to be done so this becomes super neat 👌 , they are:

1. Skipping whole blocks (you would still receive a block with no transactions data in it)
2. Good performance when you need to skip big block ranges (the Firehose needs to read the whole files to know what to filter)
3. Implementing an array of addresses directly in the proto request (instead of a dumb "string") to optimize the filtering for large number of accounts (pretty inefficient using the CEL vm...)

According to @sduchesneau point 2 is the most exciting one 😄 

On a separate note, soon I'll need to learn how to run Firehose locally for Ethereum, I might talk with SF people or indexers that have done this already.

**Comment by otaviopace** [comment]
Also, here's a pseudocode I've made on how the filtering will probably look like:

```rust
// Unnecessarily complex pseudocode for the firehose filters.
//
// For now it considers Firehose only has an Address filter (`to in [...]`).
// No filters to event signature yet.

fn build_to_filter(filter: &TriggerFilter) -> BTreeSet<Address> {
    if
        // For now block filters mean -> trigger every block, no need for filters.
        // For the future we should optimize this to 
        !filter.block.is_empty() || 
        // If log filter has wildcard_events, it means they have no addresses. For correctness we can't skip any block.
        !filter.log.wildcard_events.is_empty()
    {
        return BTreeSet::new();
    }

    // filter.call is of type: HashMap<Address, (BlockNumber, HashSet<FunctionSelector>)>
    // We just want a list of Addresses.
    let call_filter_addresses = filter.call.contract_addresses_function_signatures.keys();
    
    let log_filter_addresses = filter
        .log
        .contracts_and_events_graph
        .iter()
        .fold(BTreeSet::new(), |acc, contract_or_event| {
            match contract_or_event {
                Contract(address) => acc.insert(address),
                // Not used for now.
                Event(_) => {},
            };
            acc
        });

    call_filter_addresses
        .append(log_filter_addresses)
}

struct FirehoseFilters {
    // For now firehose only has a `to in [0xaaa, 0xbbb, ...]` filter.
    // This filters for blocks that have calls for these contract addresses.
    to: BTreeSet<Address>,
}

impl FirehoseFilters {
    fn from_chain_filter(filter: &TriggerFilter) -> Self {
        // A filter.has_templates will be needed/used once Firehose accepts
        // event signature filters.
        // When that happens, we should use this boolean to consider:
        // - If there are templates, we should filter for their log/call filters
        //   that include no addresses.
        Self {
            to: build_to_filter(filter),
        }
    }

    // CEL being the query language Firehose uses for it's filtering mechanism.
    fn to_cel(self) -> String {
        let mut cel = String::new();

        if !self.to.is_empty() {
            cel.push_str(&format!(
                "to in [{}]\n",// \n to add each filter per line
                self
                    .to
                    .iter()
                    // Add comma + address.to_string()
                    .map(|address| format!("{}, ", address))
                    .collect()
            ));
        }

        cel
    }
}

impl BlockStream for FirehoseBlockStream {
    fn next(&mut self) {
        let filters = FirehoseFilters::from_chain_filter(&self.filter);

        request_firehose(BlocksRequestV2 {
            // ...
            filters: filters.to_cel(),
        })
    }
}
```

**Comment by mangas** [comment]
With https://github.com/graphprotocol/graph-node/pull/3323/files we now push all the filters to the firehose side, but currently there's still calls being made to the tracing rpc api, is this supposed to be removed as well? 

https://github.com/graphprotocol/graph-node/blob/d290b43bd9ca8406a197e17c8fdece59c86a42b1/chain/ethereum/src/ethereum_adapter.rs#L192
https://github.com/graphprotocol/graph-node/blob/d290b43bd9ca8406a197e17c8fdece59c86a42b1/chain/ethereum/src/ethereum_adapter.rs#L231

**Comment by mangas** [comment]
@azf20 are we ok to add these filters by default to firehose instead of behind the new experimental static filters flag?

**Comment by leoyvens** [comment]
This is done afaict
