### ISSUE TITLE
A revert that keep making eth_Call to fail and retry indefinitely

### ISSUE THREAD

**Issue by dy1006** [graphprotocol/graph-node#2989]
I am getting this error repetitively and my subgraph get stuck :
```
Trying again after eth_call RPC call failed (attempt #10) with result Err(Web3Error(Transport("Unexpected response status code: 502 Bad Gateway"))), block_hash: 0xc1ba5e2caa2aab52c5bced3e81f08b9e8f3d5e61ffadca9a726904db376c83a3, block_number: 12833778
```
The following contract: 0x86ca39d10dacdf1cfe490eb984bf0e7c17d1ed37
Subgraph: https://thegraph.com/hosted-service/subgraph/iw001/bsc

**Comment by azf20** [comment]
hey @dy1006 - this is an issue with the BSC RPC that the hosted service, rather than graph-node - please follow the [status page](https://status.thegraph.com/) or in the [graphprotocol Discord](https://discord.gg/vtvv7FP) for more up-to-date details
