### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#299]
Graph Nodes currently work against a single database. Eventually we're going to have a p2p network with Kademlia or similar DHT. In the interim we should support an abstraction for having each node index a subset of data and supporting distributed query processing inside a centralized cluster.

**Comment by Jannis** [comment]
For the sake of simplicity, I'd make the initial smallest unit of indexing a subgraph. That makes query routing _relatively_ simple.
