### ISSUE TITLE
Fulltext search

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#300]
Many use cases require fulltext indexing for search box style UX.

Questions
- How should we specify which fields to index?
- How do we specify which fields to aggregate into a searchable index?
- Should we use ElasticSearch or something else?

For the decentralized network we'll likely need custom indexes so we can merkleize them. It's okay if for the hosted service we use something that doesn't support that but it's worth investigating our options to see if there is something we can use with pluggable indexes.

**Comment by orenyodfat** [comment]
any update re that ?

**Comment by Jannis** [comment]
Done.
