### ISSUE TITLE
Bug: Graph-node killed after a subgraph deployment in a MacBook Pro 2021 M1

### ISSUE THREAD

**Issue by 0xTimepunk** [graphprotocol/graph-node#3000]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After deploying a subgraph to graph-node started locally with docker, the following error appears:
```
docker-graph-node-1  | /usr/local/bin/start: line 52:   162 Killed                  graph-node --node-id "${node_id//-/_}" --postgres-url "$postgres_url" --ethereum-rpc $ethereum --ipfs "$ipfs"
docker-graph-node-1 exited with code 137
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use a MacBook Pro 2021 M1 to graph create and graph deploy a subgraph to a local running graph-node with docker

**Comment by azf20** [comment]
hi @0xTimepunk - I think Graph Node Docker images now work on M1 macs per https://github.com/graphprotocol/graph-node/issues/2325
What versions of:
- Docker Desktop
- Graph Node
Are you running?

**Comment by leoyvens** [comment]
What does the memory usage look like on your M1? 137 is out of memory, Mac doesn't kill processes over that but I speculate that docker might when running a linux image.

**Comment by 0xTimepunk** [comment]
Hey @azf20 @leoyvens 
Using docker 4.2.0 (70708)
Tried both graph-node version from the master branch and this release https://github.com/graphprotocol/graph-node/releases/tag/v0.24.2. (docker-compose up in the docker folder, without any changes to yaml file)

My M1 has 32 gigs of Ram, This is the usage just before it is killed 

![image](https://user-images.githubusercontent.com/45543880/143236780-423375dc-680c-44cf-9d4d-030afe29f14e.png)

**Comment by leoyvens** [comment]
Docker is setting a limit to the containers memory, not sure how but you need to increase that.

**Comment by 0xTimepunk** [comment]
I increased the memory limit to 16gb, yielding the following usage:

![image](https://user-images.githubusercontent.com/45543880/143300776-f322452f-5841-45b3-a485-3b37de5af26c.png)
****

Subgraph deploys with no issue, but this memory usage/need is completely abnormal @leoyvens 

I noticed even when deploying and making the entity changes the subgraph logs are slow, as if things are taking time, whereas with an old Windows machine with intel and 12gb of ram everything was super fast.

**Comment by leoyvens** [comment]
The issue with the M1 is that we don't currently build native images for M1, if you're able to build your own image, that might resolve the issue.

**Comment by 0xTimepunk** [comment]
> The issue with the M1 is that we don't currently build native images for M1, if you're able to build your own image, or build and run graph node natively, that might resolve the issue.

Would the instructions for this still be https://github.com/graphprotocol/graph-node#running-a-local-graph-node?

Thanks

**Comment by leoyvens** [comment]
@0xTimepunk yes those look right.

**Comment by flowfree** [comment]
I had the same issue on my MacBook M1 machine. I rebuild the image and it solves the issue for me.

```
# Remove the original image
docker rmi graphprotocol/graph-node:latest

# Build the image
./docker/build.sh

# Tag the newly created image
docker tag graph-node graphprotocol/graph-node:latest
```

**Comment by 0xTimepunk** [comment]
> docker tag graph-node graphprotocol/graph-node:latest

Thank you! This solves my issue as well. @azf20 and @leoyvens can you mark this answer as the accepted and maybe include it in the readme for now? At least until you build native images for m1. Might help other people.

Thanks

**Comment by azf20** [comment]
Thanks @flowfree and @0xTimepunk ! Closing this, and proposing a README update here @leoyvens: https://github.com/graphprotocol/graph-node/pull/3097
