### ISSUE TITLE
panic processing query: not implemented

### ISSUE THREAD

**Issue by JoaoCampos89** [graphprotocol/graph-node#3003]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Hosted Service: Polygon https://thegraph.com/hosted-service/subgraph/joaocampos89/coinleagues

`{"errors":[{"message":"panic processing query: not implemented: unsure on what to do about other variants"}]} for any query with passed variables`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This is happening on queries that worked before without any issue.

```
{
    "operationName": "GetGames",
    "variables": {
        "status": "Waiting",
        "first": 100,
        "orderBy": "entry",
        "orderDirection": "desc"
    },
    "query": "query GetGames($first: Int, $status: String!, $orderDirection: String, $orderBy: String) {\n  games(\n    where: {status: $status}\n    first: $first\n    orderDirection: $orderDirection\n    orderBy: $orderBy\n  ) {\n    id\n    type\n    duration\n    status\n    numCoins\n    numPlayers\n    currentPlayers\n    entry\n    startedAt\n    endedAt\n    __typename\n  }\n}\n"
}
```
This query worked before without any issue

A query with passed variables is having this error, if there is no variable it works, like on the Graph Explorer

**What is the expected behavior?**

Returning data without issues

**Comment by otaviopace** [comment]
Hello @JoaoCampos89 the fix is deployed to the Hosted Service already 🙂 

Sorry for the inconvenience!
