### ISSUE TITLE
BSC slow/stopped indexing

### ISSUE THREAD

**Issue by chrisciszak** [graphprotocol/graph-node#3026]
*bug*

There seem to be a problem with hosted subgraph indexing on BSC. For some reason our indexing is over 2 hrs behind and for the last 1hr we've been seeing "no chain head update for 30 seconds, polling for update, component: BlockStream"

Any idea what's going on? bscscan seem to be seeing the latest blocks.

Our subgraph: https://thegraph.com/hosted-service/subgraph/kryptomondao/kryptomon

**Comment by azf20** [comment]
Hi @chrisciszak - https://github.com/graphprotocol/graph-node/issues/3018 is an optimisation which will improve the situation you describe

**Comment by alberthuang24** [comment]
This problem still seems to occur frequently at the moment.

![image](https://user-images.githubusercontent.com/20190812/157247768-04dd14ab-7e6e-4607-afb4-5c1312f44e63.png)

**Comment by dcfsdcc** [comment]
![image](https://user-images.githubusercontent.com/104418451/171548613-aacf2678-4460-4b75-932e-46ddb5fa0ef6.png)

I met  the same  problem

**Comment by Georgyskr** [comment]
Hi @azf20 the same issue stands for all of hosted-service bsc subgraphs.
Delay may be up to 700 blocks 
With the same bug as described above:
`no chain head update for 30 seconds, polling for update, component: BlockStream`

**Comment by ahsondev** [comment]
Hi @azf20 
I am having the same issue in the rinkeby hosted-service subgraphs.
Can you please help me?

**Comment by halink0803** [comment]
I am also facing with this problem currently with bsc.

**Comment by arnav13081994** [comment]
I am facing the same issue. Please assist.

**Comment by soonhuat** [comment]
seem to be resolve when upgrade to graphnode:v0.30.0

**Comment by daodev21** [comment]
I'm facing the same problem on fantom testnet. Subgraph stopped indexing last night. Could you please clarify, what exactly resolves the issue?

**Comment by daodev2** [comment]
Update: it started indexing again on its own.
