### ISSUE TITLE
Have an index page listing subgraphs

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#303]
The index page for the graphql server should have links to the available subgraphs.

**Comment by leodasvacas** [comment]
@Jannis I wonder if we actually want this. We could print a simple message like "To access graphiql for a subgraph go to http://localhost:8000/<subgraph_name>". Considering `subgraph_list` will be an admin-only thing, it wouldn't make sense to expose this. To improve the discoverability of the url perhaps we should print it as the output of `graph deploy` on the cli?

**Comment by Jannis** [comment]
Yep, I agree. Those are both good ideas.

**Comment by leodasvacas** [comment]
Unassigning myself to let @nenadjaja also own the Rust side of this, though we're likely to pair on it.
