### ISSUE TITLE
Add stop block environment variable

### ISSUE THREAD

**Issue by otaviopace** [graphprotocol/graph-node#3033]
We should have a way to stop the indexing of a deployment in a pre-determined block, like this: `GRAPH_NODE_STOP_BLOCK=<deployment>:<number>,<deployment>:<number>`.

**Comment by otaviopace** [comment]
Similar feature implementation by @sduchesneau https://github.com/streamingfast/graph-node/commit/ece5270defe2104b0b35e7902eb16b12718f190f

**Comment by sduchesneau** [comment]
that implementation does not use an environment variable, bit this feature could be added. The idea in my fork/branch is to be able to run a validation (or comparison, performance, etc..) test by invoking graphman, so the stop-block can also be used to stop the whole process (not just a subgraph). 

Additional work can be done on top of what I have there to launch the indexing with a provided(env var, etc.) value per subgraph.

**Comment by azf20** [comment]
I think if our use case is performance testing, the graphman command will likely work - @otaviopace do you see a reason to have a different implementation? cc @lutter and @mangas who are also thinking about performance testing

**Comment by otaviopace** [comment]
@azf20 no, I'll close this for now.
