### ISSUE TITLE
End point to check number of blocks synced.

### ISSUE THREAD

**Issue by dexpad-dev** [graphprotocol/graph-node#3045]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Currently I am trying to run docker version of graph-node for the cronos chain.
While it tries to download all data it fails usually after few seconds, could be because of rate limiting on public rpc.

I get the following logs.
Dec 08 17:14:59 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:14:59.270 WARN Trying again after block polling failed:
Dec 08 17:15:00 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:15:00.631 INFO Downloading latest blocks from Ethereum.
Dec 08 17:15:25 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:15:25.258 WARN Trying again after block polling failed:
Dec 08 17:15:26 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:15:26.593 INFO Downloading latest blocks from Ethereum.
Dec 08 17:16:01 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:01.406 WARN Trying again after block polling failed:
Dec 08 17:16:02 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:02.889 INFO Downloading latest blocks from Ethereum.
Dec 08 17:16:50 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:50.681 WARN Trying again after block polling failed:
Dec 08 17:16:52 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:52.117 INFO Downloading latest blocks from Ethereum.
Dec 08 17:16:52 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:52.421 INFO Trying again after block polling failed:
Dec 08 17:16:53 localhost docker-compose[28191]: graph-node_1  | Dec 08 17:16:53.828 INFO Downloading latest blocks from Ethereum

I have few questions here.
1) If it shows "Trying again after block polling failed:" does it mean it will restart downloading blocks from block 1 or from the previously downloaded block.
2)Is there a way I can see how many blocks are downloaded?

**Comment by azf20** [comment]
Hey @dexpad-dev - this is syncing new blocks, not all blocks, and you don't need to wait on anything, however this error suggests there is something wrong with the cronos RPC you are using. If you run Graph Node with `GRAPH_LOG=trace` you may get more information on what the error is. Closing this issue as an RPC issue
