### ISSUE TITLE
Klaytn Cypress Mainnet support request

### ISSUE THREAD

**Issue by liftingturn** [graphprotocol/graph-node#3050]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
there is no Klaytn network in supported Networks on the Hosted Service list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Please add support for Klaytn Cypress Mainnet (Ethereum compatible). 
https://docs.klaytn.com/
Thank you.

**Comment by azf20** [comment]
hey @liftingturn - closing this as this repository relates to graph-node features & bugs, and this is a Hosted Service network request which is out of scope for graph-node (which already supports all EVM compatible chains)
