### ISSUE TITLE
Is hosted service good for production

### ISSUE THREAD

**Issue by tharinduk90** [graphprotocol/graph-node#3069]
**Do you want to request a *feature* or report a *bug*?**
   get to know about the hosted service
**What is the current behavior?**
  get to know about the hosted service
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
  i am using a hosted service for avalanche sub graph. It is working fine. So when going live can we use the hosted service or do we need to host the system  in our own servers

i saw some popular repos has use  https://github.com/Uniswap/v3-subgraph for production ?
**What is the expected behavior?**
when going live what is the method to use

**Comment by leoyvens** [comment]
Yes, the hosted service is production ready.
