### ISSUE TITLE
chain reorgs

### ISSUE THREAD

**Issue by meligame** [graphprotocol/graph-node#3073]
fn load_full_block(
        &self,
        logger: &Logger,
        block: LightEthereumBlock,
    ) -> Box<dyn Future<Item = EthereumBlock, Error = IngestorError> + Send> {
        let logger = logger.clone();
        let block_hash = block.hash.expect("block is missing block hash");

        // The early return is necessary for correctness, otherwise we'll
        // request an empty batch which is not valid in JSON-RPC.
        if block.transactions.is_empty() {
            trace!(logger, "Block {} contains no transactions", block_hash);
            return Box::new(future::ok(EthereumBlock {
                block: Arc::new(block),
                transaction_receipts: Vec::new(),
            }));
        }
        let web3 = self.web3.clone();

        // Retry, but eventually give up.
        // A receipt might be missing because the block was uncled, and the
        // transaction never made it back into the main chain.
        Box::new(
            retry("batch eth_getTransactionReceipt RPC call", &logger)
                .limit(16)
                .no_logging()
                .timeout_secs(*JSON_RPC_TIMEOUT)
                .run(move || {
                    let block = block.clone();
                    let batching_web3 = Web3::new(Batch::new(web3.transport().clone()));

                    let receipt_futures = block
                        .transactions
                        .iter()
                        .map(|tx| {
                            let logger = logger.clone();
                            let tx_hash = tx.hash;

                            Box::pin(batching_web3.eth().transaction_receipt(tx_hash))
                                .compat()
                                .from_err()
                                .map_err(IngestorError::Unknown)
                                .and_then(move |receipt_opt| {
                                    receipt_opt.ok_or_else(move || {
                                        // No receipt was returned.
                                        //
                                        // This can be because the Ethereum node no longer
                                        // considers this block to be part of the main chain,
                                        // and so the transaction is no longer in the main
                                        // chain.  Nothing we can do from here except give up
                                        // trying to ingest this block.
                                        //
                                        // This could also be because the receipt is simply not
                                        // available yet. For that case, we should retry until
                                        // it becomes available.
                                        IngestorError::ReceiptUnavailable(block_hash, tx_hash)
                                    })
                                })
                                .and_then(move |receipt| {
                                    // Check if the receipt has a block hash and is for the right
                                    // block. Parity nodes seem to return receipts with no block
                                    // hash when a transaction is no longer in the main chain, so
                                    // treat that case the same as a receipt being absent entirely.
                                    if receipt.block_hash != Some(block_hash) {
                                        info!(
                                            logger, "receipt block mismatch";
                                            "receipt_block_hash" =>
                                            receipt.block_hash.unwrap_or_default().to_string(),
                                            "block_hash" =>
                                                block_hash.to_string(),
                                            "tx_hash" => tx_hash.to_string(),
                                        );

                                        // If the receipt came from a different block, then the
                                        // Ethereum node no longer considers this block to be
                                        // in the main chain.  Nothing we can do from here
                                        // except give up trying to ingest this block.
                                        // There is no way to get the transaction receipt from
                                        // this block.
                                        Err(IngestorError::BlockUnavailable(block_hash))
                                    } else {
                                        Ok(receipt)
                                    }
                                })
                        })
                        .collect::<Vec<_>>();

                    Box::pin(batching_web3.transport().submit_batch())
                        .compat()
                        .from_err()
                        .map_err(IngestorError::Unknown)
                        .and_then(move |_| {
                            stream::futures_ordered(receipt_futures).collect().map(
                                move |transaction_receipts| EthereumBlock {
                                    block: Arc::new(block),
                                    transaction_receipts,
                                },
                            )
                        })
                        .compat()
                })
                .map_err(move |e| {
                    e.into_inner().unwrap_or_else(move || {
                        anyhow!(
                            "Ethereum node took too long to return receipts for block {}",
                            block_hash
                        )
                        .into()
                    })
                })
                .boxed()
                .compat(),
        )
    }
    
    
The parameter block is to get the latest block header information through rpc
Suppose the latest block hash is 0x1
The hash obtained by the server is 0x1 and then perform all the things in the method. After the end,
The chain reorganization happened! At this time, the hash of the block becomes 0x2
This situation exists, right?

**Comment by meligame** [comment]
After ingesting the block, I no longer care about whether it is reorganized. At this time, I have consumed Logs, which resulted in inconsistent data status.

**Comment by meligame** [comment]
@Jannis

**Comment by meligame** [comment]
please help me

**Comment by meligame** [comment]
I'm thinking of a question
The hash of a transaction never changes. Suppose his own hash is 0x1
Some part is at most a part of it becomes 0x2
When I execute the third step, if a small part of it is owned, the hash of the part of my transaction is still 0x1
Did an error occur?
When the depth of the system is deeper, how about my frequency judgment

**Comment by meligame** [comment]
The first step is to get the latest block information header Latest
The second step is to obtain the complete block information through the block_hash of the latest block,
The third step is the transcation in the for loop block
Step 4 Query transaction details through tx_hash, compare the hash of the transaction details with block_hash
If they are not equal, the block is reorganized

I'm thinking of a question
The hash of a transaction will never change. Suppose the hash of the block he belongs to is 0x1
If the block is reorganized, at most the block he belongs to becomes 0x2
When I execute the third step, if the block has not been reorganized, the block hash I found through the transaction is still 0x1
Did an error occur?
When the depth of reorganization is deeper, how should I judge?

**Comment by meligame** [comment]
I tried to write a java program according to this logic,
Sometimes chain reorganization can be detected
, But it doesn’t work most of the time

**Comment by leoyvens** [comment]
This issue tracker is only for issues with graph node itself.

**Comment by meligame** [comment]
> This issue tracker is only for issues with graph node itself.

could you help me？
I am willing to pay for your consultation fee, it is about this issue
