### ISSUE TITLE
Not Syncing in hosted service...!!

### ISSUE THREAD

**Issue by sid5494** [graphprotocol/graph-node#3076]
@leoyvens I have tried redeploying many times also waited for a week but syncing stopped at 68.3% is there any possible way to overcome this issue here is my id "QmVF2JacKeVfcqqoX9QFWc9cgW1qu4prSRPxsyZWdX92rU" and link https://thegraph.com/hosted-service/subgraph/sid5494/fantom?version=pending. Are there any suggestions on anything I can do?

**Comment by leoyvens** [comment]
That subgraph is spending almost all of its time doing contract calls. If you can optimize it to reduce the number of contract calls necessary that will a big speedup.

**Comment by azf20** [comment]
Thanks both! Closing this issue, support on hosted service specific issues and subgraph optimisations are best found in [Discord](https://discord.gg/vtvv7FP)
