### ISSUE TITLE
GraphQL parse/validation caching 

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-node#3077]
Since GraphQL `parse` and `validate` phase are static (does not depend on the user input like variables), we can implement caching for both phases (for parser: `String => query::Document`, for validation: `String | query::Document => Vec<ValidationError>`).

This might be more relevant once https://github.com/graphprotocol/graph-node/pull/3057 lands, because if we'll add more validation rules it might add some (probably minimal) overhead. 

Usually it's implemented with LRU.

**Comment by lutter** [comment]
That's a good idea! For our purposes, I think it would be enough to keep a `HashSet` of the shape hashes of the queries that were successfully validated. We already calculate that hash (a `u64`) for all queries anyway.

**Comment by dotansimha** [comment]
https://github.com/graphprotocol/graph-node/pull/3188#issuecomment-1021490277
