### ISSUE TITLE
firehose_triggers_in_block should add conditional judgment before filter

### ISSUE THREAD

**Issue by macrocan** [graphprotocol/graph-node#3080]
The method **FirehoseMapper.firehose_triggers_in_block** should add conditional judgment before filter. 
```
        if !filter.log.is_empty() {
            triggers.append(&mut parse_log_triggers(&filter.log, &block.ethereum_block));
        }
        if !filter.call.is_empty() {
            triggers.append(&mut parse_call_triggers(&filter.call, &block)?);
        }
        if !filter.block.is_empty() {
            triggers.append(&mut parse_block_triggers(filter.block.clone(), &block));
        }
```

**Comment by maoueh** [comment]
`firehose_triggers_in_block` has been deleted. But it was copied more or less directly from [an existing Ethereum code snippet](https://github.com/graphprotocol/graph-node/blob/e687fde539cd1a27e54f1591f6817d665698e504/chain/ethereum/src/chain.rs#L511-L512).

I think it might indeed help to do what you suggest, I'll update the Ethereum & Near versions to do that.
