### ISSUE TITLE
How to maintain USDT price of token to market price in decentralised exchange 

### ISSUE THREAD

**Issue by manavsharma13** [graphprotocol/graph-node#3100]
I have deployed a dex and I want deployed a uniswap subgraph for that dex 
Now i want to USDT price of token and after adding liquidity  usdt price is coming but i want to know how to maintain usdt price with market price of tokens .suppose if there are no trades on my dex but it should still show same price as market

**Comment by azf20** [comment]
Hi @manavsharma13 - if your DEX doesn't have trades, then the price for the DEX won't be changing. This presents an arbitrage opportunity, which should encourage market makers to bring the prices for the DEX in line, which will then change the subgraph's prices. Closing this issue as this isn't an issue related to Graph Node. Thanks!
