### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jjhesk** [graphprotocol/graph-node#3103]
Using `cargo build` from the latest package on centos version 8.60
I have previously install `ipfs` and `postsql`.

Trying to compile the "migrations_macro" dependency in a Rust project throws the error "ld: cannot find -lpq"

**Comment by PhantomTop** [comment]
Hello.
I suffered such error on Debian 5.10.
in debian
 sudo apt-get install libpq-dev
in Centos
yum install libpq-dev
I think it will works.

**Comment by maoueh** [comment]
Closing as a solution that seems correct has been provided. Please re-open if there is still a problem.
