### ISSUE TITLE
CORS: Localhost

### ISSUE THREAD

**Issue by RongxinZhang** [graphprotocol/graph-node#3109]
**Bug/Question**
I'm using an apollo client to connect to the graph node my local graph node.
However, it works if 
`Access to fetch at 'http://127.0.0.1:8000/subgraph/subgraphs/name/richardhall/lando' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok stat`

**Setup**

- OS: Ubuntu
- GraphNode: Run inside of docker-compose
- WebApp: Run local using creat-react-app.

```js
const SubGraphProvider = ({ children }: ProviderProps) => {
  const client = new ApolloClient({
    uri: "http://localhost:3000/subgraph" + SUBGRAPH_PATH,
    cache: new InMemoryCache(),
  })
  return <ApolloProvider client={client}>{children}</ApolloProvider>
}
```

**What is the current behavior?**
I thought that this would not be a problem as CORs is already added in, so I don't need to do anything with the dockercontainer.: https://github.com/graphprotocol/graph-node/issues/2193

Would love some guidance @leoyvens if I'm missing something.

**Comment by leoyvens** [comment]
@RongxinZhang seems like you're getting an HTTP error, and that's being masked as a CORS error. Try querying the endpoint through curl to get the real error.

**Comment by azf20** [comment]
Hi! @RongxinZhang hope you got this working, closing this issue for now, please re-open if you have identified a bug or problem!

**Comment by gwumex** [comment]
@RongxinZhang where you able to solve this
