### ISSUE TITLE
Mandate everything runs in some fixed locale `en_US.UTF8`

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-node#3118]
> We should mandate that everything runs in some fixed locale (maybe `en_US.UTF8`, though we'd need to look into if there are other locales that are more palatable to the non-English world) `graph-node` could then check on startup that its locale and the locale of the database are the expected one.

_Originally posted by @lutter in https://github.com/graphprotocol/graph-node/issues/1837#issuecomment-984160371_

**Comment by saihaj** [comment]
I search the codebase and I see this comment https://github.com/graphprotocol/graph-node/blob/85ac00cd19cabce1fbcf0979d727fb15105333d8/store/postgres/src/connection_pool.rs#L589-L594 which means non english DBs shouldn't work right cause they get marked as unavailable. That means we don't need to panic or anything? cc @lutter

**Comment by azf20** [comment]
@saihaj I wonder if we can add a specific check for `en_US.UTF8`? I think for determinism it's not enough for it to be in English, I think it needs to be specific

**Comment by leoyvens** [comment]
The POSIX locale is better for performance, so it seems worth discussing if we should choose that.

**Comment by lutter** [comment]
[This discussion](https://dba.stackexchange.com/questions/240930/postgresql-difference-between-collations-c-and-c-utf-8) is a good start. One thing to note is that switching collation would require rebuilding all indexes with `text` columns in them.

**Comment by azf20** [comment]
The majority of indexers responding to the straw poll are running `en_US.UTF8`. Proposing that we adopt that as the standard on the network, but @lutter am wondering what the migration path is for any indexers currently running a different locale? I don't know what the implications are - ideally it would be as simple as a reconfiguration, but presumably indices would need to be regenerated?

**Comment by lutter** [comment]
The 'right' choice would be to use the `C` locale because it performs better in queries etc. than `en_US.UTF8` (I am told that it can speed up comparisons by 10x)

Either way, the safest way to change locale is to recreate the database - the default locale is baked in when the database is initialized. That means the indexers would have to dump their database, recreate it, and restore from backup. There _might_ be ways for us to change that when generating queries, but it'll require some more work within `graph-node`

**Comment by azf20** [comment]
OK - so they wouldn't need to re-index, just restore from backup? Interested in @fordN's opinion from an indexer perspective here?

**Comment by saihaj** [comment]
https://github.com/graphprotocol/graph-node/pull/4163
