### ISSUE TITLE
Do not print entire block in log message

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#3123]
This [log message](https://github.com/graphprotocol/graph-node/blob/4d4947e2e0a4a662c2001fa49662c8d0078d4585/chain/ethereum/src/ethereum_adapter.rs#L1498) prints an entire block which makes the logs unreadable. It should only print a block hash or block pointer.

There might be other log messages that do that, too.

**Comment by leoyvens** [comment]
Fixed in #3125
