### ISSUE TITLE
Add new block processing algorithm to RuntimeHost

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#313]
Implement the algorithm from #281 using the database operations implemented in #290 and EthereumAdapter functionality added in #312 as a replacement for the old subscribe_to_event approach.

**Comment by timmclean** [comment]
Obsolete, see #372

**Comment by Jannis** [comment]
I've repurposed this to be about the block-stream-based event processing in `SubgraphInstanceManager`, `SubgraphInstance`, `RuntimeHost` and `WasmiModule`. So it isn't really obsolete.

**Comment by timmclean** [comment]
Oh OK sounds good!
