### ISSUE TITLE
Graph-node doesn't pick up blocks and hence doesn't run any handlers

### ISSUE THREAD

**Issue by FredCoen** [graphprotocol/graph-node#3159]
I am running a local graph node to index my local hardhat kovan fork and deployed my subgraph.
It seems to have worked fine in terms of subgraph deployment, however it doesnt seem to pick any events or store data. 
Why is not able to download blocks correctly?

the graph node logs show the following: 

Jan 14 14:47:20.311 INFO Downloading latest blocks from Ethereum. This may take a few minutes..., provider: kovan-rpc-0, component: BlockIngestor

Jan 14 14:47:20.317 INFO receipt block mismatch, tx_hash: 0x355f…2995, block_hash: 0x7509…f805, receipt_block_hash: 0x95c1…0dae, provider: kovan-rpc-0, component: BlockIngestor

Jan 14 14:47:20.317 INFO Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0x750941d78513f94ec35d83761c817be0c8ad8871330b748578e27ea7f5f6f805), provider: kovan-rpc-0, component: BlockIngestor

**Comment by azf20** [comment]
hi @FredCoen - are you using an archival Kovan node to fork from?
I don't see any logs about the subgraph deployment?

**Comment by FredCoen** [comment]
@azf20 yes it an archival node.

Here the logs of the subgraph deployment

Jan 15 19:45:58.814 INFO Starting metrics server at: http://localhost:8040, component: MetricsServer
Jan 15 19:45:58.814 INFO Starting GraphQL WebSocket server at: ws://localhost:8001, component: SubscriptionServer
Jan 15 19:45:58.816 INFO receipt block mismatch, tx_hash: 0xb1e6…e7e0, block_hash: 0xc92b…baa4, receipt_block_hash: 0x75e2…ced2, provider: kovan-rpc-0, component: BlockIngestor
Jan 15 19:45:58.816 INFO Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0xc92b1b46ff1886c57f4b3394f02d29246fc4400e8e22899c48dd9bc1379dbaa4), provider: kovan-rpc-0, component: BlockIngestor
Jan 15 19:45:58.835 INFO Resolve subgraph files using IPFS, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.835 INFO Resolve subgraph files using IPFS, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve schema, link: /ipfs/QmT4ZLss6Nhccen12jg7BU2JLPDM1AsrjkxDDVtfxLgyXj, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve schema, link: /ipfs/QmT4ZLss6Nhccen12jg7BU2JLPDM1AsrjkxDDVtfxLgyXj, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve data source, source: 29039808, name: Position, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve mapping, link: /ipfs/QmPnF9JrETKQpiuuQkkfdMnNuTh9QkAFR9kvpBU1qapRdU, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve data source, source: 29258070, name: Position, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve mapping, link: /ipfs/QmPnF9JrETKQpiuuQkkfdMnNuTh9QkAFR9kvpBU1qapRdU, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve ABI, link: /ipfs/QmcSm1RKnTeowuQQdG5zumfWNhAKdvMU7FF7dTaZR6T5vp, name: Position, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve ABI, link: /ipfs/QmcSm1RKnTeowuQQdG5zumfWNhAKdvMU7FF7dTaZR6T5vp, name: Position, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve ABI, link: /ipfs/QmV9KdYwkNNRW9bo4Y6kvnjUF3gQgubVpRpn9pZgKBF7yN, name: BorrowerPools, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve ABI, link: /ipfs/QmV9KdYwkNNRW9bo4Y6kvnjUF3gQgubVpRpn9pZgKBF7yN, name: BorrowerPools, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.836 INFO Resolve data source, source: 29039808, name: BorrowerPools, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.837 INFO Resolve mapping, link: /ipfs/QmPnF9JrETKQpiuuQkkfdMnNuTh9QkAFR9kvpBU1qapRdU, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.837 INFO Resolve ABI, link: /ipfs/QmV9KdYwkNNRW9bo4Y6kvnjUF3gQgubVpRpn9pZgKBF7yN, name: BorrowerPools, sgd: 1, subgraph_id: QmZhpULqRFQnXXw51JLur41X3XoTK9nmNKDW2zhCHUpK4x, component: SubgraphInstanceManager
Jan 15 19:45:58.837 INFO Resolve data source, source: 29258070, name: BorrowerPools, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.837 INFO Resolve mapping, link: /ipfs/QmPnF9JrETKQpiuuQkkfdMnNuTh9QkAFR9kvpBU1qapRdU, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4spm9cCcS3bWL5agYpwTeCzWMYz, component: SubgraphInstanceManager
Jan 15 19:45:58.837 INFO Resolve ABI, link: /ipfs/QmV9KdYwkNNRW9bo4Y6kvnjUF3gQgubVpRpn9pZgKBF7yN, name: BorrowerPools, sgd: 2, subgraph_id: QmfSZAutqeWVRq3aCJV4s

**Comment by FredCoen** [comment]
are these uncled block logs a concern? seems to me the blocks are not being downloaded by my graph-node and hence no handlers are being run when events are emitted through transactions i run on my local hardhat

**Comment by azf20** [comment]
It is hard to be sure - does the deployed subgraph index an existing Kovan contract, or just one deployed on the local fork? Does the graph node ever seem to process new Ethereum blocks? Can you verify that the forked rpc behaves as expected (when you query for the new blocks that are mined etc. - they don't show up as uncled, vs. the chain head)?

**Comment by azf20** [comment]
hi! cross-posting here from Discord
so if you set the ETHEREUM_REORG_THRESHOLD env variable to something low (maybe 1? default is 250) that will stop the node from fetching older blocks from the fork (which seems to be rate limited by hardhat forks somehow)
note that if you are not using the latest master, you will need to set ETHEREUM_ANCESTOR_COUNT instead. e.g. from a local config I just verified witha  hardhat fork
```
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "localhost:http://host.docker.internal:8545"
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
```
thanks @leoyvens for the pointer!
