### ISSUE TITLE
Bug: GraphQL instance poisoned if GraphQL config ENV variables set to null

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#3178]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If `GRAPH_GRAPHQL_WARN_RESULT_SIZE` or `GRAPH_GRAPHQL_ERROR_RESULT_SIZE` is set to null it leads to issues in querying the graph-node via the GraphQL server. Specifically this error is returned from subgraph queries: `cause":"[GraphQL] panic processing query: Once instance has previously been poisoned"},"msg":"Failed to query subgraph deployments worth indexing"`. This issue has effected many indexers in the past month (5+) and is tricky to debug. 

**What is the expected behavior?**
If either of the mentioned ENV variables are set to null reasonable defaults should be used that do not cause the GaphQL instance to become "poisoned". 

Here is the code in graph-node that parses these ENV variables.
https://github.com/graphprotocol/graph-node/blob/8cae63a351a62bc5a94f392f79fd9adbb3b5c941/graphql/src/store/prefetch.rs#L42-L48

**Comment by leoyvens** [comment]
We can use this helper https://github.com/graphprotocol/graph-node/blob/8ddb732844ead61015b0ea835211cf3d6471baf0/graph/src/env.rs#L43 and change it to abort rather than panic on error.

**Comment by lutter** [comment]
Does 'set to null' here mean that the env variable is not set at all?

What can happen in that case is that processing of a query runs out of memory at a very inconvenient time (the error indicates that that can happen while holding a lock).

The best way to address that would be to set `GRAPH_GRAPHQL_ERROR_RESULT_SIZE` to a value that avoids that OOM. The two `query_result` set up [here](https://github.com/graphprotocol/graph-node/blob/master/graphql/src/runner.rs#L36-L50) can be used to get a better understanding of how to set that value and how many queries it would cut off.

**Comment by leoyvens** [comment]
I think it means the env var is set to the empty string, and panics on the first access and then starts returning that poisoned error on subsequent access.

**Comment by azf20** [comment]
@fordN can you confirm if it is for ENV variables set to null, or empty string, or both?

**Comment by neysofu** [comment]
Fixed by https://github.com/graphprotocol/graph-node/pull/3364. Closing.
