### ISSUE TITLE
refactor: prefer GraphQL SDL for base/meta schema

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-node#3203]
@lutter thoughts on that? mainly around `api.rs` and the schema we are building there. I feel like using SDL might be simpler for most of the static definitions? 

Also related:
https://github.com/graphprotocol/graph-node/pull/3201
https://github.com/graphprotocol/graph-node/pull/3184

**Comment by lutter** [comment]
Yes, my preference would be to express as much as plain text files (GraphQL SDL) as possible instead of doing that in code. Of course, some of that has to be dynamic since it depends on user-supplied types.
