### ISSUE TITLE
Intermittent failure to detect a provider with trace support

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3204]
Affected subgraphs fail to start, logs show:
```
Failed to start subgraph...
error: expected triggers adapter that matches deployment Qm.. with required capabilities: traces: ... was not found
```
Even though there **was** a configured provider with `traces` at the time. This coincided with receiving 50x errors from the RPC endpoint, which may be related.

This was recently observed indexing xDai on the Hosted service for nifty.ink, DAOstack, 1hive

**Comment by leoyvens** [comment]
If the provider is considered defective at startup due to returning too many errors, then this can happen even if it is present in the configuration.

**Comment by azf20** [comment]
Duplicate of https://github.com/graphprotocol/graph-node/issues/3937
