### ISSUE TITLE
Considerable delay between emitted event in contract and data saving in subgraph

### ISSUE THREAD

**Issue by SachiniPiyumali** [graphprotocol/graph-node#3222]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

- When a event emit from the contract ( ex: When item is bought) it takes nearly 9s to update in subgraph
- When item is bought, transfer event will be emitted.
- When subgraph logs are checked regarding event it has nearly 9s of delay after confirm the transaction from meta task

![image](https://user-images.githubusercontent.com/31387868/152777088-fa90b3cc-db22-4d1e-8f0e-aad5faa77a39.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

- It is a expected situation or how can i prevent this scenario?

**Comment by leoyvens** [comment]
Old support issue, closing.
