### ISSUE TITLE
Ability to resume indexing when deploying updated subgraph.yaml

### ISSUE THREAD

**Issue by dougg0k** [graphprotocol/graph-node#3242]
Hi,

When you deploy a updated subgraph.yaml, everytime a new schema are created, is there a way to deploy and keep using the same one?

**Comment by leoyvens** [comment]
In some cases grafting might help https://thegraph.com/docs/en/developer/create-subgraph-hosted/#grafting-onto-existing-subgraphs but otherwise there is no way to reuse data from a previous deployment in a new one.
