### ISSUE TITLE
Hosted Service fails to start subgraph

### ISSUE THREAD

**Issue by giraffekey** [graphprotocol/graph-node#3243]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When attempting to start the subgraph after deploying to Hosted Service, I get the following error:

```
Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment Qm... with required capabilities:
traces: A matching Ethereum network with NodeCapabilities { archive: false, traces: true } was not found.
```

I've tried `rinkeby`, `avalanche` and `aurora-testnet`, all of which produce this error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

`graph init --product hosted-service`

(`graph -v` prints 0.26.0)

```
Protocol: ethereum
Subgraph name: {USER}/decoy
Directory: decoy
Ethereum network: rinkeby
Contract address: 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
Contract Name: Contract
```

`cd decoy && yarn deploy`

Might need to fix `subgraph.yaml` a bit. When I deploy this I get the same error and it never starts or syncs.

**What is the expected behavior?**

No errors.

**Comment by azf20** [comment]
Hey @giraffekey - I assume your subgraph is using callHandlers, these require trace filtering by Ethereum nodes, which isn't supported by the networks you mention, so the subgraph will need to use event or blockHandlers only. Closing as not a graph-node issue. Please do re-open if you are still having issues!
