### ISSUE TITLE
 what kind of server can I choose to build a graph node of eth

### ISSUE THREAD

**Issue by leilaohu888** [graphprotocol/graph-node#3248]
hello,I am very happy to join this group,I want to build a the graph node of eth,but I don't know what kind of server, how much memory, how much core CPU, how big disk,any questions
What reference is there?

**Comment by azf20** [comment]
Hey @leilaohu888! It depends on your needs & what you are using the graph-node for (e.g. testing vs. in production). [Here is a useful reference](https://forum.thegraph.com/t/testnet-docker-guide-by-stakesquid/1273) that one of the indexers put together on what they are using.

**Comment by azf20** [comment]
I recommend joining the [Graph Protocol Discord](https://discord.gg/vtvv7FP), where #indexers can help with more detailed questions. Closing this issue, please re-open if you are still having issues
