### ISSUE TITLE
Implement complete GraphQL query validation

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#325]
We should implement full query validation so that, after a query is checked, later parts of the code have less to worry about and can make the assumption that the query is valid and matches the schema.

See [the GraphQL specification](http://facebook.github.io/graphql/draft/#sec-Validation) for the validation algorithm.

**Comment by Jannis** [comment]
This is particularly important because broken queries can cause panics at the moment:
> If user enters a blank list or one that contains different types of values a panic ends the node process.  Include query validation allowing filter generation to fail and report back the error to the client instead of panicking. 
Also check to see if list is empty, index access currently panics if empty.

**Comment by timmclean** [comment]
Bumping up the milestone on this one as we need to get rid of these panics
