### ISSUE TITLE
how to build  two  the graph node in one compute

### ISSUE THREAD

**Issue by leilaohu888** [graphprotocol/graph-node#3251]
how to build  two  the graph node in one compute and how to build the graph node with postgres not in docker

**Comment by azf20** [comment]
If you have Postgres running separately, you can just remove Postgres from the docker compose (you may need to update the connection depending on your Postgres setups).

I believe if you want to run two Graph Nodes on once instance you will need to update the port configuration to avoid conflicts

**Comment by azf20** [comment]
Closing this - please do re-open if you are still having issues
