### ISSUE TITLE
Improve block stream pipelining with dynamic data sources

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#3257]
Two ideas:
- Reduce block stream pipeline size to zero if we're creating a lot of dynamic data sources
- Avoid restarting the block stream by using broader filters that make it unnecessary

**Comment by leoyvens** [comment]
Because this regresses sparse subgraphs with templates, we plan to turn this on by default only when using firehose.

**Comment by leoyvens** [comment]
This been implemented as intended so this can be closed.
