### ISSUE TITLE
GraphQL API for entity changes in a subgraph and block

### ISSUE THREAD

**Issue by neysofu** [graphprotocol/graph-node#3274]
# Objective

We want to provide new debugging capabilities for indexers, which can then be leveraged by our internal tool IXI to bisect PoI mismatches.

# Proposed changes

We should define a new GraphQL indexer route for dumping all entity changes (removals, additions, updates) that happened at a specific block.

```graphql
type Query {
  # ...

  entitiesChangedInBlock(
    subgraphId: String!
    blockNumber: Int!
  ): [EntityData!]!
}

type EntityData {
  name: String!
  fields: [String!]!
}
```

## Previous work

- https://github.com/graphprotocol/integration-testing/blob/98a5988c4d8c8dbd89194d66e1abf19a0ee52927/src/utils/entities.ts#L52: An example of the SQL query that we'd like to expose via the GraphQL route.

**Comment by lutter** [comment]
I don't fully understand the `EntityData` type. Would `name` be the name of the entity type? Ideally, you'd be able to return JSON like this:
```
{
  "Account": [{ "id": "account1", "balance": 200}, {"id": "account2", "balance: 50"}],
  "Transaction": [ .. ]
  ..
}
```
but I am not sure how you would write a GraphQL type for basically arbitrary JSON (arbitrary for at least the array contents) Maybe @dotansimha  has some idea on how to express that?

**Comment by neysofu** [comment]
Good point @lutter, my design for `EntityData` only contains field names and not values. This is not the desired behavior.

I think we have at least two options for mapping entity field values to GraphQL:

- Something akin to https://github.com/taion/graphql-type-json i.e. a custom `scalar JSON` type.
- Marshalling values as JSON, and treat the minified JSON as a `String!`.
