### ISSUE TITLE
Support Ontology network

### ISSUE THREAD

**Issue by diucicd** [graphprotocol/graph-node#3278]
**Do you want to request a *feature* or report a *bug*?**
request a feature

https://twitter.com/OntologyNetwork/status/1495669773568737280
OntologyNetwork will support EVM soon, what should we do to let subgraph support ontology chain? Our testnet has already support EVM, its endpoint is: https://polaris1.ont.io:10339.

**Comment by azf20** [comment]
Hi @diucicd - you can verify compatibility by running a local graph-node with Docker and deploying subgraphs to that local node, updating to use your Ontology endpoints: [docker-compose](https://github.com/graphprotocol/graph-node/blob/432844b67552f7981d733031e14cfaeffbba7c73/docker/docker-compose.yml#L20)

**Comment by azf20** [comment]
Closing this for now, please re-open if your chain is EVM compatible and the above suggestion does not work
