### ISSUE TITLE
Ethereum API get wrong contract return value.

### ISSUE THREAD

**Issue by abcfy2** [graphprotocol/graph-node#3306]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**

I try to use Ethereum API in event handler. Like this:

```ts
export function handleMintPassUsed(event: MintPassUsed): void {
...
  const contract = DerivedAPEContract.bind(event.address);
  const tokenURIResult = contract.try_tokenURI(tokenId);
  if (!tokenURIResult.reverted) {
    const tokenURI = tokenURIResult.value;
    log.warning("tokenURI = {}, startsWith 'ipfs://' ? {}", [
      tokenURI,
      tokenURI.startsWith("ipfs://").toString(),
    ]);
  }
}
```

But `tokenURI` will get the oldest value like: `https://tmp-for-testing.s3.ap-southeast-1.amazonaws.com/4/0xAF8c036bA046779Ee225B1eE8A5674E23b68d0fE/0x44270730f46e3829ef6ebf464c40bc4597b7cea0f0c74cff3a4989a0d7a217d5.json`

studio log:

```
WARNING
2022-03-02 01:49:46 a.m.
tokenURI = https://tmp-for-testing.s3.ap-southeast-1.amazonaws.com/4/0xAF8c036bA046779Ee225B1eE8A5674E23b68d0fE/0x44270730f46e3829ef6ebf464c40bc4597b7cea0f0c74cff3a4989a0d7a217d5.json, startsWith 'ipfs://' ? false, data_source: DerivedAPE, block_hash: 0x85d4c151397e3651983ba5ac40ec614225e16288fe103c21983cc3f5038b6791, block_number: 10080323
```

![image](https://user-images.githubusercontent.com/5327677/156224031-91929b6e-ffe8-4b2e-a8c6-0d655ef9e8ba.png)

But in fact the value should be like `ipfs://bafyreifxrnidaxluetozp6xj24jlunw7pindindzvacdfi2olmjpu3kjy4/metadata.json`

![image](https://user-images.githubusercontent.com/5327677/156223843-e57fe955-24af-43ad-ad50-d08fb5806e55.png)

What's wrong ? Seems graph node does not sync all blocks caused contract function returns oldest value ?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

`tokenURI` contract function should return the right value.

Thanks.

**Comment by leoyvens** [comment]
The call will return the value as of the block in which the event is handled, so if this is processed at block 10080323, you get the value the call had at that block.

**Comment by abcfy2** [comment]
Thanks. I think I have to find another way to do this.

**Comment by abcfy2** [comment]
Oh, `callHandlers` does not working for rinkeby, is there alternatives ?

**Comment by leoyvens** [comment]
To be able to keep the token uri updated, you need to have an event so you can do the contract call and update the entity each time it happens. For now there is no way to get call handlers working for rinkeby. I recommend you go on the Discord to get faster support to these questions https://discord.com/invite/vtvv7FP.

**Comment by jwrookie** [comment]
@abcfy2 I have the same problem and need to use etherjs to call the contract, did you solve it?
