### ISSUE TITLE
GraphQL API for block data

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#3311]
When we have detected a difference in the indexing results of two indexers, we need to gather more details and contextual information to debug what could have led to that difference.

Differences are always starting at a specific block and one of the details that we need is the _block_ itself that graph-node used for processing the subgraph in question.

This is (roughly) the schema that we need:

```graphql
type Query {
  blockData(network: String!, blockNumber: Int!): JSONObject
}
```

We cannot guarantee that graph-node always has this information (hence the nullable return value) but typically it should. A generic `JSONObject` seems reasonable as the result because we may be dealing with Ethereum blocks, NEAR blocks and others and probably don't want to type these too strictly in this schema. We'd likely forget to keep these types in sync with the actual types used when processing.

graph-node stores Ethereum block data in an `ethereum_blocks` table. Not sure about NEAR blocks. Either way, there's probably a method in one of the stores to get the right data for a network.

**Comment by neysofu** [comment]
I'm thinking about how to approach reorgs here. The API you provided here works beautifully when we either don't find a block or we do, but there's always the chance of getting multiple blocks back from the DB. I believe (please correct me if I'm wrong here) that if we want to actually fetch the block that contributed to the bad POI, we need to take `poi2$` into account and thus require an extra `subgraphId` parameter.

Either that or we return a list of blocks (`[JSONObject!]!`) and we let the clients figure it out by themselves (which kind of seems to defy the whole reason we're working on this, i.e. to facilitate cross-checking).

**Comment by Jannis** [comment]
@neysofu We could make the request based on the block hash. We have that in the cross-checking tool at the time we're ready to make a request.

It would change the schema to
```rust
type Query {
  blockData(network: String!, blockHash: Bytes!): JSONObject
}
```

**Comment by neysofu** [comment]
That solves all of our problems then, awesome :)
