### ISSUE TITLE
GraphQL API for Ethereum call cache

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#3312]
When we have detected a difference in the indexing results of two indexers, we need to gather more details and contextual information to debug what could have led to that difference.

Differences are always starting at a specific block and one of the details that we need is the Ethereum call cache that graph-node used for processing the subgraph in question.

This is (roughly) the schema that we need:

```graphql
type Query {
  cachedEthereumCalls(network: String!, blockNumber: Int!): [CachedEthereumCallData!]!
}

type CachedEthereumCallData {
  ...
}
```

**Comment by azf20** [comment]
The hosted service should create the indexes before the rollout takes place (cc @lutter)

**Comment by otaviopace** [comment]
@neysofu @Jannis shouldn't the API use `blockHash` instead of `blockNumber` so determinism is guaranteed? 🤔

**Comment by neysofu** [comment]
@otaviopace indeed, we ended up using `blockHash` for that specific reason! The GraphQL snippet in this issue is outdated.
