### ISSUE TITLE
[Bug?] ipfs.cat doesn't work even though ipfsOnEthereumContracts is enabled

### ISSUE THREAD

**Issue by Remscar** [graphprotocol/graph-node#3341]
**What is the current behavior?**
Using latest version of the graph-node locally.
Deploy a subgraph that uses `ipfs.cat`
Get this error in the graph node logs:
```
 ERRO Subgraph error 1/1, code: SubgraphSyncingFailure,
error: `ipfs.cat` is deprecated. Improved support for IPFS will be added in the future       
wasm backtrace:      0: 0x5892 - <unknown>!src/registrar/handleDomainCreated
in handler `handleDomainCreated` at block #10022062 (16b1861004b3459da36f8dfd71344d0c83badbfc855d0a53e133167527b8d35e), block_hash:
x16b1861004b3459da36f8dfd71344d0c83badbfc855d0a53e133167527b8d35e,
block_number: 10022062, sgd: 9,
subgraph_id: QmdoQcF2rzSGzAizyh8WasbNDVtPZkktvjaA1tPjy212Rg, component: SubgraphInstanceManager
 ``` 

**What is the expected behavior?**

I assumed that ipfs.cat would work on the local graph node, how do I enable it?

**Comment by Remscar** [comment]
It looks like the env variable `GRAPH_ALLOW_NON_DETERMINISTIC_IPFS` needs to be set, but there is no documentation for this.

**Comment by azf20** [comment]
Hi! This is indeed a documentation shortfall, PR here: https://github.com/graphprotocol/docs/pull/82
