### ISSUE TITLE
ISO-8601 date format for log timestamps

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/graph-node#3349]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Current log timestamp format is like `Mar 01 01:25:28.484`.
**What is the expected behavior?**
ISO-8601 format: `2022-03-01T01:25:28.484+00:00`

Using the ISO standard would make interoperability much easier. In particular easier processing and analytics of the `graph-node` logs without having to resort to custom decoding of the timestamp.

**Comment by azf20** [comment]
Thanks @aasseman! What do you think @leoyvens & @tilacog? Seems like probably quite a small change, but I wonder if it would break anything?

**Comment by leoyvens** [comment]
We can look into making this configurable.

**Comment by willser** [comment]
Hi.It seems like a issue for which easy to resolve by a new contributor.Is a good solution to add a new environment variable to config   which date format? @leoyvens @azf20

**Comment by leoyvens** [comment]
Done in #3387, thanks for tackling this @willser!
