### ISSUE TITLE
Add Date attribute value type

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#340]
For this, we need to decide on a date formatting standard and than add a Entity attribute type with GraphQL serialization/deserialization for it.

**Comment by leoyvens** [comment]
We've gone a long time without really needing dates as a first-class type. I'll close this, we can open a new issue if this comes up again.

**Comment by adamazad** [comment]
We need them for an entity. We use `createdAt` and `updatedAt` fields, and it doesn't make sense to drill those props down to another function from the main handler. :)
