### ISSUE TITLE
graphman: provide an official way to list all deployments

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#3407]
`graphman` should have a way to list all deployments. Currently, and solely as a sideeffect of how it handles its arguments, `graphman info ''` will do that, but there should be a better way for that (maybe `graphman info -l` or `-a`)

**Comment by kaiwetlesen** [comment]
I'm in favour of `graphman info --all` with a short option `graphman info -a`. This could be the new standard going forth.
