### ISSUE TITLE
graph-node isn't syncing subgraph

### ISSUE THREAD

**Issue by TimDaub** [graphprotocol/graph-node#3419]
I've managed to deploy a graph-node that logs when it's behind the Ethereum node.

```
Apr 01 12:19:55.565 INFO Syncing 1 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 14500316, current_block_head: 14500315, provider: rpinode, component: BlockIngestor
Apr 01 12:20:08.784 INFO Syncing 1 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 14500317, current_block_head: 14500316, provider: rpinode, component: BlockIngestor
Apr 01 12:20:25.967 INFO Syncing 1 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 14500318, current_block_head: 14500317, provider: rpinode, component: BlockIngestor
```

I've also managed to deploy a subgraph. But when I go to its website, I get an error:

```
{
  "errors": [
    "{\n  \"errors\": [\n    {\n      \"message\": \"Store error: query execution failed: Subgraph `QmfYShvt1zUyeMijkAJxTMYxMRR1NwSPRa81gXAJmUenz5` has not started syncing yet. Wait for it to ingest a few blocks before querying it\"\n    }\n  ]\n}"
  ]
}
```

I don't understand how to debug this. My logs never mention any synching of this subgraph. How do I find out what is happening?

**Comment by tilacog** [comment]
Hey @TimDaub!
Could you provide your subgraph code, so we can have more context to help you out, please?

**Comment by TimDaub** [comment]
Subgraph code: https://github.com/timdaub/web3-music-subgraph
graph-node HEAD commit: d1f9259f1689da7c6b53fb4965689e6d3697477e

**Comment by jessepinkman9900** [comment]
facing same issue. has this issue been solved?

**Comment by jessepinkman9900** [comment]
I solved this issue by providing a `startBlock` in `source` of `dataSource`.
[This](https://github.com/graphprotocol/graph-node/blob/master/docs/subgraph-manifest.md#151-ethereumcontractsource) says that `startBlock` is `optional` but that does not seem to be the case

**Comment by azf20** [comment]
hi @jessepinkman9900 `startBlock` is optional but if it isn't provided the subgraph will start syncing from genesis (block 0 of the chain)

**Comment by TimDaub** [comment]
> facing same issue. has this issue been solved?

haha I sadly resolved it by just deploying to the hosted service
