### ISSUE TITLE
Fast sync

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#344]
We've added a block and event stream component which makes ingesting blocks much more reliable, especially when connecting to unreliable Ethereum nodes. This reliability does come at a speed cost though. We should improve the algorithm to dynamically adjust its settings so the streaming can be as fast as the underlying node can support.

Proposed initial algorithm:
- Start at a high block chunk size (~500,000)
- Have a threshold of retries per request ratio below which the chunk size decreseases

We could also make the chunk size a configuration option.

- [ ] Investigate loading BlockStream blocks asynchronously https://github.com/graphprotocol/graph-node/issues/425

**Comment by timmclean** [comment]
I like it!
