### ISSUE TITLE
Failed to query/save blockchain data locally using graph node (postgress db)

### ISSUE THREAD

**Issue by MohaiminulEraj** [graphprotocol/graph-node#3452]
First I implemented the [graph node](https://github.com/graphprotocol/graph-node) to update the data source and store them in the db that can be queried via the GraphQL endpoint (I used Infura's mainnet endpoint in my docker-compose file)
After cloning from the uniswap's-v3 subgraph repo, I installed all the dependencies and ran the following commands
npm run codegen
npm run build
npm run create-local
npm run deploy-local
I got messages like
Upload subgraph to IPFS
Build completed: QmagGaBm7FL9uQWg1bk52Eb3LTN4owkvxEKkirtyXNLQc9
Deployed to http://127.0.0.1:8000/subgraphs/name/mohaiminuleraj/uniswap-v3/graphql
Subgraph endpoints:
Queries (HTTP): http://127.0.0.1:8000/subgraphs/name/mohaiminuleraj/uniswap-v3
Subscriptions (WS): http://127.0.0.1:8001/subgraphs/name/mohaiminuleraj/uniswap-v3
But unfortunately, I can't seem to retrieve the blockchain data and store them in the Postgres DB (using graph-node)
I am facing these issues with Uniswap-v3, compound, 0x, and decentraland subgraphs

**Comment by azf20** [comment]
Thanks @MohaiminulEraj - [Discord](https://discord.gg/vtvv7FP) is probably a better place to get help on issues like this, if you are still having problems. Closing this issue for now, please re-open if you encounter a specific issue with Graph Node
