### ISSUE TITLE
Choose a good value for REORG_THRESHOLD

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#346]
We need to pick a good value for T from the algorithm in https://github.com/graphprotocol/graph-node/issues/281#issuecomment-415654036 . We may want different values for dev vs prod, and may want it to be configurable

See also #310 on Ethereum adapter configurability.

**Comment by timmclean** [comment]
In addition to the posts cited here: https://github.com/graphprotocol/graph-node/issues/281#issuecomment-416712434

Somewhat relevant reading: https://www.theblockcrypto.com/tiny/ethereum-classic-has-experienced-multiple-100-reorg-attack/ (note: Ethereum Classic, not Ethereum)

**Comment by lutter** [comment]
Closing this as we have settled on a threshold of 50 by default.
