### ISSUE TITLE
2 issues with Bytes as IDs in the GraphQL schema

### ISSUE THREAD

**Issue by steegecs** [graphprotocol/graph-node#3476]
Issue 1: 
Byte IDs are working fine except when you have an entity that inherits from an interface. This error is thrown in these cases. When you remove the inheritance, the error disappears.
<img width="1262" alt="Screen Shot 2022-04-19 at 2 05 54 PM" src="https://user-images.githubusercontent.com/56660047/164067875-8fcad6cf-0053-4f63-8eaf-56496c6ca3fd.png">

Issue 2:
Apparently, derivedFrom does not work with Bytes. This was discussed in the graph discord.

Both of these issues seem legitimate as you would expect them to work and are useful functions.

**Comment by lutter** [comment]
@steegecs Yes, these are both legitimate bugs; it would help if you can point me to subgraphs where these two issues happen. I'll work on fixing these.

**Comment by steegecs** [comment]
Here is the repo where I have store the updated code. It should throw a bug. The issue is occurring with entities that inherit from the Event interface. 

https://github.com/steegecs/subgraphs/tree/steegecs/uniswap-v2/subgraphs/uniswap-v2

**Comment by steegecs** [comment]
Thanks!

**Comment by steegecs** [comment]
<img width="479" alt="Screen Shot 2022-04-19 at 5 25 59 PM" src="https://user-images.githubusercontent.com/56660047/164104645-574ebe55-98aa-4355-b737-2962e497383f.png">

This is also a potential issue that I saw as well and forgot to bring up. When removing from the store, it appears to still require that you pass the ID for the entity you desire to remove as a string.

**Comment by lutter** [comment]
@steegecs I managed to reproduce Issue 1 and fix it; but I can't figure out under what circumstances issue 2 happens. Do you have more detail to help reproduce this?

**Comment by steegecs** [comment]
@lutter This was a message I relayed. There were 2 people who brought it up in the graph discord channel. However, I've just tried to reproduce this and can't seem to do so either.

**Comment by steegecs** [comment]
Yeah - this is working for me. Maybe the issue that was being broached here was not being able to access the derivedFrom fields from within the program mid-execution. I have heard a few people speak about this before. I'll see if I can get back in contact with the persons who posted this second issue.

**Comment by steegecs** [comment]
Yeah - I've tried everything I can think of to get this to reproduce, but I cannot. I spoke with the person who brought up the issue and have been trying to reproduce it with their help to no avail. Sorry for the inconvenience, maybe its best to table and see if it comes up again.

**Comment by lutter** [comment]
@steegecs just for the record, I managed to reproduced the problem with `derivedFrom` and rolled out a fix to the hosted service.

**Comment by lutter** [comment]
I just opened #3493 for the last remaining problem around `remove` that was reported here; with that, everything mentioned here is addressed and I am closing the issue. If there are still problems, either reopen or (for `store.remove`) comment on #3493
