### ISSUE TITLE
ens_name_by_hash is deprecated

### ISSUE THREAD

**Issue by Pana** [graphprotocol/graph-node#3484]
**Do you want to request a *feature* or report a *bug*?**
Not sure is this a bug

**What is the current behavior?**

When I deploy the ens-graph in the graph-node, I got this error, my graph-ts version is v0.23

Apr 20 14:43:58.738 ERRO Handler skipped due to execution failure, error: `ens_name_by_hash` is deprecated	wasm backtrace:	    0: 0x2e77 - <unknown>!src/ensRegistry/handleNewOwner	    1: 0x332f - <unknown>!src/types/schema/Domain#get:isMigrated	, handler: handleNewOwner, block_hash: 0x86f1fcd88122cf33cabd241bacedf3d9f78398967a2993a08f16a163a5e7401b, block_number: 72028970, sgd: 1, subgraph_id: QmdNfQHK68775RFy4aWa8vyeGBo7F262JQsWAbiRiNh7wG, component: SubgraphInstanceManager

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No error

**Comment by Pana** [comment]
How can I use ens_name_by_hash method, since it is required in ens-subgraph, I'm trying to deploy ens and ens-subgraph in  an EVM compatible chain.

**Comment by Pana** [comment]
I found this function is not open default, to use it need set the `GRAPH_ALLOW_NON_DETERMINISTIC_IPFS` env variable to true.
Just wondering why this method is deprecated ?

**Comment by evaporei** [comment]
@Pana this is deprecated because it's a feature that isn't allowed in the network, since it isn't deterministic, just like the IPFS functions, depending on file availability, etc.

**Comment by raidichu** [comment]
> @Pana this is deprecated because it's a feature that isn't allowed in the network, since it isn't deterministic, just like the IPFS functions, depending on file availability, etc.
> 
> Related PRs:
> 
> * [Disable `ipfs.cat` by default #1958](https://github.com/graphprotocol/graph-node/pull/1958)
> * [Gas metering #2414](https://github.com/graphprotocol/graph-node/pull/2414)

How I Can resolve this problem? Is Deploying a smart contract—the deterministic way is the solution or I need allow something on my EVM
