### ISSUE TITLE
Support for endBlock in subgraph defs

### ISSUE THREAD

**Issue by jamesmorgan** [graphprotocol/graph-node#3504]
We often replace/retire contracts but still want to index the events/transactions from these older unused contracts. 

Would be great if there was a `endBlock` we could define which would allow us to set a definitive data to stop indexing contracts from. 

Would save time/resources maintaining checks for things which are no longer used. 

Thanks for an awesome product 🙏

**Comment by jurrchen** [comment]
+1 this would be fantastic.
