### ISSUE TITLE
Remove old `removed` field from EthereumEvent

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#351]
I believe this is now obsolete. Also, I believe it would make sense to overwrite the `removed` field on all Log objects to `false`, since whether a Log is part of an uncled block is an opinion of the Ethereum node, which does not necessarily match the opinion of the Graph node (in fact, this could introduce non-determinism if this field is exposed to mappings).

**Comment by Jannis** [comment]
@timmclean: This will be resolved by #408, right?

**Comment by timmclean** [comment]
Hmmm partially I think. I'll bump the milestone though because it's not important

**Comment by Jannis** [comment]
Resolved in master.
