### ISSUE TITLE
Unexpected behavior of filtering subgraphs by block hash

### ISSUE THREAD

**Issue by RickyEsclapon** [graphprotocol/graph-node#3510]
Noticed some odd behavior on _meta entity filtering for specific hashes on hosted-service which should cause an error but does not, while the same behavior does cause an error on mainnet, which lead to a project perceiving worse quality of service on mainnet. 

Take the following result for a subgraph which failed syncing at block number `9601364`:

![image](https://user-images.githubusercontent.com/89109989/165845125-ef73e14a-2fa2-46e6-a12e-1b2cf58a78d3.png)

There is odd behavior that happens when I filter to the `hash` of a much more recent block number `14674449` (hash `0x0f784d093e5c039cdcadd9e8a02ed9d55ff89afc009ab7c86f23a2a13f186928`):

![image](https://user-images.githubusercontent.com/89109989/165845689-c546542a-f054-41de-96ed-7a5cbbd6b03d.png)

Notice how the two screenshots above share the same deployment id. I would expect this to be an error when filtering for a hash that has not been reached. When filtering on the block number instead of the hash, I see the error that I would expect to see in the screenshot above:

![image](https://user-images.githubusercontent.com/89109989/165846719-dc72ef14-2373-494b-be8c-91234ecc84e7.png)

This is relevant because this behavior throws an error on mainnet subgraphs, which can cause users to perceive a lower quality of service, and we should strive to have parity in the errors thrown between the two services.

**Comment by azf20** [comment]
Got it - I think the key difference here (and the reason for errors on the network, vs errors on the  hosted service) is whether blocks are in the block cache (even if the specific subgraph hasn't indexed those blocks yet). It does indeed seem that blocks which are in the block cache don't throw the expected error

**Comment by leoyvens** [comment]
So this might be addressed by #3518.

**Comment by azf20** [comment]
@leoyvens I think this bug occurs when the blocks _are_ in the cache

**Comment by azf20** [comment]
Failed subgraph test case: `https://api.thegraph.com/subgraphs/id/QmNRkaVUwUQAwPwWgdQHYvw53A5gh3CP3giWnWQZdA2BTE`

Failed at block: 12733429

Querying by block Number:
```
{
  _meta(block: {number: 14878000}) {
    block { number }
  }
}
```
Correctly returns that that subgraph hasn't indexed that block:
```
{
  "errors": [
    {
      "message": "Failed to decode `block.number` value: `subgraph QmNRkaVUwUQAwPwWgdQHYvw53A5gh3CP3giWnWQZdA2BTE has only indexed up to block number 12733429 and data for block number 14878000 is therefore not yet available`"
    }
  ]
}
```

Whereas querying by blockHash:
```
{
  _meta(block: {hash: "0x8d69b20d632f9cd591091411555bfdff19215c5df91d477e94a826cc7256465b"}) {
    block { number }
  }
}
```
Returns data as of that block:
```
{
  "data": {
    "_meta": {
      "block": {
        "number": 14878000
      }
    }
  },
  "errors": [
    {
      "message": "indexing_error"
    }
  ]
}
```
This suggests that querying by block hash does not undergo the same indexing progress checks. This implies that if there is a query for a block which is in the block cache (so resolves to a number) but has not yet been processed by the subgraph would also just return the data of the resolved number
