### ISSUE TITLE
BSC subgraph with callHandler cause error

### ISSUE THREAD

**Issue by jiriano** [graphprotocol/graph-node#3517]
**Do you want to request a *feature* or report a *bug*?** Bug

I try to deploy a subgraph on the BSC chain and face this error:

`
Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmS58kNTGg4VYPNMEH53JymEKjcrUtCzRQmNS3pkNMTJMD[279681] with required capabilities: traces: A matching Ethereum network with NodeCapabilities { archive: false, traces: true } was not found.
`

When I deploy this subgraph to mainnet or change a subgraph by deleting the callHandler everything works fine.

**Comment by itsjerryokolo** [comment]
CallHandlers require tracing, which isn't available on BSC. It's isn't a graph-node issue.

**Comment by jiriano** [comment]
@itsjerryokolo 
Thanks for your response.
Do you know which repository is appropriate to request this feature?

**Comment by itsjerryokolo** [comment]
That's something that needs to be enabled from Binance. The graph-node connects to the RPC endpoint they provide.
