### ISSUE TITLE
Block stream produced a non-fatal error, error: Ethereum node is missing block #19005291

### ISSUE THREAD

**Issue by imokoi** [graphprotocol/graph-node#3527]
![image](https://user-images.githubusercontent.com/16015549/166632383-202e4612-4887-4853-943f-8719ef95e2e0.png)

Hello guys, My subgraph cannot be synced, I saw there is a Debug error, So my subgraph is stuck for now, how can I solve this problem?

**Comment by imokoi** [comment]
![image](https://user-images.githubusercontent.com/16015549/166633314-ca7bbaa6-3c18-4569-bc96-f01da41c6187.png)

**Comment by leoyvens** [comment]
The subgraph moved past this, please report in Discord `#hosted-service` if this happens again.
