### ISSUE TITLE
Generalize BlockStore & BasicStore with a Blockchain trait

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#354]
Hypothetically would enable blockchains other than Ethereum, with the caveat that only one blockchain type could be usable at a time.

The added abstraction would make some things a bit clearer. E.g. `revert_block` takes a `Block`, which might suggest that it actually needs the Ethereum-specific data inside the block. In reality, it just needs the metadata: block hash, block number, and parent hash -- stuff that all blockchains would have. On the other hand, it would not solve the problem of adding new, non-Ethereum data source types.

Would appreciate some input from @Jannis on whether this is worth doing.

**Comment by Jannis** [comment]
In a way this is tracked in the multi-blockchain RFC.
