### ISSUE TITLE
`/api/v0/object` is deprecated

### ISSUE THREAD

**Issue by Andrewjeska** [graphprotocol/graph-node#3565]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I'm testing my subgraph on a graph-node that's run with `docker-compose` locally.  It errors out immediately after I deploy a subgraph. 

```
graph-node_1  | May 16 21:36:26.267 INFO Received subgraph_deploy request, params: SubgraphDeployParams { name: SubgraphName("anderjaska/phlote-curator-mumbai-staging"), ipfs_hash: DeploymentHash("QmeGfrEr1MJPvBqdjMPmjYLX5FWdYurnaqvXUgcd7ofsd5"), node_id: None, debug_fork: Some(DeploymentHash("QmXS5LM38prRFvH9fMfhDYNhznvW8jyKbvt7imGr4opgei")) }, component: JsonRpcServer
graph-node_1  | May 16 21:36:26.281 INFO Syncing 1 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 26340267, current_block_head: 26340266, provider: mumbai-rpc-0, component: BlockIngestor
graph-node_1  | May 16 21:36:26.982 WARN Trying again after object.stat failed (attempt #10) with result Err(reqwest::Error { kind: Status(405), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("ipfs.infura.io")), port: Some(5001), path: "/api/v0/object/stat", query: Some("arg=QmeGfrEr1MJPvBqdjMPmjYLX5FWdYurnaqvXUgcd7ofsd5"), fragment: None } }), sgd: 0, subgraph_id: QmeGfrEr1MJPvBqdjMPmjYLX5FWdYurnaqvXUgcd7ofsd5, component: SubgraphRegistrar
```

This happens when I use infura's IPFS node, which I'd like to do. Infura has already prevented anyone from using `/api/v0/object`

```
➜  ~ curl -X POST "https://ipfs.infura.io:5001/api/v0/object/stat?arg=QmZtmD2qt6fJot32nabSP3CUjicnypEBz7bHVDhPQt9aAy"

/api/v0/object has been removed, use /api/v0/dag instead
➜  ~
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Covered above I think. This happens only when I use infura, local IPFS node works just fine. 

**What is the expected behavior?**

I would like to be able to use infura's IPFS node if possible. Any advice pointing me that way would be really helpful :)

**Comment by azf20** [comment]
hey @Andrewjeska thanks, this seems to be related to this notice https://blog.infura.io/post/changes-to-the-go-ipfs-api. Seems that [files stat is preferred](https://docs.ipfs.io/reference/http/api/#api-v0-object-stat). I wonder if this would be an easy update in graph-node @leoyvens?
