### ISSUE TITLE
How to control insertion of data in blocks table in chain schema?

### ISSUE THREAD

**Issue by rishisha19** [graphprotocol/graph-node#3587]
Hi all, 

I have a query precisely.
We are using graph node to capture events from the contracts. Lately we have seen that blocks table started consuming a lot of data on the storage in postgres. This is when we are not even in mainnet or production and just in testnet and testing our contracts and graph.

Is it normal that it consumes a lot of amount of storage to store blocks transaction?
how can we control the graph node to capture data from the blocks for only relevant information?

Thanks in advance!
--
Rishi

**Comment by leoyvens** [comment]
Set the environment variable `GRAPH_ETHEREUM_CLEANUP_BLOCKS=true`.
