### ISSUE TITLE
[BUG] Aurora - Eth Call

### ISSUE THREAD

**Issue by steegecs** [graphprotocol/graph-node#3588]
Hello! I am trying to deploy a subgraph for Trisolaris - a DEX on the aurora blockchain.

I continue to run into this error when making an ETH call in one of my handlers. I am not sure what the source of the error is. I compiled and used the ABIs for this protocol.  I have deployed subgraphs for dexes that use close to the same code and it works fine.
<img width="1241" alt="Screen Shot 2022-05-23 at 9 15 00 AM" src="https://user-images.githubusercontent.com/56660047/170065780-02db80b9-9f59-4a0f-895f-9f23dd6dcee7.png">

Any ideas what the source of this error could be?

Here is the hosted service deployment:
https://thegraph.com/hosted-service/subgraph/steegecs/trisolaris-aurora?selected=logs

The code can be found here: 
https://github.com/steegecs/subgraphs/tree/steegecs/uniswap-forks-addForks/subgraphs/uniswap-forks
https://github.com/steegecs/subgraphs/tree/steegecs/uniswap-forks-addForks/subgraphs/uniswap-forks/protocols/trisolaris

The error seems to occur when running any of the eth calls in this file:
https://github.com/steegecs/subgraphs/blob/steegecs/uniswap-forks-addForks/subgraphs/uniswap-forks/protocols/trisolaris/src/common/handlers/handleReward.ts

**Comment by azf20** [comment]
Thanks @steegecs - @pranavdaa is this the in-progress issue with Aurora?

**Comment by azf20** [comment]
hi @steegecs will close this now, but please do re-open if you are still having this issue with Aurora?
