### ISSUE TITLE
Issue of using Bytes as IDs

### ISSUE THREAD

**Issue by haowang1013** [graphprotocol/graph-node#3600]
**Do you want to request a *feature* or report a *bug*?**

- bug

**What is the current behavior?**

- Using Bytes as entity IDs seems to cause failure when resolving references.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- I created a test repo demonstrating the problem [here](https://github.com/haowang1013/graph-test)
- The graphs uses [openzeppelin-subgraphs](https://github.com/OpenZeppelin/openzeppelin-subgraphs) and it's now indexing the BYAC contract on mainnet
- Using the following 2 entities as [example](https://github.com/haowang1013/graph-test/blob/main/generated/byac.schema.graphql):
```
type ERC721Contract @entity(immutable: true) {
	id: Bytes!
	asAccount: Account!
	supportsMetadata: Boolean
	name: String
	symbol: String
	tokens: [ERC721Token!]! @derivedFrom(field: "contract")
	operators: [ERC721Operator!]! @derivedFrom(field: "contract")
	transfers: [ERC721Transfer!]! @derivedFrom(field: "contract")
}

type ERC721Transfer implements Event @entity(immutable: true) {
	id: ID!
	emitter: Account!
	transaction: Transaction!
	timestamp: BigInt!
	contract: ERC721Contract!
	token: ERC721Token!
	from: Account!
	to: Account!
}
```

So the `ERC721Contract` has a list of transfers of type `ERC721Transfer` using the derived field of `contract`

When using the query below [here](https://api.thegraph.com/subgraphs/id/QmZcEF5HAGU1maRMSQTGgAUxxrugiw9taSY7qfwe84HesE)
```
{
  erc721Contracts {
    id
    transfers(first: 5) {
      contract {
        id
      }
    }
  }
}
```

It couldn't resolve the `contract` field of the `ERC721Transfer` with an error of 
```
Null value resolved for non-null field `contract`
```

I know that the `contract` field must be set for the `ERC721Transfer`, otherwise they won't show up as `transfers` of `ERC721Contract`, but for some reason the reference cannot be resolved directly in the query.

I also did an experiment to change `ERC721Contract` to use `ID!` as the id and that seems to fixed it, so this is only a problem of using `Bytes!` as the id.

**What is the expected behavior?**

- Reference of entities using `Bytes` as id should be correctly resolved.

**Comment by lutter** [comment]
This is now live on the hosted service and the query in this issue works
