### ISSUE TITLE
`index-node` API fails for non-ethereum subgraphs

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#3607]
When trying to get the status for subgraphs not on ethereum, for example, with the query
```graphql
{
  indexingStatusForCurrentVersion(subgraphName: "lavabyrd/osmosis-block") {
    entityCount
    synced
    chains {
      network
      chainHeadBlock {
        number
        hash
      }
      latestBlock {
        number
        hash
      }
    }
  }
}
```

the server returns an error:
```json
{
  "errors": [
    {
      "message": "Store error: store error: Cannot parse H256 value from string `b161...031`: Invalid input length"
    }
  ]
}
```

This is most likely because [this](https://github.com/graphprotocol/graph-node/blob/master/graph/src/data/subgraph/status.rs#L20-L52) `EthereumBlock` struct wants an `H256`; it should just work with any old `Bytes`

**Comment by fredlacs** [comment]
I believe this issue isn't limited to non-ethereum chains
Here is a [mainnet subgraph](https://thegraph.com/hosted-service/subgraph/fredlacs/arb-bridge-eth) that gives the same error

```sh
curl 'https://api.thegraph.com/index-node/graphql' \
  --data-raw '{"operationName":null,"variables":{},"query":"{indexingStatusForCurrentVersion(subgraphName: \"fredlacs/arb-bridge-eth\") {subgraph}}"}' \
  --compressed
```
```sh
{"errors":[{"message":"Store error: store error: Cannot parse H256 value from string `1936a1c6f98b02b678ea476b8301c9e278fbef04ffb81fa1e92ba8a099a7113b354027b866d328eb3cb6aea11d3a516d`: Invalid input length"}]}
```

**Comment by 0xbe1** [comment]
@leoyvens is the fix deployed?

**Comment by traderjack** [comment]
Hi guys, so wen merge? A lot of our service are down because of this.

**Comment by fredlacs** [comment]
> Hi guys, so wen deployment? A lot of our service are down because of this.

In case it helps, we were able to work around it by querying `_meta` in the subgraph api instead of `index-node`
https://github.com/OffchainLabs/arb-token-bridge/pull/319

**Comment by traderjack** [comment]
> > Hi guys, so wen deployment? A lot of our service are down because of this.
> 
> In case it helps, we were able to work around it by querying `_meta` in the subgraph api instead of `index-node` [OffchainLabs/arb-token-bridge#319](https://github.com/OffchainLabs/arb-token-bridge/pull/319)

Appreciate this!

**Comment by leoyvens** [comment]
This is now deployed. If the `_meta` field covers your use case, that is preferrable.
