### ISSUE TITLE
Arweave "owner" transaction filtering currently uses the account's public key, rather than the easier to find short form

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3609]
The public key format is the long form which is to well known in Arweave space, which is used more to the short form displayed by the block explorer for example. Here a current long form version https://github.com/ChainSafe/subgraph-arweave-example/blob/master/subgraph.yaml#L11 and short form https://viewblock.io/arweave/address/AOvWwnkMZTItUjTEy4MNB5RJatrMf52f2RNEX8zwq5w.

**Comment by evaporei** [comment]
https://github.com/graphprotocol/graph-node/pull/3613
