### ISSUE TITLE
Node fails all requests with Err(Unknown(could not get latest block from Ethereum: Transport error: Unexpected response status code: 429 Too Many Requests))

### ISSUE THREAD

**Issue by Elod23** [graphprotocol/graph-node#3612]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

We've tried with several RPC providers now, but on all of them our own indexer node simply fails all requests.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Node doesn't throttle the RPC endpoint.

**Comment by azf20** [comment]
Behaviour here will depend on your limits and also on the chain being indexed.  @Elod23 are you still having this issue with rate limiting? Closing for now, reopen if so
