### ISSUE TITLE
 Unknown import: `Date::now` has not been defined

### ISSUE THREAD

**Issue by bijianing97** [graphprotocol/graph-node#3619]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I code in the handler.ts 
```ts
instance.createAt = BigInt.fromU64(Date.now())
```
but the local graph node exist the error
```
#10xxxxx (0x7a72…5f5e), transaction 66xxxxxxxxxxxxxxxxxxxxxxxxxxx6cc5556807b12b5a48a0: unknown import: `Date::now` has not been defined, retry_delay_s: 120, attempt: 0, sgd: 21, subgraph_id: QmR4Z2EE8w36zxxxxxxxxxxxxxxbNi3cbwkECX, component: SubgraphInstanceManager
```
How can I get the time just for createAt?
And how to sort on multiple fields ,could you give a example, I tried, but not work

**Comment by leoyvens** [comment]
For the time you should use the block timestamp. Please refer your questions to `#subgraph-development` on Discord.
