### ISSUE TITLE
cosmos: Do not unwrap an `Option`

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#3621]
The code [here](https://github.com/graphprotocol/graph-node/blob/master/chain/cosmos/src/codec.rs#L24) and [here](https://github.com/graphprotocol/graph-node/blob/master/chain/cosmos/src/codec.rs#L24) unwraps an `Option`. That has lead to startup failures in staging. The code needs to be changed to either deal witha `None` properly (e.g., by returning an empty iterator) or the `Block` struct needs to be changed to not contain an `Option`

**Comment by pienkowb** [comment]
@lutter Do you have more information about these failures (which chain, block number etc.)? This is not a normal situation. We left those `unwrap`s there because we expect the `ResultBeginBlock` structure to always be present. If it's missing, it might be a data extraction issue.

**Comment by leoyvens** [comment]
@pienkowb being a panic, it's actually hard to tell from the logs. If patch the code to not panic but bubble up an error, then we will be able to pinpoint the subgraph.
