### ISSUE TITLE
Clover subgraph failed, with required capabilities: archive,{ archive: true, traces: false } was not found.

### ISSUE THREAD

**Issue by lansehuiyi6** [graphprotocol/graph-node#3625]
Do you want to request a feature or report a bug? Bug

I try to deploy a subgraph on the Clover chain and face this error:

Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmadXvN9bYAXJYDrJ1WCeKTvcbuJ5s5dh6XhE9AWZYeA7s[316180] with required capabilities: archive: A matching Ethereum network with NodeCapabilities { archive: true, traces: false } was not found.

When I deploy this subgraph to moonriver everything works fine.

**Comment by mbartn** [comment]
I have the same issue on Fuji

**Comment by cjinghong** [comment]
same issue here

**Comment by azf20** [comment]
Hi! An archival node supporting EIP-1898 is required to make ethereum calls as part of a subgraph. This error suggests that the underlying node does not have the required configuration (`required capabilities: archive`).
