### ISSUE TITLE
Error indexing handleIncreaseLiquidity on a local graph-node on  Token#get:decimals with message: "Value is not a BigInt"

### ISSUE THREAD

**Issue by aleGiannini** [graphprotocol/graph-node#3654]
**Hi, I' m tring to deploy uniswap v3 subgraph to a local graph node that is connected to a local ethereum node on the goerli network.**

The **OS** is xubuntu v21.10 .
The **node** is hyperledger besu v22.1.2.
The **graph-node** version is 0.26.0 and run with docker-compose .

**In the subgraph.yaml i have removed this:** 
**graft:
  base: 
  block**: 

Because i haven't this subgraph deployed local, i changed the network to goerli and the start block to '7011478'.
For the deploy I use these commands:
**yarn
yarn codegen
yarn create-local
yarn deploy-local**

After deployment and after some blocks have been indexed I get this **error**:

ERRO Handler skipped due to execution failure, error: Mapping aborted at ~ **lib/@graphprotocol/graph-ts/index.ts**, line 811, column 4, with message: **Value is not a BigInt**. wasm backtrace:	    0: 0x25f8 - <unknown>! **src/types/schema/Token#get:decimals**	    1: 0x2611 - <unknown>!~ **lib/@graphprotocol/graph-ts/index/BigDecimal#constructor**	    2: 0x29e3 - <unknown>!src/mappings/
position-manager/**handleDecreaseLiquidity**	, handler: **handleIncreaseLiquidity**, block_hash: 0x41ea414f5ef6ef940b2b0557d0f403f8b2c1c32c22616dd4d45e0cf3a81dc8d0, block_number: 7011552, sgd: 1, subgraph_id: 
QmNwsfk3kJi8zzmBDVEiCGqioRnpyZM1iSTPPVYVNyDsop, component: SubgraphInstanceManager

**With which version of graph-node was this subgraph deployed?**

**Does anyone have any idea what it could be?**

**Comment by dr-fusion** [comment]
Hi Team, We are also getting same issue now for our UniV3 fork

**Comment by dr-fusion** [comment]
@aleGiannini  did you get any solution for it?

**Comment by aleGiannini** [comment]
Hi, I couldn't find a solution. It's been a while now, but if I remember correctly you can sync a the graph node and download the subgraphs data you want. Maybe you can try to do this instead of deploy it locally.
I hope it is useful to you.
