### ISSUE TITLE
GraphQL: `indexing_error` should only be returned if the subgraph has non-fatal errors feature enabled

### ISSUE THREAD

**Issue by evaporei** [graphprotocol/graph-node#3663]
An example was brought up by @itsjerryokolo with this subgraph https://thegraph.com/hosted-service/subgraph/astox/main, where it was synced up to chain head, but the errors wouldn't display in the playground, even with the `subgraphError: allow`.

<img width="337" alt="Screenshot 2022-05-30 at 11 46 53 AM" src="https://user-images.githubusercontent.com/15306309/173457185-7888d716-79af-43cf-be3a-57a5e04a6aa3.png">

This function is incomplete as described by @leoyvens https://github.com/graphprotocol/graph-node/blob/a74a37ef9ea41cadc0b7d2d255195073ecad3816/store/postgres/src/deployment.rs#L663, it returns `true` even if the subgraph doesn't use the non-fatal errors feature enabled.

**Comment by leoyvens** [comment]
Actually we should return `indexing_error` for a subgraph failed with a deterministic error, even if non-fatal errors is disabled. So maybe the code is already behaving as expected, and the function just needs to be renamed and clarified.

**Comment by azf20** [comment]
@leoyvens in that case is this about renaming, rather than a functionality issue?

**Comment by leoyvens** [comment]
Yes at this point this is just tracking the refactor in https://github.com/graphprotocol/graph-node/pull/3662.
