### ISSUE TITLE
Graph node crash on Rinkeby subgraph indexing after some period of time

### ISSUE THREAD

**Issue by air3ijai** [graphprotocol/graph-node#3668]
**Report a *bug*?**
We just deployed [ocean-subgraph](https://github.com/oceanprotocol/ocean-subgraph/tree/v3) v3 for [rinkeby](https://github.com/oceanprotocol/ocean-subgraph/blob/v3/subgraph.rinkeby.yaml) and also rewrite start block to be sync faster.
```bash
sed -i 's/startBlock:.*/startBlock: 10762423/' subgraph.rinkeby.yaml
```

It started to sync and finished after some hours. Then it worked fine ~ 1 day and after that go into restart-loop.

We used Erigon and then moved to Infura to check if it relates to the RPC endpoint, but nothing changed.

It is repeated the second time in our configuration.

**What is the current behavior?**
Index node crashes after some period of time - on second day after it was already synched.
```
/usr/local/bin/start: line 52:    28 Aborted                 (core dumped) graph-node --node-id "${node_id//-/_}" --postgres-url "$postgres_url" --ethereum-rpc $ethereum --ipfs "$ipfs"
```
<img width="1243" alt="Screenshot 2022-06-15 at 21 05 22" src="https://user-images.githubusercontent.com/88528265/173895074-c894f056-21e1-4356-bbcf-cd35e89ca64e.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Rewrite subgraph start block
2. Deploy subgraph
3. Follow the progress
4. Get the error after some period of time

**What is the expected behavior?**
Index node should continue to index subgraph

**Workaround**
We rolled-back to the graph-node `v.0.25.2` and it started to work - let's wait some days, because `v.0.26.0` also crashed only after some period of time. But at least it was able to start, unlike the latest version.

**Comment by azf20** [comment]
Hi - what OS are you running graph node on?

**Comment by air3ijai** [comment]
Hello, we are running in Kubernetes using [AWS EKS](https://aws.amazon.com/eks/) in US East (N. Virginia).
```
AMI ID: ami-02da89ddc4cc9ed18
AMI name: amazon-eks-node-1.22-v20220526
Source: amazon/amazon-eks-node-1.22-v20220526
Architecture: x86_64
Description: EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.22.6, docker: 20.10.13-2.amzn2, containerd: 1.4.13-2.amzn2.0.1)
```
[Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) is a Linux operating system from Amazon Web Services (AWS). It provides a security-focused, stable, and high-performance execution environment to develop and run cloud applications.

**Comment by leoyvens** [comment]
Check if you're not running out of memory or disk space.

**Comment by air3ijai** [comment]
During next 5 hours we saw more than 40 pod restarts.

Increased pod memory
```yaml
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 1000m
              memory: 2000Mi
```

And it started to work. Then we decreased resources slightly - `500/1500`. It at least started and continued to index. Let's see the progress.

Not clear why pod restarted if at the moment of restart we see < 200 MiB usage and limit is 1000 MiB
<img width="696" alt="Screenshot 2022-06-20 at 20 19 20" src="https://user-images.githubusercontent.com/88528265/174652384-4d4f1838-cf6d-4495-9234-f3d4691c9e16.png">
<img width="693" alt="Screenshot 2022-06-20 at 20 19 35" src="https://user-images.githubusercontent.com/88528265/174652390-a26d875e-fe3a-4365-b1f9-9ccea130ef40.png">

**Comment by air3ijai** [comment]
During last ~ 47 hours we have ~ 138 restarts and pod can't start with same error.

Increased CPU and Memory limits
```yaml
          resources:
            limits:
              cpu: 1500m
              memory: 2500Mi
            requests:
              cpu: 1500m
              memory: 2500Mi
```
It at least started and we can continue indexing, let's see the progress.

**Comment by air3ijai** [comment]
We notes just 1 restart during last `4d6h` and all looks good. So, the solution is to provide more resources to the container.

In our case, minimal working resources configuration is the following

**v.0.25.2**
```yaml
cpu: 500m
memory: 1000Mi
```

**v.0.26.0**
```yaml
cpu: 1500m
memory: 2500Mi
```

Let's consider this as a solution or maybe a workaround.

Is there any special requirements for `3 x CPU / 2.5 Memory` increase in the latest version?
