### ISSUE TITLE
Feature Request: Get results for timeseries data more efficient / block: {number_in: [] | number_gte: x number_lte: y}

### ISSUE THREAD

**Issue by froid1911** [graphprotocol/graph-node#3676]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Right now its only possible to filter results by number: #block or number_gte: #block.

**What is the expected behavior?**
It would be super helpful it would be possible to fetch intervals. Either through number_gte and number_lte or number_in: [1,2,3,4]

**Comment by azf20** [comment]
hey @froid1911 - would be great to hear a bit more about your use-case - what kind of timeseries data are you looking for? And have you also investigated creating dedicated timeseries entities in the subgraph?
