### ISSUE TITLE
How does chain provider selection work, depending on their features (archive, traces)?

### ISSUE THREAD

**Issue by jurgenwerk** [graphprotocol/graph-node#3695]
I'm looking to get some better understanding on the graph node behaviour when there are multiple providers with different capabilities, as described [here](https://github.com/graphprotocol/graph-node/blob/master/docs/config.md#configuring-ethereum-providers):

```
[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "vip"
provider = [
  { label = "mainnet1", url = "http://..", features = [], headers = { Authorization = "Bearer foo" } },
  { label = "mainnet2", url = "http://..", features = [ "archive", "traces" ] }
]
```

1. Is it correct to say that I can use an archive node for the "archive" and "traces" feature, and a full node for the "traces" feature?
2. Let's say I have 1 node with the archive + traces feature, and 1 node with the traces feature. How does the graph node decide which one to use? Can it be configured that it only uses the archive node when doing a rebuild/reindex, and then switch to the traces node when it's syncing next blocks?
3. Does the graph node offer some kind of failover when one of the providers stops working? 

Thanks!

**Comment by azf20** [comment]
hi @jurgenwerk! Good questions. I think @leoyvens can likely correct me on some of the details, but...
- Traces are actually slightly more specific than a full node, the `trace_filter` RPC is only supported on OpenEthereum & Erigon nodes
- Archive nodes are only required for eth_calls during indexing - an archive node is required for all eth_calls (whether or not the subgraph is at the chain head). There may be scope for optimisation there
- There is a general "strategy" whereby Graph Node will try and use the "cheapest" provider if there are multiple available (so it will use a full node over an archive node for finding historical events for example)
- If a given provider isn't working, it won't be used, but there isn't a smart failover in place to switch between providers. There are lots of retry strategies in place, depending on the error

**Comment by azf20** [comment]
Closing for now, please re-open if we can help further! (And indeed we could include some more of the above information in documentation)
