### ISSUE TITLE
TokenURI reverted for tokenID

### ISSUE THREAD

**Issue by vincentho312** [graphprotocol/graph-node#3698]
getTokenUri does not always returns value in graph-node, but always return value in thegraph.com hosted service
My code

`export function getTokenURI(event: Transfer): string {
  let erc721 = vrStays.bind(event.address)
  let tokenURICallResult = erc721.try_tokenURI(event.params.tokenId)

  let tokenURI = '';

  if (tokenURICallResult.reverted) {
    log.warning('tokenURI reverted for tokenID: {} contract: {}', [
      event.params.tokenId.toString(),
      event.address.toHexString()
    ])
  } else {
    tokenURI = tokenURICallResult.value
  }

  return tokenURI
}`

**Comment by azf20** [comment]
hi! please join the graphprotocol discord for help debugging specific subgraph issues!
