### ISSUE TITLE
Bug: Subgraph failed with non-deterministic error: Failed to transact block operations

### ISSUE THREAD

**Issue by sunny0714** [graphprotocol/graph-node#3708]
## NFT indexing subgraph(on Rinkeby) deployed on hosted service a month ago is not working now
The subgraph worked well for a month, but it suddenly stopped indexing

### Error Info on Subgraph Logs
https://thegraph.com/hosted-service/subgraph/sunny0714/madsubgraph?selected=logs
```
Subgraph failed with non-deterministic error: Failed to transact block operations: subgraph writer poisoned by previous error, retry_delay_s: 1800, attempt: 19
```

Please help me to fix this

**Comment by Cooker0910** [comment]
Hey, @sunny0714 
Did you solve  your problem?
I faced same problem

**Comment by Giri-Aayush** [comment]
I am facing the same error. any help?
