### ISSUE TITLE
Indexing error with no logs output

### ISSUE THREAD

**Issue by chenningg** [graphprotocol/graph-node#3709]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When publishing a subgraph onto the hosted service, the subgraph successfully syncs to about 50-55% with logs and 0 indexing errors, then abruptly fails with indexing_error. All logs are also wiped from the logs output so I have no idea where the error is.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Clone https://github.com/chenningg/subgraph-error
2. Deploy and index
3. Error appears randomly

**What is the expected behavior?**
Subgraph should sync fully and logs should be viewable.

**Comment by chenningg** [comment]
@azf20 Hi, the subgraph is deployed here: https://thegraph.com/hosted-service/subgraph/chenningg/token-transactions

The issue is that I'm provided with 0 logs to find out what the indexing error is, and thus am unsure of how to resolve the indexing error.

**Comment by azf20** [comment]
hi @chenningg - ok, yes it should show up in the `nonFatalErrors` field on the index node, sorry for the trouble - I commented about this issue here https://github.com/graphprotocol/graph-node/pull/3350#issuecomment-1181736408

**Comment by chenningg** [comment]
Thanks for tagging the other issue! Should I try redeploying to see if any error shows up or just leave it be for the moment?
