### ISSUE TITLE
Website Information Bug

### ISSUE THREAD

**Issue by Sm00g15** [graphprotocol/graph-node#374]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Text gets covered on squished screen size

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a chrome browser and make the window height about 1/2 to 2/3 of the screens height
![screen shot 2018-09-16 at 4 49 03 pm](https://user-images.githubusercontent.com/14209806/45593030-d1dc1e00-b9d0-11e8-9214-2c52bb952b17.jpg)

**What is the expected behavior?**
The text below "Getting Data Off Blockchains Is Hard" will be covered up

**Comment by Jannis** [comment]
@nenadjaja Could you look into this?

**Comment by nenadjaja** [comment]
Yep, I'll check it out
