### ISSUE TITLE
The current stable release (0.26.0) does not work with documented features

### ISSUE THREAD

**Issue by jurgenwerk** [graphprotocol/graph-node#3747]
I'm trying to deploy a subgraph using `specVersion 0.0.5` (so that I can use the the `receipt: true` feature) on a 0.26.0 graph-node and I'm getting the following error:

>✖ Failed to deploy to Graph node https://my-subgraph.com/: subgraph resolve error: resolve error: This Graph Node only supports manifest spec versions between 0.0.2 and 0.0.4, but subgraph `QmTD59KigFww9aCNHDDvwMh8g6HxLfv4hZMFzFahdi7HFb` uses `0.0.5`

I'm using:
```
"@graphprotocol/graph-cli": "0.32.0",
"@graphprotocol/graph-ts": "0.27.0"
```

I see there's a similar problem in the issue https://github.com/graphprotocol/graph-node/issues/3595 which suggests to use an unstable graph-node release to make this work.

I'm reluctant to deploy releases that are not considered stable to production environments. Are you planning on making a new release soon which supports [Transaction Receipts in Event Handlers](https://thegraph.com/docs/en/developing/creating-a-subgraph/#transaction-receipts-in-event-handlers)? Thanks!

**Comment by jurgenwerk** [comment]
Pinging @azf20, @tilacog - perhaps you have any comments regarding this issue? Thank you.

**Comment by tilacog** [comment]
@jurgenwerk could you please confirm what is the value of your `GRAPH_MAX_SPEC_VERSION` environment variable?

**Comment by jurgenwerk** [comment]
@tilacog It's not defined. 

```
[ec2-user@ip-10-81-1-4 /]$ docker exec e586b71e316d env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=e586b71e316d
POSTGRES_USER=graph-node
postgres_user=graph-node
POSTGRES_DB=graph-node
postgres_db=graph-node
postgres_host=postgres
ipfs=ipfs:5001
ethereum=poa-sokol:https://sokol-archive.blockscout.com
GRAPH_LOG=info
postgres_pass=...........
RUST_LOG=
EARLY_LOG_CHUNK_SIZE=
ETHEREUM_RPC_PARALLEL_REQUESTS=
ETHEREUM_BLOCK_CHUNK_SIZE=
node_role=combined-node
node_id=default
ethereum_polling_interval=
GRAPH_NODE_CONFIG=
disable_core_dumps=
HOME=/root
```

**Comment by azf20** [comment]
@tilacog this is the expected behaviour for 0.26.0, as it doesn't support specVersion 0.0.5, whatever environment variables you set - I think @jurgenwerk's question is when 0.27.0 will be released - this is in train with @evaporei, so should be released soon.

**Comment by jurgenwerk** [comment]
@azf20 @evaporei great, thanks! Looking very forward to 0.27.0, I hope it can happen soon.

**Comment by jurgenwerk** [comment]
Closing this as 0.27.0 was released and it fixes my problem.
