### ISSUE TITLE
Add Sepolia Testnet

### ISSUE THREAD

**Issue by pryderician** [graphprotocol/graph-node#3755]
**Since Ropsten, Rinkeby & Kiln Deprecated !**

Its Required to add new : **Sepolia Network** 

Network/Chain ID: 11155111
Genesis Hash: 0x25a5cc106..8993e6dd9
Consensus Engine: Proof of Stake
EVM Version: London
RPC : https://rpc.sepolia.dev

https://blog.ethereum.org/2022/06/21/testnet-deprecation/
https://sepolia.dev/

**Comment by 0xAlcibiades** [comment]
Is this complete yet?

**Comment by outdoteth** [comment]
Status on this?

**Comment by Masakore** [comment]
Any update?

**Comment by georgeciubotaru** [comment]
@azf20 What type of `We are working on it`? I cannot see the:
- corresponding label
- draft PR
If you guys don't see that as a priority, then just announce that, because it could already be done in 2 weeks.

**Comment by oddaf** [comment]
Sers, 

Goerli is no longer a testnet, Sepolia support is sorely needed. Can devs do something?

**Comment by smak0v** [comment]
Hey!

How long should we wait to see at least a draft or something working?

We are waiting almost one year to see the Sepolia network support.

**Comment by azf20** [comment]
Sepolia is now supported https://github.com/graphprotocol/graph-tooling/pull/1275
