### ISSUE TITLE
Error on `block_gte` for blocks before the start block

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3761]
https://github.com/graphprotocol/graph-node/pull/3673 introduced a change where the graphQL API would error for blocks before the start block.

This makes sense for filtering by block `number` ([example](https://api.thegraph.com/subgraphs/name/bacon-labs/eighty-eight-mph-v3-polygon/graphql?query=%7B%0A++dpools%28%0A++++++++block%3A+%7B%0A++++++++++number%3A123%0A++++++++%7D%0A++++++%29+%7B%0A++++++++address%0A++++++++stablecoin%0A++++++++totalDeposit%0A++++++%7D%0A%7D%0A+%0A))
But filtering by `number_gte` should return the latest data ([example](https://api.thegraph.com/subgraphs/name/bacon-labs/eighty-eight-mph-v3-polygon/graphql?query=%7B%0A++dpools%28%0A++++++++block%3A+%7B%0A++++++++++number_gte%3A123%0A++++++++%7D%0A++++++%29+%7B%0A++++++++address%0A++++++++stablecoin%0A++++++++totalDeposit%0A++++++%7D%0A%7D%0A+%0A))

**Comment by azf20** [comment]
Users have also expressed a preference to be able to query for blocks before the startBlock (previously it returned `null`), but this might not make sense with the change from #3673 @lutter

**Comment by azf20** [comment]
Users have also expressed a preference to be able to query for blocks before the startBlock (previously it returned `null`), but this might not make sense with the change from #3673 @lutter

**Comment by lutter** [comment]
Yes, we should not allow querying for `block { number }` before the start block. `number_gte` though should be made to work even with block `0`
