### ISSUE TITLE
0.27.0 DB Migration Issues

### ISSUE THREAD

**Issue by datanexus-vincent** [graphprotocol/graph-node#3804]
**Do you want to request a *feature* or report a *bug*?** 

Bug

**What is the current behavior?**

After upgrading to 0.27.0, at least one of the subgraphs I was indexing had a store error.

`{"graphQLResponse":"{\"errors\":[{\"message\":\"Store error: store error: Unrecognized enum variant: '\\u0000\\u0000\\u0000\\u0000'\"}]}"}`

I tried rewinding to fix the issue, but got the following response:

```
Pausing deployments
error: store error: Unrecognized enum variant: ' '
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Upgrade from 0.25.2 to 0.27.0 while indexing `QmRRCsJpnPzWo8CZroC619MLJ7an2XKML63Qxik2VxgGQ9`. It's a small/quick subgraph if you'd like to test upgrading while indexing. Otherwise, let me know what data you'd like from my machine to help debug.

**What is the expected behavior?**

Migrations run successfully and subgraph continues indexing.

**Comment by azf20** [comment]
Thanks @datanexus-vincent - I wonder if there was also something in the 0.25.2 -> 0.26.0 changes which might be playing a part here.. was there a reason you hadn't upgraded to 0.26.0 previously? cc @evaporei

**Comment by azf20** [comment]
hi - following up on this one @datanexus-vincent as we are looking to promote the release soon - were you able to reproduce this, and do you have any indication if it's an issue with 0.26.0?

**Comment by datanexus-vincent** [comment]
Sorry, missed the reply last week. I only upgraded from 0.25.2 because I had forgotten to upgrade my testnet setup to 0.26.0 last month. I just went through and rebuilt my testnet setup on 0.26.0, re-synced the subgraph I had issues upgrading with, and upgraded to 0.27.0 with no issues. I believe it was an issue exclusively for upgrading from 0.25.2 -> 0.27.0.

**Comment by evaporei** [comment]
Hello @datanexus-vincent sorry for the delay, how did you get the error `{"graphQLResponse":"{\"errors\":[{\"message\":\"Store error: store error: Unrecognized enum variant: '\\u0000\\u0000\\u0000\\u0000'\"}]}"}` exactly?

I tried indexing this subgraph `QmRRCsJpnPzWo8CZroC619MLJ7an2XKML63Qxik2VxgGQ9` for a bit in `0.25.2` and then did the upgrade to `0.27.0` with no issues whatsoever.

I also did a simple query to the local node and it worked fine `{ tokens { id } }` (result: `{ "data": { "tokens": [ { "id": "1" }, ... ] } }`).

**Comment by leoyvens** [comment]
This can happen if you have a old graph node running against a DB that has been migrated to 0.27, for example if you have multiple nodes running against the same DB but only one was updated.

**Comment by datanexus-vincent** [comment]
Hey @evaporei. That error occurred for every query on that subgraph after upgrading. Unfortunately though, I'm not sure I'll be able to help much more with this issue. I wasn't keeping my testnet setup in the best condition when I upgraded, I've since deleted the corrupted database / rebuilt my testnet setup, and I'm unable to replicate my issue again by syncing on 0.25.2 then upgrading to 0.27.0. Hopefully that means my original issue was a very unlikely bug that only occurred for my specific upgrade path going back multiple upgrades. I'll be more prepared to test, troubleshoot, and report bugs for future updates once I am working with our more permanent server deployment, which should be very soon.

**Comment by datanexus-vincent** [comment]
> This can happen if you have a old graph node running against a DB that has been migrated to 0.27, for example if you have multiple nodes running against the same DB but only one was updated.

Hmm, this could be the culprit, but I'm not entirely sure. I'm pretty certain I upgraded my query node at the same time, but there's a chance I could've forgotten to restart the query node resulting in this error. Like I just mentioned our testnet procedures will be seeing an overhaul soon, so I'll be more prepared to give you all better feedback for the next release.
