### ISSUE TITLE
modifying `immutable` entities does not result in the indexing error

### ISSUE THREAD

**Issue by rkrasiuk** [graphprotocol/graph-node#3808]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Modifying `immutable` entities does not result in the indexing error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Sample subgraph is deployed on the hosted service:
https://thegraph.com/hosted-service/subgraph/rkrasiuk/oasis-notifications-test

**What is the expected behavior?**
According to [this article](https://medium.com/edge-node-engineering/two-simple-subgraph-performance-improvements-a76c6b3e7eac) any modifications to entities with immutable tag should result in the indexing error

**Comment by azf20** [comment]
Hi @rkrasiuk - are you able to share the source code? (deployed subgraphs are compiled, so we can't check the mappings)

**Comment by rkrasiuk** [comment]
hey @azf20, i've just pushed the minified version to [subgraph-immutable-sample](https://github.com/rkrasiuk/subgraph-immutable-sample) and redeployed the subgraph

**Comment by azf20** [comment]
When I look at the [deployed subgraph](https://thegraph.com/hosted-service/subgraph/rkrasiuk/oasis-notifications-test), it looks like it did indeed fail?

```
Failed to transact block operations: internal constraint violated: entities of type `Urn` can not be updated since they are immutable. Entity ids are [0x953762f10b7f039ba5aca9c1fd72a26110ea8599]
```

**Comment by rkrasiuk** [comment]
@azf20 sorry, for not giving an update. i did see that it indeed failed, however afaik it failed couple of minutes after the first such update occurred, but maybe it was just because the check is done after processing some batch. anyway, closing the issue. thanks!
