### ISSUE TITLE
Loading data from IPFS inside mapping.ts times-out immediately

### ISSUE THREAD

**Issue by tarrencev** [graphprotocol/graph-node#383]
**What is the current behavior?**

When doing an `ipfs.cat("/ipfs/Qm...")` inside a mapping.ts it seems the connection to IPFS is timing out immediately, it throws the following:
```
  Sep 18 11:54:56.003 DEBG   Call event handler, signature: RegistryEntryEvent(address,bytes32,uint256,bytes), name: handleMemberRegistryEntryEvent
  Sep 18 11:54:56.004 WARN Failed to handle Ethereum event, error: Trap: Trap { kind: Host(HostExternalsError("timer is shutdown")) }, handler: handleMemberRegistryEntryEvent
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Perform `ipfs.cat("/ipfs/Qm...")` inside a mapping.

**What is the expected behavior?**

IPFS connection does not immediately timeout and data is properly loaded if possible.

**Comment by tarrencev** [comment]
@leodasvacas no problem! Is there a short term fix I can apply until it is properly resolved? i.e. reverting the ipfs timeout?

**Comment by leodasvacas** [comment]
@tarrencev Yes, to workaround you can remove this line
https://github.com/graphprotocol/graph-node/blob/8acbb44f045ab72652430409218943838f52b774/graph/src/components/link_resolver.rs#L30
and the error should not happen.

**Comment by tarrencev** [comment]
@leodasvacas hmm in that case I get the following error:
```
  Sep 18 15:39:54.435 DEBG   Call event handler, signature: RegistryEntryEvent(address,bytes32,uint256,bytes), name: handleMemberRegistryEntryEvent
  Sep 18 15:39:54.437 WARN Failed to handle Ethereum event, error: Trap: Trap { kind: Host(HostExternalsError("hyper client error \'executor failed to spawn task\'")) }, handler: handleMemberRegistryEntryEvent
```

**Comment by tarrencev** [comment]
@leodasvacas no problem! Thanks for taking a look!
