### ISSUE TITLE
Aurora Hosted Service: Failing to get transaction

### ISSUE THREAD

**Issue by dmelotik** [graphprotocol/graph-node#3835]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?** 
There seems to be an indeterministic bug where transactions are sometimes "not found" on aurora subgraphs. I have had conversation in the graph discord, and it seems to be random as a redeploy of the same build will fix the issue some of the time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?** 
This has occured with our `aurigami-aurora` subgraph. You can deploy by going into https://github.com/messari/subgraphs/tree/master/subgraphs/compound-forks and running the following commands:

```
npm install
npm run deploy --SUBGRAPH=compound-forks --PROTOCOL=rari-fuse --LOCATION=[github username]
```
> Note: you must add your hosted service endpoint to https://github.com/messari/subgraphs/blob/master/deployment/deployment.json#L215

Here are links to the conversations had on the graph discord:
- https://discord.com/channels/438038660412342282/791444347823980604/977860542855258153
- https://discord.com/channels/438038660412342282/791444347823980604/998599297375424583

**Comment by azf20** [comment]
Hi! This is a provider issue, rather than a Graph Node issue - essentially the Aurora provider is providing non-deterministic data here. They are working on a fix which should hopefully be available later this week

**Comment by dmelotik** [comment]
Fixed with new aurora rpc
