### ISSUE TITLE
Network not supported by registrar: no network near-testnet found on chain near

### ISSUE THREAD

**Issue by HolidayMan** [graphprotocol/graph-node#3838]
**Bug when trying to deploy near-testnet subgraph. **

About 2-3 days ago the following strangeness appeared and still exists: 
<img width="249" alt="изображение" src="https://user-images.githubusercontent.com/37782099/184511938-f7d4cfc4-c78f-4d6e-923f-71b95fd03e43.png">

Last deploy was 3 days ago, everything was good. But today happened the following:
<img width="1186" alt="изображение" src="https://user-images.githubusercontent.com/37782099/184511972-d524ddd0-7719-48f7-ac13-1a9171f182f6.png">

It's very strange, as I expected support of deploying subgraphs to Hosted service untill the Q4. I am not creating new subgraph, so everything must go OK, but it doesn't( 

Here's my question: is it an early halt of deploying subgraphs for Near, or just a bug?

If necessary, here's the repo of subgraph: https://github.com/NFT-Hockey/marketplace-indexer-subgraph

**Comment by Vietdung113** [comment]
Do you have any updates?
I got the same problems here.

**Comment by HolidayMan** [comment]
> Do you have any updates? I got the same problems here.

No, still the same( I'm considering about deploying my own node... Will write here about all underwater rocks if I'll do the one

**Comment by azf20** [comment]
Hi! Sorry for the delay here, this was a bug which has now been resolved. Please let us know in Discord if you continue having issues with near-testnet deployments.
