### ISSUE TITLE
[WANT HELP] How the Deployment ID is generated?

### ISSUE THREAD

**Issue by jwrookie** [graphprotocol/graph-node#3843]

**Comment by maoueh** [comment]
Subgraph manifest is fully resolved, this means finding each and every local file and uploading them to IPFS. For each of the uploaded file extracted from your original manifest, the original link in the document is replaced by something like `/ipfs:<hash>` (I don't recall the exact format) where `<hash>` is the hash of the files uploaded and computed by IPFS client.

Then, once you have this final resolved file where are local files link have been replaced by resolved IPFS hashes, you upload again this final file to IPFS and the hash of this resolved file is the deployment ID `Qm....`
