### ISSUE TITLE
Graph mainnet see when monitoring grafana its show some Subgraph working fine  but some subgraph get  error can  anyone tell us why facing such issue ?

### ISSUE THREAD

**Issue by rajeshbadak1** [graphprotocol/graph-node#3875]
Critical error logged in mapping wasm backtrace: 0: 0x2724 - <unknown>!src/generated/schema/Release#set:fundDeployer 1: 0x2826 - <unknown>!src/entities/Release/ensureRelease 2: 02c37 - <unknown>!~lib/@graphprotocol/graph-ts/index/Entity#unset 3: 0x3043 - <unknown>!src/generated/DispatcherContract/MigrationCancelled__Params#get:nextFundDeployer 

Mapping aborted at generated/schema.ts, line 589, column 4, with message: Cannot save Vault entity without an ID wasm backtrace: 0: 0x1c60 - <unknown>!<wasm function 80> 1: 0x28e9 - <unknown>!<wasm function 115> in handler `handleShortOtokenMinted` at block #12730209 (452d52495bb0e26bddse5912b537727b1be95b0170dc85544f8d785aed3fef720)

Mapping aborted at generated/schema.ts, line 589, column 4, with message: Cannot save Vault entity without an ID wasm backtrace: 0: 0x1c6d0 - <unknown>!<wasm function 80> 1: 0x1dd5 - <unknown>!<wasm function 90> 

Mapping aborted at generated/schema.ts, line 589, column 4, with message: Cannot save Vault entity without an ID wasm backtrace: 0: 0x1ce60 - <unknown>!<wasm function 80> 1: 0x28e9 - <unknown>!<wasm function 115> 

failed to process trigger: block #13468099 (0x3393…89c0), transaction ee9aaf59819efc11375abe3c5ed0953597ef4daf805b4c0379bc4343ffdd232d155: Entity SavingsManager[0x9781c4e9b9cc6a343rr5891df20ad3566fb6b301]: missing value for non-nullable field `address` wasm backtrace: 0: 0x1e12 - <unknown>!src/mappings/SavingsManager/updateSavingsManager 1: 0x350f - <unknown>!generated/SavingsManager/SavingsManager/LiquidatorDeposited__Params#get:amount

**Comment by jessepinkman9900** [comment]
any progress on this issue?

**Comment by rajeshbadak1** [comment]
Yes

**Comment by rajeshbadak1** [comment]
Yes its Resolve

**Comment by jessepinkman9900** [comment]
what was the solution?
