### ISSUE TITLE
 Wrong event order on same block from Aave clone V2 on Godwoken chain

### ISSUE THREAD

**Issue by Roger-RumbleFish** [graphprotocol/graph-node#3878]
Here is my subgraph repo -> https://github.com/Roger-RumbleFish/Subgraph-test

the issue is between `createOrLoadReserve` and `CollateralConfigurationChangedHandler`

they should be called in order 
1. createOrLoadReserve (all 6 tokens)
2. CollateralConfigurationChangedHandler (all 6 tokens)

Unfortunately some of the events are called not in correct order.  Because my events are depend on each other i have null values for wBTC reserve 

![image](https://user-images.githubusercontent.com/82821191/186887740-571ea353-e716-41bb-96e1-3f4475dfa7e4.png)

the problem is between blocks  72543 -> 72544   when i deployed the contracts 

When i make getLogs call i get them in correct order 

![image (9)](https://user-images.githubusercontent.com/82821191/186888171-703d3fe3-f6e6-4f5b-a59e-a8ef051e24c3.png)

if you need the rpc for godwoken mainnet here it is -> https://v1.mainnet.godwoken.io/rpc

to run it 
1.  `yarn`
4. `docker-compose up`
5. `yarn rebuild`

**Comment by azf20** [comment]
Hi - it is not clear to me that there is an ordering issue here, indeed I think there shouldn't be. Can you provide Graph Node logs to clarify the exact order of execution? [You can add logging to help with debugging](https://thegraph.com/docs/en/developing/assemblyscript-api/#logging-api)

**Comment by Flouse** [comment]
Hi, @Roger-RumbleFish 
Thanks for the bug report.
It was a bug in Godwoken web3-indexer which was fixed.

## PR
[Log's index should index in a block, not transaction]
- https://github.com/godwokenrises/godwoken-web3/pull/553)

## Releases
- https://github.com/godwokenrises/godwoken-info/pull/69
- https://github.com/godwokenrises/godwoken-web3/releases/tag/v1.8.5 (Godwoken testnet_v1)
- https://github.com/godwokenrises/godwoken-web3/releases/tag/v1.7.4 (Godwoken mainnet_v1)

**Comment by azf20** [comment]
Thanks!
