### ISSUE TITLE
Postgres password not optional in Ubuntu

### ISSUE THREAD

**Issue by wip-abramson** [graphprotocol/graph-node#388]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Readme states that a postgres PASSWORD is optional when spinning up a local graph-node.
  --postgres-url postgresql://USERNAME[:PASSWORD]@localhost:5432/adchain-subgraph \

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
On ubuntu 18.04 follow the Readme steps for running a local graph node. I got an authentication failed error when running the final step because password was incorrect.

**Fix**
Set up a username and password for the database ie adchain-subgraph. Then use these to connect to the database.
http://suite.opengeo.org/docs/latest/dataadmin/pgGettingStarted/firstconnect.html

**Comment by davekaj** [comment]
Thanks! It appears that the password is only optional if you have no password set for postgres. If you have a password it must be used. I will update the docs to show this. Being tracked in #433
