### ISSUE TITLE
Add Support For Candle Chain

### ISSUE THREAD

**Issue by samisbakedham** [graphprotocol/graph-node#3880]
**Do you want to request a *feature* or report a *bug*?**
Requesting a feature.
**What is the current behavior?**
TheGraph supports many EVM-compatible networks, just not Candle yet.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
To be able to use thegraph's services with Candle!
[Website](https://rpc.cndlchain.com)
RPC: https://rpc.cndlchain.com
Chain ID: 534

**Comment by azf20** [comment]
Hi! You can [run a Graph Node](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml) configured with your Candle RPC endpoint

**Comment by samisbakedham** [comment]
> Hi! You can [run a Graph Node](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml) configured with your Candle RPC endpoint

Hi! We currently are. However, how do we add native support for it?
