### ISSUE TITLE
Today Facing again some Following Error in subgraph 

### ISSUE THREAD

**Issue by rajeshbadak1** [graphprotocol/graph-node#3882]
Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 439, column 6, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_getRoundInfo` to handle this in the mapping. wasm backtrace: 0: 0x22a3 - <unknown>!generated/ProofOfHumanity/ProofOfHumanity/ProofOfHumanity__arbitratorDataListResult#constructor 1: 0x4347 - <unknown>!generated/ProofOfHumanity/ProofOfHumanity/ProofOfHumanity#getContributions 2: 0x4507 - <unknown>!src/mapping/requestStatusChange 3: 0x48c4 - <unknown>!src/mapping/addSubmission 4: 0x4988 - <unknown>!src/mapping/reapplySubmission in handler `addSubmission` at block #14892895 (f982d6c844c1e3a4c0132efe28454deb78e1969d0af26a7cf627e968ad20e685)

Error while processing block stream for a subgraph: subgraph `QmeTuu1DGmRL4AChBG7HsRsaia5HdSS5GQRtmCNag56H6W` has already processed block `12365620`; there are most likely two (or more) nodes indexing this subgraph

**Comment by azf20** [comment]
hey @rajeshbadak1 if this is still valid, please provide a bit more context about the situation and reopen
