### ISSUE TITLE
Retry web3 requests

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#389]
We need some way to handle transient web3 errors (from connection flakiness or temporary issues on the Ethereum node).

Proposed solution: a generic future-friendly retry mechanism, possibly integrated into the web3 Transport. We might need to contribute some code to the rust-web3 repo to make this possible.

**Comment by Jannis** [comment]
Before we tackle this, let's check if there isn't a retry future crate out there that we can leverage.

**Comment by Jannis** [comment]
https://github.com/srijs/rust-tokio-retry might be a candidate.
