### ISSUE TITLE
How can I use `graphman` to delete subgraph

### ISSUE THREAD

**Issue by bijianing97** [graphprotocol/graph-node#3894]
I'm running a local node by build raw code, I want to delete some subgraph and stroe in the postgres. After saw some issues committed by others , I konw the `graphman` command, but I can't find any document about where and how to use it, I can not find the entrance.
Could someone help me, thanks!

**Comment by neysofu** [comment]
Hi @bijianing97! You can use `graphman --config <CONFIG> drop [OPTIONS] <DEPLOYMENT>`. `graphman --help` is quite helpful, when you can't figure out how to do something.

**Comment by neysofu** [comment]
Is this helpful? If so, feel free to close this issue.

**Comment by azf20** [comment]
Thanks both, closing now!
