### ISSUE TITLE
Add Store method to transact multiple entity operations at once against a block stream

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#390]
This function would have the following signature:
```rust
pub trait Store {
    fn transact_against_block_stream(
        &mut self,
        operations: Vec<EntityOperation>,
        block_stream_info: BlockStreamInfo,
        block_stream_ptr: EthereumBlockPointer,
  ) -> Result<(), failure::Error>;
}
```

It does the following:

1. It rolls up all entity operations for an entity into a single operation:
    a. Merge set operations into one
    b. If the last operation for an entity is remove, discard all previous sets

It then goes to Postgres and does the following in a single transaction:

1. Apply all entity operations, one by one
  - for set operations, get the current entity and apply the attribute changes so that `null` values remove the attribute and all other values overwrite old attribute values
  - for remove operations, just delete the entity
2. Update the block stream pointer in the block stream table to the new block stream pointer (block hash + block number).

**Comment by Jannis** [comment]
Base the work on the feature/block-stream branch for now.

The `EntityOperation` type is [defined here](https://github.com/graphprotocol/graph-node/blob/feature/block-stream/graph/src/components/store.rs#L110).

**Comment by Jannis** [comment]
We'll merge the prerequisites for this (`EntityOperation`, `EthereumBlockPointer`, `BlockStreamInfo` and subgraph table migrations) before we'll start working on this.

**Comment by timmclean** [comment]
@fordN looks like this is actually going happen on master not the feature/block-stream branch
