### ISSUE TITLE
Fantom transaction returns incorrect result if reverted

### ISSUE THREAD

**Issue by harsh9200** [graphprotocol/graph-node#3900]
**Do you want to request a *feature* or report a *bug*?**
A Bug
**What is the current behavior?**
Deployment Error

If a transaction contains a function-scoped revert, trace_transaction fails to calculate the output of the subtraces after the revert that are part of the same transaction. It also seems to be setting gasUsed to 0 for all traces after the revert. This issue applies to the other tracing calls as well.

```
A non-deterministic fatal error occured at block 39182535: failed to process trigger: block #39182535 (0x0001…cd8b), transaction 385e9720b1004a0f8cbcbd98e8eb605c1377a9abee6de8e74b0742388d93312b: Decoding function outputs for the call Function { name: "deposit", inputs: [Param { name: "_amount", kind: Uint(256), internal_type: None }], outputs: [Param { name: "", kind: Uint(256), internal_type: None }], constant: None, state_mutability: NonPayable } failed, raw output: : Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist
```

Deployment URL: https://thegraph.com/hosted-service/subgraph/messari/yearn-v2-fantom?version=pending

**Comment by this-username-is-taken** [comment]
reference: https://github.com/messari/subgraphs/issues/142

**Comment by azf20** [comment]
Hi! Checking on this, it looks there is a linked issue (https://github.com/Fantom-foundation/go-opera/issues/288) which suggests this is a fantom issue, rather than a Graph Node issue?

**Comment by this-username-is-taken** [comment]
I think you are right. We filed another issue with them to track here: https://github.com/Fantom-foundation/go-opera/issues/364. Will close this one
