### ISSUE TITLE
Hosted Service Subgraph Not Returning All Records

### ISSUE THREAD

**Issue by 0xrin1** [graphprotocol/graph-node#3914]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
not all records are returned

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a counting entity.
Then create another entity that increments id whenever a new event occurs, and update the counting entity accordingly.
Make ~200 records.
Make a call to get all the created records.
Notice that not 200 records are returned, a good chunk of them are missing.

**What is the expected behavior?**
have all records returned when making an API call to the hosted service subgraph

Please let me know if this is just user error

**Comment by azf20** [comment]
Hi - can you provide a more specific example, including the query you are making?

**Comment by 0xrin1** [comment]
Sure!

Can't really share the backend because it's a private repo

But i have a feeling that it's the query because the counter goes way up and the query records records that seem to skip specific ID numbers. Makes me feel that they just aren't returned with the query

```
{
  liquidations() {
    id
  }
}
```

**Comment by azf20** [comment]
By default only 100 records are returned, update to:
```
{
  liquidations(first:1000) { id }
}
```
