### ISSUE TITLE
Mainnet subgraph failed, with required capabilities: : A matching Ethereum network with NodeCapabilities { archive: false, traces: false } was not found.

### ISSUE THREAD

**Issue by rok4f** [graphprotocol/graph-node#3915]
A bug.

I try to deploy a subgraph to Mainnet [mpmain](https://thegraph.com/studio/subgraph/mpmain/) and face this error:

Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmV4H49cp81n36EcHcEgKn1AMaie2LoTxu2vs1fm6UXRus[396313] with required capabilities: : A matching Ethereum network with NodeCapabilities { archive: false, traces: false } was not found.

When I deploy this subgraph to Rinkeby [metapoker](https://thegraph.com/studio/subgraph/metapoker/) everything works fine.

**Comment by rok4f** [comment]
Additional info, if I delete the following event handle, the error is gone:

        - event: NftOverridden(indexed uint256,indexed address,indexed uint256)
          handler: handleNftOverridden

**Comment by yohanelly95** [comment]
I just got this issue as well, not sure why. Any ideas around this? I feel this could be an RPC issue.

**Comment by azf20** [comment]
Hi - what network are you indexing and where are you deploying?

**Comment by shubham-rathod1** [comment]
I am facing the same issue but with the Mumbai network because of callHandlers in my case.

**Comment by Madalosso** [comment]
I found this issue looking for a solution but later I realized that it was a simple missed `graph codegen` before build/deploy. Rookie mistake in my case.
