### ISSUE TITLE
[How to deploy an instance of graph node to vercel, heroku or aws instance]

### ISSUE THREAD

**Issue by sanchitdawarsd** [graphprotocol/graph-node#3916]
Pls help me deploy the instance of graph-node to an endpoint so i can deploy my subgraph, i am able to run it on localhost but how can i have a server which run in background and query the data???

Pls Help

**Comment by azf20** [comment]
Hi - what network are you indexing? [You may be able to use The Graph Network or the Hosted service](https://thegraph.com/docs/en/developing/supported-networks/).
Alternatively you can just run Graph Node on a persistent machine with ports exposed appropriately (some docs [here](https://thegraph.com/docs/en/network/indexing/#graph-node-2))
You can find more support in [Discord](https://discord.com/invite/vtvv7FP), closing this issue
