### ISSUE TITLE
Correct value of `BLOCK_INGESTOR` has changed

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#3936]
PR #3688 changes how the value of the `BLOCK_INGESTOR` variable has to be set by moving mangling of the `node_id` to much earlier in the execution of the `start` script. Before that PR, `BLOCK_INGESTOR` had to be set to the unmangled name, e.g., `index-node-block-ingestor-0`. After the PR, and if name mangling is turned on (the default), it has to be set to the mangled name (`index_node_block_..`)

That behavior was always a bit weird, and we should discuss what the right way to address that is. One option, of course, is to change the `start` script to restore the old behavior.

**Comment by azf20** [comment]
@lutter is this blocked by an agreement on the right solution?

**Comment by azf20** [comment]
@lutter will this potentially break indexer setups if we don't fix before the next release?
