### ISSUE TITLE
Start Graph fail with BSC RPC

### ISSUE THREAD

**Issue by vincentho312** [graphprotocol/graph-node#3945]
I was setup my graph-node to query from BSC Mainnet with RPC: `bsc:https://bsc-dataseed1.binance.org/`

But when I start graph-node by docker-compose what emitted an error:

WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #12) with result Err(Decoder error: Error("invalid type: number, expected a (both 0x-prefixed or not) hex string with length between (0; 64]", line: 0, column: 0)), provider: bsc-rpc-0

I was trying to change other RPC (public and private) but also. This problem only happens with BSC because I still use aurora what work well

Please help me

**Comment by azf20** [comment]
Hi @vincentho312 are you still having this issue? That suggests there is an issue on the BSC node side. Please ping if this is still ongoing
