### ISSUE TITLE
File data sources: support files in IPFS directories

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#3948]
IPFS file data sources based on files in directories (e.g. https://ipfs.io/ipfs/QmaXzZhcYnsisuue5WRdQDH6FDvqkLQX1NckLqBYeYYEfm/1.json) fail with the following error:
```
        "fatalError": {
          "message": "Failed to parse multihash",
        }
```

Example mapping:
```
token.tokenURI = "/" + event.params.tokenId.toString() + ".json";
token.ipfsURI = ipfshash + token.tokenURI;
TokenMetadataTemplate.create(token.ipfsURI);
```
File data sources should be able to reference these kind of files as well as a CID

**Comment by leoyvens** [comment]
Done!
