### ISSUE TITLE
`subgraph_create` json rpc request doesn't work anymoer

### ISSUE THREAD

**Issue by Eduard-Voiculescu** [graphprotocol/graph-node#3965]
Prior to commit: b212bc42b10f8abd0aaa99f3233e6148a01e45f5, I was able to run 
```bash
curl -H "Content-Type: application/json" -d "{\"id\":\"2.0\",\"method\":\"subgraph_create\",\"params\":{\"name\":\"QmbToZtp6FHLJPrd62xS348q1Y5xJ86ALRo9zCLx83yY2d\"}}" http://127.0.0.1:8020
```

but after the above commit, I get this error message:
```bash
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":"2.0"}
```

**Comment by neysofu** [comment]
You request object lacks a `"jsonrpc": 2.0` key value (there's an `id`, but they are different things). The new library may simply be more through when checking if the request is valid. Could you please try again with a standard-compliant request and see if it works?

https://www.jsonrpc.org/specification#request_object

**Comment by Eduard-Voiculescu** [comment]
Nice, adding the `jsonrpc` field works like a charm. Thanks!
