### ISSUE TITLE
How to deploy incrementally

### ISSUE THREAD

**Issue by XdpCs** [graphprotocol/graph-node#3967]
I want to request a feature.
When I deploy a subgraph, I will traverse all blocks.
How to deploy incrementally

**Comment by azf20** [comment]
hi @XdpCS , not sure what you mean `how to deploy incrementally` - you only want to index a limited block range?

**Comment by XdpCS** [comment]
Hi @azf20.When I deploy a new contract, I don't want to deploy a new subgraph because the old contract information in the graphql will disappear within a certain period.
