### ISSUE TITLE
Hosted Service returning 504 on deploy attempt, Arbitrum Rinkeby

### ISSUE THREAD

**Issue by greenlucid** [graphprotocol/graph-node#3969]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When deploying the graph, everything seems to work properly, until the final deploy step. A `HTTP error deploying the subgraph 504` is returned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. clone https://github.com/kleros/gtcr-subgraph
2. `nvm install 12` *or whatever equivalent to change to Node v12*
3. `yarn install`
4. `node render-templates.js "arbitrum-rinkeby"`
5. `npx graph codegen`
6. `yarn fix-schema.ts`
7. `npx graph build`
8. `npx graph auth --product hosted-service {key}`
9. `npx graph deploy --product hosted-service greenlucid/curate-arbitrum-rinkeby`

This last step fails. In the deploy, everything works successfully (migrations, compile, subgraph files, upload everything to IPFS), but then the final deployment returns:
`✖ HTTP error deploying the subgraph 504`

**What is the expected behavior?**

The subgraph to be deployed at the end.

---

Other notes: I tried repeating this process with `specVersion 0.0.4` and adding as `features` the `ipfsOnEthereumContracts` and `fullTextSearch`, but same error occurs.

**Comment by jaybuidl** [comment]
A colleague has separately bumped into the same issue for a different subgraph, also on Arbitrum Rinkeby.

**Comment by greenlucid** [comment]
We were told on an alternative communication channel that The Graph deprecated Arbitrum Rinkeby from the Hosted Network without notice, so that's why.
