### ISSUE TITLE
The `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE ` env is not respected

### ISSUE THREAD

**Issue by rkrasiuk** [graphprotocol/graph-node#3998]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
we are running a hosted graph node and i've got hard time debugging the switching mode behavior. as per the docs, we've set the `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE` env to `synced` on the index node, however, given that the current version of the subgraph is synced, the new deployment never becomes pending, it simply overwrites and becomes the current version

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a

**What is the expected behavior?**
The new subgraph deployment becomes a pending version instead of the current one

Logs on new deployment
```
Sep 26 10:17:47.635 DEBG Deployment assignee is this node, broadcasting add event, node_id: index_node, assigned_to: index_node, component: SubgraphRegistrar

Sep 26 10:17:47.635 DEBG Received assignment event: Add { deployment: DeploymentLocator { id: DeploymentId(18), hash: DeploymentHash("QmbFKmnstP8jsp8bwob7p5GSf5yi87tTNtsQCPgoFM9t9e") }, node_id: NodeId("index_node") }, component: SubgraphRegistrar

Sep 26 10:17:48.179 DEBG Subgraph started, start_ms: 544, sgd: 18, subgraph_id: QmbFKmnstP8jsp8bwob7p5GSf5yi87tTNtsQCPgoFM9t9e, component: SubgraphRegistrar

Sep 26 10:17:48.182 DEBG Received assignment event: Remove { deployment: DeploymentLocator { id: DeploymentId(17), hash: DeploymentHash("Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7") }, node_id: NodeId("index_node") }, component: SubgraphRegistrar

Sep 26 10:17:48.182 INFO Stop subgraph, sgd: 17, subgraph_id: Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7, component: SubgraphInstanceManager

Sep 26 10:17:48.183 DEBG Subgraph block stream shut down cleanly, sgd: 17, subgraph_id: Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7, component: SubgraphInstanceManager

Sep 26 10:17:48.185 INFO Stopping subgraph, sgd: 17, subgraph_id: Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7, component: SubgraphInstanceManager

Sep 26 10:17:48.186 DEBG Subgraph stopped, WASM runtime thread terminated, sgd: 17, subgraph_id: Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7, component: SubgraphInstanceManager

Sep 26 10:17:48.186 DEBG Subgraph stopped, WASM runtime thread terminated, sgd: 17, subgraph_id: Qmd9A2BbBESQmcqP7HURtF3k4DimNdY62ZjEZLoKjy9na7, component: SubgraphInstanceManager

Sep 26 10:17:48.208 INFO Starting subgraph writer, queue_size: 5, sgd: 18, subgraph_id: QmbFKmnstP8jsp8bwob7p5GSf5yi87tTNtsQCPgoFM9t9e, component: SubgraphInstanceManager

Sep 26 10:17:48.265 INFO Resolve subgraph files using IPFS, sgd: 18, subgraph_id: QmbFKmnstP8jsp8bwob7p5GSf5yi87tTNtsQCPgoFM9t9e, component: SubgraphInstanceManager

Sep 26 10:17:48.265 DEBG Features {}, sgd: 18, subgraph_id: QmbFKmnstP8jsp8bwob7p5GSf5yi87tTNtsQCPgoFM9t9e, component: SubgraphInstanceManager
```

**Comment by azf20** [comment]
Hi @rkrasiuk can you share your exact Graph Node config?

**Comment by azf20** [comment]
Hi - it looks like those `env` variables are being parsed somehow, are you using some kind of orchestration tooling for your Graph Node?

**Comment by azf20** [comment]
@mangas wondered if you had any pointers here on passing in the environment variable with that helm chart setup?

**Comment by mangas** [comment]
@nickkounz if you could post your values.yaml (removing anything sensitive) it would be great. It looks like you need the a role set to index-node which would cause this env var to be omitted if the role is not present for the right pod. https://github.com/MakerOps/helm-charts/blob/main/charts/graphprotocol-node/templates/deployment.yaml#L51

Other than that, the env seems to be fine. https://github.com/MakerOps/helm-charts/blob/main/charts/graphprotocol-node/templates/deployment.yaml#L57


The env vars posted above look good but without the specific pods is hard to say. That var needs to be set on the pod that handles the subgraph creation so if you have a multi node setup you need to check if this works when submitting the request on the index-node that has the env var defined (as opposed, for example, to a query node which wouldn't have it)
