### ISSUE TITLE
Retrying a non-deterministic error loses offchain triggers

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#3999]
If a non-deterministic error happens after `offchain_monitor.ready_offchain_events()` has been called, block processing will be retried but any consumed offchain triggers will be lost until the node is restarted.

The solution I'd propose is for the offchain monitor state to be reset on retry, which would involve recreating the `SubgraphInstance` from the manifest + stored data sources.

**Comment by leoyvens** [comment]
This looks like the place to recreate the `SubgraphInstance`:
https://github.com/graphprotocol/graph-node/blob/61601fb3f7e6993b1b63ce62e1cefa536268e429/core/src/subgraph/runner.rs#L783

**Comment by leoyvens** [comment]
To clarify, the entire `IndexingContext` would need to be recreated, not just the `SubgraphInstance`.

**Comment by neysofu** [comment]
This should be closed, correct @mangas?
