### ISSUE TITLE
Find way to call contract methods by block hash, not block number

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#400]
The `eth_call` in [web3](https://docs.rs/web3/0.4.0/web3/api/struct.Eth.html#method.call) and in the [Ethereum JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call) has a block number as parameter. Block numbers do not reliably identify recent blocks due to the possibility of chain reorganizations. This will lead to incorrect data being returned when the Graph node and the Ethereum node have a different interpretation of what blocks are on the "main chain".

**Comment by leoyvens** [comment]
This EIP should allow us to do this https://eips.ethereum.org/EIPS/eip-1898.

**Comment by leoyvens** [comment]
Done in #1905.
