### ISSUE TITLE
Implement process for building binaries against GitHub release tags

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#403]

**Comment by Jannis** [comment]
For ETH San Francisco, just a one-shot binary build without automation is good enough.

**Comment by Jannis** [comment]
The Docker image is probably more valuable than this.

**Comment by leodasvacas** [comment]
This has been done for linux but not osx. Since docker is our preferred distribution method, it's unlikely that we or any user will care about getting pre-built osx binaries. I'll go ahead and close this, to be re-opened if a new motivation comes up.
