### ISSUE TITLE
Graft multiple times results in increased sync time

### ISSUE THREAD

**Issue by OlaStenberg** [graphprotocol/graph-node#4038]
**Do you want to request a *feature* or report a *bug*?**
 *bug*

**What is the current behavior?**

I believe there's an issue when using graft feature multiple times from the same base.

Example:

| # | Deployment Id | Base     | time |
|---|---------------|----------|------|
| 1 |QmA....B | QmA....A | 10h  |
| 2 |QmA....C | QmA....A | 20h  |
| 3 |QmA....D | QmA....A | 30h  |
| 4 |QmA....E | QmA....A | 40h  |

It seems like the previous graft is being factored in. This is a frustrating when deploying hotfixes on subgraphs that take 40h to graft and if you don't get it right the first time, then you will have to wait another 80h.

I've deployed new ones as soon as previous has finished and used the same start block, meaning the data hasn't increased 50% in a day.

I did try a workaround, using deployment `QmA....B` as base for deployment `#2` and that seem to copy as expected 
| # | Deployment Id | Base     | time |
|---|---------------|----------|------|
| 1 |QmA....B | QmA....A | 10h  |
| 2 |QmA....C | QmA....B | 10h  |

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try using graft on a smaller subgraph and check how long it takes to copy, then do a minimal change to generate another deplyoment id, using the same base as the first one and it should take twice as long.

**What is the expected behavior?**
Copying a 4th time with the same `base` and same `startBlock` should be done in the same duration as the first copy.

**Comment by azf20** [comment]
hey @OlaStenberg! I am not sure the issue is as you describe, there are a few things that might be relevant here:
- there was a short-lived grafting bug earlier this week which might have influenced what you were seeing
- there's a limit of 5 concurrent grafts per shard, and if a shard happens to get too many graft requests, they get queued and have to wait for other grafts to finish
- depending on how busy a shard is, grafts can take more or less time
So I think you may have been tripped up by one of those? (and thanks @lutter for the detail)

**Comment by OlaStenberg** [comment]
Hey @azf20 

I've seen this happen for a month or two and never seen it being queued, but just copies a lot slower than the first time. Then it might be related to alternative three.. 

I can't recall ever grafting a second time with the same copy speed as the first time (unless I use the workaround)

**Comment by lutter** [comment]
@OlaStenberg if you observe this again, it would be great to dig into some internal statistics we have about grafting times. Those only stick around for as long as the deployment exists; you can make sure of that by deploying the grafts to different names (like `account/graft-a` and `account/graft-b`) You can always pick one of those and deploy it to your 'real' subgraph name, too, by deploying the same IPFS hash for one of the grafts to, say, `account/my-subgraph` The backend logic deduplicates this, and the data only exists once, and indexing only happens once. Please use this judiciously so we don't drown in unneeded data ;)

**Comment by lutter** [comment]
Closing this since it doesn't seem to be an issue anymore. Feel free to reopen if this crops up again.
