### ISSUE TITLE
Make subgraph deployments persistent across restarts

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#404]
For this, nodes that we deploy for hackathons need to have a persistent Postgres database and persistent IPFS node. Any subgraph that is deployed over the JSON-RPC admin API should be resumed after restarting a node.

So basically: Need a persistent IPFS node. Need to remember subgraphs that are registered in Postgres.

**Comment by Jannis** [comment]
I've deployed a persistent IPFS node on our infra. Now it's just the Postgres side and re-loading previously registered subgraphs at startup.

**Comment by timmclean** [comment]
stealing this

**Comment by timmclean** [comment]
Major work on this has been done on the `tim/persistent-subgraphs` branch (and is in `ethsf`). There's still a bit more work to do before merging it to master, but it's working well enough for this weekend.
