### ISSUE TITLE
Aurora mainnet subgraph not syncing to latest block

### ISSUE THREAD

**Issue by kunalroute** [graphprotocol/graph-node#4045]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Aurora subgraph not syncing to latest block. Synced till block `75907817` but lastest on chain is `75909233`
Sometimes the difference between lastest block on chain and graph synced block is more than 3 days.

Log:
"DEBUG no chain head update for 30 seconds, polling for update, component: BlockStream"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://thegraph.com/hosted-service/subgraph/kunalroute/aurora-subgraph-debug?selected=logs

**What is the expected behavior?**
It should sync to latest block.

**Comment by kunalroute** [comment]
Seems working now. Closing the issue.

**Comment by kunalroute** [comment]
Issue is again occurring in Aurora.

**Comment by azf20** [comment]
I think this is now resolved, closing
