### ISSUE TITLE
Add a Firehose Block Ingestor for Ethereum

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#4059]
### Situation
Currently, Graph Node configured to use a Firehose for Ethereum indexing still needs to connect to an RPC endpoint in order to ingest blocks to keep the chain head pointer up to date.

### Resolution
Add a Firehose block ingestor for Ethereum, similar to the implementations for other protocols without an existing RPC setup

This should be configurable (i.e. to prefer an RPC or Firehose Block Ingestor)

**Comment by paymog** [comment]
Do we know when this fix will land in a usable docker image?

**Comment by mangas** [comment]
@paymog it looks like it might only be release with 0.30 in Jan.
