### ISSUE TITLE
Get the returned result of transaction NEAR protocol

### ISSUE THREAD

**Issue by HolidayMan** [graphprotocol/graph-node#4067]
Hi there! I’m writing the NEAR subgraph and stuck with the problem: how could I get the result of transaction in mapping code. I have function call, it returns some value (not writing in logs) Is there any possibility to get this value? 

It’s strange if I can get a FunctionCallAction object, args, logs, but I can’t get the returned value from this call

Example of such [transaction](https://explorer.testnet.near.org/transactions/CwomxfkmNcdBHDNHhC753dEhnfGCXFMKNq7Dhq4PuSgc)

**Comment by maoueh** [comment]
The success value of the function can be found in the `outcome.status` field when it's of type `SuccessStatusKind`:

```
  if (receipt.outcome.status.kind == near.SuccessStatusKind.VALUE) {
    const returnBytes = status.toValue()

    // Use the correct `toXXX` to depending on your known return value JSON type (if it's JSON)
    const returnValues = json.fromBytes(returnBytes).toArray()
    
    // Do something
  }
  ```
  
The `receipt` here is the object received from the receipt handler. Also, note that with asynchronous nature of NEAR, your FunctionCall and its results will be on different receipt.
