### ISSUE TITLE
FR: config.toml - improve matching Ethereum network NodeCapabilities

### ISSUE THREAD

**Issue by grassets-tech** [graphprotocol/graph-node#4094]
There is a provider in `config.toml` which supports both `archive` and `tarces`

```
provider = [{ label = "goerli-1-full", url = "http://x.x.x.x", features = [ "archive", "traces" ] }]
```

But nodes gets error, when it tries to index subgraph which requires `archive` node only
```
Oct 23 20:16:33.332 ERRO Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmWq1pmnhEvx25qxpYYj9Yp6E1xMKMVoUjXVQBxUJmreSe[2] with required capabilities: archive: A matching Ethereum network with NodeCapabilities { archive: true, traces: false } was not found., sgd: 2,
```

Workaround is to add same provider one more time, but with limited feature set, i.e.:
```
provider = [{ label = "goerli-1-full", url = "http://x.x.x.x", features = [ "archive", "traces" ] },
                    { label = "goerli-1-full", url = "http://x.x.x.x", features = [ "archive" ] },]
```

Consider improving matching to avoid duplication in config.toml

**Comment by azf20** [comment]
@leoyvens this seems unexpected? I know we have providers on the hosted service with only a single provider configured with both features

**Comment by leoyvens** [comment]
We do run this configuration, so also surprising to me. A minimal but complete config file that reproduces this would be helpful.

**Comment by grassets-tech** [comment]
Hi, 

Just tried without the explicit definition 
features = [] 
and that's ok apparently.. 

one other observation.. 
regarding the [deployment] and matching rules 
we have configs defined as per the template:


[deployment]

[[deployment.rule]]
match = { network = "gnosis" }
indexers = [ "index_node_1" ]

[[deployment.rule]]
indexers = [ "index_node_0" ]

However the deployment is still being deployed on the index_node_0 as per the log bellow:

> 
> [12:12:27.912] INFO (IndexerAgent/1): Deployment changes
>     component: "Agent"
>     deploy: [
>       {
>         "bytes32": "0x19f910c15c1d26139b348dab151f1d3ea5d1a7d2f2b1b3813e42517350c27ecf",
>         "ipfsHash": "QmQ63BCmZejMto55jNd5tVMXWLTfVA331532H39Q77E3WE"
>       }
>     ]
>     remove: []
> [12:12:27.913] INFO (indexer-agent/H39Q77E3WE/1): Index subgraph deployment
>     component: "Agent"
>     deployment: {
>       "bytes32": "0x19f910c15c1d26139b348dab151f1d3ea5d1a7d2f2b1b3813e42517350c27ecf",
>       "ipfsHash": "QmQ63BCmZejMto55jNd5tVMXWLTfVA331532H39Q77E3WE"
>     }
> [12:12:27.936] INFO (indexer-agent/H39Q77E3WE/1): Create subgraph name
> [12:12:27.953] INFO (indexer-agent/H39Q77E3WE/1): Successfully created subgraph name
> [12:12:27.953] INFO (indexer-agent/H39Q77E3WE/1): Deploy subgraph deployment
>     deployment: {
>       "bytes32": "0x19f910c15c1d26139b348dab151f1d3ea5d1a7d2f2b1b3813e42517350c27ecf",
>       "ipfsHash": "QmQ63BCmZejMto55jNd5tVMXWLTfVA331532H39Q77E3WE"
>     }
> [12:12:28.833] INFO (indexer-agent/H39Q77E3WE/1): Successfully deployed subgraph deployment
>     deployment: {
>       "bytes32": "0x19f910c15c1d26139b348dab151f1d3ea5d1a7d2f2b1b3813e42517350c27ecf",
>       "ipfsHash": "QmQ63BCmZejMto55jNd5tVMXWLTfVA331532H39Q77E3WE"
>     }
> [12:12:28.833] INFO (IndexerAgent/1): Reassign subgraph deployment
>     deployment: {
>       "bytes32": "0x19f910c15c1d26139b348dab151f1d3ea5d1a7d2f2b1b3813e42517350c27ecf",
>       "ipfsHash": "QmQ63BCmZejMto55jNd5tVMXWLTfVA331532H39Q77E3WE"
>     }
>     node: "index_node_0"
>

**Comment by grassets-tech** [comment]
@leoyvens  

config.toml - `code: SubgraphStartFailure`
`Oct 23 20:16:33.332 ERRO Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmWq1pmnhEvx25qxpYYj9Yp6E1xMKMVoUjXVQBxUJmreSe[2] with required capabilities: archive: A matching Ethereum network with NodeCapabilities { archive: true, traces: false } was not found., sgd: 2,`

```
[store]

[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph:5432/graph-node"
pool_size = 10

[chains]
ingestor = "index_node_0"

[chains.goerli]
shard = "primary"
provider = [{ label = "goerli-1-full", url = "http://<>", features = [ "archive", "traces" ] }]

[chains.gnosis]
shard = "primary"
provider = [{ label = "gnosis-1-full", url = "http://<>", features = [ "archive", "traces" ] }]

[deployment]

[[deployment.rule]]
indexers = [ "index_node_0" ]

[general]
query = "query_node_0"
```



config.toml - workaround
```
[store]

[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph:5432/graph-node"
pool_size = 10

[chains]
ingestor = "index_node_0"

[chains.goerli]
shard = "primary"
provider = [{ label = "goerli-1-full", url = "http://<>", features = [ "archive", "traces" ] },
            { label = "goerli-1-archive", url = "http://<>", features = [ "archive" ] }]

[chains.gnosis]
shard = "primary"
provider = [{ label = "gnosis-1-full", url = "http://<>", features = [ "archive", "traces" ] },
            { label = "gnosis-1-archive", url = "http://<>", features = [ "archive" ] }]

[deployment]

[[deployment.rule]]
indexers = [ "index_node_0" ]

[general]
query = "query_node_0"
```

**Comment by grassets-tech** [comment]
This error appears when configure provider is not working (e.g. rpc is not working, remote port is closed, ip is unreachable etc)., even if it is present in the configuration

Working as intendent.
Closing bug.
