### ISSUE TITLE
Add support for Arweave file data sources

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#4095]
Subgraph developers want to build subgraphs which leverage data stored on Arweave. This can now be done via a new `kind` of File Data Source

Strawman:
- Configure Graph Node with an Arweave Gateway URL
- Add `kind/arweave` file data source
- Add Arweave connector, with hash validation

**Comment by leoyvens** [comment]
We now have implementation docs/guide for that should help implementing this https://github.com/graphprotocol/graph-node/blob/master/docs/implementation/offchain.md
