### ISSUE TITLE
cargo build bug

### ISSUE THREAD

**Issue by mzaprudin** [graphprotocol/graph-node#4097]
**bug**

**What is the current behavior?**
I clone the gparh-node repository and run `cargo build`
but I get the next error
>$ cargo build
>error: failed to load manifest for workspace member `/home/m/nodes/graph-node/core`
>
>Caused by:
>  failed to parse manifest at `/home/m/nodes/graph-node/core/Cargo.toml`
>
>Caused by:
>  invalid type: map, expected a string for key `package.edition`

**What is the expected behavior?**
Building without any issue

**Comment by neysofu** [comment]
We require `rustc` 1.64.0. Try running `rustup update`.

**Comment by mzaprudin** [comment]
> We require `rustc` 1.64.0. Try running `rustup update`.

It was helpful
Thank you!
