### ISSUE TITLE
HTTP error creating the subgraph: ECONNREFUSED

### ISSUE THREAD

**Issue by shixin-guo** [graphprotocol/graph-node#4111]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
yarn run v1.22.19
$ graph create --node http://localhost:8020/ znft-goerli
✖ HTTP error creating the subgraph: ECONNREFUSED
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
follow the document and init a new project 
yarn create loacl

**What is the expected behavior?**
no error

**Comment by azf20** [comment]
Hi @shixin-guo are you running a local graph node?

**Comment by shixin-guo** [comment]
no, if we want to run an instance, do we need to install other dependence ?

**Comment by azf20** [comment]
Yes, you need to be running a local Graph Node for `yarn create local` to work. That is easiest to do with Docker, there is an [example Docker compose here](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml). Alternatively you can deploy to the subgraph studio or hosted service.
