### ISSUE TITLE
Support adding multiple ethereum rpc in the docker-compose.yml

### ISSUE THREAD

**Issue by timqian** [graphprotocol/graph-node#4122]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

We are able to connect to multiple Ethereum networks on a single graph-node. e.g.

```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://<USERNAME><:PASSWORD>@localhost:5432/<POSTGRES_DB_NAME> \
  --ethereum-rpc mainnet:https://mainnet.infura.io \
  --ethereum-rpc goerli:https://...
  --ipfs 127.0.0.1:5001 \
  --debug
```

ref: https://github.com/graphprotocol/graph-node/pull/1027

But when deploying graph-node via `docker-compose`, we can only pass one ethereum rpc address.
https://github.com/graphprotocol/graph-node/blob/a277f5596fe9840217a3ee09e69390932b48a882/docker/docker-compose.yml#L22
If we pass multiple urls, this error occurs:

```
docker-compose up
services.graph-node.environment.ethereum must be a string, number, boolean or null
```

**Comment by azf20** [comment]
Hi @timqian, have you tried [Graph Node Advanced Configuration](https://github.com/graphprotocol/graph-node/blob/master/docs/config.md)?

**Comment by timqian** [comment]
@azf20 
It Looks `the advanced configuration` requires users to start graph-node in the terminal.
Can the config TOML file being passed to docker-compose? I don't see it in the doc?

**Comment by azf20** [comment]
hi @timqian yes you can add a `GRAPH_NODE_CONFIG` e.g.

https://github.com/StakeSquid/graphprotocol-mainnet-docker/blob/master/docker-compose.yml#L164

**Comment by timqian** [comment]
👍 Thanks for the note @azf20

**Comment by neysofu** [comment]
Hey @timqian, were you able to get this sorted? Asking to make sure I can close this :smile:

**Comment by timqian** [comment]
@neysofu Yeah, the config file way works for me. Sorry I forget to close this issue
