### ISSUE TITLE
Trying again after eth_call RPC call for block #773384 - Arbitrum

### ISSUE THREAD

**Issue by rafinskipg** [graphprotocol/graph-node#4132]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Hello , i have redeployed this graph several times, but it keeps getting stuck at 2.2%. Te graph getting stuck on arbitrum-one at specific block all the time. 

https://thegraph.com/hosted-service/subgraph/rafinskipg/castles-arbitrum-v0?selected=logs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See the link above

**What is the expected behavior?**

The indexing should continue

**Comment by azf20** [comment]
Hi @rafinskipg it looks like your subgraph is spending a lot of time on `eth_calls`, that is not recommended for indexing performance. It also seems to still be indexing right now, but it hasn't reached the block you mention. You can get more information about the failure if it fails by following [this documentation](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#checking-subgraph-health). Please [join our Discord](https://discord.gg/vtvv7FP) (#hosted-service) for more help with debugging

**Comment by rafinskipg** [comment]
@azf20 

The graph is still blocked, it never passes 2.2% of the indexation
![image](https://user-images.githubusercontent.com/1152768/199971079-34282d94-0ca9-47a8-816b-a31ea7e4a18f.png)

Could you reopen this issue? It seems like a timeout with the RPC. 

I have also been posting under the hosted-service for a couple of days

**Comment by rafinskipg** [comment]
@azf20 could you reopen this issue please?
