### ISSUE TITLE
Store error: database unavailable

### ISSUE THREAD

**Issue by enzoferey** [graphprotocol/graph-node#4135]
Hi !

Not sure if this is the correct repo, if not, please let me know where I should report this issue.

We are running a subgraph on Polygon mainnet (https://thegraph.com/hosted-service/subgraph/enzoferey/zomon-subgraph) via the hosted service and we are randomly getting `[GraphQL] Store error: database unavailable` errors.

Is there any reason for doing so ?

**Comment by neysofu** [comment]
Hey @enzoferey, some subgraphs on the hosted service that are indexing Polygon experienced spotty availability on Friday. This was caused by a spike of DB load and the situation is better now. Please check and report back if you keep having problems. Thanks!

**Comment by enzoferey** [comment]
Hey @neysofu, thanks for your response. The problem did resolve on Friday around ~14:30 UTC. Across the weekend, we have seen only about a dozen of these errors along some `[Network] Bad Gateway` errors. I guess that's expected for any kind of web service 😁 

I'm closing and I will reopen if we encounter this issue again. Thank you 🙏🏻

**Comment by enzoferey** [comment]
Actually @neysofu, would you have any tip / trick to handle these possible moments of outages ? Our application is heavily relying on the indexed data to deliver value to the user. If the requests to the subgraph are constantly erroring, the whole business has to halt. Any way to introduce redundancy / avoid single point of failure ?

**Comment by azf20** [comment]
hey @enzoferey, sorry for the trouble, this was an isolated issue on the hosted service so this should not be an issue going forward. That being said, support for additional networks (including Polygon) is being added to [The Graph Network](https://thegraph.com/explorer) over the coming months, which will provide the described redundancy.

**Comment by enzoferey** [comment]
Yes @azf20, I'm looking forward moving to the decentralized network 💯

We are bit worried about the stability of it though. We read on your latest announcements how the reliability of the decentralized network on Ethereum was quite irregular early and then you fixed it. Our concerns are that it may take a few more months for you guys to support Polygon and then a few other months to stabilize it, so potentially we could me talking about +6 months (probably more) before we can do production on it.

As described on my previous comment, a disruption like this (8 hours of almost 100% of queries failing) is a big pain for our business and it not only makes us lose money but also it degrades the idea of robustness of our product towards end users. I understand it's our responsability to cover your outages, but I would like to know if there is anything you would recommend as an action step today.

**Comment by enzoferey** [comment]
@neysofu you are probably aware but this issue has been happening again for the last 24h+ and it doesn't seem to stop 😅 This time it is less severe than last time, but it's still disturbing our business a lot.

Would you suggest moving to a self hosted approach ? Thank you.

**Comment by kasparkallas** [comment]
I'm seeing this error appear on Polygon now a lot as well. Started 3-4 days ago and still happening today. The requests often get a response of `Store error: database unavailable` but not always.

**Comment by enzoferey** [comment]
Yes, I can confirm I'm still seeing this issue on both Polygon and Mumbai. It has been 5 days now...

**Comment by kasparkallas** [comment]
@enzoferey I believe the incident is described here: https://status.thegraph.com/incidents/19t7cbdfprpf

**Comment by enzoferey** [comment]
It has been 24h the hours has not been reported by our exceptions service, so it looks like resolved again, but I'm really afraid of this happening again and last for another 6 days 😓
