### ISSUE TITLE
graph-node seemingly not using firehose provider

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4145]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I'm using graph node image v0.28.2

I've configured a firehose and rpc provider like so:

```
[general]
query = "readonly.*"

[store]
[store.primary]
connection = <redacted>
pool_size = [
    { node = "indexer.*", size = 30 },
    { node = "readonly.*", size = 80 }
]
weight = 0
[store.primary.replicas.repl1]
connection = <redacted>
weight = 1

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "indexer_0",]

[chains]
ingestor = "indexer_0"


[chains.mainnet]
shard = "primary"
provider = [
    { label = "mainnet-archive", transport = "rpc", url = "http://rpc-node-proxy-service:3000/mainnet/archive", features = ["archive"] },
    { label = "firehose", details = { type = "firehose", url = "http://firehose-mainnet-server:13042"  }},
]
```

I can see the firehose server serving blocks:

```
firehose-mainnet-server-68d56cb7f4-v4vv6 firehose {"severity":"INFO","timestamp":"2022-11-07T07:46:49.617557211-05:00","logger":"firehose","message":"stream sent block","trace_id":"97b6a4dbaf6c5925869baaaea88c1b1b","block":"#2800 (526473e18687d5c416a098112f1f661fd94113081b3e8045a038cf2baf8e627a)","duration":0.490262793,"logging.googleapis.com/labels":{}}
firehose-mainnet-server-68d56cb7f4-v4vv6 firehose {"severity":"INFO","timestamp":"2022-11-07T07:48:10.327150703-05:00","logger":"firehose","message":"stream sent block","trace_id":"97b6a4dbaf6c5925869baaaea88c1b1b","block":"#3000 (6b51cf0d0c2e298ef9039c03c3aa2f219aac2ee5f4e446a3097a7834307b9777)","duration":0.835946448,"logging.googleapis.com/labels":{}}
firehose-mainnet-server-68d56cb7f4-v4vv6 firehose {"severity":"INFO","timestamp":"2022-11-07T07:49:17.988204405-05:00","logger":"firehose","message":"stream sent block","trace_id":"97b6a4dbaf6c5925869baaaea88c1b1b","block":"#3200 (0b97623595d82d9d912f847a43a73c96f57aceeed878480af7be120f921a804a)","duration":2.006604344,"logging.googleapis.com/labels":{}}
firehose-mainnet-server-68d56cb7f4-v4vv6 firehose {"severity":"INFO","timestamp":"2022-11-07T07:50:28.220652446-05:00","logger":"firehose","message":"stream sent block","trace_id":"97b6a4dbaf6c5925869baaaea88c1b1b","block":"#3400 (393fc99a61be0549eb2e44685913c5a42e1a8cf9781c7bd293b092cd585a1dee)","duration":0.561430175,"logging.googleapis.com/labels":{}}
firehose-mainnet-server-68d56cb7f4-v4vv6 firehose {"severity":"INFO","timestamp":"2022-11-07T07:51:40.744581413-05:00","logger":"firehose","message":"stream sent block","trace_id":"97b6a4dbaf6c5925869baaaea88c1b1b","block":"#3600 (e439c427110dc0b77a2c38e0417904275cf2177753eea6e6bbfc954d69da1a99)","duration":0.388566182,"logging.googleapis.com/labels":{}}
```

However, when I look at the logs of my graph node indexer, it seems that blocks are being ingested from the rpc endpoint:

```
Nov 07 12:51:44.466 INFO Done processing trigger, gas_used: 74591802, data_source: ConverterRegistryContract, handler: handleBlock, total_ms: 0, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.469 INFO Applying 2 entity operation(s), block_hash: 0xc54ef4f1a9cbf0cb97b7569125e846dd47ed40b0e48fbe086650455d3b4c2b77, block_number: 1701, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.707 DEBG 1 candidate trigger in this block, block_hash: 0xde4ffd01a43bd9374afce19ab6988e63413ea6a31ba28007a7f76be8178544bb, block_number: 1702, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.709 INFO Done processing trigger, gas_used: 74591802, data_source: ConverterRegistryContract, handler: handleBlock, total_ms: 0, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.712 INFO Applying 2 entity operation(s), block_hash: 0xde4ffd01a43bd9374afce19ab6988e63413ea6a31ba28007a7f76be8178544bb, block_number: 1702, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
```

Note that the block numbers from the graph node are ~1700 while the firehose server is serving blocks in the 3600 range. Also note the graph node is processing blocks sequentially while firehose seems to be serving blocks in groups of 200.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. launch firehose 
2. launch graph node with the above toml
3. deploy subgraph to graph node
4. view logs 

**What is the expected behavior?**

I expect either better logging from graph node to indicate it is in fact processing blocks from firehose OR for graph node to processing blocks more in sync with firehose - if firehose is serving block 3600, I expect graph node to process that block, not block 1700.

**Comment by maoueh** [comment]
Can you try to set environment `GRAPH_ETHEREUM_IS_FIREHOSE_PREFERRED=true`, it's supposed to be on by default but maybe a regression happened?

**Comment by paymog** [comment]
I'll give that a shot! What is the expected behavior if that is set to true but no firehose providers are available?

**Comment by paymog** [comment]
As a follow up, how can I verify that graph node is indeed using firehose? Are there specific log lines I can/should look out for during the indexing process?

**Comment by maoueh** [comment]
> I'll give that a shot! What is the expected behavior if that is set to true but no firehose providers are available?

It will probably complains that there is no provider or no chain configured for the deployment. As soon as the variable is set, it goes through Firehose only code paths (where Firehose can power the said code path).

The best way to check that I know is deploying a subgraph and ensuring the deployment for it is using `FirehoseBlockStream` component:

```
Nov 07 12:41:00.809 INFO Blockstream connected, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: FirehoseBlockStream
```

Here you can see that deployment `QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr` is connected via the `FirehoseBlockStream` component so you know that Firehose is powering this subgraph.

**Comment by maoueh** [comment]
Re-looking at your logs, it seems to be Firehose powered. 

About those:

```
Nov 07 12:51:44.466 INFO Done processing trigger, gas_used: 74591802, data_source: ConverterRegistryContract, handler: handleBlock, total_ms: 0, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.469 INFO Applying 2 entity operation(s), block_hash: 0xc54ef4f1a9cbf0cb97b7569125e846dd47ed40b0e48fbe086650455d3b4c2b77, block_number: 1701, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.707 DEBG 1 candidate trigger in this block, block_hash: 0xde4ffd01a43bd9374afce19ab6988e63413ea6a31ba28007a7f76be8178544bb, block_number: 1702, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.709 INFO Done processing trigger, gas_used: 74591802, data_source: ConverterRegistryContract, handler: handleBlock, total_ms: 0, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 12:51:44.712 INFO Applying 2 entity operation(s), block_hash: 0xde4ffd01a43bd9374afce19ab6988e63413ea6a31ba28007a7f76be8178544bb, block_number: 1702, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
```

What made you think it was RPC powered?

**Comment by paymog** [comment]
I tried setting that env var and I'm not seeing much difference in the logs. I do see the log line mentioning the FirehoseBlockStream during startup which is great. However, I'm still seeing that the latest blocks served by firehose are 78000:

```
firehose-mainnet-server-68d56cb7f4-2sxzn firehose {"severity":"INFO","timestamp":"2022-11-07T13:56:48.191908671-05:00","logger":"firehose","message":"stream sent block","trace_id":"156997f136a3a81f93d6e76a9cbca4c8","block":"#78000 (1f8742eb2d6c51c5975be2c9530cec99644df2c95d7613e1f9e75529ec952200)","duration":0.000025587,"logging.googleapis.com/labels":{}}
```

but what's getting indexed is about 1k blocks behind

```
Nov 07 18:57:38.636 INFO Done processing trigger, gas_used: 74649667, data_source: ConverterRegistryContract, handler: handleBlock, total_ms: 0, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
Nov 07 18:57:38.639 INFO Applying 2 entity operation(s), block_hash: 0x43a158dbd3ffeae6a6916e9dd15a3225910c532532ae94e4ddd807b4976dbae6, block_number: 76495, sgd: 1, subgraph_id: QmQ8G1RZ1NPrrqxon2iA5Wvry7waFGpze8PT3aLJhjKNyr, component: SubgraphInstanceManager
```

I thought it's not firehose powered because of the block lag between the graph node and firehose grpc server - maybe graph node buffers about 1k blocks before indexing them?

**Comment by maoueh** [comment]
It's possible that blocks are within `graph-node` system yet but not processed. I know `graph-node` has buffering of "block" not sure if it's the case here. They could be also in the `gPRC` transport layer (although I agree the difference seems big, at the same time early Ethereum a quite small when packed). I'm not sure what is the diff, but it's definitely fed by Firehose.

Also, are you producing the indexes on Firehose side? (check if you are running `combined-index-builder` app). If you have indexes, ensure you add `filters` feature on your Firehose provider for Ethereum like:

```
  { label = "firehose", details = { type = "firehose", url = "<url>", token = "<token>", features = [ "filters" ] }}
```

This way `graph-node` asks Firehose to leverage its indexes to return only what is necessary for the `subgraph`, a key element of Firehose performance.

**Comment by azf20** [comment]
@paymog are there definitely triggers of interest between the firehose chain head and the subgraph block?

You can check by querying the subgraph:
```
{
  _meta { block { number } }
}
```

**Comment by maoueh** [comment]
@paymog You are right, indexes are useful only for subgraph(s) that are at least a bit sparse (have some gap of > 200 blocks between triggers seems like a good measure of sparseness).

And it's not the case indeed for the one you mentioned.

**Comment by paymog** [comment]
Not sure how helpful this is, but I found a tool called `iftop` which summarizes network activity. Here's what I see when I run it on the graph node with the above config:

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/1986950/200595283-08d0ffa6-cc85-466e-b867-f34b237362f4.png">

it seems there's significant communication happening with the rpc provider (though that might be keepalive requests or health checks).

**Comment by maoueh** [comment]
Block ingestor within `graph-node` is still going through the RPC provider, which probably explains the high network usage with it.

**Comment by paymog** [comment]
Is Block Ingestor responsible for retrieving the latest blocks of the blockchain?

**Comment by maoueh** [comment]
Yes it is
