### ISSUE TITLE
Indexing stucks until restart

### ISSUE THREAD

**Issue by serjvanilla** [graphprotocol/graph-node#4146]
Sometimes one of the subgraphs stops indexing without errors, while others continue syncing. The only way to fix it is to restart the whole indexer. Every time it is a different subgraph. It doesn't matter if it is self-written or forked from a hosted service using an IPFS hash.

I'm deploying the `graph-node` to Kubernetes, to the same cluster with the Ethereum node (erigon) and Postgresql. Version is `0.28.2` with `GRAPH_KILL_IF_UNRESPONSIVE` set to `true`.
The logs are clear. The indexer stops producing records related to the stuck `subgraph_id` at all.

I have not found related issues, so I kindly ask for tips on diagnosing a problem in my setup.

Screenshots from Grafana for subgraph `Qmca1arSe9U94sHVpzzdUKizNyqFddsXnBZYqkALmSdSRE` https://thegraph.com/hosted-service/subgraph/indexed-finance/indexed as an example.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/3241415/200347920-4056a10c-45d5-4b8a-977e-9697edd9c98a.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3241415/200347986-f760991b-be27-4d01-84e0-483922f8e1e7.png">

**Comment by azf20** [comment]
hey @serjvanilla thanks for the report - are you able to run your Graph Node with `GRAPH_LOG=trace` to see if you get further details on the affected subgraph?

**Comment by serjvanilla** [comment]
Indexer redeployed with `GRAPH_LOG=trace`. Still, no stops since, but I'm continuously watching it. I will try to find more info in that logs as soon as any subgraph stops again.

**Comment by azf20** [comment]
Hi @serjvanilla closing this for now, but please do re-open if you saw stops as you described above!
