### ISSUE TITLE
[v0.28.2] graph-node Failed to resolve POI (E067) 

### ISSUE THREAD

**Issue by papadritta** [graphprotocol/graph-node#4172]
Hey, @fordN  I have faced the issue coming from graph-node. A few days, everything worked perfectly, and now the agent started to show `"failureReason":"IE067"`. The graph-node stuck and didn't sync. 

## The v0.28.2 graph-node  `Failed to resolve POI (E067)`
- Failed to resolve POI: POI not available for deployment at current epoch start block.
## Details:
- build from source
- in the beginning, everything worked perfectly 
- rebuilt the graph-node with no errors
- rolled back to v0.28.0 and back to v0.28.2
- used different RPC for the Gnosis chain (installed locally)
- closed subgraphs with x0x POI
- used graphman

## NOTE!: The typical [solution](https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#IE067) POI (E067) doesn't help. 

```This error typically indicates a subgraph deployment too far behind the chain head to resolve a valid POI for closing the allocation. To successfully resolve the POI and close the allocation, you'll need to wait for the index node to sync the deployment enough to generate a POI for the current epoch start block. If you do not want to wait to sync, you may choose to forfeit indexing rewards for the allocation by force closing it with a 0 POI by creating an unallocated or reallocate action item: graph indexer actions queue unallocated/reallocate <deployment-id> <allocation-id> 0 true.```

<img width="2232" alt="Screen Shot 2022-11-14 at 20 57 19" src="https://user-images.githubusercontent.com/90826754/201694933-c1566d0d-3943-476b-9faa-4e704f8d5f54.png">

**Comment by azf20** [comment]
hey @papadritta - to be clear the subgraph fails (even after restart), and you also can't close the allocation? Do you see anything more in the logs? Can you try running the Graph Nod ewith `GRAPH_LOG: trace` to see if you get more information?

**Comment by papadritta** [comment]
@azf20 Hey Adam, sure this is the log with `GRAPH_LOG="trace"`
<img width="2278" alt="Screen Shot 2022-11-15 at 13 03 56" src="https://user-images.githubusercontent.com/90826754/201839025-2b7419fd-ff8b-4577-8f39-8bb0d7d65898.png">

**Comment by papadritta** [comment]
More logs from Head :
<img width="2148" alt="Screen Shot 2022-11-15 at 13 42 44" src="https://user-images.githubusercontent.com/90826754/201849902-3390eb46-257d-48d9-8913-c1c1193ec1de.png">
<img width="2122" alt="Screen Shot 2022-11-15 at 13 44 12" src="https://user-images.githubusercontent.com/90826754/201849980-f0e6c943-50fa-43b4-88a3-0023e5183f31.png">
<img width="2131" alt="Screen Shot 2022-11-15 at 13 47 38" src="https://user-images.githubusercontent.com/90826754/201850025-2d790353-23cb-4d01-96a8-b0c667eadda5.png">
