### ISSUE TITLE
something wrong with my subgraph

### ISSUE THREAD

**Issue by 7Levy** [graphprotocol/graph-node#4176]
Nov 16 04:02:48.760 WARN Unexpected RPC error, error: Rpc(Error { code: ServerError(-32000), message: "context deadline exceeded", data: None }), sgd: 4, subgraph_id: QmPrDbaDnCWtM3AqNCJjSp9ov8SzczcADRHwjMxQy8bQ95, component: BlockStream

**Comment by azf20** [comment]
hi - can you give some more detail on the setup in which you have encountered the error? (where is the subgraph deployed, the subgraph code, the versions of software you are using etc.). Closing for now, will re-open when more detail is provided. Thanks!
