### ISSUE TITLE
method trace_filter does not exist/is not available 

### ISSUE THREAD

**Issue by Shevaister** [graphprotocol/graph-node#4182]
**Do you want to request a *feature* or report a *bug*?**

Its a *Bug*

**What is the current behavior?**

I keep geting warnings and graph interface is working but keep giving error output:

{
  "errors": [
    "{\n  \"errors\": [\n    {\n      \"message\": \"Store error: query execution failed: Subgraph `Qmcj1TALQPQkmm37P89Ux7Gd3ZzNsrrUdQ9phnkwVuLpgq` has not started syncing yet. Wait for it to ingest a few blocks before querying it\"\n    }\n  ]\n}"
  ]
}

Exact warning output from console:

Nov 17 15:35:15.960 INFO Scanning blocks [0, 0], range_size: 1, sgd: 2, subgraph_id: QmfPdLYR46QqFzwMbP93synbMyj4CY9qUSbqKwSoxqwchj, component: BlockStream
Nov 17 15:35:18.641 WARN Trying again after trace_filter RPC call for block range: [0..0] failed (attempt #10) with result Err(RPC error: Error { code: MethodNotFound, message: "The method trace_filter does not exist/is not available", data: None }

Caused by:
    Method not found: The method trace_filter does not exist/is not available), sgd: 2, subgraph_id: QmfPdLYR46QqFzwMbP93synbMyj4CY9qUSbqKwSoxqwchj, component: BlockStream

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My setup to run cargo:

cargo run -p graph-node --release -- \
  --postgres-url postgresql://root:root@localhost:5432/reminder \
  --ethereum-rpc goerli:https://goerli.infura.io/v3/<MyProjectID> \
  --ipfs 127.0.0.1:5001

**What is the expected behavior?**

I expect clear output in interface without errors

**Comment by azf20** [comment]
hi @Shevaister - it appears your subgraph uses a feature which requires trace filters (callhandlers, or blockhandlers with call filters). As such you need to use an RPC which supports the [trace_filter method](https://openethereum.github.io/JSONRPC-trace-module), and it seems that your infura endpoint does not. If you reconfigure with an endpoint which does, your subgraph should start syncing accordingly
