### ISSUE TITLE
failed to deserialize response: data did not match any variant of untagged enum Output

### ISSUE THREAD

**Issue by Shevaister** [graphprotocol/graph-node#4196]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

What i get in cli:

WARN Trying again after trace_filter RPC call for block range: [0..0] failed (attempt #10) with result Err(failed to deserialize response: data did not match any variant of untagged enum Output), sgd: 5, subgraph_id: QmSTQrdQAYiK925MLAvMepvWKuaSeZxFrE5JbmsrHwRrVZ, component: BlockStream

What i get in web interface:

{
  "errors": [
    {
      "name": "SyntaxError",
      "message": "Unexpected 'N'",
      "at": 1,
      "text": "Not found"
    }
  ]
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

cargo run -p graph-node --release -- \
  --postgres-url postgresql://root:root@localhost:5432/graph-node \
  --ethereum-rpc mainnet:http://127.0.0.1:7545 \
  --ipfs 127.0.0.1:5001 \
  --debug

**Comment by azf20** [comment]
Hey @Shevaister this looks like the callhandler functionality isn't working as expected. Are you still having issues here? Closing for now, please re-open if still valid
