### ISSUE TITLE
Fail to load data from IPFS in the subgraph, always return null

### ISSUE THREAD

**Issue by hangleang** [graphprotocol/graph-node#4198]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
When try to load data from IPFS, which in the process of pinning or pinned, it's always return null. seem like subgraph is not index the block again even after pinned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After minting NFT token, we call pinning service to pin content of CID of the token, and smart contract emitted an event with the tokenURI. then, in the subgraph, we try to load the metadata from the URI, and store into the graph. but, we failed to load the data because the CID is still pinning, no data was loaded. we have been wait for a while to let the pinning service do their job, and let subgraph index the block again, but data still not load in the subgraph, until we redeploy our subgraph, then data start to index the block

**What is the expected behavior?**
subgraph should be reindex every block since startBlock, if so, the ipfs should be able to load once it's pinned

**Comment by hangleang** [comment]
**Source**: https://thegraph.academy/developers/defining-a-subgraph/

> _However, make sure that the files are pinned on the IPFS node that the Graph Node indexing the subgraph connects to so that this is done reliably_

Based on above statement, Do I need to pin from any pinning services, which the graph node connect to, so it can index data from IPFS properly? 

If so, Are there any pinning service for that?

**Comment by azf20** [comment]
hi @hangleang we actually have some new functionality in closed beta which handles that better (retries for files it doesn't find), can you share your source code and we can take a look?

**Comment by hangleang** [comment]
Okay, that's great, thank you. You can take a look into this repo: https://github.com/hangleang/nft-marketplace-subgraph

**Comment by azf20** [comment]
Thanks all! Closing this as it should be resolved by migration to File Data Sources, which retries when a file cannot be found: [documentation](https://thegraph.com/docs/en/developing/creating-a-subgraph/#file-data-sources)
