### ISSUE TITLE
Error: failed to process trigger (sync fails at 99%)

### ISSUE THREAD

**Issue by DorianDaSilva** [graphprotocol/graph-node#4203]
There seems to be a bug when trying to index new events in the subgraph. 

I originally ran these commands to set up the subgraph and sync was 100% without issues - Issue came when trying to index the NFT minted.

I followed your instructions as stated in website

**In terminal:**

```codegen``` - build completed successfully
```build``` - build completed successfully
```deploy``` - build completed successfully

However, I get this error after build completed successfully  running ```graph deploy --studio nft-marketplace```

**error**
```
Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Version label already exists.
```
I still minted the NFT but after refreshing the subgraph on the website I initially got an error ```failed to fetch``` and after new refresh it simply went back to showing the ```indexing error``` below

```
Error: failed to process trigger: block #7977546 (0x9314…63a3), transaction f7902183755ee06baa7b755a295b3b941fa4e5b0ef2c1c4bd5137d5fe785f2ec: Entity ActiveItem[0x00x2bbaee667e6804d3cde73bb3b3c4ae7c0b5e53c1]: missing value for non-nullable field `buyer` wasm backtrace: 0: 0x2de6 - <unknown>!generated/schema/ActiveItem#save 1: 0x3745 - <unknown>!src/mapping/handleItemListed

To view more details about this indexing error, please view the documentation.
```

The whole issue is detailed in the discussion below:
https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/3872

Thank you!

**Comment by DorianDaSilva** [comment]
Turns out all I had to do was redeploy using a new version instead of running commands for ```v0.0.1``` 

Deployed ```v0.0.2``` & now it is indexing. Sorry about that!

**Comment by Rashmi-278** [comment]
@DorianDaSilva I'm Facing the same exact issue, I tried updating the version in subgraph.yaml file, it didn't work.

Can you please specify what do you mean by new version ?
