### ISSUE TITLE
Undeploying a failing Substreams powered Subgraph leave some resources dangling

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4220]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Undeploying a `Substreams` in failure mode seems to leave some element dangling as even after deployment, `SubstreamsBlockStream` are still logged out.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Hard to tell, but here what I think happened.

1. Deployed a Substreams powered Subgraph
1. This Substreams hit an error, leading to infinite re-connection
1. Undeploy the Subgraph deployment

Now messages are still logged:

```
Dec 02 16:09:46.269 INFO received err, sgd: 1, subgraph_id: QmdjX1JUTw8Q5Xv2CtPTokKNL7LHGUwkevFm8nDe8LWpsq, component: SubstreamsBlockStream
Dec 02 16:09:46.269 ERRO An error occurred while streaming blocks: status: Internal, message: "error building pipeline: failed setup request: backprocess run: scheduler run: process job result: worker ended in error: receiving stream resp: rpc error: code = Internal desc = error building pipeline: failed to setup backprocessings: load full store: load full store store_eth_prices at 0012369622-0012369621.kv: not found", details: [], metadata: MetadataMap { headers: {} }, sgd: 1, subgraph_id: QmdjX1JUTw8Q5Xv2CtPTokKNL7LHGUwkevFm8nDe8LWpsq, component: SubstreamsBlockStream
```

But this deployment is technically gone:

```
$ graphman -c environments/eth-mainnet/graph-node-dev-local.toml info ""
No matches
```

So there is some part of the deployment that was not properly terminated, probably the `SubstreamsBlockStream` was not notified that the deployment is gone.

Restarting`graph-node` completely fixed the dangling stream.

**What is the expected behavior?**

Everything stops.

**Comment by maoueh** [comment]
I hadn't time to retry that so far

**Comment by azf20** [comment]
hey @maoueh, @mangas had a look here and there isn't anything different for substreams powered subgraphs, so we were wondering if this is still valid?

**Comment by maoueh** [comment]
It happened to me only once, so it's hard to tell what happened. Could have been weird quirks on early implementations. We can close.
