### ISSUE TITLE
tag v0.29.0 : error: failed to run custom build command for `graph-chain-substreams v0.29.0 

### ISSUE THREAD

**Issue by oleksandrmarkelov** [graphprotocol/graph-node#4240]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

error: failed to run custom build command for `graph-chain-substreams v0.29.0 (/home/pops/git/graph-node/chain/substreams)`

Caused by:
  process didn't exit successfully: `/home/pops/git/graph-node/target/debug/build/graph-chain-substreams-0afc3a65ad2b8adf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=proto

  --- stderr
  thread 'main' panicked at 'Failed to compile Substreams entity proto(s): Custom { kind: Other, error: "protoc failed: codec.proto:44:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\ncodec.proto:45:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }', chain/substreams/build.rs:6:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

checkout release tag v0.29.0 and cargo build

**What is the expected behavior?**

build successful

**Comment by suntzu93** [comment]
```
sudo apt-get remove protobuf-compiler -y
wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
unzip protoc-21.12-linux-x86_64.zip -d /usr/

```
make sure protoc version is `3.21.12` by cmd : `protoc --version`

then build graph-node again.

**Comment by oleksandrmarkelov** [comment]
fix with correct version of protoc worked

**Comment by riordant** [comment]
Had this error:
```
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases
```

Above command worked.
