### ISSUE TITLE
Queries to contract deployed with factory in same block fail

### ISSUE THREAD

**Issue by coreyar** [graphprotocol/graph-node#4251]
**What is the current behavior?**
We are listening to contract creation events and then querying that contract for data in the handler of the event. This query always fails.

Here is a minimal [example](https://github.com/coreyar/child-parent-events) 

**What is the expected behavior?**
To receive the event that a contract was created and then query that contract

**Comment by incrypto32** [comment]
Hi @coreyar , i investigated this issue, and looks like its an RPC issue with chapel and not an issue with graph-node hence closing this issue, but im in talks with the BNB chain team to fix this issue.
