### ISSUE TITLE
module instantiation failed: unknown import: `ethereum::ethereum.call` has not been defined`

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-node#4253]
This subgraph fails with this error the moment a file datasource is added to the manifest.
```
module instantiation failed: unknown import: `ethereum::ethereum.call` has not been defined`
```

This is the subgraph code
https://github.com/TalentLayer/talentlayer-id-subgraph/blob/8ca4889e0ea656d9c3d0f420427020bc7b65c7eb/src/mappings/service-registry.ts#L45

I tested on this version and the version in the repo. Same error.
```
  "dependencies": {
    "@graphprotocol/graph-cli": "^0.37.0",
    "@graphprotocol/graph-ts": "^0.28.0"
  }
```

**Comment by leoyvens** [comment]
This is a known limitation/bug, you should have the file handler in its own file, not in the same file as other handlers.

**Comment by empaemanuel** [comment]
Thank you, this resolved the problem! 

> This is a known limitation/bug, you should have the file handler in its own file, not in the same file as other handlers.

Thank you! Putting the handler in a separate file resolved the problem.
