### ISSUE TITLE
Querying with `Last` doesn't work in graphiql

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#426]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Where querying a graph node with last :
```
{
  ensDomains(last: 100) {
    id
    label
    node
    owner
  }
```

The last query doesn't work at all. It will return an entire DB call, so it's as if the last query doesn't work at all. If you replace `first` with `last` it does work, so the syntax of last is okay. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just use graphiql on a subgraph and try out the last query option

**What is the expected behavior?**

Only return 100.

**Comment by davekaj** [comment]
This is still true today

**Comment by Jannis** [comment]
We only support `first` and `skip` IIRC. So this isn't necessarily be a bug.
