### ISSUE TITLE
Dollar suffix for certain table names

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4271]
**Do you want to request a *feature* or report a *bug*?**

Neither, I have a general question

Why is it that certain tables have a dollar sign suffix relative to their corresponding subgraph entity? For example, here's a postgres table made for a subgraph which has an entity called `data_sources` but the table name is called `data_sources$`

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1986950/209671284-dfd9f18a-d52d-490c-858a-7fc33e423336.png">

Why does graph node add this suffix?

**Comment by leoyvens** [comment]
All subgraphs have a `data_sources$` table which tracks dynamic data sources created by the subgraph. The `$` is added to prevent it from conflicting with the table from an entity called `DataSource`, if there is one.

**Comment by paymog** [comment]
Got it! I've also seen a table called `block$` - is there a way to know ahead of time which entities will have a table with the $ suffix?

**Comment by leoyvens** [comment]
Immutable entities have a `block$` column, but I'm not aware of a `block$` table.

**Comment by lutter** [comment]
The `$` is only used in table/column names that are generated for internal bookkeeping purposes, never for entities/attributes that come from the subgraph schema.

**Comment by paymog** [comment]
Ah got it, thanks for the explanation @lutter!
