### ISSUE TITLE
Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts

### ISSUE THREAD

**Issue by sotatek-duongdo** [graphprotocol/graph-node#4281]
Hi Team, 

```
 "@graphprotocol/graph-cli": "^0.19.0",
 "@graphprotocol/graph-ts": "^0.19.0",
```
I use graph-node local and BSC Testnet when I deployed the graph node locally but have some issues when mapping the function event.

```
Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 439, column 6, with the message: Call reverted, probably because an `assert` or `require` in the contract failed,
```
Do you have faced the same issue?

**Comment by maoueh** [comment]
You are performing a call to a contract without using the `try_XXX` version. The contract call, for a reason you will need to find, reverts/assert which fails the call (the contract could be non-initialized for example). Closing as this is not an issue with `graph-node` directly.
