### ISSUE TITLE
Remove Archive node requirement for contract calls

### ISSUE THREAD

**Issue by 0xlinus** [graphprotocol/graph-node#4300]
I understand the importance of the archive nodes for *production* subgraph, but since I'm using a local graph node connected to a local anvil node to do some testing, I really don't care about data consistency. 
I wonder if is there any way to make contract calls without the need of a archive node? and use a simple ganache/anvil node?

**Comment by maoueh** [comment]
"Normal" (so `geth`, `erigon`) RPC node can perform `eth_call` only on the latest 128 blocks. A Subgraph can started syncing way before those 128 blocks.

We cannot lift this requirement. If you are sure of you, just pretend your provider is an `archive` node, I do this for development often without any issue, `graph-node` don't check, it uses it only as a way to pick the right provider.
