### ISSUE TITLE
Substreams deployment should not require an RPC node

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4301]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Right now, to run a Substeams, someone needs to provide a Web3 provider to a full node. This seems to be required because of the block ingestor.

**What is the expected behavior?**

In the ideal world, there would be no need to have it for proper indexing. Maybe however it would be required for other things like resolving some block info at query time. I'm not sure.

**Comment by let4be** [comment]
Having related problem trying to run local "the graph" node feeding it exclusively from firehose/substreams...
I can run substreams and see data being produced but no luck starting "the graph" node

Can anyone provide an example config for feeding data from firehose+substreams?

**Comment by azf20** [comment]
@maoueh I think this was resolved such that a Firehose can be used in place of an RPC? Is the expectation here that it should work with just a Substreams endpoint (and if so, can that provide the light block info?)

**Comment by maoueh** [comment]
Closing, what would be left if being able to run `substreams` without the need to also run a `Firehose` node.
