### ISSUE TITLE
Should be able to run Substreams for other network than Ethereum

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4302]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

AFAIK today, it's not possible to run a Substreams for something else than Ethereum network.

**What is the expected behavior?**

 It should be possible to use a Substreams for any network. This raises interesting questions for network not supported at all today in `graph-node`. Even for existing networks, it raises interesting questions like the requirement for a block ingestor.

**Comment by azf20** [comment]
@maoueh do you mean other than Ethereum mainnet (I think you can configure different networks currently @mangas?), or do you mean for other protocols e.g. Solana

**Comment by mangas** [comment]
IIRC the adapter could be added to any network but we may have code that's ethereum specific. In any case this wouldn't have been tested and so it's not really ready. So think this is ticket is relevant. 

In terms of stuff like solana, I'm not sure how that would be handled, as far as I know we haven't looked into it at all.

**Comment by maoueh** [comment]
Yeah we have two cases here:
- Substreams handling for already supported networks (NEAR, Arweave, Cosmos)
- Substreams handling for network not supported within `graph-node` (Solana, Antelope and the stream of others that are building some Firehose integrations)

**Comment by maoueh** [comment]
The first bullet is probably an easy task. The second one, not quite clear what we should do exactly. There will be discussion to have around how we deal with that, around the block ingestor specifically.

For the block ingestor, we could force operators to also provide Firehose gRPC endpoint on the same URL as the Substreams endpoint. Other idea is to provide a "graph-node-block-ingestor` Substreams that would emit graph-node required block info, we simply run this Substreams `.spkg` as the block ingestor "provider".

There is probably other area that would need to work for "unsupported" network, to be discovered.

**Comment by matthewdarwin** [comment]
Is there any decision on how to move forward on this?  We are seeing requests to integrate more chains with graph-node.

**Comment by maoueh** [comment]
For head tracking, I created https://github.com/streamingfast/substreams-sink-noop/tree/develop/substreams-head-tracker, it's a Substreams that accepts a single `params` argument and I leverage Substreams RPC to retrieve the "head" block of the chain. 

Something we could use to enable any Substreams network to be consumed by graph-node!

**Comment by mangas** [comment]
Support has been added to run substreams for the already supported networks, for new chains I guess that will require a bigger discussion.
