### ISSUE TITLE
How to load genesis app state in the graph store

### ISSUE THREAD

**Issue by faza** [graphprotocol/graph-node#4316]
Hi. We were testing the subgraph for Gitopia testnet (https://gitopia.com/)

Our testnet genesis has some initial application state and we wanted to load this in graphql store. We wrote a script to load that state in the postgresql database used by graph-node (sgd<deployment-id>-<entity-name> tables). However, we are not getting these data in the qraphql queries, only the rows created by the new chain transactions are in the result.

Let us know if we need to do something else. Thanks.

**Comment by azf20** [comment]
hey @faza what is the size of the initial state?

**Comment by azf20** [comment]
hey @faza you can now use initialisation handlers https://github.com/graphprotocol/graph-node/issues/3221 to bootstrap subgraph state (please comment and re-open if this does not solve your problem)
