### ISSUE TITLE
out of bounds memory access wasm backtrace

### ISSUE THREAD

**Issue by leon-do** [graphprotocol/graph-node#4317]
Deployed a subgraph:

https://thegraph.com/hosted-service/subgraph/leon-do/goerli-erc721-erc1155?selected=logs

And ran into this error:

```
Subgraph instance failed to run: wasm trap: out of bounds memory access wasm backtrace: 0: 0x1b4e - 
<unknown>!~lib/util/memory/memcpy 1: 0x1f22 - <unknown>!~lib/memory/memory.copy 2: 0x37b0 - 
<unknown>!~lib/string/String#replaceAll 3: 0x3959 - 
<unknown>!../node_modules/@openzeppelin/subgraphs/src/fetch/erc1155/replaceURI 4: 0x3cdb - 
<unknown>!../node_modules/@openzeppelin/subgraphs/src/fetch/erc1155/fetchERC1155Token 5: 0x3eaa - 
<unknown>!../node_modules/@openzeppelin/subgraphs/src/datasources/erc1155/registerTransfer 6: 0x46e0 - 
<unknown>!../node_modules/@openzeppelin/subgraphs/src/datasources/erc1155/handleTransferBatch in handler 
`handleTransferBatch` at block #7717525 (c8433d58be49b4c1681eddbb204de305eedf4bccc1885b4cee24bcba1d070934), 
code: SubgraphSyncingFailure
```

With some help, we narrowed it down to this transaction. It's ERC1155 `TransferBatch` event:

https://goerli.etherscan.io/tx/0xe25e395952b0c386b0d9902473f5d4d2f69ea311f605b6c496e1c91d9762fc9d#eventlog

mentioned this to @tilacog

**Comment by azf20** [comment]
hey @leon-do - is this issue now resolved (it looks like the subgraph is synced)? Did you change anything on your end?

**Comment by leon-do** [comment]
looks like it's solved. thank you!

**Comment by leon-do** [comment]
> @leon-do did you did anything from your side or it fixed by itself cause im also facing the same issue on mainnet

I did not. I assumed it was solved everywhere.

**Comment by phoneix1221** [comment]
> > @leon-do did you did anything from your side or it fixed by itself cause im also facing the same issue on mainnet
> 
> I did not. I assumed it was solved everywhere.

it did not
