### ISSUE TITLE
Support `$` syntax for defining variables in queries

### ISSUE THREAD

**Issue by adamsoffer** [graphprotocol/graph-node#432]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The GraphQL server doesn't support `$` syntax for defining variables in queries. GraphQL throws an error: `data did not match any variant of untagged enum Value`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Build the adchain subgraph and start a Graph Node
2. Open GraphiQL browser at `127.0.0.1:8000/cli`
3. Run the following query: 
![46263367-3cff1780-c4dc-11e8-8daa-8dcca3818cba](https://user-images.githubusercontent.com/555740/46263377-5f913080-c4dc-11e8-94f8-10011ffc17af.png)

**What is the expected behavior?**
GraphQL server should respond with the data requested

**Comment by Jannis** [comment]
Yep, this is missing indeed.
