### ISSUE TITLE
Does `graphman check-blocks` use Firehose providers?

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4335]
**Do you want to request a *feature* or report a *bug*?**

Neither, I have a question

I just went through the release notes for 0.29 and saw that there's a new [graphman docs page](https://github.com/graphprotocol/graph-node/blob/2da697b1af17b1c947679d1b1a124628146545a6/docs/graphman.md#-check-blocks). Does the `check-blocks` command use firehose providers if they're provided for the given chain? The docs only mention JSON RPC providers but I've noticed that if both JSON RPC and Firehose providers are present for a given chain, [only the firehose provider is used during indexing](https://github.com/graphprotocol/graph-node/issues/4260).

**Comment by azf20** [comment]
hey @paymog, when using a firehose provider, Graph Node doesn't cache blocks in the same way (all blocks are streamed from the firehose), so the `check-blocks` command is not really applicable (only very simple block information is stored). I don't know what the behaviour of `check-blocks` is if used with a firehose provider configured, @tilacog can you clarify here?

**Comment by tilacog** [comment]
The `check-blocks` command uses JRPC providers only.
I'm not sure how Firehose serves transaction receipts, but IRC, they do not end up in the database. 

If that's the case, the `check-blocks` might have no effect at all.

**Comment by neysofu** [comment]
Closing as it's been answered.
