### ISSUE TITLE
Which RPC calls does firehose replace?

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4346]
**Do you want to request a *feature* or report a *bug*?**

I have a question

**What is the current behavior?**

I've launched firehose for my indexers and I'm still seeing many rpc calls being issued by the graph node. I'm specifically interested in learning which RPC calls we should expect to be eliminated once firehose is turned on.

I'm currently running graph node version 0.29.0 and firehose v1.3.3.

I see the following JSON rpc calls continuing to happen even though firehose has been enabled:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1986950/217267772-76a0080f-29e2-4299-b8de-163ae69c17af.png">

I would have intuitively guessed that firehose would replace all calls except `eth_call` which requires an archive node. However I'm still seeing calls for getting blocks by number, transaction receipts, and get logs.

**Comment by matthewdarwin** [comment]
From reading the comments here, seems like you need to be on version 0.30?  https://github.com/graphprotocol/graph-node/issues/4059

**Comment by paymog** [comment]
I'm also seeing this against my polygon firehose which I think (though I might be completely wrong!) isn't affected by #4059 

Also, 0.30 hasn't been released based on docker hub: https://hub.docker.com/r/graphprotocol/graph-node/tags?page=1&name=0.30

**Comment by maoueh** [comment]
> thinking about it more, https://github.com/graphprotocol/graph-node/issues/4059 might be for all eth-compatible chains and not just eth mainnet?

That is correct, it affects all Ethereum like chain. So right now, from the list you presented above, they all look correct, all done by the BlockIngestor which is technically not required anymore.

Have you tried with environment variable `IS_FIREHOSE_PREFERRED=true` so far?

**Comment by paymog** [comment]
Ah got it! Hopefully 0.30.0 is released soon!

Yeah, I've tried that in the past and from what I can tell `GRAPH_ETHEREUM_IS_FIREHOSE_PREFERRED` set to `true` [by default](https://github.com/graphprotocol/graph-node/blob/8e37e1c72d5838903019456cba3b3d7138ae0391/chain/ethereum/src/env.rs#L146).
