### ISSUE TITLE
Unable to Deploy Any New Subgraph

### ISSUE THREAD

**Issue by aayush4vedi** [graphprotocol/graph-node#4355]
**Do you want to request a *feature* or report a *bug*?**
A Bug

**What is the current behavior?**
Not able to deploy new subgraphs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not able to deploy any kind of new subgraphs, not even if it is the default one which gets created with the init command. The deployment command does not provide any helpful message to debug/look into the root cause of failure, just this message -**"Could not deploy subgraph on graph-node, please try again"**.

Here are the steps to reproduce the issue:
1. Create a new subgraph from dashboard
2. Initialize like `graph init --studio <INSERT_SUBGRAPH_SLUG>`
3. Deployment steps
```
❯ graph auth --studio <INSERT_DEPLOY_KEY>
Deploy key set for https://api.studio.thegraph.com/deploy/
❯ cd studio
❯ graph deploy --studio <INSERT_SUBGRAPH_SLUG>
✔ Version Label (e.g. v0.0.1) · v0.0.1
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping apiVersion from 0.0.5 to 0.0.6
  Skip migration: Bump manifest specVersion from 0.0.1 to 0.0.2
  Skip migration: Bump manifest specVersion from 0.0.2 to 0.0.4
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  ....
✔ Compile subgraph
  Copy schema file build/schema.graphql
  ....
  Write subgraph manifest build/subgraph.yaml
✔ Write compiled subgraph to build/
  Add file to IPFS ....
  Add file to IPFS ....
  Add file to IPFS ....
✔ Upload subgraph to IPFS

Build completed: <BUILD_ID>

✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Could not deploy subgraph on graph-node, please try again.

```

**What is the expected behavior?**
The deployment should go through and a deployment url & subqueries should be o/p after deploy command

**Comment by alexbakers** [comment]
`✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Could not deploy subgraph on graph-node, please try again.`

Subgraphs are not deployed.

**Comment by alexbakers** [comment]
Hello, @aayush4vedi 

 - Go this URL: https://thegraph.com/hosted-service/
 - Sign in by Github
 - Create Subgraph
 - Deploy `graph deploy --product hosted-service username/subgraph`

**Comment by azf20** [comment]
Thanks both, please [reach out on Discord](https://discord.com/invite/vtvv7FP) for support, closing this as it doesn't appear to be a Graph Node issue
