### ISSUE TITLE
SQLite planned support?

### ISSUE THREAD

**Issue by computeronix** [graphprotocol/graph-node#4370]
Are there plans to support SQLite or has then been tested with this type of database?

**Comment by matthewdarwin** [comment]
I wouldn't think SQLite would be in the plans, no.

**Comment by saihaj** [comment]
We rely on many Postgres built in features so would be difficult to make it DB agnostic

**Comment by computeronix** [comment]
thank you so much for the information!

**Comment by matthewdarwin** [comment]
If you want to write to SQLight, use substreams sink.

**Comment by samlaf** [comment]
Is there a list of the Postgres features you rely on somewhere?

**Comment by hazae41** [comment]
> Is there a list of the Postgres features you rely on somewhere?

Bumping this question
