### ISSUE TITLE
Subgraph can't be deployed locally if the `GRAPH_NODE_CONFIG` environment variable is used

### ISSUE THREAD

**Issue by Chomtana** [graphprotocol/graph-node#4379]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
Subgraph can't be deployed locally if the `GRAPH_NODE_CONFIG` environment variable is used. Even though I have added `ethereum: 'mainnet:...'` environment variable.

`GRAPH_NODE_CONFIG` environment variable is used for the graph decentralized network. While local development usually uses `ethereum: 'mainnet:...'` environment variable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Clone Stakesquid's docker compose at https://github.com/StakeSquid/graphprotocol-mainnet-docker (Commit [595d7c818e76842042a8d4b4c59ed1c843f47745 ](https://github.com/StakeSquid/graphprotocol-mainnet-docker/commit/595d7c818e76842042a8d4b4c59ed1c843f47745))
2. Expose port 8020 on query-node-0
3. Start docker compose using `bash start-essential-v2` command
4. Try deploying the example [Gravatar subgraph](https://github.com/graphprotocol/example-subgraphs/tree/main/ethereum/gravatar) and notice that it errors with "no network mainnet found on chain ethereum"
5. Add `ethereum: 'mainnet:...'` environment variable to query-node-0
6. Restart docker compose using `bash stop-essential-v2` then `bash start-essential-v2` command
7. Try deploying the example [Gravatar subgraph](https://github.com/graphprotocol/example-subgraphs/tree/main/ethereum/gravatar) and notice that it still errors with "no network mainnet found on chain ethereum"
8. Add this cause to graph-node-configs/config.tmpl

```
[chains.ethereum]
shard = "primary"
provider = [ { label = "${CHAIN_0_NAME}", url = "${CHAIN_0_RPC}", features = ["archive", "traces"] } ]
```

9. Restart docker compose using `bash stop-essential-v2` then `bash start-essential-v2` command
10. Try deploying the example [Gravatar subgraph](https://github.com/graphprotocol/example-subgraphs/tree/main/ethereum/gravatar) and notice that it still errors with "no network mainnet found on chain ethereum"

To fix it, you have to remove `GRAPH_NODE_CONFIG` environment variable from query-node-0 in Stakesquid's docker compose.

**What is the expected behavior?**
Subgraph should be able to deploy locally with either `GRAPH_NODE_CONFIG` or `ethereum` environment variable.

If that's not possible, one can't deploy both the decentralized network and local subgraphs in the same instance.

**Comment by azf20** [comment]
@trader-payne I am not sure if this limitation exists, any ideas given it is using the Stakesquid setup?

**Comment by azf20** [comment]
@Chomtana are you still having this issue? Closing for now, please ping the thread to re-open if you are still having problems

re: your last point, the type of chain configuration shouldn't mean you can only deploy to the network or locally, it should work in both cases
