### ISSUE TITLE
Leftover state in wasm runtime between events

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#438]
When processing events for a subgraph, a RuntimeHost is created for each data source. Each RuntimeHost sets up a wasmi ModuleInstance on init, reusing it to handle all events in that data source. ModuleInstances are stateful, so the mapping being run inside the module can see effects of previous runs by reading from arbitrary memory locations (inside the sandbox) or looking at `memory.size()`. This can cause non-determinism.

If we reuse the wasmi Module but not the ModuleInstance, these problems should go away. This creates a new heap each time. Hopefully the overhead of doing so isn't too bad...

**Comment by timmclean** [comment]
Nice, that sounds like it should work. The initial memory state would be all zeros, right? So that effectively zeros the state before each handler. Sounds good to me

**Comment by timmclean** [comment]
Feel free to grab the assignment on this one btw if you like

**Comment by leodasvacas** [comment]
Not all zeros, there are constants and stuff. Taking it.

**Comment by timmclean** [comment]
Makes sense! :+1:
