### ISSUE TITLE
Subgraph deployment is failed due to ETH 429 error Code

### ISSUE THREAD

**Issue by JensonCollins** [graphprotocol/graph-node#4380]
**Do you want to request a *feature* or report a *bug*?**
🐛 

**What is the current behavior?**
I have been using subgraph to index blockchain events for some contracts. After I have some updates on the subgraph mapping script, I was trying to deploy but it's showing me the error for the whole day.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/50631214/219948648-808161c5-5ffd-4e96-9a65-d9f370d59e1e.png)

**What is the expected behavior?**
All the blocks should be synced.

**Comment by rezaHssini** [comment]
I also deployed a subgraph on Goerli and get same error

**Comment by incrypto32** [comment]
Hey this was due to an issue with the RPC provider used on the hosted service, its resolved now. Closing this issue as its not a graph-node issue
