### ISSUE TITLE
Subgraph instance failing to index

### ISSUE THREAD

**Issue by yaruno** [graphprotocol/graph-node#4383]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
We've been using thegraph indexing service for several months without an issue until today we noticed that the indexing has failed.
<img width="1102" alt="Näyttökuva 2023-02-20 145048" src="https://user-images.githubusercontent.com/3228613/220125934-8f9a4975-c577-4c1d-8f6f-4e689443859b.png">

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Issue can be reproduced by building and deploying production index from https://github.com/ATARCA/nft-share-platform-subgraph to polygon network.

graph build --network matic
graph deploy --network matic --node https://api.thegraph.com/deploy/ *YOUR_ACCOUNT/SUBGRAPH*

**What is the expected behavior?**
Indexing should finish, but now gets stuck on 99.8% .

**Comment by 0xged** [comment]
Hey guys, I'm adding on top of this ticket. Our subgraph has also failed on sync while calling a function:

- https://thegraph.com/hosted-service/subgraph/mean-finance/dca-v2-yf-polygon

```
2/20/2023, 5:10:12 AM

ERROR

Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 475, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_calculateTransformToUnderlying` to handle this in the mapping. wasm backtrace: 0: 0x320c - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x526c - <unknown>!src/utils/token/transformYieldBearingSharesToUnderlying 2: 0x7971 - <unknown>!src/utils/pair-swap/create 3: 0x8367 - <unknown>!src/utils/pair/swapped 4: 0x8516 - <unknown>!src/mappings/hub/handleSwapped in handler `handleSwapped` at block #39502155 (765b27a3ff4b8ef0aee19c9baa47f647737c4c48e1afdb70234c16a4d7633e1c), code: SubgraphSyncingFailure

2/20/2023, 5:10:12 AM

ERROR

Subgraph error 1/1, code: SubgraphSyncingFailure, error: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 475, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_calculateTransformToUnderlying` to handle this in the mapping. wasm backtrace: 0: 0x320c - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x526c - <unknown>!src/utils/token/transformYieldBearingSharesToUnderlying 2: 0x7971 - <unknown>!src/utils/pair-swap/create 3: 0x8367 - <unknown>!src/utils/pair/swapped 4: 0x8516 - <unknown>!src/mappings/hub/handleSwapped in handler `handleSwapped` at block #39502155 (765b27a3ff4b8ef0aee19c9baa47f647737c4c48e1afdb70234c16a4d7633e1c), block_hash: 0x765b27a3ff4b8ef0aee19c9baa47f647737c4c48e1afdb70234c16a4d7633e1c, block_number: 39502155

2/20/2023, 5:10:12 AM

ERROR

Handler skipped due to execution failure, error: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 475, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_calculateTransformToUnderlying` to handle this in the mapping. wasm backtrace: 0: 0x320c - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x526c - <unknown>!src/utils/token/transformYieldBearingSharesToUnderlying 2: 0x7971 - <unknown>!src/utils/pair-swap/create 3: 0x8367 - <unknown>!src/utils/pair/swapped 4: 0x8516 - <unknown>!src/mappings/hub/handleSwapped , handler: handleSwapped
```

While we've simulated that call for that block with that data on Tenderly, and it works.

Simulation link: https://dashboard.tenderly.co/0xged/mean/simulator/dd3da85f-3719-4e4f-90ef-596eb5bb5db1 (you need to be logged in on tenderly)

**Comment by paymog** [comment]
It's possible that the call cache of whichever indexer is indexing your subgraph has been corrupted. This has happened for us several times and the only fix we've found is to wipe the call cache of the indexer.

**Comment by yaruno** [comment]
Issue has been resolved for us and to 0xged to my understanding from thegraph team side. Didn't get a thorough explanation on what was causing it by it may have been the cache as paymog suggested or the rpc failing on thegraph side.
