### ISSUE TITLE
Mapping execution is slow

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#439]
Assuming a mapping does not make any contract function calls, processing a single event takes ~250-300ms~ 6-12ms  on my computer. Since we cannot parallelize event processing within a subgraph, this sets a minimum processing time of 6ms/event.

The two expensive parts of mapping execution are:
- `heap.asc_new(&event)`: Most of the execution time is spent putting the event data on the heap. Here, an `EthereumEventData` instance is copied into the wasm heap, and its properties are recursively allocated/copied into the wasm heap as well.
- `invoke_export` on the event handler: Not too slow in the examples I've tried, ~10-50ms~ 1-2ms (again, assuming no contract function calls). I think we should be able to do better, but it's not the main problem.

Looking deeper into the first point: an `EthereumEventData` is being converted to a `AscEthereumEvent`. I tried to count the number of wasmi heap allocations for each property on `AscEthereumEvent`:
- `address`: 2 allocs
- `block`: 27 allocs
- `transaction`: 9 allocs
- `params`: 2 + 3 * N allocs, where N is the number of log params

So that would be about 50 allocations per Ethereum event. Each allocation involves an FFI call into wasmi, and my guess is that doing round trips into wasmi and back is slow.

Assuming I'm on the right track, I have two ideas for fixing this:

- Idea 1: Write a big binary blob into wasm memory, deserialize it and alloc as needed on the wasm side. We would implement this in AssemblyScript as part of graph-cli so that it is transparent to mapping authors.
- Idea 2: Prepare everything on the Rust side, figuring out all the wasm pointer addresses ourselves. Write one big binary blob into wasm memory and pass a pointer to it to the event handler. We'll have to tell the wasm-side allocator to start new allocations at a higher address than usual, so that it doesn't clobber the event/block data.

See also #438 for related discussion

Update: changed measurements to use `--release` :man_facepalming:

**Comment by leodasvacas** [comment]
However 250ms is still extraordinarily slow, was this measured against debug or release builds?

**Comment by timmclean** [comment]
:man_facepalming: debug. This is what I get for hiding things in bash aliases. Let's close this until it becomes a measurable issue

**Comment by timmclean** [comment]
Some measurements with `--release`:

- 5-10 ms for `heap.asc_new(&event)`
- ~1-2 ms for `invoke_export`

I'll reopen since that's still pretty slow, but low priority

**Comment by Jannis** [comment]
@leoyvens I dug up this old issue. Might be worth taking another look at and deciding what to do with this one.

**Comment by leoyvens** [comment]
@Jannis We've since optimized memory allocation so these measurements are outdated. We can close this, if this is still a bottleneck it will show up in the metrics and we can open a new issue.
