### ISSUE TITLE
How do manually delete firehose ingested blocks in v0.30.0?

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4402]
The news for version 0.30.0 say the following:

> In order to downgrade, indexers must manually delete all blocks accumulated by Firehose in the database. For this reason, we suggest caution when switching over from RPC to Firehose

However there isn't guidance on how to do this correctly. What is the mechanism to correctly delete firehose ingested blocks when switching from firehose providers to rpc providers?

**Comment by neysofu** [comment]
@mangas I'm not really sure myself. Would be able to write a small paragraph for me to include in the release notes?

**Comment by mangas** [comment]
I think we should add this to graphman rather than add docs to manually change the db data.

**Comment by paymog** [comment]
@mangas adding this to graphman would be wonderful but that would require another image to be released, right? While we wait for that graphman command to be implemented and released, do you mind sharing, at a high level, how to do the rollback? I'd guess we need to delete specific rows from the `chainX.blocks` table(s) but having a bit of confirmation around that would be wonderful.

**Comment by tilacog** [comment]
If you don't mind clearing the whole block cache, `graphman truncate` is already available.

**Comment by tilacog** [comment]
If you prefer deleting a specific block range, I'd advise doing it in chunks (of about 5k blocks). Deleting a large range at once might cause a lot of congestion in the database.

But yes, you would delete from the `chainX.blocks` table. You can use the `block_number` column as a chunk delimiter.

**Comment by paymog** [comment]
Is there a way to be more surgical and only delete the blocks which were ingested by firehose? What is it about the firehose ingested blocks that makes them different from the rpc ingested blocks? Will one of the fields be null?

**Comment by paymog** [comment]
Though I'm now also wondering what the correct order of operations would be when falling back to only rpc providers. Should the old blocks be truncated first and then do the rollback (which risks adding more unusable blocks to the cache before the rollback finishes)? Or would it be better to disable firehose and then perform the rollback which would potentially cause issues with the invalid block cache being used in rpc-only mode?

**Comment by paymog** [comment]
I found that adding the following index

```
CREATE INDEX CONCURRENTLY on chainX.blocks USING BTREE ((data->'block'->'data'));
```

significantly speeds up the following query which can be used to delete just the firehose ingested blocks

```
DELETE FROM chainX.blocks WHERE data->'block'->'data' = 'null'::jsonb';
```

I think it would be good for graph node to create and manage these indexes itself. It might also be good if there was a way to use graphman to do the following in 1 step:

1. disable firehose for a specific chain
2. delete the firehose ingested blocks

**Comment by paymog** [comment]
I just ran another experiment as follows (I'll write the conclusion further down because it's a bit hard to summarize into a one-liner):

1. enable mainnet firehose for graph node on the latest image
2. confirm that mainnet blocks are being ingested by firehose
3. wait a while for the block cache to fill up with the firehose ingested blocks
4. deploy the [ethereum blocks](https://github.com/blocklytics/ethereum-blocks/blob/master/subgraph.yaml) subgraph against mainnet starting at the earliest firehose ingested block from step 2
5. redeploy the indexer with firehose disabled
6. watch the logs for the subgraph deployed in step 4 and note that it continues to progress even though the block cache is filled with firehose ingested blocks
7. watch my RPC metrics and notice that outgoing RPC requests spike (as expected)

Conclusion: the firehose ingested blocks in the graph node block cache do not corrupt/stall the graph node indexer when firehose is disabled

This means that clearing out the block cache is not an emergency action that indexers have to take when disabling firehose on the latest image. It's good hygiene to remove the firehose ingested blocks from the cache for future performance reasons (because good blocks in the cache reduce overall latency and RPC reliance).

Does this sound correct @mangas?

**Comment by paymog** [comment]
This is no longer relevant on 0.32.0 which automatically manages this for us.
