### ISSUE TITLE
Cargo build

### ISSUE THREAD

**Issue by Matlefebvre1234** [graphprotocol/graph-node#4407]
I clone the repo and try to cargo build but i got this error 
![image](https://user-images.githubusercontent.com/49442766/221965944-87e52bd8-4822-4d0e-8356-55ab715fae57.png)
I try different branch , reinstall protoc, graph cli etc but nothing seem to work . Any idea how to solve this ?

**Comment by azf20** [comment]
@maoueh I see something about the substreams proto, I don't know if there is a dependency there?

**Comment by azf20** [comment]
@Matlefebvre1234 closing for now, please re-open if you're still having this issue!

**Comment by maoueh** [comment]
Oups missed that one, wrong version of `protoc` is the reason of this problem, I think there should be no problem anymore.
