### ISSUE TITLE
Changelog for apiVersion and specVersion?

### ISSUE THREAD

**Issue by An-dz** [graphprotocol/graph-node#4409]
I'm trying to find what are the latest `apiVersion` and `specVersion` and a changelog of what are the differences but can't find it.

So far it seems that `apiVersion` is at _0.0.7_ and `specVersion` is at _0.0.5_ but I could not find what those versions bring.

**Comment by azf20** [comment]
hey @An-dz you can see details on `apiVersion` 0.0.7 here: https://thegraph.com/docs/en/developing/assemblyscript-api/#versions
SpecVersion 0.0.5 allows fetching receipt data in handlers https://thegraph.com/docs/en/developing/creating-a-subgraph/#transaction-receipts-in-event-handlers
