### ISSUE TITLE
Add ResolveError(failure::Error) variant in QueryExecutionError

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#442]
- ~Return failure::Error in result of Store methods~
  - add ResolveError(failure::Error) variant in QueryExecutionError.
  - impl From<failure::Error> for QueryExecutionError?

**Comment by Jannis** [comment]
@fordN Is this still relevant?

**Comment by fordN** [comment]
@Jannis I don't think so. I honestly don't remember the context within which this task was made, but we now several ResolveError variants on `QueryExecutionError` and have the StoreError variant that can wrap a failure:Error so it looks like the functionality expressed in the issue has been implemented.

**Comment by Jannis** [comment]
Ok, let's close it.
