### ISSUE TITLE
Crashloop for 0.30.0 with firehose provider

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4432]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Image 0.30.0 crash loops with a firehose provider

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Not sure about minimal demo. I just tried upgrading from 0.29.0 in our dev environment to 0.30.0 and got a crash loop. I see the following log line

```
Mar 07 19:55:02.178 INFOthread ' tokio-runtime-workerStarting block ingestor for network' panicked at ', One Firehose endpoint should exist at that execution point: all connections saturated with 100 connections, increase the firehose conn_pool_size or limit for the nodenetwork_name', : node/src/main.rsmatic:
```

**What is the expected behavior?**

I expect there to be no crash loops for image 0.30.0 when using a firehose provider.

**Comment by matthewdarwin** [comment]
Several people ran into this problem last week.  @mangas

**Comment by mangas** [comment]
@paymog @matthewdarwin is this the same issue that is resolved with the master image?

**Comment by paymog** [comment]
> @paymog @matthewdarwin is this the same issue that is resolved with the master image?
> 
> Edit: If so, we should be able to cut a new release after the 10th of April. If not, can you please provide enough information to reproduce? Ideally a full config (with creds removed)

Happy to test the latest master image. Should I try [this one](https://hub.docker.com/layers/graphprotocol/graph-node/5fa50f9/images/sha256-5ae2cb75e2a1a5c2f892bae373cf6d50f5e1620d33f83a0a267f3421e430907e?context=explore)?

**Comment by rootwarp** [comment]
@paymog Thanks for the comment.
I had faced the same error, but `graph-node` does not crash anymore /w [this](https://hub.docker.com/layers/graphprotocol/graph-node/5fa50f9/images/sha256-5ae2cb75e2a1a5c2f892bae373cf6d50f5e1620d33f83a0a267f3421e430907e?context=explore) that you recommended.

**Comment by matthewdarwin** [comment]
I got another 2 people reporting this problem this week.

**Comment by aasseman** [comment]
Can confirm the problem on v0.30.0. https://github.com/graphprotocol/graph-node/commit/eb11c556da6a018f011e172e82d1c44ef291440c fixes it (though not quite sure if the solution is in this particular commit). 
Tried reverting back to v0.30.0, and the issue comes back.

**Comment by rootwarp** [comment]
> Can confirm the problem on v0.30.0. [eb11c55](https://github.com/graphprotocol/graph-node/commit/eb11c556da6a018f011e172e82d1c44ef291440c) fixes it (though not quite sure if the solution is in this particular commit). Tried reverting back to v0.30.0, and the issue comes back.

For me, it works for Polygon and Eth substream.

Thanks :)

**Comment by paymog** [comment]
Not relevant since 0.32.0 has been released and no longer has this issue
