### ISSUE TITLE
Some creative RPC providers answer with 'null' (no error) when blockhash is not found

### ISSUE THREAD

**Issue by sduchesneau** [graphprotocol/graph-node#4439]
This issue is a QUESTION that may point to a "bug" in a broad sense.

I've seen some ethereum RPC providers respond like this to an rpc_call on a blockhash that was not found (ex: race condition)
`{"jsonrpc":"2.0","id":123,"result":null}`

Most RPC providers would answer with an `"error": {...}` field in the response, so I'm worried that a simple "null" with no error may pass as deterministic and produce bad data in subgraphs.

Can you validate that the graph-node will indeed treat such a response as a temporary error that needs to be retried ?

**Comment by leoyvens** [comment]
It would be nice to reproduce, but looking at the code I'd fully expect this to be considered a non-deterministic error response, as it should be.

**Comment by azf20** [comment]
Thanks @leoyvens !
