### ISSUE TITLE
Mappings can set non-existent Entity attributes

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#4466]
Mappings can store entries in an entity that do not correspond to attributes on the underlying type. These extra entries will be silently discarded when the entity is stored, but they do influence the POI calculation. That makes it possible that a subgraph generates a divergent POI depending on whether such an entity is fetched from the internal cache (where these attributes are still present) or from the database.

To fix this, we can take two approaches:

1. Fail the subgraph when an entity has extraneous attributes
2. Silently remove these attributes before doing the POI calculation

I would prefer (1) because this generally indicates some error in the subgraph's logic, but we'd need to figure out what level of backwards compatibility we need to provide (cc @azf20)

**Comment by azf20** [comment]
Is there any way to identify whether a subgraph is doing this, without checking the mappings themselves?

**Comment by lutter** [comment]
No, it requires looking at the source and seeing if they use `store.set` directly, i.e. without going through the generated wrappers.
