### ISSUE TITLE
[Bug] EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE is not working properly in a k8s pod

### ISSUE THREAD

**Issue by nickkounz** [graphprotocol/graph-node#4491]
### Bug report

We created a bug https://github.com/graphprotocol/graph-node/issues/3998 a few month ago initially. We thought this issue has been resolved. But it's actually not.

We are running on v0.30.0 graph node on Kubernetes with `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE=synced` environment variable https://github.com/MakerOps/helm-charts/blob/main/charts/graphprotocol-node/templates/deployment.yaml#L61 setup on index-node.

The behaviour
When we re-deploy the subgraph with the same subgraphName. We are getting the following from the querier

```Markdown
# query
{
  indexingStatusForPendingVersion (subgraphName: "<subgraphName>") {
    node
    synced
    
    chains{
      latestBlock{
        number
        
      }
      earliestBlock{
        number
      }
    }
    
  }
}

# result
{
  "data": {
    "indexingStatusForPendingVersion": null 
  }
}
```

with the environment variable `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE` setup, is `indexingStatusForPendingVersion` supposed to be non null value?

We tested on a docker-compose locally and this seems working. But not on a k8s cluster. We did exec into the index-node pod and we can see the environment variable has been setup like below:

```
root@graph-index-graphprotocol-node-864fd6b5dc-9b6m2:/# env | grep EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE
EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE=synced
```

We'd like to get the `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE` environment variable work in the index-node pod in a kubernetes cluster

@mangas @azf20

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
hey @nickkounz the link you shared doesn't mention the experimental variable https://github.com/MakerOps/helm-charts/blob/main/charts/graphprotocol-node/templates/deployment.yaml#L61
I would expect to see:
```
            - name: EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE
              value: synced
```
If that is not your yaml please share your active configuration

**Comment by azf20** [comment]
Got it, thanks!
