### ISSUE TITLE
[Bug] error when running cargo build

### ISSUE THREAD

**Issue by tommycp3** [graphprotocol/graph-node#4519]
### Bug report

I clone the repo and try to cargo build but i got this error
![2023-04-06_09-37-28](https://user-images.githubusercontent.com/13199826/230237275-694fe4e7-db50-4b65-9522-e9b517008666.png)

### Relevant log output

```Shell
thread 'main' panicked at 'Failed to compile Substreams entity proto(s): Custom { kind: Other, error: "protoc failed: codec.proto:44:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\ncodec.proto:45:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }', chain/substreams/build.rs:6:10
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by incrypto32** [comment]
@tommycp3 is this issue still relevant, have you tried with the latest master? It builds perfectly for me. Closing this issue, feel free to reopen if its still an issue

**Comment by maoueh** [comment]
@incrypto32 It happens if the `protoc` version is not recent enough. @tommycp3 Please update your `protoc` version to a newer version.
