### ISSUE TITLE
[Feature] Allow spawning File Data Sources from handlers of other File Data Sources

### ISSUE THREAD

**Issue by monitz87** [graphprotocol/graph-node#4521]
### Description

Right now, the documentation states that one of the limitations of File Data Sources is that you cannot generate other Data Sources (be it File or on-chain) from the handler of a File Data Source.

From what I've gathered on the project's discord, this is an implementation limitation rather than a design choice.

The general use case here is reading a file in IPFS whose contents store the CID of another file in IPFS, which should also be read.

More specifically, NFT metadata (which is normally stored in IPFS), usually contains an `image` field whose value is the URI of an image file stored in IPFS.

As it is, reading the contents of this image is impossible without using `ipfs.cat` (which isn't deterministic, and isn't supported in The Graph Studio).

I think it is reasonable to want to store the image contents instead of the URI in the subgraph database. Or, in other words, it doesn't make much sense to me to force an IPFS dependency on the client if the subgraph already has it.

In the more general case, the "internal" file in question could contain any amount of data that is useful to the subgraph consumers.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
Thanks @monitz87 - this is in my view a valid extension, @leoyvens I think this was indeed an implementation limitation but can you confirm?

**Comment by leoyvens** [comment]
Yes, this is entirely an implementation limitation, which could be relatively straightforward to lift.
