### ISSUE TITLE
[Bug] cargo build Error Transport::new_ipc not found

### ISSUE THREAD

**Issue by Mancitiss** [graphprotocol/graph-node#4524]
### Bug report

Steps to reproduce (Follow the steps on Graph Node readme.md):
In the terminal, clone https://github.com/graphprotocol/graph-node, and run cargo build.
```
git clone https://github.com/graphprotocol/graph-node
cd graph-node
cargo build
```

expected: build successfully
what happened: error (in the logs below)

I've tried with both master branch and stable release 0.30.0 but still got the same error
I'm using Windows 10 Version 21H2 OS Build 19044.2728
Rustc version: rustc 1.66.0 (69f9c33d7 2022-12-12)
### Relevant log output

```Shell
...   
Compiling graph-node v0.30.0 (F:\Github\graph-node-0.30.0\node)
error[E0599]: no variant or associated item named `new_ipc` found for enum `graph_chain_ethereum::Transport` in the current scope
   --> node\src\chain.rs:450:31
    |
450 |             Ipc => Transport::new_ipc(&web3.url).await,
    |                               ^^^^^^^
    |                               |
    |                               variant or associated item not found in `graph_chain_ethereum::Transport`
    |                               help: there is an associated function with a similar name: `new_rpc`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `graph-node` due to previous error
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Windows

**Comment by lutter** [comment]
I assume that's because there is no IPC on Windows. Sadly, we don't have the resources (or the need) to make `graph-node` work on Windows. Building works on OSX and Linux, so you might want to try that.
