### ISSUE TITLE
Can't add dependencies with yarn or npm

### ISSUE THREAD

**Issue by ashu26jha** [graphprotocol/graph-node#4525]
### Bug report

This was when I added with 'yarn'.
Command I used:
`yarn global add @graphprotocol/graph-cli`
`graph init --studio web3drive`

<img width="686" alt="Screenshot 2023-04-10 at 18 58 34" src="https://user-images.githubusercontent.com/66910385/230910268-d1b062c5-11bd-494a-aadf-fda925ef145d.png">

When I tried 'npm'

`npm install -g @graphprotocol/graph-cli`

<img width="591" alt="Screenshot 2023-04-10 at 19 04 19" src="https://user-images.githubusercontent.com/66910385/230911282-7cd9fc5a-fda6-4a3a-a7bf-89026ede624a.png">

How to fix this issue please help

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [x] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by saihaj** [comment]
being tracked in https://github.com/graphprotocol/graph-tooling/issues/1261

**Comment by saihaj** [comment]
should be patched in [@graphprotocol/graph-cli@0.45.2](https://github.com/graphprotocol/graph-tooling/releases/tag/release-1681166300461)
