### ISSUE TITLE
[Feature] Batched writes during subgraph indexing

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#4538]
### Description

Currently Graph Node writes entities to the store on every block. This leads to a large number of database interactions during historical syncing. This can be a significant performance bottleneck.

Graph Node could instead store entity changes in memory, writing those changes to the database every X blocks, or when the diff to be written is above a certain size.

This should combine with https://github.com/graphprotocol/graph-node/issues/4477 to reduce the number and size of database updates during syncing.

### Are you aware of any blockers that must be resolved before implementing this feature? If so, which? Link to any relevant GitHub issues.

- Impact on proof of indexing (ensuring that POI is not impacted by this change)

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by neysofu** [comment]
Closed by #4606.
