### ISSUE TITLE
[Bug] Unable to run graph node locally

### ISSUE THREAD

**Issue by dev060** [graphprotocol/graph-node#4551]
### Bug report

![Screen Shot 2023-04-18 at 13 26 50](https://user-images.githubusercontent.com/91896655/232689503-81b3359b-7e56-424d-b451-3415283751d1.png)
I am getthing this error when run cargo run .. command
here is the command I ran with.
cargo run -p graph-node --release --   --postgres-url postgres:1234//postgres@localhost:5432/graph-node   --ethereum-rpc optimism:https://mainnet.optimism.io   --ipfs 127.0.0.1:5001

Thanks

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by Preston-Harrison** [comment]
Your connection string is incorrect, consider dropping the `1234` after `postgres:`

**Comment by dev060** [comment]
Yup correct. Could you take a look at this one?
getting this now...
![Screen Shot 2023-04-19 at 16 27 58](https://user-images.githubusercontent.com/91896655/233016247-4e645fe2-d75c-4d6f-802e-4e5668f54867.png)

**Comment by dev060** [comment]
one thing more.
I am trying with docker too and getting this error
even user "postgres" exists and password is 1234.
any idea?
![Screen Shot 2023-04-19 at 16 47 52](https://user-images.githubusercontent.com/91896655/233021282-01d39b74-47ea-4b43-8c27-d9c2eecf20e3.png)

**Comment by dev060** [comment]
**Error: Failed to upload file to IPFS: AbortController is not defined**

I am getting this error when deploy subgraph.
the error seems come from node_module/graphprotocol/graph-cli.
any idea?

Thanks

**Comment by azf20** [comment]
closing, please re-open if you are still seeing this issue
