### ISSUE TITLE
Unable to deploy subgraph on Sepolia network

### ISSUE THREAD

**Issue by leKg1** [graphprotocol/graph-node#4559]
![Screenshot 2023-04-20 at 13 25 15](https://user-images.githubusercontent.com/51248347/233339520-e2b38e8c-8512-4ea1-8164-c5e0a2ce13b0.png)

Sepolia is added to graph-cli from the version 0.46.1 but i am unable to deploy subgraphs on it, the error message displayed is this: `UNCAUGHT EXCEPTION: Error: Failed to deploy to Graph node https://api.thegraph.com/deploy/: subgraph failure::Subgraph indexed network is missing from manifest`

Here my subgraph.yaml file:

![Screenshot 2023-04-20 at 14 41 20](https://user-images.githubusercontent.com/51248347/233355777-41e222df-032f-4018-bcc8-b2c89666efa2.png)

**Comment by nhtera** [comment]
I have the same issue with base-testnet
![image](https://github.com/graphprotocol/graph-node/assets/2976973/8557cd38-18c8-42c2-91bf-3d202ea4e369)

**Comment by georgeciubotaru** [comment]
@leKg1 `Sepolia` is not supported by `hosted service`, try to use `studio` subgraph

**Comment by incrypto32** [comment]
> @leKg1 `Sepolia` is not supported by `hosted service`, try to use `studio` subgraph

That's right, closing this issue
