### ISSUE TITLE
Adding new EVM based chain to Graph [Feature] 

### ISSUE THREAD

**Issue by ranjith-edx** [graphprotocol/graph-node#4562]
### Description

Hi i want to create a PR to add our testnet EVM chain to the Graph . I saw the docs of add-chain.md in graph node but i'm not sure it is clear . can anyone in the team share a knowledge on this please.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
If your chain is EVM compatible then you should be able to just configure your RPC endpoint (e.g. via a [toml configuration file](https://github.com/graphprotocol/graph-node/blob/master/docs/config.md#configuring-ethereum-providers), or you can just specify as a [docker environment variable](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L22))
