### ISSUE TITLE
[Feature] Support environment variables in subgraph manifest

### ISSUE THREAD

**Issue by 0xalecks** [graphprotocol/graph-node#4591]
### Description

Would be great if I can reference environment variables in the subgraph.yaml file. For local development in a team, each dev might have different contract addresses, which means keeping a constantly unstaged subgraph.yaml file around

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
hey @0xalecks have you tried using the `networks.json` file as part of local development? There you can pull from a local file at subgraph build time
docs: https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#deploying-the-subgraph-to-multiple-networks

**Comment by azf20** [comment]
Closing based on proposed `networks.json` solution in `graph-cli`, please re-open if that doesn't work!
