### ISSUE TITLE
Implement index removal tooling

### ISSUE THREAD

**Issue by avandras** [graphprotocol/graph-node#4613]
Our hosted databases contain a lot of generated indexes, most of which are unused.  These occupy a significant amount of storage, pose overhead on all DML operations (resulting in CPU usage without much worth), and makes things a bit messy overall.  

If we could get rid of them, we could move the DBs to instances with smaller storage, thus saving some money, and also relieve the instances from some of the load, which every now and then causes live issues.

In case of DBs with (read) replicas, one has to consider index usage on the replicas as well.  Here we can leverage the already defined foreign servers.

The workflow looks like:
- set up the necessary tables, functions, and procedures
- collect index usage statistics from `pg_stat_user_indexes`
- remove attribute indexes from deployments that are older than 2 months (we can assume these won't be needed if they haven't seen usage in so many months)
- store the definition of the removed indexes in a separate table, as a safety net

**Comment by avandras** [comment]
After some adjustments of the logic, I started removing indexes from fraction-7727, where there were originally 33k+ indexes eligible for removal.  Will leave it running for a while to assess impact on resource consumption, then turn to removal in prod once the results seem satisfying.

**Comment by avandras** [comment]
Some more testing and actual usage on production results in more changes (some differences in function definition on Postgres 13 vs 14, more importantly a couple of performance improvements, and using host-specific scripts without `pg_service.conf`).

**Comment by neysofu** [comment]
Done, closing.
