### ISSUE TITLE
[Feature] Support envsubst in config file

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4636]
### Description

It would be great if the graph node config file supported [envsubst](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) or something similar so that secrets can be stored in the environment rather than directly in the config. 

This would help with the security of graph node deployments and improve overall hygiene of how graph node is configured. As inspiration, [here's another open source tool](https://vector.dev/docs/reference/configuration/#environment-variables) which has a similar feature.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by paymog** [comment]
> Some configuration sections do indeed have built-in support for env. var. expansion. For anything more complicated we already ship `envsubst` (not GNU, but [`a8m/envsubst`](https://github.com/a8m/envsubst)) in the official Docker image.

oh wonderful! are there docs on which sections support env var expansion? Is it well documented that `envsubst` is in the official docker images? are there examples of how to use it?

**Comment by neysofu** [comment]
Closing in favor of https://github.com/graphprotocol/graph-node/issues/4678.
