### ISSUE TITLE
New contributor struggling to run cargo watch

### ISSUE THREAD

**Issue by jtfirek** [graphprotocol/graph-node#4646]
### Bug report

Hello I am an advocate for the graph and I would like to create some resources to help people start contributing to the graph node and I was also planning on starting to contribute myself!

I am having some trouble running the recommend command from the [contribution page](https://github.com/graphprotocol/graph-node/blob/master/CONTRIBUTING.md#development-flow)

After running `cargo install cargo-watch && rustup component add rustfmt-preview`, I am getting errors when running the command:
```
cargo watch                       \
    -x "fmt --all"                 \
    -x check                      \
    -x "test -- --test-threads=1" \
    -x "doc --no-deps"
```

I fixed some of the errors by switching over to nightly `rustup override set nightly`. But the command is currently not working do to this error.

Thanks any help is appreciated. Also wow this is an awesome repo all the documentation and git standards are so clean and clear. Also feel free to let me know about any other dev flow things I can add to the contribution doc.

### Relevant log output

```Shell
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/jacobfirek/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/jacobfirek/.nvm/versions/node/v18.12.1/bin:/opt/homebrew/opt/openjdk/bin:/Users/jacobfirek/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Ve

  = note: ld: library not found for -lpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `migrations_macros` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by incrypto32** [comment]
@jtfirek can you try installing `libpq`

You can run `brew install libpq` that should solve this issue

**Comment by neysofu** [comment]
Thanks @incrypto32! Indeed that should work, please let us know @jtfirek if the issue persists.
