### ISSUE TITLE
[Bug] Tendely not syncing

### ISSUE THREAD

**Issue by YarikRevich** [graphprotocol/graph-node#4668]
### Bug report

After the latest updates of Tenderly JSON-RPC graph-node stopped syncing with Tenderly forks. It gets stuck on "Downloading latest blocks from Ethereum" and even lowering GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE and ETHEREUM_REORG_THRESHOLD does not help

### IPFS hash

QmfPJTX4FuDru4zopahcTeRQdW7NwW77CKmKdidQzNvfHm

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by incrypto32** [comment]
Also after the `Downloading latest blocks from Ethereum` log

can you see some logs like these?

```
Jun 06 02:21:54.231 INFO Set subgraph start block, block: Some(#6307509 (5446d96493ad228d994e1ba47a6cf5f9fc1622781faf30a0fc2b186f3b093b85)), sgd: 0, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphRegistrar
Jun 06 02:21:54.231 INFO Graft base, block: None, base: None, sgd: 0, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphRegistrar
Jun 06 02:21:54.837 INFO Resolve subgraph files using IPFS, n_templates: 0, n_data_sources: 1, sgd: 1, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphInstanceManager
Jun 06 02:21:54.843 INFO Successfully resolved subgraph files using IPFS, features: nonFatalErrors, n_templates: 0, n_data_sources: 1, sgd: 1, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphInstanceManager
Jun 06 02:21:54.875 INFO Starting subgraph writer, queue_size: 5, sgd: 1, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphInstanceManager
Jun 06 02:21:54.913 INFO Data source count at start: 1, sgd: 1, subgraph_id: QmQ4MLVSkSSRTzuTFVae5jMffZoifEicttA11ZHUQ173ED, component: SubgraphInstanceManager

```

**Comment by incrypto32** [comment]
@YarikRevich i cannot reproduce this, I've tried it with a tenderly fork and everything seems to be working fine for me, Can you give me steps for reproduction? maybe it has to do with the subgraph itself that you are trying to run

**Comment by YarikRevich** [comment]
@incrypto32 I used the following environment variables to make it work before:
- ETHEREUM_POLLING_INTERVAL: 1000
- ETHEREUM_REORG_THRESHOLD: 50
- ETHEREUM_BLOCK_BATCH_SIZE: 20
- GRAPH_ETHEREUM_REQUEST_RETRIES: 20
- GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: 1000
- GRAPH_ETHEREUM_BLOCK_INGESTOR_MAX_CONCURRENT_JSON_RPC_CALLS_FOR_TXN_RECEIPTS: 2000
