### ISSUE TITLE
[Bug] Going back from firehose ingestor to rpc-based ingestor is broken

### ISSUE THREAD

**Issue by sduchesneau** [graphprotocol/graph-node#4670]
## Steps to reproduce:
1) launch graph-node with a subgraph, without any rpc provider, so that firehose is used as the blockIngestor
2) restart graph-node without firehose, using rpc provider as the blockingestor and stream source for the subgraph
3) observe the following debug logs: `DEBG Block stream produced a non-fatal error, error: missing field `parentHash`,`

## Workaround
* Flushing the block cache fixes the issue

## Explanation
The "firehose block ingestor" is implemented differently that the "rpc block ingestor". It only saves the block hash and number to the database:

https://github.com/graphprotocol/graph-node/blob/3d6645ed3a65772dfa7ba522e8d8908ceb7cd393/store/postgres/src/chain_store.rs#L1740-L1745 
(called from 
https://github.com/graphprotocol/graph-node/blob/master/graph/src/blockchain/firehose_block_ingestor.rs#L153)

The "rpc block ingestor" saves more data in the database:
https://github.com/graphprotocol/graph-node/blob/3d6645ed3a65772dfa7ba522e8d8908ceb7cd393/store/postgres/src/chain_store.rs#L1570-L1574
(called from ingest_block() in https://github.com/graphprotocol/graph-node/blob/master/chain/ethereum/src/ingestor.rs#L181)

## Proposed solution
either:
1) fix the firehose-based ingestor so that it adds all the required fields (namely, parent_hash)
2) add a check on graph-node start: if the subgraphs are being served from RPC for a given chain, validate that the blocks are complete in the database or flush the cache)

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by sduchesneau** [comment]
@neysofu interesting. Maybe this is a regression, then ? Or maybe it does not affect subgraphs that have only a BlockHandler.

**Comment by sduchesneau** [comment]
I can reproduce the issue locally, like this:
1) launch with firehose provider
2) deploy a subgraph with initialBlock very close to HEAD and let it sync
3) unassign the subgraph 
4) leave it running for a bit, so that firehose blocks come in
5) restart with rpc provider
6) reassign the subgraph
observe: ```Jun 07 16:55:56.674 DEBG Block stream produced a non-fatal error, error: missing field `parentHash`, sgd: 1, subgraph_id: QmcG9dxbE5Eyoyz2mgRabTDNrGVwPoZBiyWFaUXmkhJ4gN, component: SubgraphInstanceManager```

**Comment by sduchesneau** [comment]
So, the issue is that the table chainXX.blocks gets filled with blocks where `data->'block'->'data' = 'null'::jsonb`, and subgraphs try to get the data from that table when using the rpc-based block-stream, then decoding the `null` into a block fails with "missing field `parentHash`".

Possible solutions:
1) when launching graph-node without firehose-based blockstream, run the following command automatically: `delete from chainXX.blocks where data->'block'->'data' = 'null'::jsonb;`

note: this will *still* fail the subgraphs temporarily, with a `block not found` error until the blocks are fetched again by the indexer

2) when launching graph-node without firehose-based blockstream, figure out if there are any `null` blocks in the cache (`select count(*) from chainXX.blocks where data->'block'->'data' = 'null'::jsonb;` != 0) and if it's the case, truncate the whole block cache

3) make firehose-based ingestor actually SAVE the blocks in the cache, like RPC does, so that the blocks are still being saved.

**Comment by paymog** [comment]
In addition to above, I think it's important that we add an index on the block cache to make the delete and select queries run quickly. The following index should work:

```
CREATE CONCURRENTLY INDEX on chainX.blocks USING BTREE ((data->'block'->'data'));
```

**Comment by sduchesneau** [comment]
Since we're not interested in the actual block->data, this index will be more efficient:
CREATE INDEX on chainX.blocks USING BTREE ((data->'block'->'data')) where data->'block'->'data' = 'null'::jsonb;
