### ISSUE TITLE
loadRelated throws error saying column does not exist

### ISSUE THREAD

**Issue by mihoward21** [graphprotocol/graph-node#4682]
### Which packages are impacted by your issue?

@graphprotocol/graph-ts

### Describe the issue

I'm trying to use the new `loadRelated` feature, but keep getting an error. Have tried with a few different entities but I am getting a column does not exist error each time: `Subgraph failed with non-deterministic error: store error: column "liquidSplit" does not exist`

### Reproduction

https://github.com/0xSplits/splits-subgraph/blob/custom-liquid-split/src/liquid-split.mapping.ts#L312

### Steps to Reproduce the Bug or Issue

When data is syncing, this line triggers an error: `let holders = store.loadRelated('LiquidSplit', liquidSplitId, 'holders');`

### Expected behavior

I would expect that line to load the `Holder` entities that are on that derived from property `holders` of `LiquidSplit`.

### Platform

- @graphprotocol/graph-ts@0.29.3

### Subgraph GraphQL Schema

```
type LiquidSplit implements Account @entity {
  id: ID!

  holders: [Holder!]! @derivedFrom(field: "liquidSplit")
}

type Holder @entity {
  id: ID!
  liquidSplit: LiquidSplit!
  account: Account!
  ownership: BigInt!
}
```

**Comment by mihoward21** [comment]
hey @incrypto32, thanks for the fix here it looks to be working.

I am running into one case where I'm still seeing an issue though. Not sure if it's the expected behavior or another bug.

I have two call handlers that are processing data for the same transaction. The first one runs and creates the related entity. Then the second one tries to load it but it seems to not exist yet or something. Is that expected behavior? Happy to share some code / open a new ticket if that helps.

Outside of that case where i'm creating and loading within the same transaction, the `.load()` is working as expected for me.

**Comment by incrypto32** [comment]
Hey @mihoward21 that is not the expected behaviour. Would you be able to provide a reproducible example? I will investigate
