### ISSUE TITLE
[Bug] RPC issues with Ganache node running locally

### ISSUE THREAD

**Issue by luzzif** [graphprotocol/graph-node#4689]
### Bug report

So, I have a Docker Compose setup which runs an IPFS node, a Postgres database and the Graph node. The Graph node then connects to a local Ganache node forking Gnosis chain running on the host machine. Everything seems to work fine except I keep seeing these errors while bootstrapping the Graph node:

```
WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #11) with result Err(Decoder error: Error("invalid length 0, expected a (both 0x-prefixed or not) hex string with length of 64", line: 0, column: 0)), provider: xdai-rpc-0
```

I think I know the cause of the issue, it must be because the genesis block for xDai/Gnosis actually has a couple attributes set to null. I've debugged the Ganache instance and that's what I get back from the fallback RPC (the official https://rpc.gnosischain.com) while calling `eth_getBlockByNumber(0, false)`:

```
{
    author: '0x0000000000000000000000000000000000000000',
    difficulty: '0x20000',
    extraData: '0x',
    gasLimit: '0x989680',
    gasUsed: '0x0',
    hash: '0x4f1dd23188aab3a76b463e4af801b52b1248ef073c648cbdc4c9333d3da79756',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    miner: '0x0000000000000000000000000000000000000000',
    number: '0x0',
    parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
    receiptsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
    signature: '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    size: '0x215',
    stateRoot: '0x40cf4430ecaa733787d1a65154a3b9efb560c95d9e324a23b97f0609b539133b',
    step: 0,
    totalDifficulty: '0x20000',
    timestamp: '0x0',
    transactions: [],
    transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    uncles: []
}
```

As you notice, a couple things are off. In particular:

- `extraData` is null, and the Graph node fails parsing the block at this point. Now I'm not sure if this is a Graph node/rust-web3 issue or the block spec actually expects the value to be strictly non-null, but in any case, the Gnosis chain's Genesis block has `extraData` set to null. 
- `mixHash` and `nonce` are missing from the fallback provider, but filled in by Ganache and set to `0x` (null). Now this might actually be a Ganache issue, if these 2 fields strictly can't be null, or a maybe a `rust-web3` library issue if they can indeed be null.

I'm open to submitting PRs if I can get some direction on the 2 points above. On point 1 I could probably open a PR on the `rust-web3` library if necessary, and on point 2 too (otherwise I'll just try to open PRs on Ganache).

Also, I'm not really sure how Gnosis chain/xDai are supported on the hosted service given that I have these 2 errors here (the second one I can understand only happening in my case specifically because of Ganache filling in data that is not there in the fallback `getBlock` call, but the other one... do you set a different genesis block number for Gnosis?)  

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by luzzif** [comment]
I also think this could be linked and potentially the same issue: https://github.com/graphprotocol/graph-node/issues/3450

**Comment by incrypto32** [comment]
Interesting, I'll investigate. though i think this might be an issue to be sent to [trufflesuite/ganache](https://github.com/trufflesuite/ganache) since ganache should behave exactly similar to what other RPC nodes do.

You do not get the error when connecting directly to a gnosis rpc right?

**Comment by luzzif** [comment]
I actually do, because of the `extraData` being set to null (`0x`) on Gnosis Chain's genesis block. The workaround I found is to set the genesis block to a later number through the `GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER` env/
