### ISSUE TITLE
 lifetime may not live long enough

### ISSUE THREAD

**Issue by supermigo** [graphprotocol/graph-node#4693]
error: lifetime may not live long enough
   --> chain/substreams/src/trigger.rs:191:50
    |
179 |       async fn process_trigger(
    |       ----- lifetime `'async_trait` defined here
...
182 |           _: Box<dyn Iterator<Item = &T::Host> + Send + '_>,
    |           - has type `Box<(dyn Iterator<Item = &<T as graph::prelude::RuntimeHostBuilder<chain::Chain>>::Host> + std::marker::Send + '1)>`
...
191 |       ) -> Result<BlockState<Chain>, MappingError> {
    |  __________________________________________________^
192 | |         for entity_change in block.changes.entity_changes.iter() {
193 | |             match entity_change.operation() {
194 | |                 Operation::Unset => {
...   |
286 | |         Ok(state)
287 | |     }
    | |_____^ associated function was supposed to return data with lifetime `'async_trait` but it is returning data with lifetime `'1`

error: could not compile `graph-chain-substreams` due to previous error

**Comment by supermigo** [comment]
use cargo update. , will get this question issues

**Comment by maoueh** [comment]
Closing since the issue seems to be resolved and compilation passes for all developers AFAIK. If it's not solve, check your Rust version.
