### ISSUE TITLE
[Bug] SSL_get1_peer_certificate

### ISSUE THREAD

**Issue by supermigo** [graphprotocol/graph-node#4694]
### Bug report

  = note: /root/graph-node/target/debug/deps/libopenssl-44643c56f48dace0.rlib(openssl-44643c56f48dace0.openssl.12493cdd-cgu.1.rcgu.o): In function `openssl::ssl::SslRef::peer_certificate':
          /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.54/src/ssl/mod.rs:2512: undefined reference to `SSL_get1_peer_certificate'
          /root/graph-node/target/debug/deps/libopenssl-44643c56f48dace0.rlib(openssl-44643c56f48dace0.openssl.12493cdd-cgu.11.rcgu.o): In function `openssl::error::Error::get':
          /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.54/src/error.rs:122: undefined reference to `ERR_get_error_all'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
Closing, please add more details on how to reproduce
