### ISSUE TITLE
[Bug] Can't query related entity if current entity has id of type Bytes

### ISSUE THREAD

**Issue by mihoward21** [graphprotocol/graph-node#4701]
### Bug report

My schema looks like this:

```
interface Account {
  id: Bytes!
}

type User implements Account @entity {
  id: Bytes!
}

type Oracle @entity {
  id: Bytes!
  owner: Account!
}
```

When I try to query for the oracles owner, I get the following error: "Failed to get entities from store: operator does not exist: bytea = text"

If I change the oracle id type to ID!, then the query runs fine. Was trying to switch all of my id's over to Bytes per this article: https://thegraph.com/blog/two-simple-subgraph-performance-improvements/

I think it should be working as I have things setup? If not, or if I'm doing something wrong please let me know!

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/0xsplits/splits-subgraph-goerli-testing

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
Thanks @mihoward21 - this query reproduces:

```
{
  oracles {
    owner {
      id
    }
  }
}
```

https://api.thegraph.com/subgraphs/name/0xsplits/splits-subgraph-goerli-testing/graphql?query=%7B%0A++oracles+%7B%0A++++owner+%7B%0A++++++id%0A++++%7D%0A++%7D%0A%7D

**Comment by mihoward21** [comment]
Just wanted to follow up here, see if there's anything I can do to help out.

I had to update that subgraph I originally linked to so it no longer hits the error. Happy to spin up a new one that hits the error if that is needed.

**Comment by rolandsaven** [comment]
I have the same issue. I don't have any interfaces present.

```graphql
type Recipe @entity {
  id: Bytes!
  ingredients: [Ingredient!]! @derivedFrom(field: "recipe")
}

type Ingredient @entity {
  id: Bytes!
  recipe: Recipe!
}
```

First of all, using the default loader result in a Value error.
```ts
let recipe = Recipe.load(
 Bytes.fromString('0x01')
);

recipe.ingredients.load();
```

Result in 
```
Subgraph instance failed to run: Mapping aborted at ~lib/@graphprotocol/graph-ts/common/value.ts, line 80, column 5, with message: Value is not a string. wasm backtrace: 0: 0x2f51 - <unknown>!~lib/@graphprotocol/graph-ts/common/value/Value#toString 1: 0x80c9
```


I can overcome this by using the `loadRelated` function directly, however, this still throws an error that is mentioned by @mihoward21

```ts
let recipe = Recipe.load(
 Bytes.fromString('0x01')
);

let ingredients = store.loadRelated(
      "Recipe",
      recipe.id.toHexString(), // recipe.id is Bytes
      "ingredients"
);
```

This will result in the following error, which indicated that the derived loader does not seem to support `Bytes`
```
Subgraph failed with non-deterministic error: failed to process trigger: block #34191029 (0x1f55…c68b), transaction 300becc0b0119422755c2b965f86b8248a88ff4e0b290a1e3dfedaf11ce08a64: store error: operator does not exist: bytea = text wasm backtrace: 0: 0x70fd - 
```

**Comment by rolandsaven** [comment]
> Just wanted to follow up here, see if there's anything I can do to help out.
> 
> I had to update that subgraph I originally linked to so it no longer hits the error. Happy to spin up a new one that hits the error if that is needed.

Did you convert back to `ID`-s?

**Comment by mihoward21** [comment]
> Did you convert back to ID-s?

Yea, I can't use Bytes for the id until this is resolved.
