### ISSUE TITLE
[Bug] block sync always delays

### ISSUE THREAD

**Issue by zhuque** [graphprotocol/graph-node#4708]
### Bug report

When running with v0.31.0 image. the  block is far distance from the latest block.  found lot's of logs .

> Jun 20 13:03:50.957 DEBG no chain head update for 30 seconds, polling for update, sgd: 7, subgraph_id: QmPJEjiqhvrw7HX25DaxdstDqehnHcUEpZJpjtTrmzkCxP, component: BlockStream
> Jun 20 13:04:20.959 DEBG no chain head update for 30 seconds, polling for update, sgd: 7, subgraph_id: QmPJEjiqhvrw7HX25DaxdstDqehnHcUEpZJpjtTrmzkCxP, component: BlockStream
> Jun 20 13:04:50.960 DEBG no chain head update for 30 seconds, polling for update, sgd: 7, subgraph_id: QmPJEjiqhvrw7HX25DaxdstDqehnHcUEpZJpjtTrmzkCxP, component: BlockStream
> 

The program sleeps long time during thoes logs. when set the log level to trace, lot's of logs like the below shows

> Jun 20 13:07:47.015 TRCE Run with retry: eth_getTransactionReceipt RPC call for transaction 0x7642f45330b192f9ed12e3f95c91ab4e76f94d4b1d62a3c04aa836da505a0aa3, provider: arbitrum-one-rpc-0, component: EthereumPollingBlockIngestor
> Jun 20 13:07:47.015 TRCE Run with retry: eth_getTransactionReceipt RPC call for transaction 0x0c372477306cb74d692a0237413ab8e5e7918cb3fd3ef089c67b78793266b1ed, provider: arbitrum-one-rpc-0, component: EthereumPollingBlockIngestor
> Jun 20 13:07:47.015 TRCE Run with retry: eth_getTransactionReceipt RPC call for transaction 0xa4352c87f4bc2e3b349254206d13a3d73b2b72f55d96c31ab6cfa3434405255f, provider: arbitrum-one-rpc-0, component: EthereumPollingBlockIngestor
> Jun 20 13:07:47.015 TRCE Run with retry: eth_getTransactionReceipt RPC call for transaction 0xf78bea8c043d6f1e0e4ab858bcababa256040b6ff08e7b7df0dad8c01b5d06e5, provider: arbitrum-one-rpc-0, component: EthereumPollingBlockIngestor

Attempted to use different RPC providers, but the issue was not resolved. I noticed that the block in the ***block*** table is much newer than the block being processed. Not sure if this is the cause here.

**Comment by chanson-chan** [comment]
I have resolved the issue of delay by adjusting the parameter ETHEREUM_REORG_THRESHOLD to 5. However, the underlying rationale behind how this parameter reduces the delay is not yet clear to me.

**Comment by azf20** [comment]
hey @zhuque can you confirm if you're using a regular RPC or perhaps a forked network?

**Comment by azf20** [comment]
Closing, please re-open if you are still experiencing this issue
