### ISSUE TITLE
[Bug] FATAL:  no pg_hba.conf entry for host "172.19.0.4", user "graph-node", database "graph-node", no encryption

### ISSUE THREAD

**Issue by ChrisChan888** [graphprotocol/graph-node#4709]
### Bug report

FATAL:  no pg_hba.conf entry for host "172.19.0.4", user "graph-node", database "graph-node", no encryption

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by leoyvens** [comment]
The error seems like a general DB connection issue, not specific to graph node
