### ISSUE TITLE
Must Type `uint256` for subgraph.yaml instead of `uint`

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#471]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you copy the abi directly, and the contract developer used `uint` instead of `uint256`, the event topic will not match, and the subgraph will not pick it up. In solidity, `uint` is an alias  for `uint256`

**What is the expected behavior?**

We should either handle both (the hash should always resolve to uint256 being used everywhere) or we explicitly note in the docs you must fix this.

**Comment by Jannis** [comment]
There's at least two things we can do here:

1. Normalize signatures: remove spaces, parameters names and normalize type names.
2. Validate that the event signature is part of the ABI at all.

Both would be good to do at build time. That would be in graph-cli actually.

**Comment by Jannis** [comment]
We now validate subgraphs in graph-cli and would catch invalid event handlers.
