### ISSUE TITLE
[Bug] creating related entity and loading in the same transaction not working

### ISSUE THREAD

**Issue by mihoward21** [graphprotocol/graph-node#4727]
### Bug report

I have two call handlers, one is creating a related entity and the other is loading it. That is working as expected except for the case where both handlers are running on the same transaction. In that case the first call handler runs and creates the entity. Then the second handler runs but when it goes to load the related field it's not finding the entity that was just created.

Here's an example [query](https://api.thegraph.com/subgraphs/name/0xsplits/splits-subgraph-goerli-testing/graphql?query=%7B%0A++user%28id%3A%220xfaa66ecff431321498be86ebfaa92b8a3f9b604a%22%29%7B%0A++++contractEarnings%7B%0A++++++contract+%7B%0A++++++++id%0A++++++%7D%0A++++++internalBalances+%7B%0A++++++++token+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++amount%0A++++++%7D%0A++++++withdrawals%7B%0A++++++++token+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++amount%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D)
In that example, the first call handler creates a `ContractEarnings` entity and sets an internal balance for it. The second call handler loads all `ContractEarnings` on the user object and moves the internal balances over to the withdrawals. I did one contract (id `0x021b97710febaf68ed56349acd46eb9e27d29a00`) in two separate transactions. The other contract (id `0x35530ee9bda38fdc0877f93d946908fb473552fd`) I ran a multicall so both steps were performed in the same transaction. You can see in the latter case there's still a balance in the internal balances, and the withdrawals are empty. Seems like the `.load` isn't finding the newly created `ContractEarnings` related entity on the user object in that case.

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/0xsplits/splits-subgraph-goerli-testing

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by mihoward21** [comment]
Happy to provide any more info that will help.

**Comment by incrypto32** [comment]
Thanks for creating the issue, I will take a look and comment here.

**Comment by mihoward21** [comment]
hey @incrypto32 just wanted to see if you had any updates. If there's any info or examples or anything I can provide that would help out let me know.

**Comment by mihoward21** [comment]
@incrypto32  Yea, let me try to map it out for you and link you to all the right places, it's not super straightforward.

Here's the [manifest](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/subgraph.template.yaml), I think it's setup correctly for this case. You can see `handleWithdrawCall` comes after `handleDistributeETHCall`

Here is where [handleDistributeETHCall](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/src/ethereum.mapping.ts#L253) and [handleWithdrawCall](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/src/ethereum.mapping.ts#L525) are defined, though most of the logic lives in some helper functions.

`handleDistributeETHCall` calls this function, [distributeSplit](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/src/helpers.ts#L247). That will go through the split and for each recipient on the split, it will call [addInternalBalance](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/src/helpers.ts#L69). Within that function the important part is we are creating a new ContractEarnings entity and a new ContractEarningsInternalBalance entity (if the id's don't exist yet), and updating the internal balance amount.

`handleWithdrawCall` calls `handleTokenWithdrawal` which calls `updateWithdrawalAmount`. Within that function, [here](https://github.com/0xSplits/splits-subgraph/blob/contract-earnings/src/helpers.ts#L536) is the important section. It calls `let contractEarningsArray = account.contractEarnings.load();` and then loops through that array and moves all associated ContractEarningsInternalBalances amounts over to ContractEarningsWithdrawal entities.

I think that's all working properly because if I do the distribution and withdrawal in separate transactions everything works fine. But when I do them together in a multicall I end up with the ContractEarningsInternalBalance still having an amount and no ContractEarningsWithdrawal entity was created. I'm assuming that `account.contractEarnings.load()` is not actually loading anything when it's all happening in one transaction, but i'm not entirely sure.

The example query I posted before got messed up, [here](https://api.thegraph.com/subgraphs/name/0xsplits/splits-subgraph-goerli-testing/graphql?query=%7B%0A++user%28id%3A%220x6647a2738b0006b3cbeb320f8cfe9e9582b8c394%22%29%7B%0A++++contractEarnings%7B%0A++++++contract+%7B%0A++++++++id%0A++++++%7D%0A++++++internalBalances+%7B%0A++++++++token+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++amount%0A++++++%7D%0A++++++withdrawals%7B%0A++++++++token+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++amount%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D) is a new one that shows one working flow from two transactions and one incorrect one from a multicall transaction.

**Comment by incrypto32** [comment]
Thanks @mihoward21 , i took a look at it, will get this prioritsed

**Comment by incrypto32** [comment]
@mihoward21 this is now on hosted service. Your use case should be working now.

**Comment by mihoward21** [comment]
amazing thank you!
