### ISSUE TITLE
How to set start block to load data from when creating local graph node

### ISSUE THREAD

**Issue by millicare** [graphprotocol/graph-node#4728]
### Bug report

I'm trying to run my own graph node for avalanche network and it seems like it is loading data for only latest blocks.
My contract which would be deployed to graph node created long time ago so I may need graph node to keep all blocks on avalanche network or at least from the block number I would specify. How can I do that when deploying graph node? Is there any config option for that?

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
Hi - data for historical blocks is fetched on an as-needed basis from the rpc, recent blocks are loaded for syncing subgraphs near the chain head, so if you deploy a subgraph graph-node will request the data it needs
