### ISSUE TITLE
[Bug] where or operation error structure

### ISSUE THREAD

**Issue by huazhuangnan** [graphprotocol/graph-node#4732]
### Bug report

Structure ``` ... where: { or: { xxx_contains_nocase: "xxx", xxx_contains_nocase: "xxx"}} ...``` query is not work
``` ... or: { xxx_contains_nocase: "xxx", xxx_contains_nocase: "xxx"} ... ``` query work

### Relevant log output

```Shell
Invalid value provided for argument `where`: Object({\"or\": Object({\"name_contains_nocase\": String(\"xx\"), \"symbol_contains_nocase\": String(\"xx\")})})
```

### Subgraph name or link to explorer

https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2/graphql?query=query+MyQuery+%7B%0A++tokens%28where%3A+%7Bor%3A+%7Bname_contains_nocase%3A+%22xx%22%2C+symbol_contains_nocase%3A+%22xx%22%7D%7D%29+%7B%0A++++name%0A++++symbol%0A++%7D%0A%7D

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Windows

**Comment by azf20** [comment]
hi @huazhuangnan I think you need [the following query](https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2/graphql?query=query+MyQuery+%7B%0A++tokens%28%0A++++where%3A+%7Bor%3A+%5B%7Bname_contains_nocase%3A+%22xx%22%7D%2C+%7Bsymbol_contains_nocase%3A+%22xx%22%7D%5D%7D%0A++%29+%7B%0A++++name%0A++++symbol%0A++%7D%0A%7D):
```
query MyQuery {
  tokens(
    where: {or: [{name_contains_nocase: "xx"}, {symbol_contains_nocase: "xx"}]}
  ) {
    name
    symbol
  }
}
```
