### ISSUE TITLE
[Feature] Do not cache invalid eth_call results in case node returned invalid results.

### ISSUE THREAD

**Issue by SozinM** [graphprotocol/graph-node#4756]
### Description

During the implementation of https://github.com/graphprotocol/graph-node/pull/1270 it was discussed that we probably should not cache invalid data.
We experienced this issue with the following graph-node logs:
```
 Jul 11 15:11:32.995 DEBG eth_call, data: a290bf38000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000005ab, address: d2863157539b1d11f39ce23fc4834b62082f6874, sgd: 271, subgraph_id: QmW7j8ipQ8cbf8agCLYjRgJkxwUaS9F8Xa46XkCfSFPUxW, component: SubgraphInstanceManager
 Jul 11 15:11:33.010 INFO Contract call reverted, reason: empty response, sgd: 271, subgraph_id: QmW7j8ipQ8cbf8agCLYjRgJkxwUaS9F8Xa46XkCfSFPUxW, component: SubgraphInstanceManager
```
The eth call is on block 44939006.
This was caused by the node outage (that happened at the same time) which caused eth_call to return an invalid result.
After that eth_call was cached and we needed to clean the eth_call call for this block.

CC @leoyvens @Jannis 

### Some information to help us out

- [X] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by balakhonoff** [comment]
Just my two cents, it is really hard to track that some wrong node responses lead to the wrong cache, and we know about it only from the customers, because only they know that the code which shouldn't raise any errors is actually raising them. And the descriptions of errors always pointing to wrong reasons which is confusing.

**Comment by SozinM** [comment]
Curl with request:
```
curl -H "Content-Type: application/json" -d '{"method":"eth_call","params": [{"data":"0xa290bf38000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000005ab","gas":"0x2faf080","to":"0xd2863157539b1d11f39ce23fc4834b62082f6874"},{"blockHash":"0xf0862352a99eab45a31d5952419c7004e4b6da9fe441ca94782499107977abc0"}],"id":1,"jsonrpc":"2.0"}' <endpoint>
```

**Comment by azf20** [comment]
hey @SozinM what chain is that on?

Agree that invalid data shouldn't be cached, but I think we don't cache nulls / error states, just identifiable reverts, can you share some more about the cached result to see if we need to alter that logic somehow?

**Comment by SozinM** [comment]
Hi @azf20 
Eirgon nodes have specific when they return incorrect data for correct eth_calls few seconds after restart.
For example they return 0x for the first few seconds
```
{"jsonrpc":"2.0","id":1,"result":"0x"}
```
And then they start to return correct data
```
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000012af7fff047174c00000"}
```

So the graph is caching this as the correct data and chain*.call_cache table end up with entries like this:
```
                                 id                                 | return_value |              contract_address              | block_number 
--------------------------------------------------------------------+--------------+--------------------------------------------+--------------
 \x44f783ab496ffd747b83e97f9aede47badb9cc9ebf5387f68b7f7aaddca54b31 | \x           | \xcf2b421011fff1200bd8bf5b9cdc7ea179f445ff |     11267745
```

Also, I'm already working on this issue and will prepare PR the following week.
I plan to invert logic and store cache after decoding and verifying that the eth_call return value is valid in here https://github.com/graphprotocol/graph-node/blob/70a2c99eab1da27e970fe6fe22459fbd26417f28/chain/ethereum/src/ethereum_adapter.rs#L1303

I will still store undecoded eth_call results because it will be a bit hard for me to manage migration to different type of cache

**Comment by azf20** [comment]
interesting, thanks I didn't know that about Erigon, is there an issue on the Erigon side for that?

On the proposed approach cc @lutter @incrypto32 in case you have a perspective

**Comment by SozinM** [comment]
We are in the process of discussion in erigon discord. https://discord.com/channels/687972960811745322/873165719372722176/1151131404529324032
I will create an issue when I have enough details and link it here.

**Comment by incrypto32** [comment]
@azf20 @SozinM  My understanding was that we consider `0x` as a revert and we didn't cache it. But in the code it looks like thats not the case. 

@SozinM The implementation sounds good to me, we do the decoding anyways, so it makes sense to cache the result after the decoding is successful.

I'd also let @lutter comment on his thoughts on your plan @SozinM

**Comment by SozinM** [comment]
https://github.com/graphprotocol/graph-node/pull/4879 - I will refactor it a bit and test everything, but that's outline for changes I want to do

**Comment by SozinM** [comment]
@incrypto32 @lutter @azf20 
I tested this code, everything works as expected.
Correct calls are getting cached, calls that return 0x are not getting cached.

I would like you to review the code and give me some pointers on how to refactor it.
I've added comments to the places if feel like need refactoring so you could add your comments too!

**Comment by incrypto32** [comment]
Thanks, Will take a look Monday.

**Comment by SozinM** [comment]
Bump @incrypto32

**Comment by incrypto32** [comment]
Hey @lutter will be reviewing it later this week or next.
