### ISSUE TITLE
[Feature] Support Substreams on networks where no `chain` implementation exists yet in `graph-node`

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4769]
### Description

This is a follow up of #4302 see it for general description. See also https://github.com/graphprotocol/graph-node/issues/4302#issuecomment-1632714489 which could be used to implement a `SubstreamsBlockIngestor`, one of the main problem in solving this issue.

First objective of this would be to support Solana Substreams powered Subgraph.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by maoueh** [comment]
Tested on Solana, had a small problem because the start block there is not 0 and on start with make a request to get the genesis block. 

Does `graph-node` has support to change what is the genesis block of a chain in the config?

**Comment by maoueh** [comment]
Config tested:

```
[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.sol-mainnet]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams", details = { type = "substreams", url = "https://mainnet.sol.streamingfast.io:443", token = "$SUBSTREAMS_API_TOKEN", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]
```

**Comment by maoueh** [comment]
And the RPC response:

```
Oct 26 10:48:43.245 INFO Next response received Error: Status { code: Unknown, message: "rpc error: code = InvalidArgument desc = invalid start block 0, must be >= 1690600 (the first streamable block of the chain)", details: b"\x08\x02\x12|rpc error: code = InvalidArgument desc = invalid start block 0, must be >= 1690600 (the first streamable block of the chain)", source: None }, provider: substreams, deployment: , component:
```

**Comment by maoueh** [comment]
Seems that 0 not respected by Substreams is actually a backend problem as Firehose accepts this and we made already some change to accepte `initialBlock: 0` as chain's genesis.

Tracked via https://github.com/streamingfast/substreams/issues/290#issuecomment-1781728171, I think we will be good to go after that.

**Comment by azf20** [comment]
Thanks @maoueh is this ok to close now?

**Comment by maoueh** [comment]
Yes let's close it, works as expected.

**Comment by maoueh** [comment]
There is #4942 remaining but it's not a blocker

**Comment by nabeel99** [comment]
Hey, has there been any updates to this, is there any ongoing effort to integrate solana in the graph-node to enable subgraph as a sink for solana-substreams ?

**Comment by matthewdarwin** [comment]
It works as of graph-node 0.35.

**Comment by nabeel99** [comment]
> It works as of graph-node 0.35.

cool, was trying to find the p.r that impl the support for solana, as i could not find anything related to it in the release notes for 0.35.
