### ISSUE TITLE
[Feature] Track handlers in `subgraph_features` table

### ISSUE THREAD

**Issue by incrypto32** [graphprotocol/graph-node#4772]
### Description

It would be nice to have insights into which handlers are used by subgraphs.
eg: If a subgraph uses a call handler or not, How many subgraphs use blockHandlers with call filter etc.

It would also be beneficial to know if the handlers are in a template or a normal datasource.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by Mehmet456** [comment]
yes

**Comment by lazyfuhrer** [comment]
You can assign me @incrypto32

**Comment by incrypto32** [comment]
Alright @lazyfuhrer Thanks, let me know here if you need any clarifications/help.

**Comment by incrypto32** [comment]
@lazyfuhrer how's it going with the implementation, feel free to drop any questions here? Are you actively working on it?

**Comment by incrypto32** [comment]
hmm, that question makes me think if we should take a more structured approach here. 
Like counting the number of handlers for each type of handler. I'll get back to you on this.

**Comment by incrypto32** [comment]
@lazyfuhrer a new column `handlers` which is a string array with values `call`,`block`,`event` etc would do.

**Comment by lazyfuhrer** [comment]
Can you tell me more about the approach? like from where should I start

**Comment by incrypto32** [comment]
[This](https://github.com/graphprotocol/graph-node/blob/aeacbebd09603fae485430d9ce169cee94fe6f90/core/src/subgraph/instance_manager.rs#L267) is where the `subgraph_features` is created.

You'll need to create a new column in that table with a diesel migration, then bring the create a string array of the list of types of handlers, this might be available in the manifest. A little bit of work there.

If you feel like its a bit too much for a good first issue let me know, I can recommend other simpler issues to start with if you are intrested.

**Comment by lazyfuhrer** [comment]
Thanks for the explanation. I'll give you an update soon @incrypto32

**Comment by incrypto32** [comment]
Hey @lazyfuhrer checking in on the status of this. Let me know if you have questions
