### ISSUE TITLE
Nested child filters should be an attestable error

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#4775]
Right now a query such as:
```graphql
{
  marketHourlySnapshots(where: {market_: {inputToken_: {symbol_not: "GHO"}}}) {
    market {
      inputToken {
        symbol
      }
  }
}
```
Will result in the error `Store error: query execution failed: Child filters can not be nested`, which is not attestable according to [QueryExecutionError::is_attestable](https://github.com/graphprotocol/graph-node/blob/a5eedc78364d20b828457aea7f9a5ee3c5187895/graph/src/data/query/error.rs#L79C1-L80). We should make this attestable so the gateway can report it back to users.

**Comment by compojoom** [comment]
So is this a bug, or a missing feature?

**Comment by azf20** [comment]
hey @compojoom a bit of both depending on the use case
