### ISSUE TITLE
[Question] Meaning of 0 entities when committing write batch?

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4786]
### Description

I'm reviewing some of the logs of my graph node and I see the following log line:

```
Jul 27 07:04:14.886 INFO Committed write batch, time_ms: 36, weight: 240, entities: 0, block_count: 1, block_number: 9415777, sgd: 10602, subgraph_id: QmNMRm1BAckERBxwhAE9fd689VMb8vgahZbRTp9jbtXeXQ, component: SubgraphInstanceManager
```

What does it mean for a write batch of have 0 entities but a non zero weight? Does `entities` in this log line measure new rows written to the database and not account for row updates?

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
@paymog I think `entities` should include updates, but @lutter can you provide some colour on what `weight` means here and if any store updates are taking place?

**Comment by lutter** [comment]
IIRC, `entities` includes updates; a write with no entity changes can happen, e.g., when the subgraph is synced to advance the block pointer in the database. When a subgraph is synced, batching is turned off and we write at every block.

The `weight` is a measure of how much memory the entities and some supporting data structures take - it's our best guess at how many bytes that data uses.

**Comment by paymog** [comment]
Got it, thank you for the explanation!
