### ISSUE TITLE
IPFS schema resolution sometimes hangs on start up

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#479]
To reproduce:
- Run graph-node on the `tim/debug-start-up` branch (based on `ethsf`) without `--release` and deploy a subgraph
- Rerun the graph-node (with `--debug`) 10-20 times until it gets stuck at `DEBG Resolving subgraph <ID>`

**Comment by leodasvacas** [comment]
I think #366 fixed this, at least I haven't observed this since.
