### ISSUE TITLE
[Bug] Validate entities before creating Proof of Indexing

### ISSUE THREAD

**Issue by incrypto32** [graphprotocol/graph-node#4791]
### Bug report

When investigating a POI divergence between two graph-node versions, a polygon subgraph `QmWTuqjkyGogHMBuGvQHZjkb189CN4EtGi8ps1yT76Vj9V` diverges at block `45504938`, On further investigation by checking logs the only difference found was a `Proof of Indexing` event log 

<img width="1262" alt="Screenshot 2023-08-04 at 9 05 05 PM" src="https://github.com/graphprotocol/graph-node/assets/44740264/1ad18197-6e23-4897-954c-e0263ea07801">

The `HourlyVolumeBySource` does not have  a field named `marginAndLiquidation` but still that field is being set to 0 in this case.

Here is the [schema](https://api.thegraph.com/ipfs/api/v0/cat?arg=QmfBAQwYcabyiQ9BH5txv8yQiMnBR9V7bba1nLyXRqiRqt) of this subgraph. There is another entity `FeeStat` which has `marginAndLiquidation` entity

### IPFS hash

QmWTuqjkyGogHMBuGvQHZjkb189CN4EtGi8ps1yT76Vj9V

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by leoyvens** [comment]
I'd vaguely suspect there is a determinism issue here related to validation of fields not present in the schema and how that might be different depending on whether the entity is present in the entity cache when being set.
