### ISSUE TITLE
[Bug] Regression: Only Last 2 Fulltext Tags Work

### ISSUE THREAD

**Issue by Faolain** [graphprotocol/graph-node#4794]
### Bug report

Hey all, 

Our users reported that our search functionality no longer worked on our frontend https://dev.marketplace.dclimate.net/ around May 31 which was strange to us as we had not touched that part of our codebase for some time and our subgraph had also not changed. Worst of all we were not seeing this issue locally. We had not gotten a chance to investigate more deeply until recently whereupon @eloramirez1356 did a deep dive and discovered that this issue was not being seen locally (deploying local graph and using local graph node) because our local docker graph node version was fixed to `image: graphprotocol/graph-node:6499d38` and that a change to the graph node since that image has caused this regression to surface on our deployed graph on the hosted service (and this image likely is used on the decentralized service too?) where **Only the Last 2 Fulltext Tags Work on a Schema**.

## Background:
We have the following schema with 4 @fulltext tags which powers our search/filtering functionality, basically the title and description of assets which get published to the graph. 

```
type _Schema_
  @fulltext(
    name: "assetSearch"
    language: en
    algorithm: rank
    include: [
      { entity: "Asset", fields: [{ name: "title" }, { name: "description" }] }
    ]
  )
    @fulltext(
    name: "subscriptionAssetSearch"
    language: en
    algorithm: rank
    include: [
      { entity: "SubscriptionAsset", fields: [{ name: "title" }, { name: "description" }] }
    ]
  )
  @fulltext(
    name: "geohashSearch"
    language: en
    algorithm: rank
    include: [{ entity: "Asset", fields: [{ name: "geohash" }] }]
  )
  @fulltext(
    name: "subscriptionGeohashSearch"
    language: en
    algorithm: rank
    include: [{ entity: "SubscriptionAsset", fields: [{ name: "geohash" }] }]
  )
  ```

This was previously working when deployed to the *hosted service*. This was also working locally. At some point around May 31st this stopped working on the hosted service. After some debugging by @eloramirez1356 it was discovered that

> the first 2 tags (fulltext searches) don't work, but the last 2 works as expected, and if I vary the order of these tags in the schema, doing a new deployment of the schema with the different order, only the last 2 fulltext tags are the ones that works as expected.

So essentially it seems that a graph node image update which occurred around May 31st creates a regression where only the last 2 Fulltext tags work. 

Old Graph Image (Working with 4 Fulltext Queries):
image: graphprotocol/graph-node:6499d38

New Image which definitely doesn't work (but likely it was in a version prior to this one)
image: 0.31.0

## Additional Information**
**Node url to query:** https://api.thegraph.com/subgraphs/name/dclimate/dclimate-dev-marketplace

**Queries to verify the issue** (https://api.thegraph.com/subgraphs/name/dclimate/dclimate-dev-marketplace/graphql?query=%7B%0A++%23Query+to+get+the+asset+which+has+geohash+on+the+title%0A++assets%28where%3A+%7Btitle_contains%3A+%22geohash%22%7D%29%7B%0A++++id%0A++++title%0A++++description%0A++++geohash%0A++%7D%0A%0A++%23+Fulltext+search+by+title+or+description%0A++++assetSearch%28text%3A+%22geohash%22%29+%7B%0A++++id%0A++++title%0A++++description%0A++%7D%0A%0A++%23Fulltext+search+by+geohash%0A++geohashSearch%28text%3A+%22dp3wth%22%29+%7B%0A++++++++++++id%0A++++%09%09%09%09geohash%0A++++++++++++slashed%0A++++++++%7D%0A%7D).

If you execute that query you will see that you receive an asset from the first query which has "geohash" text in the title, but then executing the fulltext search with the same text for titles or descriptions, it does not return anything but it should return the same asset as the first query. 

On the other hand, if we run the last query where we execute a fulltext search by geohash field, if we use the geohash of the asset obtained in the first query, we successfully obtain the same asset of the first query.

This last fulltext works because it is one of the last 2 fulltext tags defined in the schema (suspecting that in node-graph version 0.31.0 only the last 2 tags defined in the schema works, and this did not happen with previous versions)

This last fulltext search works because it was one of the last 2 tags defined in the schema. Only the last 2 are the ones working properly, but the previous ones defined don't work 
![image](https://github.com/graphprotocol/graph-node/assets/9613083/9d6af2dc-b47e-4697-9d47-ffb33e7d5d34)

**Last Notes**

0.31.0 may be the source of the regression since it was shortly after its release where users reported the search functionality no longer working, and it would make sense as it seems there were some fulltext changes? 
 
<img width="379" alt="Screenshot 2023-08-08 at 6 50 44 PM" src="https://github.com/graphprotocol/graph-node/assets/9613083/285d7a37-46bc-40f7-a426-c5e1572a14ac">

**Update** We updated our subgraph schema for our users so that the searchbar works (by switching the order within the schema so that searchbar information is last so now the other fulltext tags regarding geohash do not work) 

### Subgraph name or link to explorer

https://api.thegraph.com/subgraphs/name/dclimate/dclimate-dev-marketplace

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by lutter** [comment]
I can reproduce the issue. It was caused by [this change](https://github.com/graphprotocol/graph-node/pull/4606/commits/ad1c6ead6214906247d32504e542bcb64b8fe74f#diff-b93fca17fcdb1f28e8e50bdfe51a0d010f8630e7d607628604e6eec8806d2dcbR1756-R1775)
