### ISSUE TITLE
[Feature] Configuring Etherum providers using multiple RPC endpoints(httpFallback or quorum)

### ISSUE THREAD

**Issue by josedev-union** [graphprotocol/graph-node#4797]
### Description

We have been operating several graph nodes and facing `get genesis failed` failure frequently when the RPC endpoint is unhealthy or the connection is not good(could be regional issue?).
I want to configure the providers with multiple rcp endpoints as httpfallback mode in which the first rpc endpoint is bad, then fallback to the second one. But I cannot find this kind of feature support mentioning in the doc https://github.com/graphprotocol/graph-node/blob/master/docs/config.md#configuring-ethereum-providers.
Is this built-in function already and just doc not updated?

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
hey @josedev-union you can configure multiple RPC endpoints, but is the issue that you are looking for specific fallback behaviour?

**Comment by josedev-union** [comment]
> hey @josedev-union you can configure multiple RPC endpoints, but is the issue that you are looking for specific fallback behaviour?

@azf20 yeah, i think i can configure multiple RPC endpoints as chain provider url but only one endpoint is used for each subgraph or even for provider health check.

**Comment by matthewdarwin** [comment]
I'm not sure why we should allow multiple RPC endpoints.  User should send queries to proxyd and proxyd can be configured with multiple endpoints.

https://github.com/ethereum-optimism/optimism/tree/4be8847aacaa35cab2a63b274b79567ff6240051/proxyd

**Comment by azf20** [comment]
👍 agree with @matthewdarwin that it makes sense to leverage dedicated proxy tooling here. Closing for now, re-open if you have a different view @josedev-union
