### ISSUE TITLE
[Bug] Huge increase in RAM on the archive node during graph synchronization (up to 60Gb per hour)

### ISSUE THREAD

**Issue by KyrylR** [graphprotocol/graph-node#4800]
### Bug report

When the subgraph follows a logic that requires an RPC call during each event, such as an RPC call to retrieve the account balance when an ERC20 transfer event occurs, the Ethereum Archiving Node experiences a significant increase in RAM. In our situation, the amount of RAM increased to 60GB in just one hour.

Can anyone help determine if this issue is coming from the Graph node or if it is an RPC-side issue?

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
Hey @KyrylR this will depend a bit on the node you are using - but it sounds like this is an issue on the archive node side, the Graph Node is just making eth RPC calls based on the configuration of the subgraph
