### ISSUE TITLE
Question: which blocks are stored in graph-node postgresql database?

### ISSUE THREAD

**Issue by zxsimba** [graphprotocol/graph-node#4802]
We have a self hosted graph-node server which is connected to bsc chain,
when we deploy a new subgraph with a specific start block , graph-node begins to fetch some historical blocks from the specified start block, but I don't know it stores all of them or only relevant blocks? if it stores only relevant blocks how the relevant blocks are determined?

Thanks

**Comment by azf20** [comment]
hey @zxsimba - Graph Node has two modes of data fetching. While syncing historical blocks (e.g. when syncing a subgraph for the first time), it fetches the data from the startblock for the subgraph, but it will only fetch blocks where it discovers triggers for that subgraph (based on the configuration of the subgraph) - until it catches up to the chain head. At the same time, Graph Node is always ingesting new blocks at the chain head, which are then passed to all subgraphs which are syncing at the chain head.
