### ISSUE TITLE
[Bug] Not finding out the network defined in the docker-compose while trying to deploy locally.

### ISSUE THREAD

**Issue by SunlightLuck** [graphprotocol/graph-node#4813]
### Bug report

[https://github.com/radiant-capital/radiant-subgraph/tree/fix-local](https://github.com/radiant-capital/radiant-subgraph/tree/fix-local)
While trying to deploy subgraph to the local node in this repo, it fails with the error of `Failed to deploy to Graph node http://localhost:8020/: network not supported by registrar: no network 31337 found on chain ethereum`.

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by incrypto32** [comment]
Im not able to reproduce this, tried with the same docker-compose.yml on your repo and the subgraph was deployed successfully

**Comment by incrypto32** [comment]
Im not able to reproduce this, tried with the same docker-compose.yml on your repo and the subgraph was deployed successfully

**Comment by incrypto32** [comment]
I would check the local node running is working fine. Thats the only possibility that i see to see the same error.

**Comment by SunlightLuck** [comment]
> Im not able to reproduce this, tried with the same docker-compose.yml on your repo and the subgraph was deployed successfully

Did you try the same commands in the Readme of the repo and it worked correctly without any issues?

**Comment by SunlightLuck** [comment]
> Im not able to reproduce this, tried with the same docker-compose.yml on your repo and the subgraph was deployed successfully

FYI, I'm running it on ubuntu.

**Comment by incrypto32** [comment]
> Did you try the same commands in the Readme of the repo and it worked correctly without any issues?

That is right except for i ran `docker compose up` manuall not using `yarn:start-node` 
And everything worked fine.

**Comment by SunlightLuck** [comment]
> > Did you try the same commands in the Readme of the repo and it worked correctly without any issues?
> 
> That is right except for i ran `docker compose up` manuall not using `yarn:start-node` And everything worked fine.

getting such warnings while running `docker compose up`. Is it the same with your end?
![image](https://github.com/graphprotocol/graph-node/assets/96634736/ab922950-8315-49d3-ac9b-2c2043bddcdb)

**Comment by SunlightLuck** [comment]
![image](https://github.com/graphprotocol/graph-node/assets/96634736/b3212fa9-72d9-40c8-82ec-e4cbfd74229c)
and this error when use `ethereum: "31337:http://host.docker.internal:8545"` in the docker-compose.yml

**Comment by incrypto32** [comment]
> I would check the local node running is working fine. Thats the only possibility that i see to see the same error.

As i suggested this seems to be the issue. The local node at 8545 is not working properly

**Comment by SunlightLuck** [comment]
> > Did you try the same commands in the Readme of the repo and it worked correctly without any issues?
> 
> That is right except for i ran `docker compose up` manuall not using `yarn:start-node` And everything worked fine.

Then how did you manage to deploy it on the local node successfully?

**Comment by incrypto32** [comment]
I mean i just ran `docker compose up` instead of the yarn script

**Comment by SunlightLuck** [comment]
> > I would check the local node running is working fine. Thats the only possibility that i see to see the same error.
> 
> As i suggested this seems to be the issue. The local node at 8545 is not working properly

I run `npx hardhat node` for the local node.

**Comment by SunlightLuck** [comment]
I was able to deploy it by running hardhat node with `--hostname 0.0.0.0`
@incrypto32

**Comment by incrypto32** [comment]
Glad you could me it work.
