### ISSUE TITLE
[Feature] Go from ipfs/go-ipvs:v0.10.0 to ipfs/kubo:v0.22.0

### ISSUE THREAD

**Issue by computeronix** [graphprotocol/graph-node#4819]
### Description

ipfs/go-ipfs is now ipfs/kubo

as mentioned here: https://hub.docker.com/r/ipfs/go-ipfs

In the docker file this version should be updated to use a newer image under the kubo side

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by maoueh** [comment]
I confirm that `ipfs/kubo:v0.14.0` works properly, I didn't test with `0.22.0` but I don't see why it wouldn't work.

**Comment by computeronix** [comment]
Closing as this resolves the change of image packages in Docker and can be further evaluated in the future as updates are checked across the software

thank you again!
