### ISSUE TITLE
[Bug] Configuration error while executing graphman

### ISSUE THREAD

**Issue by mehditvk8** [graphprotocol/graph-node#4821]
### Bug report

I run the graph-node with docker-compose using the following command:
```
docker compose up
```
after the graph-node run successfully I execute the following command:
```
docker compose exec -it graph-node graphman config check
```
but I got the following error:

> Error: Configuration error
   Caused by:
      No such file or directory (os error 2)

**Edited:** As I understand from the documentations graphman requires a `config.toml` file that should be pass to graphman command using `--config` flag. But I can not find any help for the content of config file.

### Relevant log output

```Shell
Error: Configuration error

Caused by:
    No such file or directory (os error 2)
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by trader-payne** [comment]
RTM: https://github.com/graphprotocol/graph-node/blob/master/docs/config.md

**Comment by mehditvk8** [comment]
Thanks @trader-payne. That was helpfull. But I think this configuration file must be exist in the docker container. Maybe you forgot to put it in the container. If not, can you explain why don't you put it in the container?

**Comment by bijianing97** [comment]
@mehditvk8 
Hello, I encountered the same problem. I also started with Docker, but I don't know where config.toml is, or how to write it. Can you give me a simple example? I want to use graphman drop. Thank you.

**Comment by jessepinkman9900** [comment]
hope this helps

```
[general]

[store]
[store.primary]
connection = "postgresql://<username>:<pass>@<host>:<port>/<db>"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "peering", url = "<json-rpc-node>", features = [ "archive", "traces" ] },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
```
