### ISSUE TITLE
[Bug] graph-node stuck when encounter uncled block on shibuya

### ISSUE THREAD

**Issue by cezary-stroczynski** [graphprotocol/graph-node#4822]
### Bug report

I'm using `graphprotocol/graph-node:v0.31.0` docker image for Shibuya network.
Whenever I deploy a new subgraph version to my graph-node it doesn't start syncing and it just loop with the error message about uncled block. I have to restart the container and then it start syncing very slowly but the error message persist.

### Relevant log output

```Shell
{
  "errors": [
    "{\n  \"errors\": [\n    {\n      \"message\": \"Store error: query execution failed: Subgraph `QmNYM7RGb2VbBrorLHD5E6op1MGZrB9YEethQSX36naP4A` has not started syncing yet. Wait for it to ingest a few blocks before querying it\"\n    }\n  ]\n}"
  ]
}


Aug 24 09:21:36.138 ERRO Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0xf849f1ef670ae0d61856874709ab6c13ecf5b733bd5f82c5b44b38ee573974ea), provider: shibuya, component: EthereumPollingBlockIngestor
```

### IPFS hash

QmNYM7RGb2VbBrorLHD5E6op1MGZrB9YEethQSX36naP4A

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
hey @cezary-stroczynski - are you still encountering this issue? Closing for now, please re-open if this issue is still open
