### ISSUE TITLE
[Bug] Subgraph with callHandler causes error on bsc, polygon, arbitrum 

### ISSUE THREAD

**Issue by ekrembal** [graphprotocol/graph-node#4823]
### Bug report

We have been working on implementing Proof of Innocence on RAILGUN, which requires indexing for every call to a transact function. RAILGUN is deployed on several chains, and our indexer currently works on the Ethereum and Goerli testnet. However, when I try to deploy the same subgraph for BSC, Polygon, and Arbitrum, I encounter the error output.

- Are there any plans to run nodes with NodeCapabilities { archive: false, traces: true } on those networks?
- How can I run my own node with those capabilities?

### Relevant log output

```Shell
Subgraph instance failed to run: A matching Ethereum network with NodeCapabilities { archive: false, traces: true } was not found.
```

### IPFS hash

QmUbAfWFWYr7f3Kq7n7rC9meaF52r9ZSShQz4WJwDCBKeR

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/ekrembal/railgun-transactions-polygon

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by incrypto32** [comment]
> Note: Call handlers currently depend on the Parity tracing API. Certain networks, such as BNB chain and Arbitrum, does not support this API. If a subgraph indexing one of these networks contain one or more call handlers, it will not start syncing. Subgraph developers should instead use event handlers. These are far more performant than call handlers, and are supported on every evm network.

Quoting the docs [here](https://thegraph.com/docs/en/developing/creating-a-subgraph/#defining-a-call-handler)
