### ISSUE TITLE
Discussion: Issues updating Matchstick's graph-node dependencies

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-node#4837]
Hello there 👋🏻  Recently we started updating [Matchstick](https://github.com/LimeChain/matchstick) to support [`loadInBlock` and `loadRelated` ](https://github.com/LimeChain/matchstick/issues/397). `loadRelated` requires us to update the graph-node versions that we use as [Matchstick dependencies (currently 0.26.0)](https://github.com/LimeChain/matchstick/blob/main/Cargo.toml#L8-L14). Unfortunately we are encountering some issues with that. 

First one is (rustc 1.68.0 (2c8cc3432 2023-03-06)
![image](https://github.com/graphprotocol/graph-node/assets/20456492/5a0bd397-fcfc-4d64-b823-cd54e53e314f)

And the second one is 
![Screenshot 2023-08-29 at 10 38 49](https://github.com/graphprotocol/graph-node/assets/20456492/d946d01f-6e13-4143-bb68-8c1fe6f49561)

Previously the `common` module was made public here in order for us to use the `mock_context` and `mock_data_source` functions
https://github.com/graphprotocol/graph-node/blob/0545d7baf2351a3e0cc79a184458d6f3be86f520/runtime/test/src/lib.rs#L1

I would appreciate any suggestion how we could fix/circumvent those issues.

CC: @azf20 @axiomatic-aardvark

**Comment by axiomatic-aardvark** [comment]
I think the `common` module should be public. Keen to hear from @azf20, @lutter and @leoyvens

**Comment by azf20** [comment]
@dimitrovmaksim closing as I think you resolved this in https://github.com/LimeChain/matchstick/issues/403, but please re-open if you're still blocked here!
