### ISSUE TITLE
Add support for manifests in Arweave File Data Sources

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#4867]
Context:
[What are Arweave manifests](https://help.ardrive.io/hc/en-us/articles/5300353421467-Arweave-Manifests)?
[Bundlr docs](https://docs.bundlr.network/developer-docs/sdk#upload-a-folder)

_This may be supported but would be valuable to verify_

**Comment by mangas** [comment]
https://github.com/graphprotocol/graph-node/pull/4865

**Comment by azf20** [comment]
Updated docs https://github.com/graphprotocol/docs/pull/514
