### ISSUE TITLE
[Bug] Various reports that Firehose powered Subgraphs are silently stop processing blocks

### ISSUE THREAD

**Issue by maoueh** [graphprotocol/graph-node#4869]
### Bug report

Fork of [#4863](https://github.com/graphprotocol/graph-node/issues/4863) so that Firehose related problem are split from Substreams powered Subgraphs. Those are different complete components, within the Firehose stack as well as within `graph-node` implementation so bundling those together.

I'll bring some of the comments from the other thread once I've been able to choose where they should be tracked.

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Other (please specify in your bug report)

**Comment by azf20** [comment]
@maoueh closing this given inactivity, please re-open if you're tracking anything on this
I think https://github.com/graphprotocol/graph-node/issues/4976 may have helped here
