### ISSUE TITLE
Better handling of PoI internally

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#4873]
In the code, we have to special-case the PoI entity type in quite a few places because it's a type that is not in the input schema. It would be much better to inject the proper GraphQL definition into the input schema by adding something like

```graphql
type __PoI @entity {
  ID: String!,
  digest: Bytes!
}
```

early when we ingest an input schema and treat it like a normal type

**Comment by azf20** [comment]
@lutter is this still valid?
