### ISSUE TITLE
[Bug] Some Amount values are showing as negative.

### ISSUE THREAD

**Issue by cinjon** [graphprotocol/graph-node#4898]
### Bug report

I am having a weird issue where a very small amount of numbers are getting displayed incorrectly, consistently. You can see it here: https://api.thegraph.com/subgraphs/name/cinjon/research-portfolio-v1-goerli/ and in the attached screenshots. It's a minority of amounts and I don't see any rhyme or reason to them. This is one such amount: 0xf9f1da88f9710aaaaa. Another is 0x8ed3584e45652aaaaa. They are not the largest amounts, so I think that rules out it being an overflow. I posted on the Discord and Jerry helpfully suggesting posting here instead. This is using @graphprotocol/graph-ts: 0.29.3.

![image](https://github.com/graphprotocol/graph-node/assets/615351/7c41b22c-7752-4178-8e58-5e92a38ac45d)

The query is below. Notice it's not happening if we use this accountAddress: 0x6849db46b51E825bc1469C93D039D044eD31d158. It has a different amount.

```
query accountBalances($accountAddress: Bytes!, $block: Block_height) {
  account(id: $accountAddress, block: $block) {

	ERC20Reservations(where: {claimed: false}) {
		ERC20Contract {
			id
			totalSupply {
				value
				valueExact
			}
			decimals
			asResearch {
				minter {
					id
				}	
				researchIdentifier
			}
			name
			symbol		
		}
		ERC20Distributor {
			id
		}
		amount
		claimed
	}

  }
}
```

Here's the associated GQL:
```
,{
  "name": "ERC20ReservationForAccount",
  "fields": [
    { "name": "ERC20Distributor",     "type": "ERC20Distributor!"                                   },
    { "name": "ERC20Contract",        "type": "ERC20Contract!"                                      },
    { "name": "index",                "type": "BigInt!"                                             },
    { "name": "account",              "type": "Account!"                                            },
    { "name": "claimed",              "type": "Boolean!"                                            },
    { "name": "amount",               "type": "BigInt!"                                             },
    { "name": "proof",                "type": "[String!]"                                           }
  ]
},
```

And here is where it's declared in the datasource:
```
      log.info("for account", []);
      let reservationAccountAddress = Address.fromString(
        reservationKeySplit[1]
      );
      let reservation = new ERC20ReservationForAccount(
        distributor.id.toHexString() +
          "/" +
          reservationIndex.toBigInt().toHexString()
      );
      let reservationAmountByteArray = Bytes.fromUint8Array(
        ByteArray.fromHexString(reservationAmount.toString()).reverse()
      );
      let amount = BigInt.fromByteArray(reservationAmountByteArray);
      reservation.amount = amount;
```

### IPFS hash

QmQR58w8qSBY6EYaznuPrSCGa8UjwcCun1BHUF6oN6ePUF

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/cinjon/research-portfolio-v1-goerli

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
hey @cinjon you are doing quite a lot of transformations to calculate the amount:

```
let reservationAmountByteArray = Bytes.fromUint8Array(
        ByteArray.fromHexString(reservationAmount.toString()).reverse()
      );
      let amount = BigInt.fromByteArray(reservationAmountByteArray);
      reservation.amount = amount;
```

Why is this required, and where does `reservationAmount` come from? Do the non-negative values of `amount` look correct / is there any way of verifying what the values should be?

**Comment by cinjon** [comment]
Thanks for replying @azf20. All of the values are correct. The problem is that we are getting the decimal from a signed 2's complement and that's failing for some values. See the attached screenshot for an example.

The `reservationAmount` comes from a manifest object, where the manifest is a json hosted at ipfs, e.g. the one here: https://ipfs.io/ipfs/bafkreibtut5iow2pvdy4xnurcadtvzp3igz4cuu3sc34t57kwcdubuzc24. See below for the code to yield that reservationAmount.

What's the recommended way to do this conversion from hex to decimal in TheGraph's assemblyscript?

```
  // parse as JSON, iterate over entries
  let manifestParsed = json.fromBytes(manifestData).toObject();
  if (manifestParsed === null) {
    return;
  }

  let reservations = manifestParsed.get("claims");
  if (reservations === null) {
    return;
  }

  let reservationsObject = reservations.toObject();
  if (reservationsObject === null) {
    return;
  }

  let reservationEntries = reservationsObject.entries;
  for (let i: i32 = 0; i < reservationEntries.length; ++i) {
    // add Reservation for each entry
    let entry = reservationEntries[i];
    let reservationKey = entry.key;
    let reservationKeySplit = reservationKey.split("/");

    let reservationValue = entry.value;
    let reservationObject = reservationValue.toObject();
    if (reservationObject == null) {
      continue;
    }
    let reservationIndex = reservationObject.get("index");
    let reservationAmount = reservationObject.get("amount");
...
```


![image](https://github.com/graphprotocol/graph-node/assets/615351/b179dc57-58c3-4c9d-8316-3ff6af8f1fd6)

**Comment by azf20** [comment]
hey @cinjon you should be able to use `parseInt` on the hex

**Comment by azf20** [comment]
Closing, please re-open if that doesn't work for you!
