### ISSUE TITLE
[Feature] AssemblyScript API to force contract calls ( eth_call ) to the latest block

### ISSUE THREAD

**Issue by kaliubuntu0206** [graphprotocol/graph-node#4904]
### Description

Archive nodes requires a lot of storage space ( 14TB for ethereum mainnet ) and sync time.

I suggest to add an API to enable forcing calls to a recent block which is supported by full nodes as well.

( Something like recent_<contract_method> would be great )

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by kaliubuntu0206** [comment]
@incrypto32 Yes but I am querying immutable state like ERC20's name / symbol calls. I don't think not all staticcalls would need historic lookups.

**Comment by incrypto32** [comment]
What do you think the benefit of doing this is? Im not seeing very significant performance gains for the added complexity. Besides that ERC20's name and symbol can be changed if the contract supports it(?)

**Comment by kaliubuntu0206** [comment]
@incrypto32 Yes but not many contract does it and I believe the risk should be bared by the subgraph deployer. I just want to do some simple eth_calls without historic lookups via subgraph otherwise I need to code an alternative backend every time when I need to do it.

**Comment by incrypto32** [comment]
Sorry, i dont really understand your usecase right. If you are looking to just get the constant fields like name and symbol, You still get it with the normal eth-call api supported in subgraphs.
The results are the same, and the performance gains would be negligible, Am I missing something

**Comment by kaliubuntu0206** [comment]
@incrypto32 Yes, what I mean is that normal eth-call requires archive nodes since subgraphs would call `eth_call` with specific block params which is not supported by a normal full-node which only has a pruned state. So it would be great if we could have some subgraph contract API that could enforce `eth_call` with latest block params.

**Comment by incrypto32** [comment]
Its not just eth-calls that require an archive node, there are other roc calls made by graph-node that requires an archive node, so adding just this feature won't help.

**Comment by kaliubuntu0206** [comment]
@incrypto32 Which calls? Since those are not documented.
