### ISSUE TITLE
Add documentation about self hosted service supported networks

### ISSUE THREAD

**Issue by zxsimba** [graphprotocol/graph-node#4909]
### Description

https://thegraph.com/docs/en/developing/supported-networks/

this document does not include any information about which networks are supported in graph-node software. we are planning to run a private graph node service for many chains, but don't know which chains are supported by  graph-node.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
Hi @zxsimba can you provide a bit more context on your use case. Graph Node supports indexing EVM chains via RPC, and EVM, NEAR, Cosmos and Arweave chains via a Firehose.

**Comment by zxsimba** [comment]
I want to run a private graph-node instance for many ethereum like networks (L1 and L2),
including bnb, base, opbnb, arbitrum, zksync.
according to: https://thegraph.com/docs/en/developing/supported-networks/ 
among the mentioned networks, the Decentralized Network only supports arbitrum (in beta),

I want to know if the software (graph node) supports these networks? and in general every ethereum like chain?
If no, providing a document about supported networks will be helpful.
Thanks

**Comment by azf20** [comment]
> I want to know if the software (graph node) supports these networks? and in general every ethereum like chain?

As I mentioned, Graph Node supports indexing EVM chains via RPC.
