### ISSUE TITLE
[Bug] Cannot remove unused deployment

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4913]
### Bug report

I cannot remove an used deployment, I'm getting an error about lock timeouts

### Relevant log output

```Shell
root@goldskyraw-indexer-0-graph-node-5f8f45ccf4-wlzd6:/# graphman unused remove
====================================    1 ====================================
removing sgd436 from primary
   deployment id: QmVGEFxeM4a6pQxm57uMTB23cYvo7ek591e98KzjJ8YNym
        entities: 88286826
removal failed: store error: canceling statement due to lock timeout
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
hey @paymog is this running 0.32.0? And is it only affecting this one deployment?

**Comment by paymog** [comment]
@azf20 Yup, running 0.32.0 and it's only affecting one deployment (so far, I'm doing some pruning). I'm able to successfully remove other deployments without issue

```
root@goldskyraw-indexer-0-graph-node-5f8f45ccf4-wlzd6:/# graphman drop sgd435
Found 1 deployment(s) to remove:
name       | uniswap-v2
deployment | QmcbeTkD9ocqu2d7KQhmiAKXvXjxuf7mYr6M7PmgELym9B

Continue? [y/N] y
unassigning QmcbeTkD9ocqu2d7KQhmiAKXvXjxuf7mYr6M7PmgELym9B[435]
Removing subgraph uniswap-v2
Recording unused deployments. This might take a while.
id        | 435
shard     | primary
namespace | sgd435
subgraphs |
entities  | 243572223
Recorded 1 unused deployments
====================================    1 ====================================
removing sgd435 from primary
   deployment id: QmcbeTkD9ocqu2d7KQhmiAKXvXjxuf7mYr6M7PmgELym9B
        entities: 243572223
done removing sgd435 from primary in 3.7s
```

**Comment by paymog** [comment]
ah, looks like there's a vaccuum happening on the tables for `sgd436`: https://gist.github.com/paymog/ff32882c3abe09cf7feeaddeb7a24369
