### ISSUE TITLE
[Bug] graph node stops syncing

### ISSUE THREAD

**Issue by mehditvk8** [graphprotocol/graph-node#4914]
### Bug report

I am using graph-node docker version. I run a graph-node that configured with `config.toml` file. Then I deploy a subgraph on the running graph-node. Everything is OK for about an hour. after that every time I watch the deployment status using the
`
graphman info --all -s
`
command, the `chain head block` field increased after a while but the `latest block` field stays constant for a long hours.
when I check the logs I just see the following errors:

> block was likely uncled

> provider wents backward. ignoring the latest block.

For more information: I deployed subgraph on USDC contract on `polygon-zkevm` network. 
Can someone explains me why does this happen?

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
hey @mehditvk8 can you share the logs themselves?

**Comment by mehditvk8** [comment]
hey @azf20 I mentioned errors that I got from the logs above. There is nothing more useful.

**Comment by azf20** [comment]
ok - I think we would need more diagnostics or a reproduction case to understand further, and I think this may be a duplicate with this other issue you created https://github.com/graphprotocol/graph-node/issues/4921, so closing for now
