### ISSUE TITLE
[Feature] Allow subgraph developers to create on-chain event to indicate if and when a subgraph upgrade will occur

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/graph-node#4918]
## User problem
Indexer unknowingly allocates to a soon-to-upgrade subgraph but has no way of knowing the upgrade is going to happen.

When the upgrade occurs, Indexers are essentially stuck earning no rewards until the current epoch is over or until they initiate a `0x0` transaction to "free" their allocation.

## User stories
As a subgraph developers I want the ability to share with Indexers **WHAT** subgraph I plan to upgrade **WHEN** without needing to install any additional software

As an Indexer I want the ability to monitor **WHAT** will be upgraded **WHEN** on-chain using the existing monitoring tools deployed in my stack (i.e. Grafana)

As an Indexer I want to see a warning in the Graph Explorer not to allocate to soon-to-upgrade subgraphs.

## Related tooling
The Subgraph Upgrade Pre-syncing functionality of Subgraph Radio works toward solving this issue: https://docs.graphops.xyz/graphcast/radios/subgraph-radio/subgraph-upgrade-presyncing

However, subgraph developers are continuing to update subgraphs but are not sending [`UpgradeIntentMessage`](https://docs.graphops.xyz/graphcast/radios/subgraph-radio/subgraph-upgrade-presyncing#send-an-upgrade-intent-message)s with Graphcast CLI to notify Indexers. The utility of the Subgraph Radio Upgrade Pre-syncing functionality is largely dependent on subgraph developers and Indexers installing and using the Graphcase CLI (in addition to existing tooling requirements). 
 
## Hypothetical new UX
`graph schedule <ACTION> <TIMESTAMP>`

### Examples
``` bash
graph schedule upgrade <OLD_SUBGRAPH_SLUG> <NEW_SUBGRAPH_SLUG> <UPGRADE_TIMESTAMP>
graph schedule publish <SUBGRAPH_SLUG> <TIMESTAMP>
```

### Are you aware of any blockers that must be resolved before implementing this feature? If so, which? Link to any relevant GitHub issues.

Implementing `schedule` functionality on The Graph CLI's other methods

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by kw1knode** [comment]
An on-chain activity would enable various third-party tools (such as GraphScan, Web3Alerts, and indexer tools) to provide indexers with enhanced visibility regarding anticipated actions from the consumer side.
