### ISSUE TITLE
Hello, how do i change my node from localhost to 0.0.0.0

### ISSUE THREAD

**Issue by userbox020** [graphprotocol/graph-node#4929]
### Bug report

Thanks in advance

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by YaroShkvorets** [comment]
What do you mean?

**Comment by azf20** [comment]
Closing, @userbox020 please re-open with more reproduction info

**Comment by userbox020** [comment]
@azf20, @YaroShkvorets lol bros if you dont know how to start the graph-node server and not even know the difference between localhost and 0.0.0.0 
I would better look at code by myself fork it and solve it, I bet with a simple flag can be on the start up command will do
