### ISSUE TITLE
Allow dynamically adding/removing tracked contract addresses

### ISSUE THREAD

**Issue by tsuberim** [graphprotocol/graph-node#493]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Tracked contracts are statically defined and can't be added/removed at runtime.

In some scenarios we want to be able to dynamically add/remove tracked contract addresses based on events that happen in another contract (e.g. when we have a contract that creates other contracts).

**Comment by Jannis** [comment]
Tracked via #719.

**Comment by Abhikumar98** [comment]
Is there any article that I can refer for thi?
