### ISSUE TITLE
[Bug] Querying not activated yet, Can't query

### ISSUE THREAD

**Issue by dalveytech-adrew** [graphprotocol/graph-node#4934]
### Bug report

When I use studio to query data, the following error occurs:

`
{"errors":[{"message":"Querying not activated yet; make sure to add some GRT to your balance in the studio"}]}
`

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
hey @dalveytech-adrew that isn't a Graph Node issue, if you join the [discord](https://discord.gg/vtvv7FP) you should be able to get help with querying subgraphs on the studio or explorer
