### ISSUE TITLE
[Bug] File Data Sources subgraph gets stuck

### ISSUE THREAD

**Issue by juanmardefago** [graphprotocol/graph-node#4936]
### Bug report

While indexing the latest FDS refactor for the core network subgraph, we found that it got stuck and made no progress in days.
The issue didn't leave any logs at the UI level, so after asking around, we could finally get some low level logs to start debugging, but that also makes the issue potentially more on graph-node itself that in the subgraph code 😅 .

This subgraph uses "normal" File Data Sources (i.e. triggered from event handlers), as well ass "off-chain" File Data Sources (i.e. triggered from within another file data source handler), and since those features are quite new (particularly the latter), we think that might be related to the issue itself.

### Relevant log output

```Shell
hread 'QmeQsdT17ZtKVrceijUmKtqP4PXCDiQ75ooiAsQNxhxM9K[635136]' panicked at 'assertion failed: self.hosts.last().and_then(|h| h.creation_block_number()) <=\n    data_source.creation_block()', /graph-node/core/src/subgraph/context/instance.rs:136:9
```

### IPFS hash

QmeQsdT17ZtKVrceijUmKtqP4PXCDiQ75ooiAsQNxhxM9K

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/graphprotocol/graph-network-mainnet-staging?version=pending

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by lutter** [comment]
Subgraph `QmbAreB7zPavfTrKQawXJLFqytcqq9bC5WxqBC2b6L5JLR` exhibits the same issue, with the same panic
