### ISSUE TITLE
[Bug] Subgraph never flips to synced

### ISSUE THREAD

**Issue by wyze** [graphprotocol/graph-node#4959]
### Bug report

This subgraph was working as expected on graph-node 0.30.0 but I tried upgrading to 0.31.0, 0.32.0, and 0.33.0, and now the subgraph doesn't flip to sync even when it is at 100%.

This is running inside docker.

Subgraph source is here: https://github.com/wyze/subgraphs/tree/master/subgraphs/meem

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by wyze** [comment]
Followup, after a day, it looks like they finally switched over to "synced" = true in the database.

**Comment by azf20** [comment]
Thanks, closing - please re-open if you think this is a recurring issue
