### ISSUE TITLE
[Question] Is it possible for a subgraph that's failed to become not-failed again by itself?

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4969]
### Bug report

I'm building some monitoring infrastructure around subgraphs that have entered the `failed` and/or `synced` state. I'm specifically monitoring the [failed](https://github.com/graphprotocol/graph-node/blob/bcd5e65e4e45a84a22b52dc53ba6420c6ba8a65c/store/postgres/src/deployment.rs#L129) and [synced](https://github.com/graphprotocol/graph-node/blob/bcd5e65e4e45a84a22b52dc53ba6420c6ba8a65c/store/postgres/src/deployment.rs#L131) columns in the `subgraph_deployments` table.

My monitoring infrastructure is repeatedly alarming on the same subgraph faililng. ie: the subgraph enters the `failed=true` state, seems switch to `failed=false` and then become `failed=true` again. 

Is it possible for this to happen without any intervention like rewinding on the part of the indexer?

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by paymog** [comment]
As usual, I think I [found the relevant code](https://github.com/graphprotocol/graph-node/blob/ba3a6804861ea8c8fcd73c308dcfa147a20203e6/store/postgres/src/deployment_store.rs#L1586-L1681). It seems non-deterministic errors are wiped during initialization which either causes the subgraph to be `healthy` or `unhealthy`, neither of which [map to a `failed` state](https://github.com/graphprotocol/graph-node/blob/fb34bfac4425aa716e3aae1493d7cf616fe24854/graph/src/data/subgraph/schema.rs#L50-L55). Am I reading this correctly?

**Comment by azf20** [comment]
👍 non-deterministically failed subgraphs are retried on initialisation, and also retried on a periodic basis when the Graph Node is running. Closing, do re-open if you have further questions
