### ISSUE TITLE
[Bug] Failed to get entities from store: could not resize shared memory segment

### ISSUE THREAD

**Issue by eldimious** [graphprotocol/graph-node#4987]
### Bug report

Hello, i am trying to run graph node locally, and i have deployed a uniswap forks subgraph. When i try to fetch entities i get the following issue: `Failed to get entities from store: could not resize shared memory segment`

I am wondering if there is a workaround to fix the above one? Or if i just should modify postgres docker to increase shared memory?

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
Hi @eldimious can you please provide more information about your local graph node config

**Comment by eldimious** [comment]
Hello @azf20 i just use docker compose file from https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml to run graph node locally and also run an ethereum node using ethereum/client-go:stable img in the same docker-compose file

**Comment by azf20** [comment]
ok - does it fail in the same way for any subgraph you deploy?

**Comment by eldimious** [comment]
Nope, mostly for uniswapv2 / pancakeswap, i suspect is related to amount of tokens / liquidityPools that these platforms have.
My flow is to try to fetch all liquidity pools for uniswapv2, and when try to execute graphql with skip, fails at some point because of above message

**Comment by azf20** [comment]
try using `first` and `id_gt` https://thegraph.com/docs/en/querying/graphql-api/#example-using-first-and-id_ge

**Comment by eldimious** [comment]
Ok thanks for the hint, i will try it and let u know

**Comment by eldimious** [comment]
Hey @azf20 indeed seems that using lastid instead of skip is more performant and i have not received the above error. Thanks for the help!
