### ISSUE TITLE
[Feature] Auto-incrementing ids

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#5018]
### Description

In a lot of situations, the `id` of an entity doesn't really carry any meaning, and it's only used to distinguish between different entities of the same type. Unfortunately, it's also often not easy to come up with unique id's from within the mappings because the environment is very restricted. That often leads to very long `id` values that are simply a combination of other attributes of the entity that duplicate data and therefore waste space.

To address that, we should do the following:
* Allow `Int8` as the type of an `id` field
* When `store.set(entity_type, id, data)` is called and the `id` argument is the string `"auto"`, set the `id` value of the entity to the next value from a sequence that `graph-node` maintains internally
* Calling `store.get(entity_type, id)` with `id = "auto"` will return `null`

The implementation for the internal sequence could use a Postgres sequence, but that will require a lot of roundtrips to the database. Instead, we should do the following:
* When a subgraph is started, query the `max(id) + 1` for all entities that have an `id` of type `Int8` and use that as initial values for a map of sequences in `IndexingState`
* Whenever we need a new `id` for an `"auto"` entity, get a new value from `IndexingState` and update the sequence there appropriately

Most of this can be implemented entirely within `graph-node`. The main thing that needs to change in `graph-tooling` is that we accept `id: Int8` in subgraph schemas and do a similar automatic conversion to `String` for the various `store.*` calls that we do for `Bytes`.

**Comment by leoyvens** [comment]
What if instead of an integer, we used an array of integers for auto ids? This allows for hierarchical id generation, for which I can think of a few uses:
1. ID generation across causality regions. The processing order is not defined across causality regions, so a single sequence wouldn't work. But if the first element of the id is the causality region, then we're good.
2. An idea is to have the ID be `[block_number, seq_num_in_block]`, which may be useful for being more local and reproducible without syncing the whole subgraph.

**Comment by lutter** [comment]
@leoyvens Yes, good points; I hadn't thought about making this really deterministic (for what I described, we'd need to roll back the counter state on reverts, too)

I think a format `[block_number, causality region, seq_num_in_block]` would be deterministic. The question is: can we jam that into 8 bytes or do we have to resort to `bytea`? Block numbers are 4 bytes, so we have 4 more bytes to play with; is there a reasonable upper bound on the number of causality regions? Could we use 2 bytes for that? Then we'd have 2 bytes for the sequence number which should be plenty.

**Comment by lutter** [comment]
Looking some more into this, I think this would be possible:

* have one counter per entity type
* if the entity type does not have causality regions, `id` can be `Int8` or `Bytes`, and use the form `[block_number, seq_in_block]` That takes 8 bytes as an `Int8` and 9 bytes as a `bytea`
* if the entity type does have causality regions, `id` can be `Bytes` and uses the form `[block_number, causality_region, seq_in_block]`. That's too big for an `int8`, but is 13 bytes for a `bytea`
