### ISSUE TITLE
[Bug] Event handlers not firing in order

### ISSUE THREAD

**Issue by GundamDweeb** [graphprotocol/graph-node#5026]
### Bug report

On a subgraph I am working on there is an entity created in an event (Minted event) which creates a Mint entity with the transaction hash.

When trying to retrieve this entity in the AddLiquidity event which is the last in the list, it does not exist yet.

Here is an example of the [event](https://goerli.etherscan.io/tx/0x728588893cbe11b2ac5c82a36c9101b6ab1daff542a7c7d2c284f4c44c300605#eventlog)

It seems this happens when the templated datasource is created in the same transaction as the Minted and AddLiquidity event. Minted event exists on the templated datasource for the contract deployed in the tx.

### Relevant log output

```Subgraph failed with non-deterministic error: failed to process trigger: block #9727530 (0x2858…1719), transaction 728588893cbe11b2ac5c82a36c9101b6ab1daff542a7c7d2c284f4c44c300605: Entity Mint[MINT-0x728588893cbe11b2ac5c82a36c9101b6ab1daff542a7c7d2c284f4c44c300605]: missing value for non-nullable field `date` wasm backtrace: 0: 0x31de - <unknown>!generated/schema/Mint#save 1: 0x371b - <unknown>!src/router/handleAddLiquidity , retry_delay_s: 138, attempt: 0```

### IPFS hash

QmUpJzhLwq5pDdjEMxdugpdJLSATMkvo6xREmW9RrSphuq

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/gundamdweeb/nftx-v3-vaults?version=pending&selected=logs

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

### EDIT: 

This bug was initially encountered on a goerli deployment of the ecosystem when a template datasource (NewVault) is created, and event A (Minted) is emitted for that new datasource where the entity (Mint) should be created. The later event B (AddLiquidity) is emitted after event A, where this Mint entity does not exist yet.

Here is the [transaction](https://goerli.etherscan.io/tx/0x728588893cbe11b2ac5c82a36c9101b6ab1daff542a7c7d2c284f4c44c300605#eventlog) that I first encountered it.

**Comment by GundamDweeb** [comment]
Hey @azf20 I added you to the private repo. I initially encountered it on the goerli version of the deployment at this [transaction](https://goerli.etherscan.io/tx/0x728588893cbe11b2ac5c82a36c9101b6ab1daff542a7c7d2c284f4c44c300605#eventlog).

Have added an edit above.

**Comment by incrypto32** [comment]
@GundamDweeb the error message doesn't look like its missing the `Mint` entity, it seems that the `date` field was somehow not set or set to null. Maybe you are getting the `date` field from somewhere else and that was null.
Would be great if you could post the code snippet where the `Mint` entity is being created and the `date` field being set

**Comment by GundamDweeb** [comment]
Hey @incrypto32 I know that is what the error message is saying, however the mint entity is fully created in the `Minted` Event with date before it is being retrieved in another Event (`AddLiquidity`), where we are trying to update the type only, and then when saving it throws an error because the entity has been partially set (not created in the Minted Event).

Here are the code snippets from `Minted` and `AddLiquidity` Events:

 
 Minted Event

```
export function handleMint(event: MintEvent): void {
  let vaultAddress = event.address;
  //Check address against vaultId
  let txHash = event.transaction.hash;
  let mint = getMint(txHash);
  let account = getUser(event.params.to);
  let amounts = event.params.amounts;
  let nftIds = event.params.nftIds;
  mint.type = "Mint";
  mint.user = account.id;
  mint.vault = vaultAddress.toHexString();
  mint.date = event.block.timestamp;
  mint.nftIds = nftIds;

  .....Other work.....

  mint.save();
  account.save();
  
  ```
  
 Helper `getMint()`
 
 ```
 export function getMint(txHash: Bytes,  source: Address = ADDRESS_ZERO): Mint {
  let mint = Mint.load("MINT-" + txHash.toHexString());
  if (!mint) {
    mint = new Mint("MINT-" + txHash.toHexString());
    mint.source = source;
  }
  return mint as Mint;
}
 ```
 
 AddLiquidity Event
 
 ```
 export function handleAddLiquidity(event: AddLiquidityEvent): void {
  let mint = getMint(event.transaction.hash);
  mint.type = 'AddLiquidity';
  mint.save()

 ...Other Work...
}
 ```

**Comment by incrypto32** [comment]
I'll investigate and get back

**Comment by incrypto32** [comment]
@GundamDweeb is the code for this subgraph public? I'd like to deploy it locally to debug

**Comment by GundamDweeb** [comment]
@incrypto32 It's currently private but I can ask to add you to the repo.

**Comment by incrypto32** [comment]
@GundamDweeb any luck?

**Comment by GundamDweeb** [comment]
Hey @incrypto32 I can add you but I have sent you a friend request on discord. Its happening on another repo now. Might be easier to show you

**Comment by GundamDweeb** [comment]
Here is another example of the same error on another subgraph I am working on (For the same project).

So dynamic datasource is created in same transaction as an event on that datasource. 
Here is a [tx](https://sepolia.etherscan.io/tx/0xd74fd08be87f2adf8b68b504f17fc1cb1e2dd48ecec9f12c9f4ac0b7403b0b1e#eventlog) to explain: 
1. Datasource `Pool` is created at logIndex 37 - `PoolCreated` event
2. `Mint` event on the new datasource is emitted - logIndex 42
3. `IncreaseLiquidity` event is emitted on logIndex 44

`IncreaseLiquidity` is on a standard datasource.

What happens is `IncreaseLiquidity` handler fires first, then `PoolCreated` & pool datasource is created, then `Mint` event is emitted, even though `IncreaseLiquidity` is the last event in the three.

**Comment by incrypto32** [comment]
@GundamDweeb, thank you for your comprehensive feedback. I've reviewed the issue and confirmed it. Although it might not be immediately obvious, this is the intended behavior as of now. Triggers from existing data sources are processed first, followed by the creation of the dynamic data source in that specific block. Currently, there are no plans to modify this behavior. We will ensure to clarify this in the documentation for better understanding.

**Comment by GundamDweeb** [comment]
This has reared it's ugly head once more - on a uniswap subgraph no less
