### ISSUE TITLE
[Feature] Add Holesky Testnet

### ISSUE THREAD

**Issue by mariopino** [graphprotocol/graph-node#5031]
### Description

Network/Chain ID: 17000
Genesis Hash: 0xb5f7f9124..a4661bde4
Consensus Engine: Proof of Stake
EVM Version: London
RPC: https://ethereum-holesky.publicnode.com

https://holesky.dev/

### Are you aware of any blockers that must be resolved before implementing this feature? If so, which? Link to any relevant GitHub issues.

Nope

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
hey @mariopino thanks - do you have a specific use case in mind for indexing Holesky? (Subgraphs are most commonly used by dapp developers, while Holesky is more staking, infrastructure and protocol-developer focused)

**Comment by VVander** [comment]
Hi @azf20 , I'm not the OP, but I am a staking protocol developer. We need Holesky support because some of our tooling depends on you. "Holesky is for stakers" != "everyone else should ignore Holesky". 

For example, we use 0xSplits contracts, and their frontend depends on graph. If we want to do a dress rehearsal for mainnet on Holesky, we need to either A) write our own scripts to manage everything and then use that on mainnet as well or B) ask you nicely to simply deploy to Holesky :)

**Comment by RaekwonIII** [comment]
> Hi @azf20 , I'm not the OP, but I am a staking protocol developer. We need Holesky support because some of our tooling depends on you. "Holesky is primarily for stakers" != "everyone else should ignore Holesky".
> 
> For example, we use 0xSplits contracts, and their frontend depends on graph. If we want to do a dress rehearsal for mainnet on Holesky, we need to either A) write our own scripts to manage everything, then use that on mainnet as well or B) ask you nicely to simply deploy to Holesky :)

I'd like to echo prev response, similar situation here: I am working for a distributed validator technology network, and we rely on subgraphs to foster our developer ecosystem and let people build staking applications on top. Believe it or not: staking also relies on smart contracts, which produce Events, which needs to be indexed, which need indexers.

And it's not just for frontend development, it's to be able to provide correct input when submitting smart contract transactions. Alternatives are the same as described above: scripts and tooling which is much worse to develop, maintain and use.

**Comment by azf20** [comment]
Thanks for that context @RaekwonIII @VVander, we will follow up next week 🙏

**Comment by azf20** [comment]
This is now supported on Subgraph Studio
