### ISSUE TITLE
[Bug] Gnosis run with retry: eth_getBlockByNumber(latest) no txs RPC call failed

### ISSUE THREAD

**Issue by eldimious** [graphprotocol/graph-node#5036]
### Bug report

Hello, i am trying to run locally using docker compose a graph node and a gnosis node. For some reason seams that graph-node stucks on a specific block and can not fetch any new block from gnosis. It constantly returns error: `WARN Trying again after eth_getBlockByNumber(latest) no txs RPC call failed (attempt #5179) with result Err(Unknown(could not get latest block from Ethereum: Cannot send request. Internal task finished.)), provider: gnosis1, component: EthereumPollingBlockIngestor`

My config.toml for gnosis chain has 2 providers, gnosis1 uses my local gnosis node, while gnosis2 uses an node provider like alchemy.

[chains.gnosis]
shard = "primary"
provider = [
  { label = "gnosis1", url = "ws://xxx", features = [
  ], transport = "ws" },
  { label = "gnosis2", url = "xxx", features = [
    "archive",
    "traces",
  ], transport = "rpc" },
]

Do you have any idea about the root of the issue?

### Relevant log output

```Shell
graph-node           | Dec 01 14:03:13.853 WARN Trying again after eth_getBlockByNumber(latest) no txs RPC call failed (attempt #5179) with result Err(Unknown(could not get latest block from Ethereum: Cannot send request. Internal task finished.)), provider: gnosis1, component: EthereumPollingBlockIngestor
graph-node           | Dec 01 14:03:14.666 WARN Trying again after eth_getBlockByNumber(latest) no txs RPC call failed (attempt #5180) with result Err(Unknown(could not get latest block from Ethereum: Cannot send request. Internal task finished.)), provider: gnosis1, component: EthereumPollingBlockIngestor
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
Hi @eldimious , does this happen immediately? (i.e. does it ingest any blocks)

I notice you are using `ws` for the local node, do you see the same thing if you use an `rpc` connection?

**Comment by eldimious** [comment]
Hello @azf20 yep i am using wss, when i do use my local node (is a full node) for gnosis, mainnet, etc to subscribe to new block head, and i am using rpc (which is an archive one) as fallback.

Rn i got pretty much the same issue on avalanche too where i do use same config like

```js
[chains.avalanche]
shard = "primary"
provider = [
  { label = "avalanche1", url = "ws://my_local_avalanche(full node)", features = [
  ], transport = "ws" },
  { label = "avalanche2", url = "https://alchemy_provider" (archive), features = [
    "archive",
    "traces",
  ], transport = "rpc" },
]
```

and my docker-compose is like this https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml with only change i run geth / avalanche / gnosis nodes too

**Comment by eldimious** [comment]
@azf20 hello thanks for your hint. Seems that using rpc url for gnosis, graph node keeps in sync. Are wss not stable?

**Comment by azf20** [comment]
hey @eldimious I think that wss is indeed not stable, but @leoyvens may have a more detailed summary.
Closing this issue for now, please re-open if you see this issue with rpc.
