### ISSUE TITLE
Optimize subgraph synced check

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#5085]
Every time we process a block, we check if the subgraph has reached the chain head and can be considered synced. Right now this requires a roundtrip to the DB to check the chain head, here:
https://github.com/graphprotocol/graph-node/blob/fe96516fb6dd8300d9eafd9e40a7eb6eb7ee7395/core/src/subgraph/runner.rs#L753

This overhead is unnecessary, since if a subgraph checks the chain head once and sees that it is very far, there is no need to check again on every block processed.

**Comment by lutter** [comment]
In a similar vein, there is a check in the runner to see if the subgraph is synced: 
https://github.com/graphprotocol/graph-node/blob/master/core/src/subgraph/runner.rs#L590

The runner should know whether a subgraph is synced and only ask the store for that when it starts a subgraph; after that, it already is in control of the synced status and keep that in memory.
