### ISSUE TITLE
[Feature] make it easier to debug issues by providing subgraph hash in http request header to substreams

### ISSUE THREAD

**Issue by matthewdarwin** [graphprotocol/graph-node#5098]
### Description

When using substreams powered subgraphs, when connecting to the substreams grpc endpoint also provide the subgraph hash via an HTTP request header (eg x-subgraph-hash).  This can be logged on the substreams side to improve ability to debug problems.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by azf20** [comment]
Thanks @matthewdarwin - @mangas would this be a simple thing to add?

**Comment by YaroShkvorets** [comment]
PR: https://github.com/graphprotocol/graph-node/pull/5319
