### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by saez0pub** [graphprotocol/graph-node#5103]
### Description

Hello,

I'm waiting for https://github.com/graphprotocol/graph-node/pull/4991.
The last release (v0.33.0) is from 3 month ago.
The [number of commits](https://github.com/graphprotocol/graph-node/compare/e12c79cff17e31d93175b5a1fca95a1f30f5dcf5...master) since this last release is quite high.
Do you think a new release is coming soon ?

Thanks.

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by incrypto32** [comment]
Yes a new release is coming soon, ideally in a week or two
