### ISSUE TITLE
[Bug] Account-like optimization does not work for subqueries

### ISSUE THREAD

**Issue by avandras** [graphprotocol/graph-node#5153]
### Bug report

During recent CPU usage peaks on the hosted shard `uniswap-a` I noticed that the peaks are mostly attributable to a single query:

```sql
select $15 as entity, to_jsonb(c.*) as data
  from (select c.* from "sgd647572"."pool_day_data" c
 where c.block_range @> $1 and (c."date" >= $2 and exists (
    select $16
      from "sgd647572"."pool" as i
     where i."id" = c."pool" and i.block_range @> $3 and (i."id" in ($4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14))
)) order by "date" desc, "id" desc limit $17) c
```

When checking what I could do to improve its performance, I noticed that `sgd647572.pool` is already treated with the account-like optimization:

```sql
graph-uniswap-a=> SELECT * FROM subgraphs.table_stats WHERE is_account_like;
 id | deployment |   table_name   | is_account_like | last_pruned_block 
----+------------+----------------+-----------------+-------------------
  4 |     647572 | token_day_data | t               |                  
  3 |     647572 | token          | t               |                  
  1 |     647572 | pool           | t               |                  
  2 |     647572 | tick           | t               |                  
(4 rows)
```

Despite this, the subquery above doesn't contain the to conditions that help the query planner choose the brin indexes.  According to @lutter this is indeed a bug.

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by leoyvens** [comment]
This is probably caused by #5010 which can be reverted in configuration by setting `GRAPH_STORE_USE_BRIN_FOR_ALL_QUERY_TYPES="true"` on the query nodes. So not really a Graph Node bug, unless we decided we want to change something about #5010.

**Comment by avandras** [comment]
Based on what @leoyvens said, closing this.
