### ISSUE TITLE
[Bug] Cannot build docker image for v0.34.1 on Mac M2

### ISSUE THREAD

**Issue by gauthiermyr** [graphprotocol/graph-node#5211]
### Bug report

On my Mac M2, I was successfully able to build the docker image for v0.33.0 but when I'm trying to build it for v0.34.1 I get `build failed`. 

I already tried to increase my docker resources but it still does not work

(see logs)

### Relevant log output

```Shell
=> [graph-node-build 3/3] RUN apt-get update     && apt-get install -y cmake protobuf-compiler &&     cd /graph-node &&     RUSTFLAGS="-g" cargo build --release --package graph-node     && cp t  1907.0s
 => => # rlib --extern shellexpand=/graph-node/target/release/deps/libshellexpand-fe96ccc21ce06f33.rlib --extern termcolor=/graph-node/target/release/deps/libtermcolor-2e2e8699247cbd0b.rlib --extern url=
 => => # /graph-node/target/release/deps/liburl-c374006a30c88f8b.rlib -g -L native=/usr/lib/aarch64-linux-gnu -L native=/graph-node/target/release/build/ring-ec045581d413568e/out -L native=/graph-node/ta
 => => # rget/release/build/secp256k1-sys-7f2db8a0770c8dcd/out -L native=/graph-node/target/release/build/psm-88d125fcc2dc3776/out -L native=/graph-node/target/release/build/zstd-sys-c39f00a988e647c4/out
 => => #  -L native=/graph-node/target/release/build/wasmtime-fiber-91ff7e7fa2421911/out -L native=/graph-node/target/release/build/wasmtime-runtime-085c1f0495a1a7e1/out -L native=/graph-node/target/rele
 => => # ase/build/blake3-ae06b6d01e216f87/out` (signal: 9, SIGKILL: kill)
 => => # warning: build failed, waiting for other jobs to finish...
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by Doozers** [comment]
I'm having the same issue for 0.34.0 & 0.34.1

**Comment by chrisdotn** [comment]
I'm having the same issue with 0.34.0 and 0.34.1. I've been using podman with this config:

```
> podman machine list
NAME                     VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        42 hours ago  Currently running  5           8GiB        100GiB
```

I've tried to increase the memory up to 16GB, which resulted in the same error.

**Comment by leoyvens** [comment]
Try a lot of RAM. 32 GB or even 48 GB.

**Comment by chrisdotn** [comment]
More ram solved it for me. I tried with 48 GB, which worked. I haven't tried with 32 GB that might also work.

**Comment by leoyvens** [comment]
Thanks for reporting back, closing as resolved.

**Comment by gauthiermyr** [comment]
Don't have enough RAM to build it locally then..
