### ISSUE TITLE
[Bug]  validate module in substream-powered-subgraphs

### ISSUE THREAD

**Issue by matthewdarwin** [graphprotocol/graph-node#5225]
### Bug report

If a user provides an IPFS hash of a  substream-powered-subgraph, graph-node should ensure the spkg file has a `graph_out` module.  Graph-node always connects to substreams requesting `graph_out`, and if it is not there, then no point in sending the request.

### Relevant log output

```Shell
I noticed this because I was reviewing a list of subraph hashes.  I didn't observe the missing check directly.
```

### IPFS hash

QmZPsXyBjR2NFfDc17pxrrWcoAPmi8Fya7azC3qGWzfeU5

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment]
@mangas does Graph Node have knowledge of substreams spkg internals to easily to this today?

**Comment by matthewdarwin** [comment]
Bump this issue.  Triaging issues on hosted service, 2 subgraphs had this issue. @azf20 @mangas
