### ISSUE TITLE
Subgraph not keeping up with chain head

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-node#5235]
### Bug report

This subgraph( QmPy7o9wnKEidMJUvVTiDdne2rrdJ28v122b7WJK6oRQkH)  indexing zk-sync era is consistently 20-30 blocks behind chainhead. cc @leoyvens 

Proposed fix:  Change the behaviour of `GRAPH_CHAIN_HEAD_WATCHER_TIMEOUT`

### IPFS hash

QmPy7o9wnKEidMJUvVTiDdne2rrdJ28v122b7WJK6oRQkH

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by leoyvens** [comment]
We did some improvements in this area, we can re-open if it reproduces again.
