### ISSUE TITLE
Add key-based authentication for Firehose/Substreams providers

### ISSUE THREAD

**Issue by YaroShkvorets** [graphprotocol/graph-node#5258]
### Description

In addition to JWT-based authentication, Firehose and Substreams endpoints [now support key-based authentication](https://github.com/streamingfast/firehose-core/commit/7411f2b49205b5b9fe785302c509f8ca877955f9) via `x-api-key` header.

Proposal to add optional `key` field to Firehose config struct in addition to `token`.  Operators can continue using `token` or switch to `key`.

Example config with token (used today):
```
provider = [
     { label = "substreams", details = {type = "substreams", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]
```

Example config with key:
```
provider = [
     { label = "substreams", details = {type = "substreams", url = "$SUBSTREAMS_ENDPOINT", key = "$SUBSTREAMS_API_KEY", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]
```

### Some information to help us out

- [X] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by YaroShkvorets** [comment]
PR: https://github.com/graphprotocol/graph-node/pull/5259

**Comment by YaroShkvorets** [comment]
Rebased this PR on top of the latest master branch per your request @mangas 

There is something else to consider. We've had a discussion with @abourget about this header, and he mentioned they would eventually want to be able to specify arbitrary headers in the config for firehose/substreams provider. I.e. not just `X-Api-Key` for authentication but also `X-Sf-Substreams-Parallel-Workers` for example, and others.

So we have two options:
- merge this PR now and implement arbitrary headers feature in the future
- not merge this PR and implement arbitrary headers feature instead that would cover this header as well.

**Comment by azf20** [comment]
Thanks!
