### ISSUE TITLE
Storage getting full due to block storage 

### ISSUE THREAD

**Issue by rdx4499** [graphprotocol/graph-node#5260]
I have deployed graph node on aws with limited storage, I am running docker on ec2. For some reason my graph node randomly storing block data on ipfs folder. I have also made  DISABLE_BLOCK_INGESTOR to true. But it's not working.

This is my docker compose file.
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - 172.18.0.1:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://rpc.v4.testnet.pulsechain.com'
      GRAPH_LOG: info
      DISABLE_BLOCK_INGESTOR: true
  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

**Comment by azf20** [comment]
hey @rdx4499 you are seeing block data in the ipfs folder, not in the database?

**Comment by rdx4499** [comment]
Yes, In in ipfs data folder there is blocks folder which is storing lot of data, 
currently I have switched to ubuntu instances with same configuration but it is not storing block data this time   
Storing this block data was unpredictable, as when I clean all the data and resync my subgraph it does not store blocks initially, but after some days it's get filled. (This is when I was using amazon linux )

**Comment by rdx4499** [comment]
> hey @rdx4499 you are seeing block data in the ipfs folder, not in the database?

Yes @azf20, In ipfs data folder there is blocks folder which is storing lot of data,
currently I have switched to ubuntu instances with same configuration but it is not storing block data this time
Storing this block data was unpredictable, as when I clean all the data and resync my subgraph it does not store blocks initially, but after some days it's get filled. (This is when I was using amazon linux )
