### ISSUE TITLE
[Bug] Derived loaders does not respect causality regions

### ISSUE THREAD

**Issue by incrypto32** [graphprotocol/graph-node#5267]
### Bug report

Derived loaders are not respecting causality regions.
Entities created by file data sources are not allowed to be loaded from an onchain handler but it can be loaded when entities are linked via a derived field in another entity. 

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment]
hey @psparacino thanks, would be great to understand the specific use-case in a bit more detail, can you share where you are using `ipfs.cat` in this way?
