### ISSUE TITLE
block polling failed issue in graph node

### ISSUE THREAD

**Issue by mihiradx** [graphprotocol/graph-node#5277]
We have set up a Graph Node on a Docker system. 
Here is the error we encountered while syncing blockchain data:

Error: "ERRO Trying again after block polling failed: Block data unavailable, block was likely uncled (block hash = 0xd7649c6c8da4bb868dfd5450bfca0b5573c5a88ddd5a15635ad4e1997b3c6), provider: abeychain-rpc-0, component: EthereumPollingBlockIngestor"

Any suggestions on what the issue could be?

**Comment by azf20** [comment]
Hey @mihiradx this is expected behaviour in case of a re-org. If this is happening continuously there may be some issue with the RPC (is it EVM compatible?), closing for now please re-open if you are having issues
