### ISSUE TITLE
[Feature] Add support for fetching block receipts using eth_getBlockReceipts

### ISSUE THREAD

**Issue by tornadocontrib** [graphprotocol/graph-node#5290]
### Description

Currently Graph Node requires syncing block receipts and this would cause overload on RPC since it would call like from 50 requests to 100 requests of eth_getTransactionReceipt for high throughput networks like BSC or Polygon.

See related issues here https://github.com/graphprotocol/graph-node/issues?q=is%3Aissue+receipt+is%3Aclosed.

Have created a PR on rust-web3 to support this https://github.com/graphprotocol/rust-web3/pull/15

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by tornadocontrib** [comment]
cc @lutter @incrypto32 could you please check? I think this is a must have feature to run subgraphs on the top of serviced nodes.

**Comment by azf20** [comment]
Thanks @tornadocontrib, this does indeed look interesting. Checking specs for support for this method, it seems like it is pretty widely adopted but might not work for all EVM clients? (just thinking about whether configuration might be required)

**Comment by tornadocontrib** [comment]
@azf20 Yeah, but it has been adopted to major EVM chains like Ethereum https://github.com/ethereum/go-ethereum/pull/27702, BSC ( https://github.com/bnb-chain/bsc/pull/2068 ), Polygon ( They use Erigon so it is already implemented ), Avalanche ( https://github.com/ava-labs/coreth/pull/429 ), Op-stack chains ( They use the latest Geth ) , and this is the only method to enable running graph-node with serviced nodes like Infura or Quicknode especially for the high throughput chains like BSC or Mainnet.

**Comment by tornadocontrib** [comment]
@maoueh Yeah but the problem is eth_getBlockReceipts is not a chain dependent method but it relies whether the node would support it or not ( For example some people could run old nodes that doesn't support this method yet, or the provider simply didn't whitelisted this method on their load balancer, etc. ) So think it should be disabled by users manually.

**Comment by maoueh** [comment]
I'm not sure I understand your concern. My proposition is to make `eth_getBlockReceipts{num: <genesis|0>}` and if it fails, it's not supported otherwise it is.

Network is indeed not related but making the call and have it succeed means it's available.

**Comment by tornadocontrib** [comment]
@azf20 @maoueh Is there any plans to implement those? I think it is an important feature that would be able to cut expenses and speedup sync drastically

**Comment by azf20** [comment]
hey @tornadocontrib yes thanks for this, we are investigating and plan to implement, will keep this thread up to date
