### ISSUE TITLE
Define a GraphQL schema for a built-in "subgraph of subgraphs"

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#531]
Could be based on the schema that we have in graph-cli for validating subgraph manifests.
https://github.com/graphprotocol/graph-cli/blob/master/manifest-schema.graphql

**Comment by fordN** [comment]
```graphql
type Subgraph @entity {
    id: ID!
    name: String!
    manifest: SubgraphManifest!
    description: String!
    numberEntities: Int!
    createdAt: BigInt!
    updatedAt: BigInt!
    repository: GithubRepository
}

type GithubRepository @entity {
    id: ID!
    url: String!
    tags: [GithubTag]
    contributors: [GithubContributor!]
}

type GithubContributor @entity {
    id: ID!
    userName: String!
    avatarUrl: String!
    Repos: [GithubRepository!] @derivedFrom(name: "contributors")
}

type GithubTag @entity {
    id: ID!
    name: String!
}

type SubgraphManifest @entity {
    id: ID!
    specVersion: String!
    schema: Schema!
    dataSources: [DataSource!]!
}

union DataSource = EthereumContractDataSource

type EthereumContractDataSource @entity {
    id: ID!
    kind: String!
    name: String!
    source: EthereumContractSource!
    mapping: EthereumContractMapping!
}

type EthereumContractSource @entity {
    id: ID!
    address: String!
    abi: String!
}

type EthereumContractMapping @entity {
    id: ID!
    kind: String!
    apiVersion: String!
    language: String!
    file: File!
    entities: [String!]!
    abis: [EthereumContractAbi!]!
    eventHandlers: [EthereumContractEventHandlers]!
}

type EthereumContractAbi @entity {
    id: ID!
    name: String!
    file: File!
}

type EthereumContractEventHandler @entity {
    id: ID!
    event: String!
    handler: String!
}
```

**Comment by nenadjaja** [comment]
Looks good @fordN ! 
A few things:
1. What's a `GithubTag` and what do we need it for?
2. Do we have the information about what's the network that a contract is deployed to?

**Comment by nenadjaja** [comment]
I am a little confused about why do we use `__subgraphs`. In my understanding, introspection is predefined in GraphQL, and there are 3 options for introspection queries: `__type`, `__schema` and `__typename`. Are we defining our own introspection query?

**Comment by Jannis** [comment]
@fordN A couple of remarks:

- Move `description` from `Subgraph` to `SubgraphManifest` and make it optional.
- Move `repository` from `Subgraph` to `SubgraphManifest` and make it just a `String` (optional).
    * We don't track any other details about the repository in the database (no tags, contributors etc.).
    * As a consequence, drop `GithubRepository`, `GithubContribitor` and `GithubTag`.
- Remove `union DataSource`, as it isn't used and we currently don't support unions.
- Change all instances of `File` to `Link`.
- Add `type Link @entity { key: String!, value: String! }` (see https://github.com/ipld/specs/blob/master/IPLD.md#what-is-a-merkle-link for more info about merkle-links / IPLD links).

**Comment by Jannis** [comment]
@nenadjaja Sorry about the confusion. The `__` in `__subgraphs` was supposed to indicate that it is an internal subgraph.

However, now that we have `/by-id/<subgraph id>` and `/by-name/<subgraph name>`, how about we expose this internal "subgraph of subgraphs" at `/subgraphs`?

**Comment by nenadjaja** [comment]
@Jannis If we don't store Github repo info in the database, how are we going to get contributors and other data? Make an API call when the page loads?

**Comment by Jannis** [comment]
About how we'd store these entities in Postgres: I saw somewhere that we could use `subgraphs` in the `event source` column. That's not a good idea. We'll want to be able to query this data efficiently, via the primary key, which is `(subgraph ID, entity type, ID)`, so let's use `subgraphs` as the `subgraph ID` in Postgres and leave `event source` blank.

**Comment by Jannis** [comment]
@nenadjaja GitHub has a GraphQL API, we can use an Apollo link with `ApolloClient` to combine that endpoint with ours.

**Comment by fordN** [comment]
updated schema

```graphql
type Subgraph @entity {
    id: ID!
    name: String!
    manifest: SubgraphManifest!
    numberEntities: Int!
    createdAt: BigInt!
    updatedAt: BigInt!
}

type SubgraphManifest @entity {
    id: ID!
    specVersion: String!
    description: String!
    schema: String!
    dataSources: [EthereumContractDataSource!]!
    repository: String
}


type EthereumContractDataSource @entity {
    id: ID!
    kind: String!
    name: String!
    source: EthereumContractSource!
    mapping: EthereumContractMapping!
}

type EthereumContractSource @entity {
    id: ID!
    address: String!
    abi: String!
}

type EthereumContractMapping @entity {
    id: ID!
    kind: String!
    apiVersion: String!
    language: String!
    file: Link!
    entities: [String!]!
    abis: [EthereumContractAbi!]!
    eventHandlers: [EthereumContractEventHandler]!
}

type EthereumContractAbi @entity {
    id: ID!
    name: String!
    file: Link!
}

type EthereumContractEventHandler @entity {
    id: ID!
    event: String!
    handler: String!
}
```

**Comment by Jannis** [comment]
Looks good! @leodasvacas This is the schema for the built-in "subgraph of subgraphs".

**Comment by leodasvacas** [comment]
@Jannis Great, I'll get to it, thanks for giving the green light.

**Comment by leodasvacas** [comment]
@fordN What's `Link` meant to be? Can I use `String` for it?

**Comment by leodasvacas** [comment]
In that line, I'm also cutting `updated_at` since updating only makes sense when tied to a name.
