### ISSUE TITLE
When a subgraph is deployed, parse it, write it to Postgres as entities using `subgraphs` as the subgraph ID

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#532]
Depends on https://github.com/graphprotocol/graph-node/issues/531.

Includes deploying this implicit subgraph of subgraphs at startup.

<s>Includes listening to the store for subgraph updates from the GraphQL servers to keep the available subgraphs and their schemas up to date.</s>

**Comment by timmclean** [comment]
If we have all query nodes storing schemas from all subgraphs, will that be a scalability issue?

**Comment by leodasvacas** [comment]
I didn't quite get the requirements for this one.

> keep the available subgraphs and their schemas up to date

Why is this necessary? Isn't it just a matter of putting the subgraph in the store upon deployment?

**Comment by Jannis** [comment]
There are two aspects here:

1. We'll want to be able to query which subgraphs are deployed, what data sources they have etc. We'll want to do this through GraphQL, so when a subgraph is deployed, its manifest needs to
     1. either be stored either as entities (so we can reuse the existing query logic), or
     2. be queryable through a dedicated GraphQL resolver much like `StoreResolver`.

For this, putting the subgraphs into the store is enough.

2. When a subgraph `foo` is queried via e.g. `http://somehost.com/foo/graphql` or subscribed to via `ws://somehost.com/foo`, the GraphQL/HTTP server or GraphQL/WebSocket server need to be able to load the schema of `foo` in order to pass it to the GraphQL runner.

That's what the `keep the available subgraphs and their schemas up to date` is about. Now, it may be fine to resolve the subgraph's schema using the store when the request comes in. In that case we can lazily resolve it in the GraphQL/HTTP or GraphQL/WebSocket server and then pass it to the GraphQL runner. Perhaps that's what we should start with.

@leodasvacas @timmclean What do you think?

**Comment by timmclean** [comment]
Sounds good to me. I like the lazy schema resolution :+1:
My sense is that if all query nodes can handle any query, then we shouldn't have any subgraph-specific state in the query nodes (caching or otherwise). But schemas are small, so I might be overestimating the issue

**Comment by Jannis** [comment]
If we lazily resolve schema at query time, that requires a roundtrip to Postgres to get the schema string, followed by transforming that original schema into an API schema. So it'll add a bit of an overhead, but until we find that to be problematic, it's better than caching — because this way, we avoid the problem of cache invalidation when a subgraph name is updated/removed and the subgraph version that was deployed to the name should no longer be available for querying.

One easy optimization we can make is to not just put the original schema into the database, but also store the wrapped API schema in the database. But again, that's a premature optimization with downsides — e.g. an `graph-node` update could affect the API schema generation and then the version in the database could be incompatible.

**Comment by leodasvacas** [comment]
We must always resolve the id to query, and a cache by id never goes stale so that I think is worth it.

**Comment by leodasvacas** [comment]
In that line, I'm also cutting `updated_at` since updating only makes sense when tied to a name.
