### ISSUE TITLE
Allow to query any subgraph that is in Postgres, not just the ones currently deployed

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#534]

**Comment by leodasvacas** [comment]
This should probably results from the simplest implementation, it seems we'd have to go out of our way to _not_ allow this.

**Comment by Jannis** [comment]
We don't currently support it, as only a subgraph that has gone through `subgraph_deploy` can be queried right now. Persistent subgraphs can change this though. But yes, ultimately, doing this should be simpler than restricting which subgraphs can be queried. 😄
