### ISSUE TITLE
Check for under/overflow when reading BigInts from Asc as U256

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#536]
In the new simplified types for Asc we no longer have a direct representation for U256, we just use BigInt for everything. But we lost some overflow checks in that process, we should get them back. This will require that we no longer read from asc as ethabi::Token directly, we'll need to read to an intermediate type.

**Comment by Jannis** [comment]
@leoyvens Is this still an issue?

**Comment by leoyvens** [comment]
Yes, it would still be nice to check this.

**Comment by leoyvens** [comment]
I'm reticent to change the behavior on graph node at this point. It could just print a warning. But nobody has ever complained about this so I'll just close for now.
