### ISSUE TITLE
[Feature] Allow for hard coded values for Declarative calls

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-node#5401]
### Description

There are instances where subgraphs have hard coded values that get referenced (such as stablecoin contract addresses or factory a address) which are not obtainable through the event.params. 

It would be nice to be able to input a static string for Declarative calls inside the manifest as released in #5264 

e.g.

```
          calls:
            Oracle.getPrice: Oracle[event.address].getPrice('0x04068da6c83afcfa0e13ba15a6696662335d5b75') #USDC 
```

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by encalypto** [comment]
This was added in PR #5498, closing this ticket.
