### ISSUE TITLE
[Feature] Sync log for deployments

### ISSUE THREAD

**Issue by Data-Nexus** [graphprotocol/graph-node#5435]
### Description

We have a `created_at` field in the `deployment_schemas` table, but it would be nice to also have a `synced_at`. 

This is primarily to benchmark sync speeds for various subgraphs. 

### Some information to help us out

- [X] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by Shiyasmohd** [comment]
This #5566 PR adds this feature and has been merged
