### ISSUE TITLE
Turn the GraphQL implementation into a standalone crate

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#544]
**Do you want to request a *feature* or report a *bug*?**
Architectural proposal

**What is the current behavior?**
The project contains a built-in graphql parser. While it is spec-compliant in terms of the core language principles (query and sdl parsing), the current implementation contains a various pieces within the execution engine that prevent it from being applicable to use-cases outside of this project. For instance, there is no concept of registering field-specific resolvers.

**What is the expected behavior?**
The graphql implementation should follow the widely accepted design goals as described in the spec and implemented by the broad array of other libraries for the various different platforms. 

The aforementioned limitation around the hard-coded resolver could be re-implemented on top of that using a configured default field resolver (as seen in other libraries, e.g. graphql-js) or by explicitly registering the custom graph-node resolver in a schema post-processing step (visitor) for all fields that don't explicitly register a custom resolver. The same concept can be applied for type resolvers.

By moving the graphql implementation to a separate project / repository, you also open it up for non-graph-node users. This could help with maintenance, robustness, etc. by attracting more contributors from the whole Rust community. Building a rfc/spec compliant library that follows the design widely adopted design principles of the graphql community would also help with compatibility with possible extensions or even client-side libraries.

**Comment by Jannis** [comment]
Making our GraphQL crate useful outside the project is currently not a priority for us. As we move forward, there will likely be a number of requirements that are hard or impossible to implement with the typical per-field resolver abstraction that most libraries provide (think: flexible query routing, metering etc.).

Just to clarify: The GraphQL parser used in this project is not built in. We're using https://github.com/graphql-rust/graphql-parser for this. The part that is built into graph-node is query/subscription execution.

It's also worth noting that our current GraphQL implementation is a 1:1 implementation of the GraphQL specification (with some parts currently missing, like validation). As such, it is standards compliant. The GraphQL specification mandates no specific resolver design.

**Comment by fubhy** [comment]
Correct, it does not mandate a concrete resolver implementation, after all the spec focused exclusively on the language features. However, it does prevent customization of the schema in the most critical place: field resolvers.

> As we move forward, there will likely be a number of requirements that are hard or impossible to implement with the typical per-field resolver abstraction that most libraries provide (think: flexible query routing, metering etc.).

Can you give a more concrete example of what you think would be impossible with standard field level resolvers? The resolve info and context should transport enough information to traverse the inbound query and apply optimizations without taking away customization capabilities. Buffering of resolvers might also be helpful in this context. Furthermore, you can process incoming queries with customized visitors on the AST level to apply pre-execution optimizations or even write additional information into the resolver context that can then be used to execute, including these optimizations, on the field level.

**Comment by Jannis** [comment]
Custom field resolvers — to the degree that we decide to support them — will likely be defined by e.g. referencing a resolver function from the schema. The actual logic for that custom resolver would then dynamically dispatch to that resolver function.

Note that, in The Graph, there are no fixed fields to resolve other than `Query` and `Subscription`. All other fields are dynamically resolved based on the entity types being queried. Our schema is much more dynamic than in common web services that use GraphQL with explicitly defined resolvers.

**Comment by fubhy** [comment]
> Note that, in The Graph, there are no fixed fields to resolve other than Query and Subscription

GraphQL, at its core, is as popular as it has become over the past years because of the flexibility and control it hands over to the front-end engineers. By limiting the schema to a tightly coupled, storage-derived implementation you are taking away that freedom entirely.

I would still like to understand the roadblocks you see for allowing full control of the schema's field resolvers. Maybe I can help to find a way around those.

**Comment by Jannis** [comment]
@fubhy We seem to be thinking about GraphQL differently. I personally am leaning more towards the Prisma-approach to GraphQL, which is to provide a standard API on top of a user-defined data model, with certain conventions. I'll buy that GraphQL is successful because it puts clients in control over what they can query (which fields, which related data etc.), but I'm less convinced that it's due to the flexibility of the schema. It seems we have different perspectives on that, which I think is fine.

My concerns about entirely user-defined field resolvers (i.e. no mandated GraphQL API from our side — I interpret this is what you're suggesting?) is partly about developer experience (like I said, I prefer standardized APIs) and partly about validation of non-uniform queries in the decentralized network (adding @Zerim so he can think about this a little).

Having said all this, if the GraphQL execution crate by itself is useful, it should be possible to extract it into a standalone crate, so others can use it. The Graph Node would still use it to execute GraphQL queries/subscriptions against its store resolver.

When it comes to custom field resolvers, what are you missing compared to the current entity-based API, where most fields correspond to entity attributes / relationships? E.g. things that you cannot do in e.g. event handlers?

**Comment by Zerim** [comment]
Don't have a ton to add here, I think Jannis has captured my thoughts pretty well.

If there's something we've built that can be extracted and generalized into it's own crate, then we're happy to accept PRs which make our work more useful for the community! We can add it to our backlog as well, but it probably won't be a short-term priority.

As for how we parse GraphQL schemas, I'll echo that our use case is a bit narrower than the one that the GraphQL spec aims to support. Specifically we are using the GraphQL IDL for *data modeling*, which has slightly different concerns than a generic interface definition language.

For example, consider this example from the GraphQL spec using field arguments:
```graphql
type Person {
  name: String
  picture(size: Int): Url
}
```
What information does the field argument `size` convey in a data modeling context? How would you use it to inform the SQL schema, in the general case?

Restricting the use of the GraphQL IDL to data modeling allows us to deterministically compute the appropriate schema at the storage layer, or in our merkelized indexes in our decentralized network, and expose them through a standard interface. In the future that interface may expand to support multiple query languages, another reason for not having GraphQL-specific concepts like field arguments be a part of our data model.

That being said, I could imagine getting around this by having something like "derived attributes" where maybe we specify a directive that a certain field should be ignored from a data modeling perspective, and that custom resolve logic will be supplied for that field.

But that doesn't really align with the current goals for the project, we're not trying to be a generic GraphQL server... so if you're arguing that the goals of the project should be expanded to meet your use case (I'm not sure that you are), I think it would help us if we understood more what you're trying to build :)

Finally, I'll note that if you would like to integrate our more prescriptive API into a more flexible GraphQL API server, there are tools for doing that (i.e. [Schema Stitching with Apollo](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html))

I guess I had more to say that I thought 😂

**Comment by fubhy** [comment]
Thanks for taking the time to explain your perspectives. Appreciated!

After reading your comments and also your reference to Prisma I think I now better understand where you are coming from. However, I also believe that you are misunderstanding a very important notion of Prisma that makes a big difference in this case. Now that I realized that, though, I think I also better understand your arguments and might have a better suggestion moving forward.

First, let me respond to some of the things brought up in your previous comments, though:

> I personally am leaning more towards the Prisma-approach to GraphQL, which is to provide a standard API on top of a user-defined data model, with certain conventions. I'll buy that GraphQL is successful because it puts clients in control over what they can query (which fields, which related data etc.), but I'm less convinced that it's due to the flexibility of the schema. It seems we have different perspectives on that, which I think is fine.

In reality, complex applications have more than just a single data model in a single storage layer. GraphQL is here to abstract the knowledge of the underlying storage layer(s) (multiple!), local & remote APIs and potentially more. Ideally, the **END-USER** GraphQL schema is specifically designed according to the concrete data requirements of a specific user interface and completely takes away the burden of understanding the underlying database models. Front-end engineers don't think of their data in terms of rows and columns or join tables or whatnot. They don't want to go back to writing SQL queries in their templates and then restructure, combine, compute, etc. the returned raw data to fit the requirements for visualization in the user interface.

I therefore stand by my original argument that the **END-USER** schema needs to be 100% customizable, including the ability to completely take control of all field resolvers. The **END-USER** schema should also have zero business-logic related / storage data-model related directives or other implementation details in it.

> Finally, I'll note that if you would like to integrate our more prescriptive API into a more flexible GraphQL API server, there are tools for doing that (i.e. Schema Stitching with Apollo)

Schema stitching is nice in theory but comes with its own can of worms and complexities. As soon as you are sharding a schema across multiple remote graphql engines you are penalizing the performance, tooling, developer experience, etc. It's nice in theory and might work well in some scenarios but it's certainly not the the go-to solution in most cases.

=======================

Back to the original issue:

You mentioned Prisma in your comments. That's interesting because Prisma, at the surface, actually does what I suggested in my original comment (allows full schema customization, etc. for the end-user schema). So far, what you are doing here only covers the "back-end side" of what Prisma is doing. The user-facing part that I am arguing for is completely missing (as far as I can tell). The issue I have with your approach is, that so far you are also exposing the low-level data model layer as the end-user schema. This is what sets you apart from Prisma. Prisma, in fact, has two schemas. One for data modeling and generating a storage layer, and one for the end-user which might be completely different. Instead of directly exposing the data layer as the schema, Prisma actually generates code which can be used in the end-user schema's resolvers. Underneath, that code queries that data schema (also with GraphQL) but completely leaves the developer in control of how the end-user schema works.

I don't have a problem with you using the SDL for data modeling as long as that is an **internal** abstraction. Currently, however, it looks like you also want to expose that schema to the end-user as a means to query data in a dApp for instance. This is where we disagree. 

So, with a better understanding of your arguments now and also since you brought up Prisma I think instead of changing your underlying SDL based data modeling and storage layer generations I think I want to propose to actually **ADD** another layer on top. This would mean having two schemas in the end: One for data modeling, using directives as you do now, etc. for generating the storage layer and an API (like Prisma) that enables a fully custom top level schema to be built around it.

At that point, the only difference to Prisma would be that you are serving from a different storage layer and that you would also derive the indexing logic from it.

**Comment by fubhy** [comment]
I also opened https://github.com/graphprotocol/graph-node/issues/545 by the way, which also contains some arguments that are relevant for this discussion.

At Devcon IV I had a ~1 hour conversation with Yaniv over dinner where we also spoke about all this. I am with Melonport by the way. We would love to integrate this into our dApps data layer. I've been working with GraphQL since even before it was officially released, hence my (arguably slightly stubborn) views ;-)

Would you be interested in discussing this further in a video call? Maybe it would be easier to understand each others arguments that way and potentially even find a solution that would satisfy both ends of the problem space (front-end and back-end).

**Comment by Jannis** [comment]
I think even when we talk about Prisma, we're still talking about two different things. 😉

The only two schemas I see playing part in Prisma are the data model schema (e.g. `type User { ... }`) and the (generated) Prisma API schema (`type Query { users(...): [User!]! ... }`).

The second one is generated based on the first and that's precisely what we're doing as well: the data model schema corresponds to the schema that we currently include in the subgraph. The Prisma API schema corresponds to the one that we derive and serve after loading the subgraph.

I assume when you talk about the layer _on top_ of this, you mean what something like a custom GraphQL server built using the [Prisma Client](https://www.prisma.io/docs/understand-prisma/prisma-basics-datamodel-client-and-server-fgz4/#prisma-client)?

Nothing prevents us to implement a _Graph Client_ library on top of the current GraphQL API that allows for the same scenario. If that's not it, then I'm not sure which piece you think is missing (compared to Prisma, if we stay with this comparison for the moment)?

---

Ok, back to the more forward-looking part of the discussion:

Assuming we did something like this, we need to maintain a few properties that we can maintain in the decentralized network. Such as:

* Resolvers need to run in a controlled environment (e.g. WASM) for things like 
  metering, execution control etc.

* Resolvers need to operate in a way that will  work in the decentralized network. Their execution needs to be possible at all, scale well and we must be able to validate results from resolvers; the last one may be the biggest concern. A uniform API makes this comparably easy.

Until the decentralized design has reached a degree of completeness where we can assess this, I'm a little cautious about adding a feature like this.

Having said that—I could get on board with the concept of having two schemas (one schema for the underlying data model—types, fields, relationships, and one app-facing schema that is implemented via resolvers that in turn are written on an API generated from the data model schema).

(Using the Prisma architecture as an analogy, this would be like combining an app-facing schema + custom resolvers + a (generated) Prisma Client.)

**Comment by leoyvens** [comment]
This was an interesting discussion but is now old and out of context.
