### ISSUE TITLE
Avoid using the SDL for transporting implementation details

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-node#546]
**Do you want to request a *feature* or report a *bug*?**
Architectural proposal

**What is the current behavior?**
The SDL is used to generate the index storage schema and also uses directives in the style of meta programming for implementation details.

**What is the expected behavior?**
The SDL format of the schema should, _in my opinion_, be a frontend-defined contract and therefore completely unaware of any implementation details / business logic of the fulfilling backend. Directives are therefore not the right fit for transporting that kind of information.

**Comment by leoyvens** [comment]
Is your concern here about the `@derivedFrom` directive? It can be helpful for the frontend to know that a field is related to another.

**Comment by leoyvens** [comment]
Closing due to oldness.
