### ISSUE TITLE
Subgraph deployment is persisted even if it fails

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#547]
**What is the current behavior?**
Subgraphs deployments are persisted even if starting them fails.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Deploying an invalid subgraph.
- Restart the node.
- The node attempts to strat the invalid subgrpah.

**What is the expected behavior?**
Deployments of subgraphs that error on `start` are not persisted.

**Comment by timmclean** [comment]
I think we'll fix this one by having a little state machine for each subgraph:
- Initial processing: the initial catch up to the chain head
- Streaming: caught up to chain head at least once, now just processing new blocks as they come in
- Terminated: subgraph experienced an unrecoverable error during processing, will no longer process blocks

Subgraph that are terminated will not be started again on node restart, so you won't get the error again each time (we might want a way to force a retry though).

**Comment by timmclean** [comment]
Can you give an example of how to make an invalid subgraph?

**Comment by leodasvacas** [comment]
That's even better than I thought, I was just thinking of subgraphs that fail to resolve. Like in this issue @davekaj found https://github.com/graphprotocol/graph-cli/issues/166, where a space in the contract address causes a parse failure.

**Comment by timmclean** [comment]
Ah I see, makes sense. Do you think there will be a class of errors that should cause the deployment to reject completely, but that we won't pick up on the graph-cli side? We could even block the deployment fully for those... it would take a bit more work though and I'm thinking we could handle most (all?) of them during compilation instead.

I'll plan on implementing the Terminated state either way

**Comment by timmclean** [comment]
All right I'll see what I can do!

**Comment by Jannis** [comment]
There is one problem with this: if the subgraph fails due to a bug in `graph-node` and we update `graph-node`, the node should try indexing the subgraph again.

So we may have to include some form of reliable `graph-node` versioning information in the failed -> retry or not logic.

**Comment by leodasvacas** [comment]
@Jannis Don't agree with that, only a minority of failed subgraphs will have failed due to bugs, and we can't tell which ones.

This makes me think that if `graph-node` makes a breaking change, it should not try to redeploy any subgraphs. But making the cli and the node aware of their versions is an independent issue.

**Comment by leodasvacas** [comment]
I think we probably don't want to do this, considering that it wouldn't make the failure visible on the explorer.
