### ISSUE TITLE
Add back component names to logging?

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#549]
This section of the logs all have component=SubgraphInstanceManager:

```
  block_number: 5295703
   block_hash: 0x76c484b5722d6f4339d4b5bc5d29d5b3f33107301e48c425a17e77653dcb5027
    Nov 01 14:25:55.065 INFO Processing events from block
    Nov 01 14:25:55.065 INFO 1 event found for this subgraph
    Nov 01 14:25:55.067 DEBG Process Ethereum event, handler: handleLandUpdate, signature: Update(uint256,address,address,string)
    Nov 01 14:25:55.265 DEBG Call smart contract, function: decodeTokenId, contract: LANDRegistry, address: 0xf87e…5d4d
    Nov 01 14:26:05.763 INFO Applying 2 entity operation(s)
```

Should these change the "component" property to SubgraphInstance, RuntimeHost, and EthereumAdapter?

(Main downsides: it's less readable for end users, and it means putting a line at the top of every e.g. EthereumAdapter method)

cc @Jannis for input

**Comment by leodasvacas** [comment]
We publish logs for users now and I don't think the component info is helpful for them (or that helpful for us).
