### ISSUE TITLE
Add contributing guidelines and a code of conduct

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#55]
As @fordN pointed out, Rust / Diesel could serve as an inspiration:

https://github.com/diesel-rs/diesel/blob/master/CONTRIBUTING.md
https://github.com/diesel-rs/diesel/blob/master/code_of_conduct.md

**Comment by yanivtal** [comment]
This was done in bd9a0c0b57fe732fc138b0fba00d729580194226
