### ISSUE TITLE
[Bug] handle reverted eth_calls on declared eth_calls

### ISSUE THREAD

**Issue by Shiyasmohd** [graphprotocol/graph-node#5514]
### Bug report

Declared eth_calls executes before eth_calls on handlers triggered. But when declared eth_calls get reverted, subgraph get stuck in syncing.

Repo that can reproduce this error - [Link](https://github.com/Shiyasmohd/declared-eth-call-err)
Deployment ID: `QmfH5xCioLUqd1zM2b2QGE6Br5uZdks2tx2A1NPB1dZQSK`

Subgraph that sync when declared eth_call is removed
Deployment ID: `QmaWD3fz3Y6PZdEmZ9QQ79fkVwTzh49JBqLcbzG85wDMrr`

### Relevant log output

```Shell
Error: Ethereum node returned an error for an eth_call: RPC error: Error { code: ServerError(-32015), message: "VM execution error.", data: Some(String("Reverted ERC721URIStorage: URI query for nonexistent token")) }
```

### IPFS hash

QmfH5xCioLUqd1zM2b2QGE6Br5uZdks2tx2A1NPB1dZQSK

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by incrypto32** [comment]
@Shiyasmohd can i close it? this is non-issue now right?

**Comment by Shiyasmohd** [comment]
Yes. Closing this issue.
