### ISSUE TITLE
[Bug] Substreams BigDecimal encoding issue when value is zero

### ISSUE THREAD

**Issue by DenisCarriere** [graphprotocol/graph-node#5644]
### Bug report

```rust
tables
    .create_row("Balance", token.as_str())
    .set("owner", owner)
    .set_bigdecimal("balance", &0.to_string());
```

Using `set_bigint_or_zero` does work in the event the value is `0`, however this forces to use `BigInt` GraphQL type.

Using Substreams Entity Changes https://github.com/streamingfast/substreams-sink-entity-changes

### Relevant log output

```Shell
postgres    | 2024-09-15 04:12:42.032 UTC [577] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
postgres    | 2024-09-15 04:12:42.032 UTC [577] CONTEXT:  unnamed portal parameter $2
postgres    | 2024-09-15 04:12:42.032 UTC [577] STATEMENT:  select $1 as entity, to_jsonb(e.*) as data
postgres    | 	  from "sgd1"."balance" e
postgres    | 	 where exists (select 1 from unnest($2) as p(g$id) where id = p.g$id) and e.block_range @> $3
postgres    | 	union all
postgres    | 	select $4 as entity, to_jsonb(e.*) as data
postgres    | 	  from "sgd1"."block" e
postgres    | 	 where exists (select 1 from unnest($5) as p(g$id) where id = p.g$id) and e.block_range @> $6
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by YaroShkvorets** [comment]
@DenisCarriere seems to work. Make sure you declare `balance: BigDecimal!` in the `schema.graphql`

Quick example: https://github.com/YaroShkvorets/common-subgraphs/tree/main/substreams-entities

**Comment by DenisCarriere** [comment]
@YaroShkvorets thanks for looking into this

This issue doesn't seem to be related to `BigDecimal` but instead a missing Entity in one of the pointer fields

Will be closing this issue
