### ISSUE TITLE
[Feature] A way to list deployed Subgraphs

### ISSUE THREAD

**Issue by folex** [graphprotocol/graph-node#5649]
### Description

Hello! 

Is there a way to list the subgraphs that are already deployed on the Graph Node instance?

Thank you!

### Some information to help us out

- [ ] Tick this box if you plan on implementing this feature yourself.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

**Comment by Shiyasmohd** [comment]
@folex You can use this graphman command to list all the deployments in a graph-node.
```
graphman info --all
```
