### ISSUE TITLE
slog-async ERRO due to channel overflow

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#567]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

You get an error message from the logger due to channel overflow. It kinda looks like something is going wrong, but really the subgraph continues on. The error is as follows:

`Nov 09 12:14:46.036 ERRO slog-async: logger dropped messages due to channel overflow, count: 69`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm not exactly sure what caused the error, but the first time I saw it was with the aragon subgraph. 

**What is the expected behavior?**

It shouldn't show an error, because this will throw off anyone using the hosted service. We should increase the limit for messages, or maybe not make this message return an ERRO

**Comment by timmclean** [comment]
This one would be good to take care of before launch -- users are going to see it a lot. It will happen any time lots of logging happens at once

**Comment by Jannis** [comment]
By default, the and logger uses a buffer of 128 logs. If it can't flush them fast enough and there are more logs then that number it'll drop them. That's when you get that message.

We can increase the buffer size to whatever we like.

**Comment by leodasvacas** [comment]
https://github.com/graphprotocol/graph-node/pull/1056 should be the fix.
