### ISSUE TITLE
issue handling uint8 event params types   

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#569]
Attempt reading the event in the mapping cause mapping failure.
Reading a uint8 state variable from the contract also cause mapping failure.

It might be related to the automatic generated getter for the i32 type.

**Comment by leodasvacas** [comment]
Thanks for reporting this, for reference this is an example of code where @orenyodfat hit this issue and worked around it:

https://github.com/ben-kaufman/subgraph/blob/81602488504ec3ac60cf789a9f23b8c85e2266ea/src/mappings/genesisProtocol/GenesisProtocol.ts#L114

**Comment by leodasvacas** [comment]
This has been fixed in graph-ts master.

**Comment by Jannis** [comment]
[graph-ts 0.4.2](https://github.com/graphprotocol/graph-ts/releases/tag/v0.4.2) has been released with the fix.
