### ISSUE TITLE
Querying is returning `null` when we should see `false`

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#571]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When a value is set into the store as `false` , when we query it is is getting returned as `null`. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

First I was pulling in an event which was a byte string of all 0x00000....0 (which is false in solidity), and then when I was querying the graph node I was getting `null` returned.

Then to be sure I explicitly set the variable to `false` in the mapping, and I was still getting null returned. So it seems we have an error here. 

**What is the expected behavior?**

I just want to see `false` in my queries! 🥑

**Comment by fordN** [comment]
I have been able to replicate this issue.  
Looks like it is stemming from the `graph-cli`/`graph-ts` side of things.   Looking in Postgres the entry shows that empty data was entered: `"testBool": {"type": "Null"}}`.

**Comment by fordN** [comment]
It appears the false value is being confused for `null` by the set function which is causing it to `unset` it in the entities typemap.   

Here is the function generated from the graphql schema in my test project and output to `schema.ts` (using `yarn codegen`):  
```
set testBool(value: boolean) {
    if (value === null) {
      this.unset("testBool");
    } else {
      this.set("testBool", Value.fromBoolean(value as boolean));
    }
  }
```

Removing the logic and simply `set`ing the value fixed the issue, the boolean entity attribute loaded correctly into my db.  Here is my modified `set` function:
```
set testBool(value: boolean) {
    this.set("testBool", Value.fromBoolean(value as boolean));
  }
```
Does a false boolean value and a null value get stored the same way? Why does `value===null` appear to be truthy while `value as boolean` correctly converts it to false?  
`0`, `null`, and `false` are all represented by a null pointer?

Let's check out the wast file that the `set` function compiles to...

Before: 
```
(func $src/types/schema/EnsDomain#set:trueBool (; 36 ;) (type $iiv) (param $0 i32) (param $1 i32)
  (if
   (i32.eq
    (i32.and
     (get_local $1)
     (i32.const 1)
    )
    (i32.const 0)
   )
   (call $~lib/@graphprotocol/graph-ts/index/Entity#unset
    (get_local $0)
    (i32.const 320)
   )
   (call $~lib/@graphprotocol/graph-ts/index/TypedMap<String,Value>#set
    (get_local $0)
    (i32.const 320)
    (call $~lib/@graphprotocol/graph-ts/index/Value.fromBoolean
     (get_local $1)
    )
   )
  )
 )
```

After: 
```
(func $src/types/schema/EnsDomain#set:testBool (; 33 ;) (type $iiv) (param $0 i32) (param $1 i32)
  (call $~lib/@graphprotocol/graph-ts/index/TypedMap<String,Value>#set
   (get_local $0)
   (i32.const 268)
   (call $~lib/@graphprotocol/graph-ts/index/Value.fromBoolean
    (get_local $1)
   )
  )
 )
```

**Comment by fordN** [comment]
@Jannis it looks like in the case of `boolean` attributes we cannot rely on `value === null` to check if it should be `unset()`, so we'll need to update [_generateEntityFieldSetter()](https://github.com/graphprotocol/graph-cli/blob/master/src/codegen/schema.js#L97).

**Comment by Jannis** [comment]
Interestingly, the generated boolean setter doesn't allow `null` to be passed in (the argument type is `boolean`, not `boolean | null`). If that works, it is because the compiler somehow lets it slip through.

So that `unset` call should be removed altogether if the type is not nullable. More specifically, the `value === null` branch at https://github.com/graphprotocol/graph-cli/blob/master/src/codegen/schema.js#L160 should only be included in the generated code if `paramType instanceof tsCodegen.NullableType` is true.

**Comment by leodasvacas** [comment]
@Jannis thanks for the pointers. That seems like a good fix for the urgent issue, we can figure out how to have a consistent unset API later.

**Comment by leodasvacas** [comment]
We have a fix that we consider reasonable until AS gains support for `boolean | null`.
