### ISSUE TITLE
error trying to deploy subgraph

### ISSUE THREAD

**Issue by LiorRabin** [graphprotocol/graph-node#582]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to deploy my new subgraph and encounter errors in `graph-ts`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See screenshot attached

**What is the expected behavior?**
To be able to deploy the subgraph.

![screen shot 2018-11-19 at 17 02 40](https://user-images.githubusercontent.com/6675831/48715217-2bed9f80-ec1d-11e8-81ab-c3b931c4859d.png)

**Comment by Jannis** [comment]
@LiorRabin Hi!

There is a simple fix, we are working on making this unnecessary (see https://github.com/graphprotocol/graph-ts/issues/7).

Add the following at the top of your mapping:
```typescript
import 'allocator/arena'
export { allocate_memory }
```

That'll make it build.

**Comment by LiorRabin** [comment]
@Jannis thx! works like a charm :)
