### ISSUE TITLE
Inability to fetch ETH balance from inside a mapping

### ISSUE THREAD

**Issue by tsuberim** [graphprotocol/graph-node#594]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
No ability to fetch ETH balance of an address from inside a mapping.

**What is the expected behavior?**
Expose a function `ETH.balance(address: Address): BigInt`

**Comment by davekaj** [comment]
Closing this in favour of new issue https://github.com/graphprotocol/graph-node/issues/895
