### ISSUE TITLE
Mark AscType trait as unsafe

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#607]
There are some obligations that implementors of the `AscType` trait have in order to maintain memory safety, so we should mark `AscType` as unsafe. This is because `AscType`'s default implementations of `to_asc_bytes`, `from_asc_bytes`, and `asc_size` use unsafe Rust features in a way that is only safe if the type implementing `AscType` has certain properties. We should mark the `AscType` trait as `unsafe` so that implementors are made aware of these requirements.

(From the [nomicon](https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html):
> On trait declarations, `unsafe` means that implementors of the trait must check the trait documentation to ensure their implementation maintains the contracts the trait requires.

)

Any type implementing `AscType` must follow these rules:

1. The type cannot be a Rust pointer or reference. `from_asc_bytes` allows the assembly script mapping to control the memory address of the pointer or reference. `to_asc_bytes` leaks a memory address to the assembly script mappings, which will allow nondeterminism in the mappings and also could be used to help defeat ASLR. The `AscPtr` type is fine, however, because internally it is just a u32 offset into wasm memory and does not affect safety on the Rust side.
2. The type must never be in a state where it has uninitialized memory. In particular, for structs, the compiler may leave gaps between fields for alignment. The uninitialized bytes in these gaps will leak to the mappings via `to_asc_bytes`.
3. All possible byte sequences that match the type's size must be a valid state for the type. This seems to suggest that most enums are unsafe.
4. Any struct or enum fields must be of types that also follow these rules (the struct must not contain any pointers or references, etc).

Any type implementing `AscType` can alternatively override the built-in methods, removing the need to follow these rules (e.g. `AscString` and `ArrayBuffer` do this).

In addition, we also care about these properties are needed for correctness (but not safety):

5. The type must have a portable, defined memory layout. E.g. structs must be labelled `repr(C)`, `repr(u*)` or `repr(i*)`.
6. For determinism, all possible values for a type must be represented in memory in a canonical form. E.g. we can't have a fraction type `struct Fraction { top: i64, bottom: u64 }` unless we are careful to store the fraction only in reduced form (in which case we would need to be careful to check that invariant on deserialization).

I think we can cover most of these rules by using structs with `repr(C)` and being careful about what is in those structs. We need to make sure that the C representation of all structs have no padding. I'm tempted to say that we should use `repr(C, packed)` to solve this problem, but apparently [`repr(packed)` has soundness issues](https://github.com/rust-lang/rust/issues/27060) :( Enums don't seem to be safe as implemented in the `from_asc_bytes` direction currently.

**Comment by leodasvacas** [comment]
At first I thought this was just about code quality but now I see the bug aspect of this which is that it exposes padding bytes which is a source of non-determinism. Fully eliminating non-determinism is important mostly for the distributed network, so it is not the biggest priority atm and it might be the case that we'll move away from the current serialization format entirely before it becomes a priority.

That said if eliminating the padding bytes turns out to not be so difficult, then we might as well do it.

**Comment by timmclean** [comment]
Non-determinism is part of it. I'm most worried about the memory safety pieces though. Do we currently transmute to any enums? I think that can be used to trigger undefined behaviour in rustc. Another safety issue is if we expose padding bytes to mappings, that's uninitialized memory, which could contain secret keys, etc

**Comment by leodasvacas** [comment]
> Do we currently transmute to any enums
 
No.

> that's uninitialized memory, which could contain secret keys, etc

Arg that's a very good point. We should make "no padding" part of the requirements. This can be tested for by asserting the size of all our `AscType`s.

**Comment by timmclean** [comment]
Another thought on enums: maybe we should have separate to/from traits so that the enums we have can only be transmuted in one direction

**Comment by timmclean** [comment]
Thinking more on this... are you sure we don't transmute to an enum somewhere? How does store.set tell the host what type of value is being set?
