### ISSUE TITLE
Validate that entities put in the store contain only fields that exist in the schema

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#615]
Right now we'll hapilly put anything the mapping sends us into the store without validating that the fields actually belong to the schema for that entity. See https://github.com/graphprotocol/graph-node/issues/600 for a case of this happening due to a bug. But could also happen due to user error.

We should also validate that the fields can be converted to the type declared in the schema.

**Comment by Jannis** [comment]
Yeah, this would be lovely to catch. It would require schema knowledge in e.g. the host `WasmiModule` so that we can validate `store.set` operations. Not _that_ hard I imagine, the only thing I'm not sure is how we'd best pass the schema to the module.

**Comment by leodasvacas** [comment]
@Jannis I thought a bit about this. Since the store will soon become the source of truth for schemas, then `store.set` will have easy access to the schema and can do the validation.

**Comment by Jannis** [comment]
@leodasvacas Will it? In what way?

**Comment by lutter** [comment]
This has crept up again in the context of https://github.com/graphprotocol/graph-ts/issues/79

I'll add some validation; in particular, this will check for a `store.set` that

* the entity type actually exists
* the values being set actually have the proper type for the field
* non-nullable fields are not set to null
