### ISSUE TITLE
Support indexing events without specifying a contract address

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#616]
At present you have to specify the address from which events will come. For some event types (for instance, ERC20 transfer), it's beneficial to be able to listen to all matching events, regardless of the address that emitted them.

**Comment by Jannis** [comment]
This may be easy to add support for.

Let's assume we make the `address` field under `dataSources > source` optional but keep the `abi` field so we can identify what ABI the event relates to.

We would now call `eth_getLogs` without an address, which is fine. We should still be able decode event parameters using the ABI (don't need the contract address for that). We may have to relax some checks to allow events to get through to to the mapping runtime but that's easy. Beyond that, no changes should be needed. You should even be able to access the contract by binding ABI + event address.

Let me double-check the related code. My gut feeling is this won't be hard.

**Comment by sorawit** [comment]
Any update on this?

**Comment by Jannis** [comment]
ERC20 will also need internal transaction triggers / function call triggers, as the standard doesn't require contracts to implement events. We're actively working on this right now.

Still, making `address` optional can be useful on its own. I'll put it on next week's development agenda.

**Comment by Jannis** [comment]
@sorawit @Arachnid Support for this has been merged into graph-node, but using it in subgraphs also requires https://github.com/graphprotocol/graph-cli/pull/240 (+ a new graph-cli release). You can expect a release this week.

**Comment by Arachnid** [comment]
Thank you!

Re ERC20 - transfer events are mandatory, but the spec doesn't specify a mandatory event for minting/burning.

**Comment by Jannis** [comment]
@Arachnid Yep, you're right about `Transfer`.

**Comment by FlacoJones** [comment]
Just wondering, but wouldn't it be trivial for me to make an unrelated contract with a different address but identical Event signatures, and alter data for a subgraph indexing in an address-agnostic way like this?

**Comment by liuyihua-cn** [comment]
This is very useful, but if there is a document to explain how can I use this? Very thanks！

**Comment by cezary-stroczynski** [comment]
Hi! Is it possible to define source with `callHandlers` but without contract address? I know it's possible with `eventHandlers` but when I try to use `callHandlers` I got error `subgraph source address is required`

**Comment by azf20** [comment]
Hi I don't think this is possible currently, and would also not be performant given the current reliance on `trace_filter` for fetching calls

**Comment by NBMSacha** [comment]
@FlacoJones 100% - ideally a bytecode protection would be great for this usecase.
