### ISSUE TITLE
Send queries to older subgraph version until latest version has synced

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#622]
Uploading a new version of a subgraph results in a potentially lengthy rebuild, during which the graph can't be queried. It'd be great if we could upload a new version of an existing subgraph, and have the node build the new subgraph in parallel with serving the old one, only switching over once the new graph is fully up to date.

**Comment by timmclean** [comment]
We now have experimental support for this that can be enabled with an environment variable, `EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE=synced`

**Comment by numonedad** [comment]
There's no docs covering this feature. Also, how do you pick the new version vs the old one when issuing queries or using graphiql?

**Comment by azf20** [comment]
hey @numonedad! are you running a local node or using the hosted service?
You can use the Qm hash of the pending version to query it before it has fully synced, e.g. :
https://api.thegraph.com/subgraphs/id/Qmhash (or your local node URL)
