### ISSUE TITLE
Feature request: Monitoring API

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#623]
For monitoring a production service, it'd be useful to have a few endpoints that can be used to retrieve information about the node and its subgraphs:

 - Node health
 - Subgraph status (syncing/synced and block number)
 - Subgraph & entity size

**Comment by yanivtal** [comment]
This is in progress now 🙂

**Comment by Jannis** [comment]
The first related feature has landed in master: the number of entities can now be queried at the special `/subgraphs` route using e.g.
```graphql
{
  subgraphs {
    id
    entityCount
  }
}
```

The data model for subgraph status and progress information is pending review here: https://github.com/graphprotocol/graph-node/issues/585.

We have nothing planned for node health itself yet. Any suggestions on what information would be useful here? System diagnostics like CPU/memory/disk usage come to mind but that's more a responsibility of the environment the node is running in (e.g. Kubernetes, AWS etc.).

**Comment by Arachnid** [comment]
> We have nothing planned for node health itself yet. Any suggestions on what information would be useful here? System diagnostics like CPU/memory/disk usage come to mind but that's more a responsibility of the environment the node is running in (e.g. Kubernetes, AWS etc.).

First of all, a simple health endpoint that returns 200 if the node is up and healthy would be useful. Presently I'm using `/subgraphs/name/ens`, which obviously isn't ideal.

Second, endpoints to report sync state in an easily parseable format for monitoring tools, so they can verify if the node is ready to serve.

**Comment by Jannis** [comment]
@Arachnid Regarding the health check endpoint, that sounds good.

As for the sync state and subgraph status, we're planning to implement them as part of the `/subgraphs` API, so you could send a GraphQL query like
```
{
  subgraphs {
    id
    entityCount
    status // One of: 'syncing', 'synced', 'failed', 'paused'
    processedEthereumBlocksCount
    totalEthereumBlocksCount
  }
}
```
The result would of course be JSON. Would that be suitable for monitoring tools?

**Comment by Arachnid** [comment]
Most monitoring tools have fairly basic capabilities; I'm not sure you can rely on JSON parsing.

**Comment by Arachnid** [comment]
Google's stackdriver monitoring uses collectd, which does actually appear to have a [JSON plugin](https://collectd.org/wiki/index.php/Plugin:cURL-JSON).

**Comment by lutter** [comment]
Is this still an issue or does the `/subgraphs` endpoint give you what you need?

**Comment by Arachnid** [comment]
I think that endpoint does the job.

**Comment by timqian** [comment]
@lutter @Arachnid How can I query the `/subgraphs` endpoint?
I tried `http://localhost:8080/subgraphs`, but it returns a `404` and I can not find doc about this endpoint

**Comment by azf20** [comment]
hey @timqian that endpoint doesn't exist, but you can use the one documented here:
https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/#checking-subgraph-health
