### ISSUE TITLE
Error in using store.get to grab fields that were set in the graphql schema with`Int` field. 

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#625]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
See the entity I have below:
```
type UserStats @entity {
    id: ID! # 1
    totalUsers: Int
}
```
So when we `store.set` the Int field in a mapping, and `store.get` it the next time the mapping runs, we get a failure with `Value is not an i32`. Total users is just supposed to have  1 added each time the mapping runs.

I have confirmed that it fails right here:
```
  get totalUsers(): i32 | null {
    let value = this.get("totalUsers");
    if (value === null) {
      return null;
    } else {
      return 1
      //return value.toI32() as i32 | null; - THIS LINE FAILS !!
    }
  }
```
As you can see, when I replace the autogenerated `return` value with `1`, it works. 

So it fails on the `toI32()` function from `graph-ts` :
```
  toI32(): i32 {
    assert(this.kind == ValueKind.INT, 'Value is not an i32.')
    return this.data as i32
  }
```
This makes sense because this is the same error message.

**SO WHAT IS HAPPENING??**

My assumption is that when we get `Int`s from the store with the line: 
```
    let value = this.get("totalUsers");
```
they aren't actually `i32`s. But the autogenerated function we have for it forces it to use `toI32()` and then we get the failure. So therefore everytime we try to `store.get` an `Int` we will fail.

**Extra note**
Even just equalling it to itself fails in the same way: 
```
    userStats.totalUsers = userStats.totalUsers
```
So it is becoming clear that what we set on the store and what we get back are not the same things!

**Comment by Jannis** [comment]
@davekaj Just a quick check: is this still an issue?

**Comment by davekaj** [comment]
I just double checked, no longer an issue, closing!
