### ISSUE TITLE
Update serde_json dependency

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#636]
As the comment on `Cargo.toml` says:
> #Pin to serde_json 1.0.25. Newer releases use ryu instead of dtoa for floating
 point (de)serialization, which caused test failures. What may be happening
 here is that we write entities to the store with f32 values and then what
 comes back when deserializing is not f32 and so serde_json cannot match float
 values to our Value::Float(f32) variant. Would have to investigate further how
 we can fix this.

A consequence of this is that we can't update `sentry` because it requires serde_json at least `1.0.27`.

**Comment by timmclean** [comment]
ahhh fun!

**Comment by lutter** [comment]
I had to look into this because I'd need to update sentry (since the openssl 0.9.24 crate it pulls in does not work with the openssl-1.1.1 library in Fedora 29)

It seems the corruption we are getting is due to `f32` and `f64` confusion. The following program shows the exact `f64` value that the tests trip over as 'corrupted':
```
fn main() {
    let f : f32 = 159.1;
    let d = f as f64;
    println!("f: {:?} d: {:?} x: {:?}", f, d, d as f32);
}
```

It may have to do with GraphQL floats being `f64`, though I am not sure how that would get to the database.

**Comment by lutter** [comment]
And ryu seems to do the right thing:
```
extern crate ryu;

fn main() {
    let f : f32 = 159.1;
    let d = f as f64;
    let x = d as f32;
    println!("f: {:?} d: {:?} x: {:?}", f, d, x);
    println!("ryu f: {}", ryu::Buffer::new().format(f).to_owned());
    println!("ryu d: {}", ryu::Buffer::new().format(d).to_owned());
    println!("ryu x: {}", ryu::Buffer::new().format(x).to_owned());
}
# prints
# f: 159.1 d: 159.10000610351563 x: 159.1
# ryu f: 159.1
# ryu d: 159.10000610351562
# ryu x: 159.1
```

**Comment by leodasvacas** [comment]
Yes, GraphQL floats are indeed `f64`. We're likely to drop the half-baked support we have for `f32` and `Float` in favor of a new `BigDecimal`, so feel free to do any workarounds necessary here.

**Comment by lutter** [comment]
Managed to isolate and reproduce the problem, looks like a regression in serde_json. [reproducer](https://gist.github.com/lutter/2820e2c98331d5b5b6b95d62912e2e0f) | [serde_json issue](https://github.com/serde-rs/json/issues/520)
