### ISSUE TITLE
Mixing of path types in server/websocket

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#638]
```
Dec 11 01:25:02.513 CRIT assertion failed: `(left == right)`
  left: `Some("\\")`,
 right: `Some("/")`, location: server\websocket\src\server.rs:108
```

**Comment by Jannis** [comment]
We're currently using std::path for working with URL paths... either we need to tell it to use `/` instead of `\` everywhere (if that's even possible) or use a URL library for this.

**Comment by adamsoffer** [comment]
@timmclean I ran into a nearly identical issue after updating to the lastest Graph Node. 

```
CRIT assertion failed: `(left == right)`
  left: `Some("http:")`,
 right: `Some("/")`, location: server/websocket/src/server.rs:38
```
