### ISSUE TITLE
Support stateless smart contracts 

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#651]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Right now we do not support the ability to grab the input transaction data from a smart contract state changing call. 

**What is the desired behavior?**

If we support adding this as a field that can be grabbed from Ethereum, we can then support stateless smart contracts (like [peepeth](https://peepeth.com/about).) Basically, it stores no state, which makes an app really cheap. But then the front end application reads the input data, and converts it to human-readable format to present to us humans. 

I would say we don't need to rush this, it is a feature we can add when we have some downtime. I don't know of many apps that use stateless calls like this. But from what I understand it wouldn't be hard to add, so it is worth it for us to add it when we have the capacity to.

**Comment by leoyvens** [comment]
Call triggers covered a lot of this.
