### ISSUE TITLE
overrun of entity id  

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#655]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

overrun of entity id  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 https://github.com/daostack/subgraph/blob/bug_v1/src/domain/proposal.ts#L131
 seems like the the debug call overrun the proposal.id 
**What is the expected behavior?**

**Comment by leodasvacas** [comment]
Hi @orenyodfat thanks for the report! It'd be good to have the error messages in the node logs (if there are any), but this could be a case of #600 which we just fixed today. Could you try bumping your graph-cli to 0.5.1, re-running `graph codegen` and checking if this can still be reproduced?

**Comment by orenyodfat** [comment]
Thanks @leodasvacas .looks ok.
