### ISSUE TITLE
Add support for subgraph names with more than one path segment (e.g. `foo/bar`)

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#658]
We'll want this in order to namespace subgraphs by e.g. account / organization / user in hosted environments.

There are two parts to this:

1. Allowing subgraph names with slashes.
2. Updating the request handlers in the GraphQL HTTP and WebSocket servers to support multi-segment subgraph names.

**Comment by timmclean** [comment]
I've got this one in progress actually!
