### ISSUE TITLE
Issues with GraphQL List field contains filter

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-node#678]
- [x] Contains filters are not showing up for List field types in the GraphiQL docs.  
- [x] When added as a filter to a query, a List contains filter triggers an error message. 
Example: `Argument "where" has invalid value {owners_contains: ["QUERY_VALUE"]}. In field "owners.contains": Unknown field. 
- [x] Using a "ListAttribute_contains" filter in a query leads to an error: `Failed to get entities from store: operator does not exist: text @> text`

**Comment by heri16** [comment]
@fordN "_contains" is available for List fields, isn't it weird why "_in" is not available for List fields?
