### ISSUE TITLE
CRIT transaction not in a block, location: libcore/option.rs:1008

### ISSUE THREAD

**Issue by bohendo** [graphprotocol/graph-node#679]
**Do you want to request a *feature* or report a *bug*?**

🐛🐜🐞

**What is the current behavior?**

We're having some trouble with the graph-node that's powering https://dao-explorer.com

We're running the docker image `graphprotocol/graph-node:v0.5.0` and it syncs sooooo smoothly, this last release was a massive improvement and killing that startup-deadlock bug has made a world of difference.

Now things are running super smoothly.. for about a day or two. Then the graph node stops syncing and stops responding to queries.

After the latest hiccup, the logs surrounding the error message in the title of this issue looks like this:

```
  block_number: 7051849
   block_hash: 0xc39b53b0b6cf8048e932459b966a43524a4abe70f1ce7afc2b55f14d22327d93
    Jan 12 05:06:36.994 INFO Processing events from block
    Jan 12 05:06:36.994 INFO No events found in this block for this subgraph
    Jan 12 05:06:36.995 INFO Applying 0 entity operation(s)
  component: BlockStream
   Jan 12 05:06:36.996 DEBG Identify next step
   Jan 12 05:06:36.996 DEBG Chain head pointer, number: 7051849, hash: 0xc39b53b0b6cf8048e932459b966a43524a4abe70f1ce7afc2b55f14d22327d93
   Jan 12 05:06:36.996 DEBG Subgraph pointer, number: 7051849, hash: 0xc39b53b0b6cf8048e932459b966a43524a4abe70f1ce7afc2b55f14d22327d93
Jan 12 05:06:57.546 CRIT transaction not in a block, location: libcore/option.rs:1008
component: GraphQlRunner
 Jan 12 05:07:24.479 INFO Execute query
 Jan 12 05:07:24.855 INFO Execute query
   Jan 12 07:41:09.821 DEBG Skipping 331 block(s) with no relevant events...
   Jan 12 07:41:09.834 DEBG Identify next step
   Jan 12 07:41:09.836 DEBG Chain head pointer, number: 7052451, hash: 0xa48ee3ea8b4ddb56d21a425f9d986de2439de55b201ad86dbc4cbdb4954c6ca8
   Jan 12 07:41:09.836 DEBG Subgraph pointer, number: 7052401, hash: 0x59e2537f41070022f011f69eeccd87702a58914bae3a3e2e012b8f922181c7d4
  block_number: 7052402
   block_hash: 0x3afc81266f40b86663c1f1d5fd469db658923b58118ee7cf3b57b4d0f25ab33c
    Jan 12 07:41:09.841 INFO Processing events from block
    Jan 12 07:41:09.841 INFO No events found in this block for this subgraph
    Jan 12 07:41:09.841 INFO Applying 0 entity operation(s)
  component: BlockStream
   Jan 12 07:41:09.872 DEBG Identify next step
   Jan 12 07:41:09.874 DEBG Chain head pointer, number: 7052451, hash: 0xa48ee3ea8b4ddb56d21a425f9d986de2439de55b201ad86dbc4cbdb4954c6ca8
   Jan 12 07:41:09.874 DEBG Subgraph pointer, number: 7052402, hash: 0x3afc81266f40b86663c1f1d5fd469db658923b58118ee7cf3b57b4d0f25ab33c

```

These logs were also being printed at a time where development on the front end was ongoing so the node was likely serving lots of new & unusual queries.

This time, as I was poking around & reviewing logs, I noticed the graph-node just unstick itself & resume syncing & serving queries normally but usually I restart the node to get it running again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm worried that this bug will be hard to reproduce. I can help you run the code at https://gitlab.com/shivgupt/DAOexplorer but we rarely notice this bug within the first day of it being deployed so idk how helpful that'll be.. 😔

**What is the expected behavior?**

No `CRIT` in logs & no service interruption.

**Comment by bohendo** [comment]
The reorg idea sounds pretty likely.

It's probably not a nodes-out-of-sync situation since this graph node is syncing against a specific eth-node rather than a cluster of nodes eg Infura.

**Comment by Jannis** [comment]
Thanks @bohendo, that's good to know.

**Comment by timmclean** [comment]
Hi @bohendo, thanks for the quality report. Can I ask what type of Ethereum node you are running graph-node against (parity, geth, etc)?

**Comment by bohendo** [comment]
I'm running `Parity-Ethereum/v2.2.6-unstable-e9396e158-20190109/x86_64-linux-musl/rustc1.31.1`, build via this [dockerfile](https://gitlab.com/bohendo/ethprovider/blob/master/modules/parity/manual.Dockerfile), running with these [options](https://gitlab.com/bohendo/ethprovider/blob/master/modules/parity/entry.sh) and behind an nginx proxy with this [config](https://gitlab.com/bohendo/ethprovider/blob/master/modules/proxy/nginx.conf) (graph node is configured to hit the `/rpc` endpoint)

**Comment by timmclean** [comment]
Thanks!

@Jannis I think you're right about the reorg situation. A reorg can cause graph-node to ask for transaction receipts from transactions that are pending (no longer included in any block in what the Ethereum node considers to be the main chain). My guess here is that there are some differences between how geth and parity behave when asked for a receipt of a transaction that is pending; geth appears to consistently return null, which we do handle properly, while it sounds like Parity returns a partial receipt with some fields missing. Interestingly, it looks like this behaviour caught rust-web3 by surprise too -- older versions [assume that a receipt will always have a block hash](https://docs.rs/web3/0.3.1/web3/types/struct.TransactionReceipt.html#structfield.block_hash).

Assuming my understanding is correct, we should be able to fix this by treating receipts with missing block hashes the same way we treat null receipts.

**Comment by timmclean** [comment]
Hi @bohendo, hopefully this is now fixed, let us know if there's still an issue!
