### ISSUE TITLE
Spurious failure on `revert_block_with_partial_update`

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#709]
While testing something unrelated, I got this test failure:
```
thread 'tokio-runtime-worker-0' panicked at 'assertion failed: `(left == right)`
  left: `Entity({"age": Int(67), "coffee": Bool(false), "weight": Float(184.4), "bin_name": Bytes(Bytes([74, 111, 104, 110, 116, 111, 110])), "favorite_color": Null, "id": String("1"), "name": String("Johnton"), "email": String("tonofjohn@email.com")})`,
 right: `Entity({"bin_name": Bytes(Bytes([74, 111, 104, 110, 116, 111, 110])), "email": String("tonofjohn@email.com"), "weight": Float(184.4), "name": String("Johnton"), "id": String("1"), "age": Int(67), "coffee": Bool(false)})`', store/postgres/tests/store.rs:1468:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test revert_block_with_partial_update ... FAILED
```
Note that the first entity has `"favorite_color": Null` which the second doesn't.

This suggests a race condition, could be something specific to the test or could be an actual bug. Ping @timmclean and @fordN.

**Comment by timmclean** [comment]
This might have to do with the fact that we don't currently clear the entity history table between test runs, which I've seen cause weird things... I've been meaning to fix that

**Comment by leodasvacas** [comment]
That's probably it, because after it failed once it's now consistenly failing, when run against the same test db,
