### ISSUE TITLE
Deploying a new version while the previous is still pending removes both deployment assignments and stop

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#712]
```
2411-component: SubgraphRegistrar
2412- Jan 25 00:36:52.760 DEBG Received assignment event: Remove { subgraph_id: SubgraphDeploymentId("Qmb2f2HZ5YfznCsLbhGqMbsvhGREdH1PGsZABBb2CpcdeP"), node_id: NodeId("index_node_mainnet_0") }
2413: Jan 25 00:36:52.770 DEBG Wrote new subgraph version to store, subgraph_hash: QmUHLbgjeoXgfhM5AXDCc6hBdLjDEYoWfNJniAkwBj81GL, subgraph_name: lutter/the-count
2414: Jan 25 00:36:53.030 DEBG Received assignment event: Remove { subgraph_id: SubgraphDeploymentId("QmUHLbgjeoXgfhM5AXDCc6hBdLjDEYoWfNJniAkwBj81GL"), node_id: NodeId("index_node_mainnet_0") }
```

**Comment by timmclean** [comment]
Is this going by the logging or is this actually happening? The logging is a bit misleading here. I'll do some testing on my side either way

**Comment by timmclean** [comment]
I couldn't reproduce this locally unfortunately.
I don't see any issues with the log output posted here -- it looks like correct behaviour, assuming the new version was assigned to a different node ID. The next things that would be helpful in understanding this issue would be:
- a query of the SubgraphDeploymentAssignments entities after the problem shows up
- assuming the assignment does exist but indexing is not running, the log output from the node that the new version was assigned to

**Comment by timmclean** [comment]
It's possible that this is just an instance of #713?

**Comment by Jannis** [comment]
Haven't seen in it since, I'll close this issue until it happens again.
