### ISSUE TITLE
Soft-reset the module between handler calls

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#716]
After #702 we re-instantiate the WASM runtime between each call, to free memory and ensure no state is carried over. This works well, but it can cost us a couple milliseconds on each call. A soft reset of the module, which means resetting memory contents and size, and also global state, would likely be more performant. This was attempted in [this branch](https://github.com/graphprotocol/graph-node/blob/leo/reset-memory/runtime/wasm/src/module/mod.rs) with no success. Parity needs to do similar things with their runtime, so we may be able to cooperate with them when revisiting this in the future.

**Comment by leoyvens** [comment]
It seems that Substrate figured this out, but it added some restrictions and seems complicated https://github.com/paritytech/substrate/pull/3011

**Comment by Jannis** [comment]
@leoyvens Has this changed with switching to wasmtime or is this still something we might want to do?

**Comment by leoyvens** [comment]
It's still an interesting optimization in theory, but I don't think this will be worth pursuing.
