### ISSUE TITLE
Finalize GraphQL API

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#717]
Things to consider here:

* Connections API
* Pagination
* Interfaces / unions
* Aggregates
* Custom resolvers

**Comment by fubhy** [comment]
I'd love to see support for interfaces and unions. As far as I can tell adding the resolveType logic from the spec could be part of the engine based on the used entity.

**Comment by fubhy** [comment]
This was originally in the February 2019 milestone. Is there any updated ETA for this @Jannis? Any way I can help without interfering somehow?

**Comment by Jannis** [comment]
We have support for interfaces now but not unions. We're planning to revamp the GraphQL API after network launch and release it as a v2 API.
