### ISSUE TITLE
Create (subgraph) and (subgraph, entity) indexes on entities table if they don't exist yet

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#724]
These would greatly improve queries against the "subgraph of subgraphs". Let's add them to a new migration in graph-node.

So basically these two indexes (correct me if they could be improved):
```sql
CREATE INDEX subgraph_idx ON entities (subgraph);
CREATE INDEX subgraph_entity_idx ON entities (subgraph, entity);
```

**Comment by lutter** [comment]
I believe only the second index is needed, as postgres uses the prefix of indexes, i.e. the index on `(subgraph, entity)` will also be used by queries that only have a `subgraph = 'value'` constraint. See [here](https://www.postgresql.org/docs/10/indexes-multicolumn.html), especially the paragraph starting with "A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns"

**Comment by Jannis** [comment]
Ah, great. I did not see a difference after adding the second index but that may be because both were doing almost the same job by filtering the `subgraph` attribute efficiently as the first thing.
