### ISSUE TITLE
Adjust subgraph deployment assignment cost dynamically

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#729]
Right now we're costing every subgraph identically, however, some (e.g. ENS) are much more resource intensive than others (e.g. Decentraland). As more subgraphs get added to a node, this might lead to scaling problems.

This metric could be based on factors like:

* number of entities created / modified
* number of events processed
* amount of time required for past handlers

**Comment by lutter** [comment]
See #940 for one way we could use to measure subgraph cost.

**Comment by lutter** [comment]
We've completely changed our strategy for assigning subgraphs, and this ticket doesn't make much sense any more.
