### ISSUE TITLE
Design convention for collecting and writing metrics in graph-node

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#730]
We'll want to understand aspects such as

* query load and times
* subgraph usage (number of queries, entities being queried)
* indexing stats (event handler times, block processing times, ...)

We already collect logs for subgraphs and we have tickets for creating an indexing and query stats writer but it would good to look at this more holistically and design a solution that we can use across all of graph-node to gather interesting data.

**Comment by lutter** [comment]
I think this ticket has been overtaken by events, and is covered by a number of other tickets.
