### ISSUE TITLE
Indexed strings and arrays are not parsed correctly

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#731]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I am pretty sure that we are not parsing strings properly in our events, but I can't confirm it because I haven't been able to pinpoint where we handle this in the graph node. I will explain:

Ethereum event logs do a peculiar thing, when you `index` a `string` it stores the `string` as the hash of itself, so that it fits into a topic which is a `bytes32`. For non-indexed event fields which are strings, it allows a string of arbitrary length to be stored in logs. But all event data must be `bytes32`. So in order to publish it, the format is as follows:

`data[0] - The size of the data memory to follow (right now always 32)`
`data[1] - the length in bytes of the string`

From here on, there can be multiple more data fields to represent the string. See the following two examples from etherscan:

https://etherscan.io/tx/0xc760d94f4512aac26123ad4345b824cdf271d0b3c9529778a42d3329b88b35bc#eventlog
![screen shot 2019-02-01 at 8 50 55 pm](https://user-images.githubusercontent.com/22417382/52158136-296ae580-2663-11e9-98c6-647f556abd67.png)

https://etherscan.io/tx/0xdd7c3b3a528b9bd5ac15a29630fefad04e233c0c7aad28f70af3d75c5f9cce53#eventlog
![screen shot 2019-02-01 at 8 51 01 pm](https://user-images.githubusercontent.com/22417382/52158137-2a9c1280-2663-11e9-894f-207bf11707e2.png)

This bug got me for a while, and I *hope* I am correct in my findings, because I have already went through a few red herrings. I believe @timmclean wrote this part, so hopeful he has time to comment on this issue. Otherwise I believe @Jannis or @leodasvacas might be able to help me figure out if I am correct in my analysis. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm trying to do it on the latest version of decentraland, where I am trying to store `Estates`, so doing that will produce the following error:

```
ERRO Subgraph instance failed to run: Failed to process event: Failed to parse parameters of event: Update(uint256,address,address,string): Invalid data, id: QmTxSsbovpeDVbAbfzRZ5E4YyRzUoiFXhRqWY5DM16vdPz
  component: BlockStream
```

**What is the expected behavior?**

We watch for strings in event data, and produce types that dynamically have the amount of fields to grab the full string of any event.

**Comment by Arachnid** [comment]
I'm encountering this issue with the ENS subgraph. It appears to me that when you see an indexed string event, you try and parse it as a string (variable length, in ABI encoding) instead of a bytes32 (fixed length). A workaround is to rename the parameter to bytes32 in both the manifest and the ABI.

**Comment by Jannis** [comment]
@Arachnid Yep, this is a bug in ethabi that we have reported at https://github.com/paritytech/ethabi/issues/146.

We have all the information and test data for fixing this in our ethabi fork, it's just a matter of priorities. #616 is on my list for this week (in addition to #719), but we could take care of this one next week. Does that sound good?

**Comment by Arachnid** [comment]
It's not a blocking issue for us. Worth reopening this issue, though?

**Comment by Jannis** [comment]
Yes, good point.

**Comment by Arachnid** [comment]
Looks like I was wrong about the workaround. It changes the topic0, and there doesn't appear to be a way to specify that separately from the ABI.

**Comment by Jannis** [comment]
@Arachnid I have a fix for that in our fork of `ethabi`. According to https://solidity.readthedocs.io/en/develop/abi-spec.html#encoding-of-indexed-event-parameters, indexed `string`, array and `bytes` parameters are encodeded and then hashed before they get added to the event topic as a `bytes32` value.

Thus, my understanding is they can only be read as a `bytes32`. Could you check https://github.com/graphprotocol/ethabi/pull/2 and let me know if your understanding matches mine? The docs I linked above are a little vague on how the indexed values would later be read again.

**Comment by Arachnid** [comment]
I don't speak Rust, but that looks correct to me. You can only read out the hashed value for an indexed string.

**Comment by Jannis** [comment]
@Arachnid Thanks, yep, that matches my understanding.

**Comment by fepvenancio** [comment]
For me to use my event.param.assets[index].collection I had to change my abi from:
```
{
        "components": [
          {
            "internalType": "address",
            "name": "collection",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          }
        ],
        "indexed": true,
        "internalType": "struct DataTypes.Asset[]",
        "name": "assets",
        "type": "tuple[]"
      }
```
To:
```
{
        "components": [
          {
            "indexed": true,
            "internalType": "address",
            "name": "collection",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "tokenId",
            "type": "uint256"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.Asset[]",
        "name": "assets",
        "type": "tuple[]"
      }
```

But I still have the same initial problem when I deploy I get the error: 

Error: failed to process trigger: block #5139412 (0x671d…4ab3), transaction 0f690b1245a7c83a61ffb5870c72226edf458d9ecd1e496cd6814a73f2aef669: Event with the signature "Borrow(indexed address,indexed bytes32,uint256,uint256,address,(indexed address,uint256)[])" not found in contract "Action" of data source "action"

DeploymentId: QmXUN8bY7atiWcFEyhtCFqSAe8G9WAtXKbBehyykEiMLzH

**Comment by azf20** [comment]
hey @fepvenancio - I _think_ that in this case the indexed struct is only acccessible as a `bytes32` (i.e. you can't just switch `indexed` to `false`)

**Comment by fepvenancio** [comment]
Yes I forgot to remove this. It's fixed and running.
