### ISSUE TITLE
Read from IPFS crash the subgraph if hash is invalid/ doesn’t exist

### ISSUE THREAD

**Issue by ben-kaufman** [graphprotocol/graph-node#732]
Currently when calling `ipfs.cat` the function will behave as follows:
If the hash is a valid reference to an existing data on IPFS it will return the data.
If the hash queried is invalid or if it points to data which is not stored in the IPFS node it will cause the event listener to crash.

This behavior makes accessing to IPFS reliably practically impossible, as it’s impossible to verify the data exist before sending a query, and in case it indeed doesn’t exist it causes the system to crash.

A possible fix would be to return an empty response in case the query failed.
This would allow to gracefully handle errors and continue the operation of the subgraph.

**Comment by Jannis** [comment]
Plan of record: Make `ipfs.cat` return `null` if a file is not available. Log a warning in Graph Node in this is case.
