### ISSUE TITLE
Make transaction input data available to mappings

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#734]
This will also require small changes in https://github.com/graphprotocol/graph-ts.

**Comment by leodasvacas** [comment]
This will be a bit more complicated now that we are no longer making breaking changes to the node. A disadvantage of the way we serialize things to AS is that adding a field is a breaking change. The `graph-ts` change can be made normally, but the node should to support older `graph-ts` versions. So we'll need to copy paste the existing `AscType` struct that will have fields added into a new struct for the new version, and decide which one we want at runtime based on `specVersion` which we'll need to bumb. `graph-cli` should bump the `specVersion` automatically so this is not a pain for users. @fordN we can pair on this stuff if you want.
