### ISSUE TITLE
Creating a Fasting Feedback loop for Subgraph Testing and Iterations

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#738]
I have expressed how long the testing and development cycle has been for decentraland, and the more I think about it, this is an important feature we should add very soon.

Reason being, is that any significant project with a lot of data, and a lot of transactions, will run into this problem. And if we require that they wait many hours to test their subgraph, that is not good.

For example, with decentraland, I have to wait about 3 or 4 hours to test some new mappings. There is no way around it  because these mappings require that the entities exist, from the old mappings running. So therefore I just haven't been able to test them. 

This is also even bad when the cycle is 10 minutes. Sometimes you forget one `!` in the schema, and you don't learn this until the mapping runs and you try to query. Feels like time wasted

**Suggestions for a solution**
* when the subgraph crashes, we can restart from the exact block it crashed with an updated mapping 
* I think it would be nice if you could keep these semi-synced versions saved, while also being able to start from scratch. Because at some point you will want to test the whole thing, while also not losing potentially hours of syncing. Decentraland is shaping up to be a 10 hour subgraph, and you want to always be able to save your progress and not worry about over-writing.
* I think having a command to pass to the graph-node that lets you sync up to a certain block, and have that saved could be useful. Maybe it even stops syncing at this point, and waits for another deploy before starting up again
* It also brings up the question, because we are changing the mappings while testing, the wasm runtime is changing, while keeping the same data to work on top of. Maybe we should run it in a `--test` mode or something? You shouldn't be allowed to accidentally upload a subgraph to hosted service that had its db populated with two different runtime. 

@Jannis Will need your input!

**Comment by Jannis** [comment]
@davekaj With #951 merged you suggested we should close this. I'd leave it open because there are more things we can do to improve the development experience / feedback loop.

**Comment by leoyvens** [comment]
Also we have matchstick now.
