### ISSUE TITLE
Make long quries queries (and subscription queries) time out

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#742]

**Comment by Jannis** [comment]
One option could be Postgres' `statement_timeout` setting. https://github.com/rust-lang/crates.io/blob/master/src/db.rs#L103 may be something to to look at in order to integrate `statement_timeout` into r2d2 connection pooling.

**Comment by Jannis** [comment]
Another improvement would be to make the GraphQL execution asynchronous and combine it with a `Cancelable`. The `Cancelable` could then be triggered by a timeout.

**Comment by leodasvacas** [comment]
The way things currently work, I believe checking for timeouts somewhere between resolving each object will probably be fine.
