### ISSUE TITLE
Git ignore docker/data directory

### ISSUE THREAD

**Issue by rhlsthrm** [graphprotocol/graph-node#745]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
I am running the docker compose setup. Everything works great, except I have thousands of unstaged commits in the `docker/data` directory.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run `docker compose up` inside the `docker/` directory and wait.

**What is the expected behavior?**
Files should be ignored, so my git should be clean.

**Comment by Jannis** [comment]
Thanks @rhlsthrm, this is fixed on master.
