### ISSUE TITLE
IPFS Pinning - Designing a Robust and live handling of ipfs `cat`

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#748]
The current behaviour of `ipfs.cat()` is that it will search for the file for 10 seconds, and then fail, and the graph node crashes. The first and most important thing to deal with here is liveness:
1. We shall allow the graph node to continue operation when `ipfs.cat()` cannot find the file in the allotted time. This is a quirk of IPFS we cannot fix ourselves, sometimes this will inevitably happen (quite often actually in my experience). 
2. The allotted time is up for debate. 10 seconds is too short from my experience building subgraphs. I would say either 30 seconds or 1 minute is appropriate. I'm inclined to go with 30 seconds, since we should really encourage subgraph developers to pre-pin (more on that later).
3. There should be clear logs that this is happening, that there is a 30 second wait, that the file was found, or that it wasnt and it has been skipped. 
4. Pretty sure LEO is working on this now, so that is good. 

Making it robust:
1. I believe Jannis is planning on having an IPFS stream, and block stream. So the IPFS stream should go through the blocks along with the block stream, and then once it is fully synced, it should go back and start searching for the documents that it missed on IPFS. For an extended time. Maybe 2 minutes, and then it should continuously loop through them all and keep trying to get the files until it is satisfied. 

Instructing developers how to create their subgraph, with IPFS's network in mind:
1.   First and foremost, it should be stressed to any subgraph developer that their IPFS files should be pinned to their own node, and then shared on as many public gateways as possible. This is how  they can ensure their files are as easily accessible as possible. 
2. If for some reason this isn't a possibility, then they should write the mappings in mind with the fact that some IPFS files will not be found right away, or may never be found. This means that mapping operations should not fail when data is missing. (i.e. creating an entity based on an IPFS file being found, and then loading that entity with full expectations that the fields will exist and won't be null. This would crash the graph node

**Comment by leoyvens** [comment]
`ipfs.cat` is going to be replaced by IPFS data sources.
