### ISSUE TITLE
IPFS Has Either a File Size or File Count Limit

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#753]
Tried to publish 18 different contracts, hardcoded in the subgraph.yaml. Total of 37 files (2 * 18) + 1

IPFS Fails. I brought it down to 21 files and it worked 

Not sure if it is file size or file amount. We shall investigate!

**Comment by Jannis** [comment]
This is actually about the hosted service, not Graph Node itself. We know what's going on and will resolve it.
