### ISSUE TITLE
Add function signature support for anonymous events 

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#756]
This feature request is specifically to allow for a Maker subgraph to work. Right now, it is impossible to get any CDP data from events because of how they use anonyomous events. 

See the Solidity code here, for anonymous events : https://github.com/dapphub/ds-note/blob/master/src/note.sol
See solidity docs for anonymous explained: https://solidity.readthedocs.io/en/v0.5.4/contracts.html#events

Basically, the anonymous modifier removes the event signature as topic0, which is what the graph node searches for while indexing. But `contract DSNote` sets up the `LogNote` event to have the signature of the method that was called to be topic0, thus the contract events are easily indexable by what functions are emitting events, rather than just the events themselves. 

This is not a totally common pattern, I have only seen Maker use it. However they are so big, and we have a few teams who want to build this subgraph, so it would be great to add this functionality soon.

Note that the method signature is only four bytes, so the graph node will be searching for `0x1234567800000000......`. see an example here : https://etherscan.io/address/0x448a5065aebb8e423f0896e6c5d525c040f59af3#events (side note, I just noticed these events also emit some event topics that are not bytes32, which link back to decetraland and livepeer, and the ethabi not supporting the broken solidity compiler of the past)

At first I thought the simplest solution would be to do something like the following in the `subgraph.yaml` :
```
- anonymousEvent: CreateCDP(address,uint256,uint256)
- handler: handleCreateCDP
```
Then, when graph node sees that it is anonymousEvent instead of event, it will only take the first 4 bytes of the hash, and append the other 28 bytes with `0`'s, which will allow it to find the anonymous events.

HOWEVER, it makes me think, that this doesn't necessarily prepare the graph node to deal with ALL anoyonmous events. You could easily make an anoymous event, and index the user address as topic 0, which would take the user address instead, and append 12 bytes to the end. 

Maybe a better solution would be to require that the user pass in the hashed value directly, and leave it up the the subgraph creator to predetermine the hash, rather than have the graph node hash it. So it would look like:

Handles method signatures :
```
- anonymousEvent: 0x123456780000000000000000000000000000000000000000000000000000000000000000
- handler: handleUserAddress
```
Handles addresses:
```
- anonymousEvent: 0x1234567890123456789012345678901234567890123456789000000000000000000000000
- handler: handleCreateCDP
```
This is what I would recommend we do

**Comment by davekaj** [comment]
@leodasvacas @Jannis

**Comment by leodasvacas** [comment]
@davekaj If we allowed the manifest to specify the filter for `topic0`, that would resolves this, yes?

That would be straightforward to implement, but there's the question of how exactly we want to write this in the manifest. Perhaps we can allow:
```
- topic0: 0x1234567890
  handler: handleFoo
```
So an `eventHandler` should specify either an `event` or a `topic0`. @olibearo opinions?

**Comment by davekaj** [comment]
that looks good to me. I think it could be :
```
- topic0: 0x1234567890
  handler: handleFoo
```
or
```
- topic0: 0x12345678900000000000.... (up to 20 bytes total)
  handler: handleFoo
```
Whichever is easier. But I believe it will have to match the full 00000 topic. See some example events being emitted here https://etherscan.io/address/0xbda109309f9fafa6dd6a9cb9f1df4085b27ee8ef#events

**Comment by Jannis** [comment]
Should we just allow `event` to either be `0x...` or a valid event from the ABI? That could simplify the implementation a bit.

**Comment by davekaj** [comment]
I like that idea. It is a small feature we are adding, basically to support maker (but it will be good for other projects in the future as well). If we can make the implementation simpler I think it is worth it!

**Comment by leodasvacas** [comment]
It does make it simpler, good idea.

**Comment by leodasvacas** [comment]
@Jannis @davekaj actually we can't just replace `event` with `topic0`. We need the event signature so that we decode the logs. So I propose that `topic0` is an additional field, optionally provided. If not provided, it is defaulted to the hash of the `event` field.

**Comment by davekaj** [comment]
makes sense. the solution sounds good to me!

**Comment by Jannis** [comment]
@leodasvacas Ah! 👍

**Comment by leodasvacas** [comment]
## Rationale

This is about allowing arbitrary filters on topic0, and not just the event signature. Maker needs this.

## Requirements

It must be possible to filter on arbitrary values of topic0.

## Proposed User Experience

In the manifest entry for an event handlers, add a `topic0` field which can be optionally provided. If not provided, it will be defaulted to the hash of the `event` field. If provided it must be a `0x` prefixed hex string that will be used as the topic0 filter.

## Proposed Implementation

graph-node:
- Add the optional `topic0` field to `MappingEventHandler` so we can backwards-compatibly parse it. Also add it `EthereumContractEventHandlerEntity` for the subgraph of subgraphs.
- Possibly add a struct with non-optional `topic0` to be used when matching events.
- Update logic in `matches_log_signature`, `event_handler_for_log` and `create_log_filter_from_subgraph` to account for the `topic0` field.

graph-cli: - Accept and validate the `topic0` field.

## Proposed Documentation Updates

Update graph-node/docs/subgraph-manifest.md with the new `topic0` field.

## Proposed Tests / Acceptance Criteria

graph-node: Manual tests that the feature works end-to-end.
graph-cli: Validation tests.

## Tasks

- [ ] (0.5d) graph-cli: Add validation and tests for the `topic0` field.
- [ ] (1d) graph-node: Parse `topic0` and update log matching logic to handle it.
- [ ] (0.1d) graph-node: Document the `topic0` field.
- [ ] (0.5d) End-to-end testing (possibly @davekaj will also do this task).

**Comment by k06a** [comment]
But how to capture all the smart contract anonymous events without filtering?
