### ISSUE TITLE
Stack Traces for mapping handlers

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#757]
Often when running a subgraph, a failure will happen, and there is no indication of what line caused the error. This can be frustrating for debugging. Often this leads to commenting out blocks of code until the line can be identified. Not a bad solution, but if the failure happens after 30 mins or more of subgraph syncing, it can slow down the process of iterative development a lot.

Showing stack trace errors, up to the line that failed would help, along with an error message.

This could have some overlap with this issue in graph-ts -  https://github.com/graphprotocol/graph-ts/issues/40

**Comment by leoyvens** [comment]
Our stack traces have since improved.
