### ISSUE TITLE
Subgraph remains in 'failed' state after restart, should go back to 'syncing'

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#759]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current and desired behavior?**

When a subgraph fails due to a node error such as
```
Subgraph instance failed to run: Error while processing block stream
for a subgraph: store error: Failed to set entity (subgraphs, SubgraphDeployment,
QmUqmv9NGSewTLVwbaj1ikGU6dS4gJpvkxYMhXLrjgvxj3): out of shared memory, id:
QmUqmv9NGSewTLVwbaj1ikGU6dS4gJpvkxYMhXLrjgvxj3
```
it should pick back up after restarting the node. This actually happens but the `failed` state of the subgraph isn't reset to `syncing` properly.

**Comment by SuperDev123-hub** [comment]
Subgraph syncing failed on mumbai network.
What should I do now?
