### ISSUE TITLE
AssemblyScript compiler bug

### ISSUE THREAD

**Issue by stunndard** [graphprotocol/graph-node#760]
I have very odd beahvior when compiled graph is executing.
Below is the schema:

```
type Post @entity {
  id: ID! # id
  tags: String
  link: String
  title: String
  score: Int
  pinned: Int   # this should be Boolean
  content: String
  excerpt: String
  rewarded: Int # this should be Boolean
  imageUrl: String
  rewardable: Int # this should be Boolean
  rewardScore: Int
  actionAfter: Bytes
  actionBefore: Bytes
```
Then I have a function and call it:

```TypeScript
export function decodeBoolean(action: ByteArray): u32 {
    // check magic byte 0x03 for boolean parameter
    if (action[0] != 0x03) {
       return 0;
    }

    let len: i32 = action[1];
    // boolean len is always 1
    if (len != 1) {
       return 0;
    }
    let resB: u32 = action[2];
    // any value other than 0 is "boolean true"
    if (resB != 0) {
      resB = 1;
    } else {
      resB = 0;
    }
    return resB as u32;
}
  ...
  let score: u32 = decodeInt(action); if (score === null) return "scoreNull";
  action = decodeRemain(action);     if (action === null) return "scoreActNull";
  post.score = score;

  post.actionBefore = action;
  // the BUG IS HERE: pinned is always null
  let pinned = decodeBoolean(action); //if (pinned === null) return "pinnedNull";
  action = decodeRemain(action);   //   if (action === null) return "pinnedActNull";
  post.pinned = pinned;
  post.actionAfter = action;

  ...
  post.save();
```

This is what I have in the graph data after queriing it via graphql:
```json
      {
        "actionAfter": "0x0220516d716d68416a64686a616a73684167736632332028495046532068617368290207657863657270740301000106fe1c075bcd150301010104fe1e0320",
        "actionBefore": "0x0301000220516d716d68416a64686a616a73684167736632332028495046532068617368290207657863657270740301000106fe1c075bcd150301010104fe1e0320",
        "excerpt": null,
        "id": "Yajhhsg12gsfhA",
        "imageUrl": null,
        "link": "link http://test.com",
        "pinned": null,
        "rewardScore": null,
        "rewardable": null,
        "rewarded": null,
        "score": 12345,
        "tags": "tags tags",
        "title": "Cool post title"
      }
```
So whatever value is returned from `decodeBoolean` it becomes `null` instead of actual data. I've tried different types. like `boolean` for `decodeBoolean` function, tried to change variable names, return computed value like `return xx as u32` or constant like `return 0`, nothing works. Anything returned from `decodeBoolean` and assigned to a variable becomes `null`.

Before calling `decodeBoolean` I call some other functions like `decodeInt` and they work as expected and return correct values.

**What is the expected behavior?**
Work correctly.

**Comment by Jannis** [comment]
@stunndard Have you tried using `Boolean` in the schema and return `true` or `false` from `decodeBoolean` (and make the return type of `decodeBoolean` `boolean`)?

**Comment by stunndard** [comment]
Yeah, tried that from the start, still had `null` assigned to a variable, first thought it's some `booelan` type bug, that's why I've tried to change it to i32 or u32 types, nothing works.

**Comment by stunndard** [comment]
wast assembly:
```
(func $src/ParseActions/decodeBoolean (; 68 ;) (type $ii) (param $0 i32) (result i32)
  (local $1 i32)
  (local $2 i32)
  get_local $0
  i32.const 0
  call $~lib/internal/typedarray/TypedArray<u8,u32>#__get
  i32.const 255
  i32.and
  i32.const 3
  i32.ne
  if
   i32.const 0
   return
  end
  get_local $0
  i32.const 1
  call $~lib/internal/typedarray/TypedArray<u8,u32>#__get
  i32.const 255
  i32.and
  set_local $1
  get_local $1
  i32.const 1
  i32.ne
  if
   i32.const 0
   return
  end
  get_local $0
  i32.const 2
  call $~lib/internal/typedarray/TypedArray<u8,u32>#__get
  i32.const 255
  i32.and
  set_local $2
  get_local $2
  i32.const 0
  i32.ne
  if
   i32.const 1
   set_local $2
  else
   i32.const 0
   set_local $2
  end
  get_local $2
)
```
calling code assembly:
```
  call $src/types/schema/Post#set:score
  get_local $3
  get_local $1
  call $src/types/schema/Post#set:actionBefore
  get_local $1
  call $src/ParseActions/decodeBoolean
  set_local $8
  get_local $1
  call $src/ParseActions/decodeRemain
  set_local $1
  get_local $3
  get_local $8
  call $src/types/schema/Post#set:pinned
  get_local $3
  get_local $1
  call $src/types/schema/Post#set:actionAfter
```

**Comment by MaxGraey** [comment]
```ts
set pinned(value: i32 | null) {
    if (value === null) {
      this.unset("pinned");
    } else {
      this.set("pinned", Value.fromI32(value as i32));
    }
  }
```
Assembly script doesn't support plained nullable types like `i32 | null`. Latest version of AS preint warning about this

**Comment by stunndard** [comment]
Yeah, I noticed that if `decodeBoolean` return type is `boolean` and it returns `false`, it becomes `null`. But if it returns `true`, it remains `true`. So how can we use `Boolean` type in graphql schema and be able to assign `false` to it, so it gets saved to the database?

**Comment by leodasvacas** [comment]
Thanks @MaxGraey for jumping in! We should upgrade our AS version to get the warning improvement.

@stunndard  `Boolean` or `Int` as nullable don't make a lot of sense because AS does not support nullable values for those, you should use the non-nullable `Boolean!` and `Int!`. But yes, `false` and `0` do work, we will not consider those as being `null` in the store. Does that answer your issue?

**Comment by Jannis** [comment]
@leodasvacas Now that we bumped our AssemblyScript version, we should get warnings for those setters, I assume? And if so, the next step probably is to remove `| null` for primitive value types like `i32` and `boolean`.

**Comment by leodasvacas** [comment]
@Jannis Yes I think they do error or warn. Afaik we don't generate those setters since https://github.com/graphprotocol/graph-cli/pull/185, this must have been against an old version. Closing unless someone can repro again.
