### ISSUE TITLE
Develop convenient way to decode transaction inputs

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#767]
Perhaps ethabi provides something here that we can expose to mappings. Its CLI provides convenient decoding of byte arrays: https://github.com/paritytech/ethabi#examples

If we know the parameter types to a function, we should be able to decode its inputs with e.g. https://docs.rs/ethabi/6.1.0/ethabi/fn.decode.html

**Comment by Jannis** [comment]
@fordN This sounds good. I'd change the the generated code a little bit, not 100% decided what would be best though. But the approach feels solid.

**Comment by leoyvens** [comment]
Thanks to @otaviopace we have this now!
