### ISSUE TITLE
Store events hit the Postgres notify size limit

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#768]
The error message:
```
graph-node_1  |  Feb 19 09:53:39.115 INFO Received subgraph_deploy request, params: SubgraphDeployParams { name: SubgraphName("daostack"), ipfs_hash: SubgraphDeploymentId("QmbdCphiS1qgFDmnAB2cktD2tFKjPgH41pkRvRJsTCxhHk"), node_id: None }
postgres_1    | 2019-02-19 09:53:39.180 UTC [68] ERROR:  payload string too long
postgres_1    | 2019-02-19 09:53:39.180 UTC [68] STATEMENT:  SELECT pg_notify($1, $2)
```

**Comment by Jannis** [comment]
From the Postgres [NOTIFY documentation](https://www.postgresql.org/docs/9.0/sql-notify.html):

> The "payload" string to be communicated along with the notification. This must be specified as a simple string literal. In the default configuration it must be shorter than 8000 bytes. (If binary data or large amounts of information need to be communicated, it's best to put it in a database table and send the key of the record.)

Unfortunately, this appears to be a hard limit, at least according to https://stackoverflow.com/a/41059797. One of the comments there suggests `NOTIFY` isn't intended for row data.

We'll have to find another way to communicate store event data with Graph Node.

**Comment by buendiadas** [comment]
Hi, I just got into this problem, downloaded the last version. 

Is this a new problem so I can rollback to another version?

**Comment by lutter** [comment]
@buendiadas the change that made the event size grow landed with PR #735 - if you go back to commit 755e05bf or earlier the issue should disappear for you. I am working on a fix for this right now. I'll fix it by splitting large messages into smaller messages that fit into the 8000 byte limit.

**Comment by lutter** [comment]
@buendiadas one warning: there is a migration in that PR that gets rid of some triggers. If you go back to an older version, you need to make sure you run the migration in `store/postgres/migrations/2019-02-04-114900_remove_entity_change_triggers/down.sql` Otherwise, a whole bunch of stuff won't work right.

**Comment by lutter** [comment]
There are two things we can do to limit message size:

1. split larger messages upon sending and reassemble them in the receiver. To keep that logic simple, we'd rely on pg sending messages in order (no interleaving across txns) The docs seem to say that, but it's not entirely clear
2. Stuff large messages into a table and send the id of the table row; clean old messages (say older than 5mins) when inserting new ones.

My concern with (1) is that we would rely on pg behavior that's not clearly documented, and therefore might change. Writing the message splitting in a way that is robust against interleaving messages from different txns seems a bit excessive - we'd need to tag each partial message with some unique id for the overall message, and the receiver would need to be able to reassemble multiple messages, passing them on only when it has fully reassembled one.

**Comment by lutter** [comment]
Here's the salient bit from [the docs](https://www.postgresql.org/docs/9.6/sql-notify.html)

>    notifications from different transactions will never get folded into one notification. Except for dropping later instances of duplicate notifications, NOTIFY guarantees that notifications from the same transaction get delivered in the order they were sent. It is also guaranteed that messages from different transactions are delivered in the order in which the transactions committed.

**Comment by 0x13e** [comment]
I also just started hitting this after running the indexer headless for a few days. At this point the Indexer.Block.Realtime.Fetcher is just in an infinite termination loop as the large pgsql notification will never complete.
