### ISSUE TITLE
Remove indexes of a subgraph deployment when the last version that points to it is superseded

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#774]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Currently, every new subgraph deployment adds new indexes to the Postgres database. These are then never cleaned up. With enough indexing and query I/O, this eventually causes `out of memory` errors due to the maximum number of locks per transaction being exhausted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run a Graph Node for a long enough time with significant indexing and query I/O.

**What is the expected behavior?**

Ideally, we'd delete the indexes as soon as a subgraph deployment goes out of scope — i.e., the last version that points to it gets superseded by another version. If that same deployment is ever started again, we'll want to recreate its indexes. 

I first thought deleting indexes when a deployment is unassigned would be good enough but when a deployment is moved manually from one node to the next, we'd first un-assign and then re-assign it. And I _think_ we don't to drop and recreate indexes in this situation.

**Comment by lutter** [comment]
Regarding the last sentence: we probably want a notion of active vs inactive deployment, and drop indexes on the active -> inactive transition (active ~ used by at least one subgraph as the current or pending version)

**Comment by Jannis** [comment]
We kind of have that in the form of subgraph deployment assignments. Do you feel that's not good enough?
