### ISSUE TITLE
Subgraph gets stuck when eth_getLogs fails because there are too many results

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#776]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When catching up with historical data, the block stream asks for `eth_getLogs` on 100,000 blocks at once. It is possible that the eth node (Infura in my case) responds with
```
  Error { code: ServerError(-32005), message: "query returned more than 1000 results", data: None }
```

We blindly retry the request, even though there is no chance retrying it will ever succeed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This was observed with the Dice2Win subgraph, with the subgraph at block 6290742, while the ethereum head ptr was at 7271924.

**What is the expected behavior?**

The code should realize that it has to reduce the size of the range (e.g., by repeatedly halving it) until this error isn't returned any more. When I manually reduced the range to 100 blocks in the code, the block stream started working again.

As a sidenote, the logs should show more details about what exactly went wrong when `eth_getLogs` fails. Right now it just says something like `Trying again after eth_getLogs RPC call failed (attempt #15)` which does not have enough detail to understand what's happening.

**Comment by Jannis** [comment]
Interesting. This is long after the node requests eth_getLogs for 100,000 blocks at once. The fast scan algorithm ends at 4,000,000 blocks (by default) and 3,000,000 blocks (hosted service, IIRC).

After that I believe we ask for chunks of 10,000 at a time (with several of such 10,000 block requests running in parallel).

The 1000 results limit must be new. I agree with the proposed solution to retry with smaller ranges. It may also make sense to start out with a smaller block range size in the first place.

**Comment by lutter** [comment]
The thing that made me mention 100,000 in the above is that things started working again when I changed the `100_000` on [this line](https://github.com/graphprotocol/graph-node/blob/master/datasource/ethereum/src/block_stream.rs#L325) to `100`, after trying `10_0001 and `1_000` to no avail. From what you said, there might be another problem with not backing off large ranges as intended.

**Comment by Jannis** [comment]
That coffee eventually ends up calling https://github.com/graphprotocol/graph-node/blob/a5cad36f3943ed3f7d6401df4c045ed5bc80a7f9/datasource/ethereum/src/ethereum_adapter.rs#L96, which has the chunking logic I talked about.

First I was thinking of baking a range backoff into that `log_stream` function but that could get pretty messy. I think the best approach might be too wrap the body of log_stream into a back-off-retry future of sorts.

**Comment by Jannis** [comment]
@lutter Have we observed this since?

**Comment by lutter** [comment]
Nope, haven't seen it since then. Closing it; will reopen if I ever run into it again.

**Comment by lutter** [comment]
We've now seen this again with Decentraland

**Comment by Jannis** [comment]
Yep. I agree the ideal solution would half the block range size until it either reaches 1 and still fails (in which case we'd either fail the subgraph or keep retrying indefinitely; the former would make it easier for us to catch the problem) or succeeds.

When it succeeds with a certain block range size, we should either increase it again for the next batch of `eth_getLogs` requests or stay on this size for a certain number of batches until we try the initialize range size again.

**Comment by leodasvacas** [comment]
I've observed this happening even with no relevant logs in the range. My theory is that the bloom filter has a lot of false positives and Infura is counting those for the 1000 limit.
