### ISSUE TITLE
`BigInt` variables passed to queries return incorrect results

### ISSUE THREAD

**Issue by NoahHydro** [graphprotocol/graph-node#789]
**This is a bug**

Right now, queries that use `BigInt` variables do not return correctly. Passing `"123"` into the query below (using Apollo) will return no results, but hard-coding `"123"` into the query will return results,

```
query myQuery($variable: BigInt!) {
  entities(where: { field: $variable }) {
    ...
  }
}
```

A minimal reproduction is available at: https://github.com/NoahZinsmeister/bigint-bug

**Comment by rhlsthrm** [comment]
Hi @NoahHydro, has this been pushed into production?

**Comment by leodasvacas** [comment]
@rhlsthrm I think we're pushing tomorrow, right @Jannis?

**Comment by Jannis** [comment]
Just rolled this out to production.
