### ISSUE TITLE
Event handler crashes in new Graph Node version

### ISSUE THREAD

**Issue by ben-kaufman** [graphprotocol/graph-node#801]
The Graph Node crashes with the following error whenever the following event occurs:
```
 Mar 04 09:39:29.040 ERRO Subgraph instance failed to run: Failed to process event: Failed to parse parameters of event: NewSchemeProposal(address,bytes32,address,address,bytes32,bytes4,string): Cannot decode string, id: QmaQFNEzoDymDGoDLQx4mY1PXozfas5QK3Y1GCwrpPfxDk
```

I have reproduced the transaction which makes it crash on Kovan:
https://kovan.etherscan.io/tx/0xa0557a9e7b47fcd8332fd91f8200468a762335a9ff56aecbd43af2790a84ff45

You can see the subgraph and the crash logs here:
https://thegraph.com/explorer/subgraph/ben-kaufman/daostack-alchemy

**Comment by ben-kaufman** [comment]
Update:
A similar issue was raised after I updated another contract we track. We added a boolean to an object which we keep in a mapping. And when trying to read from it from the subgraph I receive this:
```
graph-node_1  |   Mar 05 12:47:44.066 ERRO Subgraph instance failed to run: Failed to process event: Failed to handle Ethereum event with handler "handleNewProposal": Trap: Trap { kind: Host(HostExportError("Failed to call function \"proposals\" of contract \"GenesisProtocol\": ABI error: Cannot decode bool")) }, id: QmaiVH6BV8JuqGd3RJyn9361URtEAds2oSPY5MWWsMiSBe
```

**Comment by Jannis** [comment]
@ben-kaufman Is the subgraph source code available somewhere so I could run it myself?

**Comment by Jannis** [comment]
@ben-kaufman I've been able to clone https://github.com/daostack/subgraph, create an `.env` file using `kovan` as the network name and run `npm run deploy` to deploy it locally. Are these the right steps to reproduce?

**Comment by ben-kaufman** [comment]
Almost, just run `mom run test` instead of deploy. And you’ll need to check out a branch which suffers from the issue, the one currently on GitHub is https://github.com/daostack/subgraph/tree/schemeregistrar_2?files=1

**Comment by ben-kaufman** [comment]
Oh sorry if you’re on Ganache then you should just call the contract after you use deploy, not run the tests.

**Comment by Jannis** [comment]
Well, the contract on Kovan already has events that break with Graph Node, right? So I'm assuming I can just run `npm run deploy` and the subgraph will fail eventually. Is that not correct?

**Comment by ben-kaufman** [comment]
Not on the main branch, because it does not listen to the problematic contracts over there.

**Comment by Jannis** [comment]
Ok, yep, I've managed to reproduce it with the following steps:

1. Start a local Graph Node for Kovan (from https://github.com/graphprotocol/graph-node `master`)
2. Register the subgraph name with `graph create --node http://localhost:8020/ 
3. Clone https://github.com/daostack/subgraph
4. Check out the `schemeregistrar_2` branch
jannis/daostack`.
5. Create the following `.env` file:
   ```sh
   network="kovan"
   subgraph="jannis/daostack"
   
   # Not necessary for Docker deployment
   graph_node="http://localhost:8020/"
   ipfs_node="http://localhost:5001"
   access_token=
   ```
6. Run `npm run deploy`

**Comment by Jannis** [comment]
I have a rough idea of what is going on. We've forked `ethabi` recently and in our fork, indexed event parameters are not correctly parsed using the event topics.

Event parameters that are marked as `indexed` in the smart contract are moved into the event's topics rather than being part of the event data (see https://solidity.readthedocs.io/en/develop/contracts.html?highlight=indexed#events for more information). However, something isn't right with that in our `ethabi` fork. I'll continue investigating.

**Comment by Jannis** [comment]
@ben-kaufman I found the problem and have a fix pending for our `ethabi` fork. Once that's merged, `graph-node` will be fixed again.

**Comment by ben-kaufman** [comment]
@Jannis great, thanks!
