### ISSUE TITLE
Test `multiple_data_sources_per_subgraph` is not really passing

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#803]
It's printing an error despite showing up green. The error: `called Result::unwrap() on an Err value: SpawnError { is_shutdown: true }`. This is most likely just an issue with the test and not an actual bug.

**Comment by perfectmak** [comment]
@leodasvacas can I look into this? I'm new here and I really like what graph-node is doing, so I feel fixing some test case would help me get better know how iit works intenally.

**Comment by leodasvacas** [comment]
@perfectmak If you want to take a look you're more than welcome!
