### ISSUE TITLE
Internal transaction triggers

### ISSUE THREAD

**Issue by olibearo** [graphprotocol/graph-node#806]
__How can an internal tx be defined as a datasource?__

- address of the contract being watched
- function signature

__What arugments can be provided to internal tx handlers?__

- call input
- call output
- `from` address
- `value` sent
- call type
- gas used

__Ordering of triggers between internal txs and events__

We need a canonical order to have the index be deterministic in the decentralized network. If the event and the internal tx occur in separate txs then the tx order should be used to order triggers. If the event and the internal tx occur in the same tx there are some options:
1. Let the mapping author specify the order either implicitly through the index of each datasource or explicitly through some new manifest properties 
2. Provide a conventional order for events and internal txs occurring in the same tx
3. Inspect the call chain within the tx to see if the event and internal tx occur in the same link. If the event and the internal tx happen in separate links of the call chain, then respect that order. If the event and the internal tx happen in the same link of the call chain, provide a conventional order

To inspect the call chain, we need to have access to the opcodes run in the VM trace. Geth labels each step of the VM with the OPCODE name, but parity-ethereum does not as far as I can tell (the labels for the opcodes might be hiding in some of the hex they provide for the trace). 

__State used for view functions called in a mapping triggered by an internal tx__

It seems that a primary use case for internal tx triggers is when the contract being indexed does not already package the delta in state into a log event. A mapping has two options for calculating this state delta in the absence of a log event:

1. Use the input and output of the call combined with a priori knowledge of the logic in the contract to produce an entity
2. Run view functions against the contract before and after the tx has been executed to calculate a delta and produce an entity

To run view functions before and after a tx, you need the state of the contract just before the tx producing the trigger and just after. 

To get this state you need to get the contract state at the end of the previous block, replay the txs up until the trigger tx, take note of the pre tx state, execute the trigger tx, and take note of the post tx state. Geth and parity-ethereum's tracing apis give you access to these pre and post tx states. With these two states, then spin up an EVM, seed a state, and run the desired view functions.

A shortcoming of the parity-ethereum tracing api is that if a single tx calls out to the contract twice and produces two internal tx triggers, we need to manually instrument the EVM to capture the incremental changes in the state before and after each internal tx. Geth gives you the ability to track the storage of a contract after each opcode.

**Comment by olibearo** [comment]
A couple of outstanding questions:

**Which ethereum-node should we use?** 

An archive node is needed. Geth has better tracing capabilities, but we would need to write a rust client for it.

We could also work with Parity to extend the tracing api to provide opcodes in the VM trace and track the state of the contract at incremental steps within a transaction.

**What is the performance of syncing the index for a heavily used ERC20 contract leveraging internal txs?**

**Comment by leodasvacas** [comment]
Related issues: #298 #788

One thing that's not obvious to me is how the ethereum API will be used to listen to the internal transactions. Does that API already give us the ordering among internal transactions?

It seems that even when inspecting the call chain there are cases where we can't tell exactly what the proper order should be, I worry that those edge cases will make that approach too complicated for users to rely on. Maybe we could start with a simple canonical ordering like: In each transaction, process all internal transactions first, and then all events. With time we'll see what are the users' needs wrt the ordering.

> State used for view functions called in a mapping triggered by an internal tx

Could we punt on this part and first focus on having the triggers at all?

**Comment by olibearo** [comment]
@leodasvacas yeah, good questions. 

A parity-ethereum archive node with the `--tracing` flag on let's you search a traces database using [filters](https://tomusdrw.github.io/rust-web3/web3/api/struct.Traces.html#method.filter). It's similar to how we currently query logs except that you can only use a block range and the addresses involved in the call.

The returned traces include the input field for the call, so you can apply another filter for the function signature the subgraph is subscribed to. You can't apply this filter on the parity-ethereum side right now though, but we could request it or submit a patch upstream.

As far as ordering, I agree, I'd like to choose a convention initially. This way we don't have to do any heavy EVM replay to produce triggers.

We might be able to punt on intermediate state for view functions. The first use cases for internal txs are erc20 tokens without `Transfer`/`Mint` events and Gnosis Safe, so the next thing I have to do is determine if those subgraphs can work on only the IO provided to the internal tx and the post block state.
