### ISSUE TITLE
Improve how we maintain entity_history

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#807]
I just had a look at the production dump I have, trying to understand in more detail how `entity_history` works, and came across a bunch of things that could be greatly improved.

The dump has 10M rows in the `entities` table, and 39M rows in the `entity_history` table. The latter takes up 41GB of storage. For comparison, `ethereum_blocks` is 104 GB.

* there are 22M history entries for the `subgraphs` subgraph, even though we explicitly exclude it, and never use these entries during reversion
* there are 5M entries for other subgraphs where `data_before = data_after`
* there are 10M entries for other subgraphs where `data_before` is null, i.e. they just record the creation of the entity that's also in the `entities` table.
* we never use `data_after` when we revert, so roughly half the size of the table is never used

If we remove the 27M entries from the first two points, the `entity_history` table would shrink to about 13GB. If we then also remove the unused `data_after` column, the table would shrink to about 7GB. (These are guesses, not actual measurements)

Finally, if we used a scheme that doesn't force us to maintain identical copies of entities in `entities` and `entity_history` for entities that are never updated, we'd be left with 2.2M 'old' entity versions, which would roughly take 1.2GB to store. (That also means that only about 20% of entities are ever changed again after creation)

There are two aspects to this: one is just the sheer amount of storage we need for history, and the other is the number of rows in `entity_history`, which slows down any operation involving history. Aggravating this is that most entities are relatively small, and Postgres stores them in the actual table rather than in toast (large object) storage so that things like full table scans actually have to wade through the entire ~ 40GB of storage. Contrast that with `ethereum_blocks`, where the actual table only takes up about 500MB.

**Comment by fordN** [comment]
I think it's a good idea to remove the `data_after` column to get the significant data volume reduction you noted.   The information is still available by simply scanning to the next `data_before`.  The only thing we really lose out on (which hasn't been used much anyways) is the ability to easily query for the changes that were effected by a specific block: saved queries and views could be created to facilitate peering into an entities history of changes.    

For the case where `data_before`=`data_after` I wonder how much we can reduce the load on the DB by going further upstream and not even apply these transactions to the `entities` table in the first place. We could add a `BEFORE` trigger `FOR EACH ROW` that skips the operation if `data_before`=`data_after`.

**Comment by lutter** [comment]
@fordN agreed on dropping `data_after`; and yes, I also realized that I should rework the triggers to have `WHEN` conditions to avoid going into plsql at all for those rows.

**Comment by Jannis** [comment]
With #808 merged and #822 resolved by hand, is this done?

**Comment by lutter** [comment]
For cleanliness, we should also drop the `data_after` column (I just nulled it out everywhere) But that's fairly low priority.

**Comment by Jannis** [comment]
@lutter Is this something you want to take care of this week or should we postpone it indefinitely and close this issue?

**Comment by lutter** [comment]
Let's close this; it'll become moot once we are fully migrated into split entities tables.
