### ISSUE TITLE
Short-circuit storing of unchanged entities

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#810]
It's quite common that mappings load and then store an entity without making any changes to it. In production, that happens for 25%-30% of the total entity store operations. We should therefore catch that an entity is unchanged and not store it at all as early as we possible can, at the very latest in the `Store` before we actually talk to the database.

**Comment by Jannis** [comment]
@lutter Is this something we want to include in #142?

**Comment by lutter** [comment]
Linked it to #142

**Comment by lutter** [comment]
The `EntityCache` that was added a while ago does that
