### ISSUE TITLE
Update entityCount when updating entities

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#835]
`entity_count` is currently very slow to query, we should tradeoff precision or freshness for the sake of performance. Some methods of using postgres to get us estimates can be found [here](https://www.citusdata.com/blog/2016/10/12/count-performance/). We may want to wait for #142 before taking a look at this.

**Comment by lutter** [comment]
I am leaning towards denormalizing the `entity_count` outright (i.e., adjust it every time we add/remove entities) The two things that need to happen for that are (1) that we have the db tell us whether an upsert was an insert or an update and (2) move the block reversion logic out of a stored procedure and into the app code itself, which has all kinds of other benefits, too.

**Comment by Jannis** [comment]
@lutter I'm on board with that. Estimating won't lead to a good and predictable user experience.
