### ISSUE TITLE
Query parameters appear to be ignored

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#848]
I'm using graphql-client in Python, and it appears the server is ignoring query parameters supplied; specifying 'skip' as a parameter seems to give the first 100 results regardless of what value is specified:

```
>>> from graphql_client import GraphQLClient
>>> client = GraphQLClient('https://api.thegraph.com/subgraphs/name/ensdomains/ens')
>>> client.query('{auctionedNames(where:{state:FINALIZED},orderBy:id,skip:$skip){id}}', {'skip': 0})['data']['auctionedNames'][0]['id']
'0x0000000000000000000000000000000000000000000000000000000000000000'
>>> client.query('{auctionedNames(where:{state:FINALIZED},orderBy:id,skip:$skip){id}}', {'skip': 100})['data']['auctionedNames'][0]['id']
'0x0000000000000000000000000000000000000000000000000000000000000000'
```

**Comment by leodasvacas** [comment]
Hi @Arachnid, sorry for taking a while to investigate. You're missing the variable declaration in the query. Your query string should be:
 `"query($skip: Int) {auctionedNames(where:{state:FINALIZED},orderBy:id,skip:$skip){id}}"`

Let me know if it works for you.

**Comment by Arachnid** [comment]
Oh! Sorry about that. Shouldn't it raise an error for an undefined variable, then?

**Comment by Jannis** [comment]
According to https://graphql.github.io/graphql-spec/draft/#sec-Validation.Variables, yes. Full query validation is a feature that's missing right now: #325.

**Comment by Jannis** [comment]
I'm closing it as a duplicate of #325. But it provides another reason to implement validation.
