### ISSUE TITLE
Add support for https protocol in ipfs connection

### ISSUE THREAD

**Issue by jellegerbrandy** [graphprotocol/graph-node#854]
The Rust IPFS client library we use only supports host + port,

**What is the current behavior?**

Starting the graph-node docker container with an `ipfs` url like `https://ipfs.infura.io`  will lead to a timeout error:
```
graph-node_1  | wait-for-it.sh: waiting 30 seconds for https://ipfs.infura.io
graph-node_1  | wait-for-it.sh: timeout occurred after waiting 30 seconds for https://ipfs.infura.io
client_graph-node_1 exited with code 124
```
**What is the expected behavior?**

It should just work :-)

**Comment by jellegerbrandy** [comment]
Added an issue at the rust-ipfs-api repo: https://github.com/ferristseng/rust-ipfs-api/issues/30

**Comment by orenyodfat** [comment]
Any update re that ?
