### ISSUE TITLE
Move block reversion logic into Rust code

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#859]
Right now, block reversion happens in a stored procedure. As a consequence, we currently query the same information twice: once in the stored proc to do the revert, and once in the app to generate an appropriate `StoreEvent`. This would allow us to get rid of one of these queries. For maintenance, it would be much better to pull that logic into the Rust code and get rid of the stored procedure.

This will also make it possible to denormalize the `entityCount` for each subgraph in issue #835

**Comment by Jannis** [comment]
This was merged as part of #887, right? Can we close it?

**Comment by lutter** [comment]
Yes, this is done.
