### ISSUE TITLE
Support for calling Ether Balances in mappings

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#895]
Right now there is no way to call an ether balance of an account or a contract. 

This functionality is very useful in protocols that use ether - this includes Uniswap and Compound, and likely also Dharma and Maker. 

This might block me on Uniswap (figuring out if I can work around it right now). With compound we were able to get around it, because they added a getter function that allowed us to read the ether balance of their smart contracts. 

It should return the Eth balance in WEI.

**Comment by coffee-converter** [comment]
This would be super nice...is it still yet to be implemented?

**Comment by davekaj** [comment]
yes still yet to be implemented :(

**Comment by sebastiantf** [comment]
This is a must-have API. Quite surprising this is not yet available.
Are there any general purpose contracts available on all chains that lets you query the eth balance? Could be used as a workaround for this.
