### ISSUE TITLE
Subgraph says synced when it has erroed

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#896]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

This happened:
![Captura de Tela 2019-04-26 às 15 48 36](https://user-images.githubusercontent.com/9885558/56830184-115aca80-683c-11e9-820a-04f22d492952.png)

Two things are wrong:
- Label says "synced" but the logs show a fatal error.
   - Probably a node issue, but needs more investigation to rule out an UI issue.
- Syncing indicator is at the end but the block number is actually old.
   - This is most likely an UI issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm not sure how reproducible this is, but it happened with the Compound subgraph of ID Qmd8oC75NpDQoF4vc51GuihA3LnBwXwK5ErFYd9ekRSSLd.

**What is the expected behavior?**

Label says "failed" and indicator is at the correct position.

**Comment by nenadjaja** [comment]
I ran the query that we use in `explorer-api` to get the subgraph version data from the `graph` DB, and it returns `true` for both: `synced` and `failed` fields.
<img width="771" alt="Screen Shot 2019-04-26 at 12 27 10 PM" src="https://user-images.githubusercontent.com/1865664/56831828-10677000-681f-11e9-986c-1be1996aa1da.png">

Here is the query:
```
select v.data->'createdAt'->>'data' as "createdAt",
      d.data->'id'->>'data' as "deploymentId",
      d.data->'latestEthereumBlockNumber'->>'data' as "latestEthereumBlockNumber",
      d.data->'totalEthereumBlocksCount'->>'data' as "totalEthereumBlocksCount",
      (d.data->'synced'->>'data')::bool as synced,
      (d.data->'failed'->>'data')::bool as failed,
      m.data->'description'->>'data' as description,
      m.data->'repository'->>'data' as repository,
      m.data->'schema'->>'data' as schema,
      e.data->'network'->>'data' as network
      from subgraphs.entities v,
           subgraphs.entities d,
           subgraphs.entities m,
           subgraphs.entities e
      where v.entity='SubgraphVersion'
      and d.entity='SubgraphDeployment'
      and m.entity='SubgraphManifest'
      and e.entity='EthereumContractDataSource'
      and d.id = v.data->'deployment'->>'data'
      and m.id = d.data->'manifest'->>'data'
      and e.id = m.data->'dataSources'->'data'->0->>'data'
      and v.id = ':versionId';
```

**Comment by leodasvacas** [comment]
It's strange for it to say "synced" on such an old block, that part is an node issue. But if the node says failed then the UI should have picked up on that, that part is an UI issue.

**Comment by dOrgJelli** [comment]
Is there an ETA on this fix by chance?

**Comment by leodasvacas** [comment]
@dOrgJelli Actually I don't think there is an issue with the node here. We mark a subgraph as "synced" if it has ever fully synced, so that is working as designed. And the subgraph is marked as failed in the DB so showing the "synced" label is an issue with the UI, not the node. So I'll close this as not a bug.
