### ISSUE TITLE
Graph Node crash after deploying new subgraph

### ISSUE THREAD

**Issue by ben-kaufman** [graphprotocol/graph-node#900]
Right after I successfully deployed a subgraph to the graph-node (which already hosted 2 other subgraphs) I got this issue whenever I tried to query the graph node:
`
"Internal server error: GraphQL server error (internal error): Error resolving subgraph name: Failed to get entities from store: out of shared memory, query = "SELECT \"entities\".\"data\", \"entities\".\"entity\" FROM \"entities\" WHERE \"entities\".\"entity\" = ANY($1) AND \"entities\".\"subgraph\" = $2 AND data -> $3->> \'data\' = $4 -- binds: [[\"Subgraph\"], \"subgraphs\", \"name\", \"v16\"]"" 
`
I had to restart the subgraph to get it to work again but the error returned few hours later. We deleted 2 out of the 3 hosted subgraphs and for now it seems to be working well again.

**Comment by leodasvacas** [comment]
Thanks for reporting. `out of shared memory` signals is an issue inside the DB, we've seen this before due to having too many indexes, see #764, it may happen if you have a DB in which you've deployed many subgraph versions. In the latest graph-node release we've take a measure to fix this by putting each subgraph in its own DB table, but right now that is only done for new subgraphs. So if you did deploy a new subgraph, that should permanently fix it for you. Ping @lutter.

**Comment by leodasvacas** [comment]
There is also the question of whether that code should be made more robust by retrying the query, we're starting to need a general "reset the subgraph" failure mode for things like #823.

**Comment by lutter** [comment]
Can you do the following in psql
```
select count(*) from pg_indexes where indexname like 'qm%';
select remove_unassigned_deployment_indexes();
select count(*) from pg_indexes where indexname like 'qm%';
```

and add the output from these commands to this issue? 

If that gets rid of enough indexes, your problem should go away. We also changed how we store entities (with PR #887) which will avoid this problem in the future, but you still need to do the above for your existing entities.

**Comment by leodasvacas** [comment]
Another issue here is that the subgraph was not marked as fail after this error.

**Comment by lutter** [comment]
This should not be an issue anymore as of graph-node v0.13.0 which will migrate subgraphs into their own entities tables.
