### ISSUE TITLE
Print tx hash of event that causes handler to fail 

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#903]
When a handler fails, in the past you always knew what contract it failed on because you hard coded it into the manifest. 

With dynamic data sources, we have potentially 100's of contracts (such as ENS resolvers). When an error occurs, there is no log data on the contract of transaction, we just have the block number. 

In the past, armed with just the block number you could pretty easily find the failing tx and event on etherscan, which really helps with debugging. 

**Suggested Solution:**
On handler errors we show the tx hash that contains the event logs that caused it to fail. If it is easy, we may as well include the contract address too. This will make debugging on dynamic datasources and normal data sources easier

**Comment by Jannis** [comment]
I think we do this now.
