### ISSUE TITLE
Subgraph console fails for two or more named queries

### ISSUE THREAD

**Issue by paulrberg** [graphprotocol/graph-node#934]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

The subgraph console with the following error:

```
{
  "errors": [
    {
      "message": "Operation name required"
    }
  ]
}
```

![Error](https://media.discordapp.net/attachments/438070183794573313/576910153987653633/Screen_Shot_2019-05-12_at_00.14.37.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Go to any subgraph in the explorer
2. Write up two queries and **name** them (find an example below)
3. Run them

Example:

```
query Transactions {
  transactions {
    id
  }
}

query Blocks {
  blocks {
    id
  }
}
```

**What is the expected behavior?**
Both queries should be successfully executed.

**Comment by markusbkoch** [comment]
I'm having the same issue. Any updates?

**Comment by Rjrunner44** [comment]
still seems broken for me...almost 2 years later...

**Comment by schmidsi** [comment]
Hey @Rjrunner44, thanks for re-reporting. Sorry about that. We were working on a better overall better dev-experience and will unveil it soon. Until then, the recommended work-around is to use https://graphiql-online.com.

**Comment by schmidsi** [comment]
Actually, looking at this again it seems like this is against the GraphQL spec. Instead of:

```graphql
query Transactions {
  transactions {
    id
  }
}

query Blocks {
  blocks {
    id
  }
}
```

You should just write:
```graphql
query BlocksAndTransactions {
  transactions {
    id
  }
  blocks {
    id
  }
}
```

**Comment by schmidsi** [comment]
Closing this since I think I was able to answer the original question an @paulrberg gave a thumbs up. Feel free to reopen it if that does not solve the problem for you.
