### ISSUE TITLE
Input Mainnet and Testnet Contract address info so that the graph node can do both without editing the code

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#952]
Feature request from Nico at Decentraland:
```
Feature request
I’m deploying the same graph for ropsten and mainnet so,
is there a way to specify a subgraph.yaml on the deploy command?
I’d still need to change the hardcoded contract 
addresses I used to `bind` the contracts, but that’s not too bad (edited) 
```

My input - Nico makes a good point about having to change the `bind` addresses. It would be cool if we could derive from the input of the manifest and the deploy command if we are on ropsten, mainnet, kovan, etc, in the mappings, so one could use a switch case for the contract address to bind to. 

Related to some thoughts on this old issue https://github.com/graphprotocol/graph-node/issues/515

**Comment by davekaj** [comment]
@nicoantangelo

**Comment by leoyvens** [comment]
We now have `dataSource.address()` which I think solves this.
