### ISSUE TITLE
IPFS timeouts

### ISSUE THREAD

**Issue by ziegfried** [graphprotocol/graph-node#963]
**Do you want to request a *feature* or report a *bug*?**

A little bit of both :)

**What is the current behavior?**

When retrieving data from IPFS using the `ipfs.cat()` host export, there is fairly short timeout (I believe around 20 seconds) before it gives up and returns `null` instead.

In addition, when retrieving multiple IPFS objects then there is a good chance that the subgraph terminates because of a mapping handler hitting a timeout (I saw 180 seconds being a hard limit here).

I have tried using `ipfs.map()`/`ipfs.mapJSON()` instead of `ipfs.cat()`, but some objects that don't exist anymore caused the whole subgraph to fail, without a way to prevent this from the mapping code.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The [Peepeth subgraph](https://github.com/ziegfried/peepeth-subgraph) is good example for this. It currently misses on a good amount of the data from IPFS and has some defensive measures in the mapping code that prevent to retrieve more than 8 IPFS objects per handler invocation.

**What is the expected behavior?**

Some ideas to improve the situation:

1) Make the timeout for `ipfs.cat()` calls configurable, as well as the timeout
2) Some way to pin IPFS object on the first run of the subgraph, so it's readily available on subsequent runs
3) Add an option that allows the subgraph to continue if `ipfs.map()` or `ipfs.mapJSON()` calls  fail for objects that don't exist or time out.

**Comment by Jannis** [comment]
Yes, at the very least we should do 2 and 3.

**Comment by ziegfried** [comment]
Awesome! I've also set up an IPFS server where I've been pinning all the Peepeth ipfs blocks I could retrieve. Is there a good way to share this with the thegraph-hosted graph-node? Maybe add it as a bootstrap-peer?

**Comment by Jannis** [comment]
IPFS support will change in the network and we're not planning to make IPFS changes before that.

**Comment by folex** [comment]
Hello! Were any `ipfs`-related timeouts added to the graph cli?
