### ISSUE TITLE
Provide `msg.sender` to arguments passed to call handlers

### ISSUE THREAD

**Issue by olibearo** [graphprotocol/graph-node#970]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

`msg.sender`, the address which is making the call to the observed contract, is not passed to call handlers

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

---

**What is the expected behavior?**

---

**Comment by ziegfried** [comment]
Is `sender` different from the `from` address of the transaction? The `from` address can be obtained from the `call` instance passed to the handler:

```typescript
export function handleMyCall(call: MyCall): void {
    let sender: Address = call.transaction.from;
    // or
    let sender: string = call.transaction.from.toHex()
}
```

**Comment by Jannis** [comment]
@olibearo We added `from`, right? Shall we close this issue?

**Comment by Jannis** [comment]
We have `from` and that's the same as `msg.sender`.
