### ISSUE TITLE
GraphQL `_contains` filter do not work as expected

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#973]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using a `_contains` filter in GraphQL, results are not returned as expected. For example, for [ENS](https://thegraph.com/explorer/subgraph/ensdomains/ens), this query should return a lot of results, but returns none:
```
{
  domains(first: 5, where:{name_contains:"e"}) {
    name
  }
}
```

**What is the expected behavior?**
The above query returns results.

The underlying issue is that the argument of the `_contains` filter is passed verbatim into a SQL `like` clause, i.e. the query contains something along the lines of `name like 'e'`. The transformation needs to be changed to generate SQL like `name like '%e%'`. In fact, this query does return results, though users should not have to write that:
```
{
  domains(first: 5, where:{name_contains:"%e%"}) {
    name
  }
}
```

**Comment by Jannis** [comment]
Fixed as of #1015.
