### ISSUE TITLE
Contract adddress, function name and data not logged in `eth_call` retries

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#981]
**Do you want to request a *feature* or report a *bug*?**

I'd consider this a bug because it makes debugging hard. But it's somewhere in between.

**What is the current behavior?**

When an Ethereum function call fails, we retry, sometimes forever. The current logs look like this:
```
     Jun 05 13:03:50.815 DEBG Trying again after eth_call RPC call failed (attempt #24) with result Err(CallError(ErrorMessage { msg: "RPC error: Error { code: ServerError(-32015), message: \"VM execution error.\", data: Some(String(\"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000125072696365206973206e6f742076616c69640000000000000000000000000000\")) }" }))
```

**What is the expected behavior?**

For debugging these calls, it would be immensely useful if the following was logged as well:

* name of the function being called
* address of the contract being called
* the encoded call data

**Comment by leoyvens** [comment]
This issue is from before contract calls reverts being detected and logged so I think this is fixed.
